package com.vicmatskiv.mw;

import static com.vicmatskiv.weaponlib.compatibility.CompatibilityProvider.compatibility;

import com.vicmatskiv.weaponlib.ai.EntityConfiguration;
import com.vicmatskiv.weaponlib.ai.EntityCustomMob;
import com.vicmatskiv.weaponlib.ai.InfectionAttack;
import com.vicmatskiv.weaponlib.compatibility.CompatibleBiomeType;
import com.vicmatskiv.weaponlib.compatibility.CompatibleEntityAIAttackOnCollide;
import com.vicmatskiv.weaponlib.mission.GoToLocationAction;
import com.vicmatskiv.weaponlib.mission.KillEntityAction;
import com.vicmatskiv.weaponlib.mission.MissionOffering;
import com.vicmatskiv.weaponlib.mission.MissionOffering.Level;
import com.vicmatskiv.weaponlib.mission.ObtainItemAction;

import net.minecraft.entity.EntityCreature;
import net.minecraft.entity.ai.EntityAIHurtByTarget;
import net.minecraft.entity.ai.EntityAILookIdle;
import net.minecraft.entity.ai.EntityAISwimming;
import net.minecraft.entity.ai.EntityAIWander;
import net.minecraft.entity.ai.EntityAIWatchClosest;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Items;
import net.minecraft.world.EnumDifficulty;

public class Entities {

    public static void init(CommonProxy commonProxy) {
        
        String missionDescription = "Claire arrives at the safe house, explaining that she escaped a car bombing after Phelps aborted the mission. Hunt arranges a meeting with Max, and warns her that she has been given a fake list on a disc equipped with a tracking device. Max and her agents escape, taking Hunt with them, just before a CIA team raids their location.";

        new EntityConfiguration.Builder()
            .withName("bandit1")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(20)
            .withEntityIdSupplier(() -> 10000)
            
            .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
            .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
            .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 7, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Biped", "bandit1.png")
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Biped", "bandit3.png")
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Biped", "bandit4.png")
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Biped", "bandit5.png")
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Biped", "bandit6.png")
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Biped", "bandit7.png")
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Biped", "bandit8.png")
            .withHurtSound("hurt")
            .withPushability(false)
            .withCollidability(true)
            .withDespawnability(false)
            .withInvulnerability()
            .withAmbientSound("drawweapon")
//            .withAiTask(1, e -> new EntityAISwimming(e))
//            .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
//            .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
//            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
//            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
//            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
//            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityIronGolem.class, true))
//            .withMissionOffering(
//                    new MissionOffering.Builder("Kill 1 cow")
//                    .withMissionDescription(missionDescription)
//                    .withGoal(new KillEntityAction("cow"), 1)
//                    .withLevel(Level.EASY)
//                    .withReward(Attachments.ACOG)
//                    .withReward(Guns.M4A1)
//                    .build()
//                    )
//            .withMissionOffering(
//                    new MissionOffering.Builder("Bring an apple")
//                    .withMissionDescription(missionDescription)
//                    .withGoal(new ObtainItemAction(Items.APPLE, false), 1)
//                    .withMaxDuration(1000)
//                    .withCooldownTime(500)
//                    .withLevel(Level.EASY)
//                    .withReward(Guns.M4A1)
//                    .build())
//            
//            .withMissionOffering(
//                    new MissionOffering.Builder("Find a location")
//                    .withMissionDescription(missionDescription)
//                    .withGoal(new GoToLocationAction(500, 4, 500, 10), 1)
//                    .withMaxDuration(1000)
//                    .withCooldownTime(1000)
//                    .withLevel(Level.EASY)
//                    .withReward(Guns.M4A1)
//                    .build())
//                    
//            .withMissionOffering(
//                    new MissionOffering.Builder("Kill 2 cows")
//                    .withMissionDescription(missionDescription)
//                    .withGoal(new KillEntityAction("cow"), 2)
//                    .requiresAll("Kill 1 cow")
//                    .withLevel(Level.EASY)
//                    .withReward(Items.APPLE, 5)
//                    .withReward(Items.DIAMOND_SWORD)
//                    .build()
//                    )
//            .withMissionOffering(
//                    new MissionOffering.Builder("Kill 3 cows")
//                    .withMissionDescription(missionDescription)
//                    .requiresAll("Kill 2 cows")
//                    .withLevel(Level.MEDIUM)
//                    .withGoal(new KillEntityAction("cow"), 3)
//                    .withReward(Items.DIAMOND_AXE)
//                    .withReward(Items.DIAMOND_PICKAXE)
//                    .withReward(Items.DIAMOND_BOOTS)
//                    .build()
//                    )
//            .withMissionOffering(
//                    new MissionOffering.Builder("Kill 3 zombies")
//                    .withMissionDescription(missionDescription)
//                    .withGoal(new KillEntityAction("zombie"), 3)
//                    .withLevel(Level.HARD)
//                    .withReward(Items.DIAMOND_AXE)
//                    .withReward(Items.DIAMOND_PICKAXE)
//                    .withReward(Items.DIAMOND_BOOTS)
//                    .withReward(Items.DIAMOND_SWORD)
//                    .build()
//                    )
//            .withMissionOffering(
//                    new MissionOffering.Builder("Kill 4 zombies")
//                    .withMissionDescription(missionDescription)
//                    .withGoal(new KillEntityAction("zombie"), 4)
//                    .requiresAll("Kill 3 zombies")
//                    .withLevel(Level.HARD)
//                    .withReward(Items.DIAMOND_AXE)
//                    .withReward(Items.DIAMOND_PICKAXE)
//                    .withReward(Items.DIAMOND_BOOTS)
//                    .withReward(Items.DIAMOND_SWORD)
//                    .build()
//                    )
//            .withMissionOffering(
//                    new MissionOffering.Builder("Kill 5 zombies")
//                    .withMissionDescription(missionDescription)
//                    .withGoal(new KillEntityAction("zombie"), 5)
//                    .requiresAll("Kill 4 zombies")
//                    .withLevel(Level.HARD)
//                    .withReward(Items.DIAMOND_AXE)
//                    .withReward(Items.DIAMOND_PICKAXE)
//                    .withReward(Items.DIAMOND_BOOTS)
//                    .withReward(Items.DIAMOND_SWORD)
//                    .build()
//                    )
//            .withMissionOffering(
//                    new MissionOffering.Builder("Kill 6 zombies")
//                    .withMissionDescription(missionDescription)
//                    .withGoal(new KillEntityAction("zombie"), 6)
//                    .requiresAll("Kill 5 zombies")
//                    .withLevel(Level.HARD)
//                    .withReward(Items.DIAMOND_AXE)
//                    .withReward(Items.DIAMOND_PICKAXE)
//                    .withReward(Items.DIAMOND_BOOTS)
//                    .withReward(Items.DIAMOND_SWORD)
//                    .build()
//                    )
            
            .withIntroDialog("The Mysterious Stranger admired your family cow and asked if it was for sale.\n\nWhen you nodded, he offered to trade some Magic Beans, that (if planted in tilled dirt) would lead to more wealth than you could imagine.")
            .withIntroDialog("So you handed him your cow, and grabbed the Magic Beans.\n\nPleased with yourself, you hurried away, looking for tilled dirt in which to plant the Magic Beans.\n\nYou couldn't wait to see how proud your mother would be for")
            .withIntroDialog("being so shrewd!  Untold wealth in return for an old, milkless cow; what a good deal you made!\n\nSo off you went, looking for a place to plant the Magic Beans with room to grow...")
            .withIntroImage("mob.png")
            .withDialogBackground("black_leather.png")
            .withRewardsBackground("rewards.png")
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("zombieBlistered")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(250)
            .withEntityIdSupplier(() -> 10001)
//          .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
//          .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
//          .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
//          .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
//           .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
//          .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.ZombieBlistered", "zombieblistered.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withMaxSpeed(0.45F) // 0.1-0.3 is normal speed
            .withCollisionAttackDamage(15.0)
            .withAiTask(1, e -> new EntityAISwimming(e))
//          .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
//           .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
//           .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
//          .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("zombieRipper")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(150)
            .withEntityIdSupplier(() -> 10002)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.RipperZombie", "ripperzombie.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withMaxSpeed(0.3F) // 0.1-0.3 is normal speed
            .withCollisionAttackDamage(10.0)
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("tornzombie")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(30)
            .withEntityIdSupplier(() -> 10003)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(20, 1, 5, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.TornZombie", "tornzombie.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))

            .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("necromorph")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(200)
            .withEntityIdSupplier(() -> 10004)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Necromorph", "necromorph.png")
            .withHurtSound("necromorph_hurt")
            .withAmbientSound("necromorph_ambient")
            .withStepSound("step")
            .withDeathSound("necromorph_death")
            .withMaxSpeed(0.35F) // 0.1-0.3 is normal speed
            .withCollisionAttackDamage(5.0)
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("licker")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(200)
            .withEntityIdSupplier(() -> 10005)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Licker", "licker.png")
            .withHurtSound("hurt")
            .withAmbientSound("drawweapon")
    //      .withStepSound("step")
    //      .withAmbientSound(sound)
            .withMaxSpeed(0.35F) // 0.1-0.3 is normal speed
            .withCollisionAttackDamage(10.0)
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("zombie")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(30)
            .withEntityIdSupplier(() -> 10006)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(50, 80, 150, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Zombie", "zombie_1.png")
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Zombie", "zombie_2.png")
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Zombie", "zombie_3.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
            .withMaxSpeed(0.3F) // 0.1-0.3 is normal speed
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("hazmat_zombie")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(40)
            .withEntityIdSupplier(() -> 10007)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(50, 80, 150, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.HazmatZombie", "hazmatzombie.png")
            .withHurtSound("hazmatzombie_hurt")
            .withAmbientSound("hazmatzombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("hazmatzombie_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
            .withMaxSpeed(0.3F) // 0.1-0.3 is normal speed
//            .withCollisionAttackDamage(30.0)
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("Defiled Zombie")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(300)
            .withEntityIdSupplier(() -> 10008)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.DefiledZombie", "defiledzombie.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    
//           .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("deathclaw")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(5000)
            .withEntityIdSupplier(() -> 10009)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.vicmatskiv.mw.models.Deathclaw", "deathclaw.png")
            .withHurtSound("deathclaw_hurt")
            .withAmbientSound("deathclaw_ambient")
          .withStepSound("deathclaw_step")
            .withDeathSound("deathclaw_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
            .withCollisionAttackDamage(30.0)
            .withMaxSpeed(0.45F) // 0.1-0.3 is normal speed
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 100.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        }

}