// Date: 2/19/2017 12:05:54 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import com.vicmatskiv.weaponlib.ModelWithAttachments;

public class AK12action extends ModelWithAttachments
{
  //fields
    ModelRenderer gun74;
    ModelRenderer gun75;
    ModelRenderer gun76;
    ModelRenderer gun77;
    ModelRenderer gun87;
    ModelRenderer gun90;
  
  public AK12action()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      gun74 = new ModelRenderer(this, 0, 0);
      gun74.addBox(0F, 0F, 0F, 1, 1, 11);
      gun74.setRotationPoint(-0.6F, -11.5F, -27F);
      gun74.setTextureSize(64, 32);
      gun74.mirror = true;
      setRotation(gun74, 0F, 0F, 0F);
      gun75 = new ModelRenderer(this, 0, 0);
      gun75.addBox(0F, 0F, 0F, 3, 1, 11);
      gun75.setRotationPoint(-3.4F, -11.5F, -27F);
      gun75.setTextureSize(64, 32);
      gun75.mirror = true;
      setRotation(gun75, 0F, 0F, 0F);
      gun76 = new ModelRenderer(this, 0, 0);
      gun76.addBox(0F, 0F, 0F, 3, 1, 11);
      gun76.setRotationPoint(-3.4F, -11.5F, -27F);
      gun76.setTextureSize(64, 32);
      gun76.mirror = true;
      setRotation(gun76, 0F, 0F, -1.33843F);
      gun77 = new ModelRenderer(this, 0, 0);
      gun77.addBox(0F, 0F, 0F, 1, 3, 11);
      gun77.setRotationPoint(0.4F, -11.5F, -27F);
      gun77.setTextureSize(64, 32);
      gun77.mirror = true;
      setRotation(gun77, 0F, 0F, 2.899932F);
      gun87 = new ModelRenderer(this, 0, 0);
      gun87.addBox(0F, 0F, 0F, 3, 1, 8);
      gun87.setRotationPoint(-3F, -13.8F, -35F);
      gun87.setTextureSize(64, 32);
      gun87.mirror = true;
      setRotation(gun87, 0F, 0F, 0F);
      gun90 = new ModelRenderer(this, 0, 0);
      gun90.addBox(0F, 0F, 0F, 2, 1, 1);
      gun90.setRotationPoint(-0.3F, -13.9F, -34.8F);
      gun90.setTextureSize(64, 32);
      gun90.mirror = true;
      setRotation(gun90, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun74.render(f5);
    gun75.render(f5);
    gun76.render(f5);
    gun77.render(f5);
    gun87.render(f5);
    gun90.render(f5);
  }

}
