// Date: 6/24/2019 1:59:36 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AK47stock extends ModelBase
{
  //fields
    ModelRenderer gun233;
    ModelRenderer gun234;
    ModelRenderer gun235;
    ModelRenderer gun236;
    ModelRenderer gun237;
    ModelRenderer gun238;
    ModelRenderer gun239;
    ModelRenderer gun240;
    ModelRenderer gun241;
    ModelRenderer gun242;
    ModelRenderer gun243;
    ModelRenderer gun244;
    ModelRenderer gun245;
    ModelRenderer gun348;
    ModelRenderer gun349;
    ModelRenderer gun365;
  
  public AK47stock()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      gun233 = new ModelRenderer(this, 0, 0);
      gun233.addBox(0F, 0F, 0F, 4, 4, 27);
      gun233.setRotationPoint(-3.5F, -10.9F, 3.5F);
      gun233.setTextureSize(64, 32);
      gun233.mirror = true;
      setRotation(gun233, -0.1858931F, 0F, 0F);
      gun234 = new ModelRenderer(this, 0, 0);
      gun234.addBox(0F, 0F, 0F, 3, 2, 11);
      gun234.setRotationPoint(-3F, -11.9F, 3.5F);
      gun234.setTextureSize(64, 32);
      gun234.mirror = true;
      setRotation(gun234, -0.1858931F, 0F, 0F);
      gun235 = new ModelRenderer(this, 0, 0);
      gun235.addBox(0F, 0F, 0F, 4, 2, 5);
      gun235.setRotationPoint(-3.5F, -8.3F, 8.5F);
      gun235.setTextureSize(64, 32);
      gun235.mirror = true;
      setRotation(gun235, 0.4833219F, 0F, 0F);
      gun236 = new ModelRenderer(this, 0, 0);
      gun236.addBox(0F, 0F, 0F, 3, 2, 5);
      gun236.setRotationPoint(-3F, -9.2F, 8.5F);
      gun236.setTextureSize(64, 32);
      gun236.mirror = true;
      setRotation(gun236, 0.4833219F, 0F, 0F);
      gun237 = new ModelRenderer(this, 0, 0);
      gun237.addBox(0F, 0F, 0F, 3, 2, 18);
      gun237.setRotationPoint(-3F, -11.5F, 12.95F);
      gun237.setTextureSize(64, 32);
      gun237.mirror = true;
      setRotation(gun237, -0.0872665F, 0F, 0F);
      gun238 = new ModelRenderer(this, 0, 0);
      gun238.addBox(0F, 0F, 0F, 4, 4, 18);
      gun238.setRotationPoint(-3.5F, -10.6F, 12.75F);
      gun238.setTextureSize(64, 32);
      gun238.mirror = true;
      setRotation(gun238, -0.0872665F, 0F, 0F);
      gun239 = new ModelRenderer(this, 0, 0);
      gun239.addBox(0F, 0F, 0F, 4, 3, 27);
      gun239.setRotationPoint(-3.5F, -9.6F, 3.5F);
      gun239.setTextureSize(64, 32);
      gun239.mirror = true;
      setRotation(gun239, -0.2974289F, 0F, 0F);
      gun240 = new ModelRenderer(this, 0, 0);
      gun240.addBox(0F, 0F, 0F, 4, 6, 4);
      gun240.setRotationPoint(-3.5F, -5.7F, 26.4F);
      gun240.setTextureSize(64, 32);
      gun240.mirror = true;
      setRotation(gun240, -0.1115358F, 0F, 0F);
      gun241 = new ModelRenderer(this, 0, 0);
      gun241.addBox(0F, 0F, 0F, 4, 1, 1);
      gun241.setRotationPoint(-3.5F, 0.1F, 28.6F);
      gun241.setTextureSize(64, 32);
      gun241.mirror = true;
      setRotation(gun241, -0.1115358F, 0F, 0F);
      gun242 = new ModelRenderer(this, 100, 0);
      gun242.addBox(0F, 0F, 0F, 2, 2, 1);
      gun242.setRotationPoint(-2.9F, -9.9F, 30.8F);
      gun242.setTextureSize(64, 32);
      gun242.mirror = true;
      setRotation(gun242, -0.0872665F, 0F, 0F);
      gun243 = new ModelRenderer(this, 100, 0);
      gun243.addBox(0F, 0F, 0F, 3, 10, 2);
      gun243.setRotationPoint(-3.4F, -8.9F, 29.7F);
      gun243.setTextureSize(64, 32);
      gun243.mirror = true;
      setRotation(gun243, -0.0872665F, 0F, 0F);
      gun244 = new ModelRenderer(this, 100, 0);
      gun244.addBox(0F, 0F, 0F, 1, 10, 2);
      gun244.setRotationPoint(-0.6F, -8.9F, 29.7F);
      gun244.setTextureSize(64, 32);
      gun244.mirror = true;
      setRotation(gun244, -0.0872665F, 0F, 0F);
      gun245 = new ModelRenderer(this, 100, 0);
      gun245.addBox(0F, 0F, 0F, 1, 2, 1);
      gun245.setRotationPoint(-1.1F, -9.9F, 30.8F);
      gun245.setTextureSize(64, 32);
      gun245.mirror = true;
      setRotation(gun245, -0.0872665F, 0F, 0F);
      gun348 = new ModelRenderer(this, 100, 0);
      gun348.addBox(0F, 0F, 0F, 1, 1, 3);
      gun348.setRotationPoint(-0.4F, -8.6F, 7.5F);
      gun348.setTextureSize(64, 32);
      gun348.mirror = true;
      setRotation(gun348, -0.1858931F, 0F, 0F);
      gun349 = new ModelRenderer(this, 100, 0);
      gun349.addBox(0F, 0F, 0F, 1, 3, 1);
      gun349.setRotationPoint(-0.1F, -9.5F, 8.5F);
      gun349.setTextureSize(64, 32);
      gun349.mirror = true;
      setRotation(gun349, -0.1858931F, 0F, 0F);
      gun365 = new ModelRenderer(this, 100, 0);
      gun365.addBox(0F, 0F, 0F, 2, 1, 4);
      gun365.setRotationPoint(-2.5F, -12F, 3.5F);
      gun365.setTextureSize(64, 32);
      gun365.mirror = true;
      setRotation(gun365, -0.1858931F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun233.render(f5);
    gun234.render(f5);
    gun235.render(f5);
    gun236.render(f5);
    gun237.render(f5);
    gun238.render(f5);
    gun239.render(f5);
    gun240.render(f5);
    gun241.render(f5);
    gun242.render(f5);
    gun243.render(f5);
    gun244.render(f5);
    gun245.render(f5);
    gun348.render(f5);
    gun349.render(f5);
    gun365.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
