// Date: 1/4/2017 7:28:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class DragunovMag extends ModelBase
{
  //fields
    ModelRenderer gun2;
    ModelRenderer gun99;
    ModelRenderer gun100;
    ModelRenderer gun4;
    ModelRenderer gun5;
    ModelRenderer gun6;
    ModelRenderer gun7;
    ModelRenderer gun8;
    ModelRenderer gun9;
    ModelRenderer gun10;
    ModelRenderer gun11;
    ModelRenderer gun12;
    ModelRenderer gun13;
    ModelRenderer gun14;
  
  public DragunovMag()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun2 = new ModelRenderer(this, 0, 0);
      gun2.addBox(0F, 0F, 0F, 3, 6, 7);
      gun2.setRotationPoint(1F, -11F, 2.5F);
      gun2.setTextureSize(64, 32);
      gun2.mirror = true;
      setRotation(gun2, -1.673038F, 0F, 0F);
      gun99 = new ModelRenderer(this, 0, 0);
      gun99.addBox(0F, 0F, 0F, 3, 9, 7);
      gun99.setRotationPoint(1F, -11F, 2.5F);
      gun99.setTextureSize(64, 32);
      gun99.mirror = true;
      setRotation(gun99, -1.673038F, 0F, 0F);
      gun100 = new ModelRenderer(this, 0, 0);
      gun100.addBox(0F, 0F, 0F, 4, 6, 7);
      gun100.setRotationPoint(0.5F, -11F, 2F);
      gun100.setTextureSize(64, 32);
      gun100.mirror = true;
      setRotation(gun100, -1.673038F, 0F, 0F);
      gun4 = new ModelRenderer(this, 0, 0);
      gun4.addBox(0F, 0F, 0F, 1, 6, 1);
      gun4.setRotationPoint(0.3F, -10.5F, -4F);
      gun4.setTextureSize(64, 32);
      gun4.mirror = true;
      setRotation(gun4, 0.3346075F, 0F, 0F);
      gun5 = new ModelRenderer(this, 0, 0);
      gun5.addBox(0F, 0F, 0F, 1, 6, 1);
      gun5.setRotationPoint(3.7F, -10.5F, -4F);
      gun5.setTextureSize(64, 32);
      gun5.mirror = true;
      setRotation(gun5, 0.3346075F, 0F, 0F);
      gun6 = new ModelRenderer(this, 0, 0);
      gun6.addBox(0F, 0F, 0F, 1, 1, 4);
      gun6.setRotationPoint(0.3F, -11.5F, -3.9F);
      gun6.setTextureSize(64, 32);
      gun6.mirror = true;
      setRotation(gun6, -0.1115358F, 0F, 0F);
      gun7 = new ModelRenderer(this, 0, 0);
      gun7.addBox(0F, 0F, 0F, 1, 1, 4);
      gun7.setRotationPoint(3.7F, -11.5F, -3.9F);
      gun7.setTextureSize(64, 32);
      gun7.mirror = true;
      setRotation(gun7, -0.1115358F, 0F, 0F);
      gun8 = new ModelRenderer(this, 0, 0);
      gun8.addBox(0F, 0F, 0F, 1, 1, 6);
      gun8.setRotationPoint(0.3F, -10.1F, -0.1F);
      gun8.setTextureSize(64, 32);
      gun8.mirror = true;
      setRotation(gun8, -2.119181F, 0F, 0F);
      gun9 = new ModelRenderer(this, 0, 0);
      gun9.addBox(0F, 0F, 0F, 1, 1, 6);
      gun9.setRotationPoint(3.7F, -10.1F, -0.1F);
      gun9.setTextureSize(64, 32);
      gun9.mirror = true;
      setRotation(gun9, -2.119181F, 0F, 0F);
      gun10 = new ModelRenderer(this, 0, 0);
      gun10.addBox(0F, 0F, 0F, 1, 1, 6);
      gun10.setRotationPoint(0.8F, -11F, -4.2F);
      gun10.setTextureSize(64, 32);
      gun10.mirror = true;
      setRotation(gun10, -1.673038F, 0F, 0F);
      gun11 = new ModelRenderer(this, 0, 0);
      gun11.addBox(0F, 0F, 0F, 1, 1, 6);
      gun11.setRotationPoint(3.2F, -11F, -4.2F);
      gun11.setTextureSize(64, 32);
      gun11.mirror = true;
      setRotation(gun11, -1.673038F, 0F, 0F);
      gun12 = new ModelRenderer(this, 0, 0);
      gun12.addBox(0F, 0F, 0F, 1, 1, 6);
      gun12.setRotationPoint(3.2F, -11.1F, -5.5F);
      gun12.setTextureSize(64, 32);
      gun12.mirror = true;
      setRotation(gun12, -1.673038F, 0F, 0F);
      gun13 = new ModelRenderer(this, 0, 0);
      gun13.addBox(0F, 0F, 0F, 1, 1, 6);
      gun13.setRotationPoint(0.8F, -11.1F, -5.5F);
      gun13.setTextureSize(64, 32);
      gun13.mirror = true;
      setRotation(gun13, -1.673038F, 0F, 0F);
      gun14 = new ModelRenderer(this, 0, 0);
      gun14.addBox(0F, 0F, 0F, 3, 1, 7);
      gun14.setRotationPoint(1F, -11.75F, -5.6F);
      gun14.setTextureSize(64, 32);
      gun14.mirror = true;
      setRotation(gun14, -1.673038F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun2.render(f5);
    gun99.render(f5);
    gun100.render(f5);
    gun4.render(f5);
    gun5.render(f5);
    gun6.render(f5);
    gun7.render(f5);
    gun8.render(f5);
    gun9.render(f5);
    gun10.render(f5);
    gun11.render(f5);
    gun12.render(f5);
    gun13.render(f5);
    gun14.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
