// Date: 10/27/2018 5:09:49 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Dufflebag extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer dufflebag1;
    ModelRenderer dufflebag2;
    ModelRenderer dufflebag3;
    ModelRenderer dufflebag4;
    ModelRenderer dufflebag5;
    ModelRenderer dufflebag6;
    ModelRenderer dufflebag7;
    ModelRenderer dufflebag8;
    ModelRenderer dufflebag9;
    ModelRenderer dufflebag10;
    ModelRenderer dufflebag11;
    ModelRenderer dufflebag12;
  
  public Dufflebag()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(256, 256);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(256, 256);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(256, 256);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(256, 256);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(256, 256);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(256, 256);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      dufflebag1 = new ModelRenderer(this, 0, 100);
      dufflebag1.addBox(1F, -4F, 2F, 6, 16, 6);
      dufflebag1.setRotationPoint(0F, 0F, 0F);
      dufflebag1.setTextureSize(256, 256);
      dufflebag1.mirror = true;
      setRotation(dufflebag1, 0F, 0F, 0.7807508F);
      dufflebag2 = new ModelRenderer(this, 0, 100);
      dufflebag2.addBox(0.5F, -4F, 3F, 1, 16, 4);
      dufflebag2.setRotationPoint(0F, 0F, 0F);
      dufflebag2.setTextureSize(256, 256);
      dufflebag2.mirror = true;
      setRotation(dufflebag2, 0F, 0F, 0.7807508F);
      dufflebag3 = new ModelRenderer(this, 0, 100);
      dufflebag3.addBox(6.5F, -4F, 3F, 1, 16, 4);
      dufflebag3.setRotationPoint(0F, 0F, 0F);
      dufflebag3.setTextureSize(256, 256);
      dufflebag3.mirror = true;
      setRotation(dufflebag3, 0F, 0F, 0.7807508F);
      dufflebag4 = new ModelRenderer(this, 0, 100);
      dufflebag4.addBox(1.1F, -1F, 6.1F, 6, 2, 2);
      dufflebag4.setRotationPoint(0F, 0F, 0F);
      dufflebag4.setTextureSize(256, 256);
      dufflebag4.mirror = true;
      setRotation(dufflebag4, 0F, 0F, 0.7807508F);
      dufflebag5 = new ModelRenderer(this, 0, 100);
      dufflebag5.addBox(0.9F, -1F, 6.1F, 1, 2, 2);
      dufflebag5.setRotationPoint(0F, 0F, 0F);
      dufflebag5.setTextureSize(256, 256);
      dufflebag5.mirror = true;
      setRotation(dufflebag5, 0F, 0F, 0.7807508F);
      dufflebag6 = new ModelRenderer(this, 0, 100);
      dufflebag6.addBox(1.1F, 6F, 6.1F, 6, 2, 2);
      dufflebag6.setRotationPoint(0F, 0F, 0F);
      dufflebag6.setTextureSize(256, 256);
      dufflebag6.mirror = true;
      setRotation(dufflebag6, 0F, 0F, 0.7807508F);
      dufflebag7 = new ModelRenderer(this, 0, 100);
      dufflebag7.addBox(0.9F, 6F, 6.1F, 1, 2, 2);
      dufflebag7.setRotationPoint(0F, 0F, 0F);
      dufflebag7.setTextureSize(256, 256);
      dufflebag7.mirror = true;
      setRotation(dufflebag7, 0F, 0F, 0.7807508F);
      dufflebag8 = new ModelRenderer(this, 0, 100);
      dufflebag8.addBox(6.6F, -3.5F, 5.5F, 1, 15, 1);
      dufflebag8.setRotationPoint(0F, 0F, 0F);
      dufflebag8.setTextureSize(256, 256);
      dufflebag8.mirror = true;
      setRotation(dufflebag8, 0F, 0F, 0.7807508F);
      dufflebag9 = new ModelRenderer(this, 0, 100);
      dufflebag9.addBox(0.4F, -3.5F, 5.5F, 1, 15, 1);
      dufflebag9.setRotationPoint(0F, 0F, 0F);
      dufflebag9.setTextureSize(256, 256);
      dufflebag9.mirror = true;
      setRotation(dufflebag9, 0F, 0F, 0.7807508F);
      dufflebag10 = new ModelRenderer(this, 0, 100);
      dufflebag10.addBox(-4.1F, 10F, -2.1F, 1, 1, 5);
      dufflebag10.setRotationPoint(0F, 0F, 0F);
      dufflebag10.setTextureSize(256, 256);
      dufflebag10.mirror = true;
      setRotation(dufflebag10, 0F, 0F, 0F);
      dufflebag11 = new ModelRenderer(this, 0, 100);
      dufflebag11.addBox(2.5F, -0.1F, -2.1F, 1, 1, 5);
      dufflebag11.setRotationPoint(0F, 0F, 0F);
      dufflebag11.setTextureSize(256, 256);
      dufflebag11.mirror = true;
      setRotation(dufflebag11, 0F, 0F, 0F);
      dufflebag12 = new ModelRenderer(this, 0, 100);
      dufflebag12.addBox(2.4F, -1F, -2.1F, 1, 12, 1);
      dufflebag12.setRotationPoint(0F, 0F, 0F);
      dufflebag12.setTextureSize(256, 256);
      dufflebag12.mirror = true;
      setRotation(dufflebag12, 0F, 0F, 0.5576792F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    dufflebag1.render(f5);
    dufflebag2.render(f5);
    dufflebag3.render(f5);
    dufflebag4.render(f5);
    dufflebag5.render(f5);
    dufflebag6.render(f5);
    dufflebag7.render(f5);
    dufflebag8.render(f5);
    dufflebag9.render(f5);
    dufflebag10.render(f5);
    dufflebag11.render(f5);
    dufflebag12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
