// Date: 2/18/2019 11:20:35 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ElectricBoxOpened extends ModelBase
{
  //fields
    ModelRenderer ElectricBox1;
    ModelRenderer ElectricBox2;
    ModelRenderer ElectricBox3;
    ModelRenderer ElectricBox4;
    ModelRenderer ElectricBox5;
    ModelRenderer ElectricBox6;
    ModelRenderer ElectricBox7;
    ModelRenderer ElectricBox8;
    ModelRenderer ElectricBox9;
    ModelRenderer ElectricBox10;
    ModelRenderer ElectricBox11;
    ModelRenderer ElectricBox12;
    ModelRenderer ElectricBox13;
    ModelRenderer ElectricBox14;
    ModelRenderer ElectricBox15;
    ModelRenderer ElectricBox16;
    ModelRenderer ElectricBox17;
  
  public ElectricBoxOpened()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      ElectricBox1 = new ModelRenderer(this, 0, 0);
      ElectricBox1.addBox(0F, 0F, 0F, 12, 2, 5);
      ElectricBox1.setRotationPoint(-6F, -8F, 3F);
      ElectricBox1.setTextureSize(256, 256);
      ElectricBox1.mirror = true;
      setRotation(ElectricBox1, 0F, 0F, 0F);
      ElectricBox2 = new ModelRenderer(this, 0, 0);
      ElectricBox2.addBox(-0.7F, 0F, 0F, 10, 14, 1);
      ElectricBox2.setRotationPoint(-5F, -7F, 2.5F);
      ElectricBox2.setTextureSize(256, 256);
      ElectricBox2.mirror = true;
      setRotation(ElectricBox2, 0F, 2.007645F, 0F);
      ElectricBox3 = new ModelRenderer(this, 0, 40);
      ElectricBox3.addBox(0F, 0F, 0F, 2, 16, 2);
      ElectricBox3.setRotationPoint(-1F, 8F, 5F);
      ElectricBox3.setTextureSize(256, 256);
      ElectricBox3.mirror = true;
      setRotation(ElectricBox3, 0F, -0.7853982F, 0F);
      ElectricBox4 = new ModelRenderer(this, 0, 40);
      ElectricBox4.addBox(0F, 0F, 0F, 2, 16, 2);
      ElectricBox4.setRotationPoint(0.5F, 8F, 5F);
      ElectricBox4.setTextureSize(256, 256);
      ElectricBox4.mirror = true;
      setRotation(ElectricBox4, 0F, -0.7853982F, 0F);
      ElectricBox5 = new ModelRenderer(this, 0, 0);
      ElectricBox5.addBox(0F, 0F, 0F, 12, 2, 5);
      ElectricBox5.setRotationPoint(-6F, 6F, 3F);
      ElectricBox5.setTextureSize(256, 256);
      ElectricBox5.mirror = true;
      setRotation(ElectricBox5, 0F, 0F, 0F);
      ElectricBox6 = new ModelRenderer(this, 0, 0);
      ElectricBox6.addBox(0F, 0F, 0F, 2, 12, 5);
      ElectricBox6.setRotationPoint(-6F, -6F, 3F);
      ElectricBox6.setTextureSize(256, 256);
      ElectricBox6.mirror = true;
      setRotation(ElectricBox6, 0F, 0F, 0F);
      ElectricBox7 = new ModelRenderer(this, 0, 0);
      ElectricBox7.addBox(0F, 0F, 0F, 2, 12, 5);
      ElectricBox7.setRotationPoint(4F, -6F, 3F);
      ElectricBox7.setTextureSize(256, 256);
      ElectricBox7.mirror = true;
      setRotation(ElectricBox7, 0F, 0F, 0F);
      ElectricBox8 = new ModelRenderer(this, 0, 0);
      ElectricBox8.addBox(0F, 0F, 0F, 8, 12, 4);
      ElectricBox8.setRotationPoint(-4F, -6F, 4F);
      ElectricBox8.setTextureSize(256, 256);
      ElectricBox8.mirror = true;
      setRotation(ElectricBox8, 0F, 0F, 0F);
      ElectricBox9 = new ModelRenderer(this, 0, 90);
      ElectricBox9.addBox(0F, 0F, 0F, 7, 5, 1);
      ElectricBox9.setRotationPoint(-3.5F, -4F, 3.5F);
      ElectricBox9.setTextureSize(256, 256);
      ElectricBox9.mirror = true;
      setRotation(ElectricBox9, 0F, 0F, 0F);
      ElectricBox10 = new ModelRenderer(this, 0, 70);
      ElectricBox10.addBox(0F, 0F, 0F, 1, 3, 1);
      ElectricBox10.setRotationPoint(-3F, -3F, 3.3F);
      ElectricBox10.setTextureSize(256, 256);
      ElectricBox10.mirror = true;
      setRotation(ElectricBox10, 0F, 0F, 0F);
      ElectricBox11 = new ModelRenderer(this, 0, 70);
      ElectricBox11.addBox(0F, 0F, 0F, 1, 3, 1);
      ElectricBox11.setRotationPoint(-1.5F, -3F, 3.3F);
      ElectricBox11.setTextureSize(256, 256);
      ElectricBox11.mirror = true;
      setRotation(ElectricBox11, 0F, 0F, 0F);
      ElectricBox12 = new ModelRenderer(this, 0, 70);
      ElectricBox12.addBox(0F, 0F, 0F, 1, 3, 1);
      ElectricBox12.setRotationPoint(0.5F, -3F, 3.3F);
      ElectricBox12.setTextureSize(256, 256);
      ElectricBox12.mirror = true;
      setRotation(ElectricBox12, 0F, 0F, 0F);
      ElectricBox13 = new ModelRenderer(this, 0, 70);
      ElectricBox13.addBox(0F, 0F, 0F, 1, 3, 1);
      ElectricBox13.setRotationPoint(2F, -3F, 3.3F);
      ElectricBox13.setTextureSize(256, 256);
      ElectricBox13.mirror = true;
      setRotation(ElectricBox13, 0F, 0F, 0F);
      ElectricBox14 = new ModelRenderer(this, 0, 70);
      ElectricBox14.addBox(0F, -0.5F, 0F, 1, 2, 1);
      ElectricBox14.setRotationPoint(-3F, -2F, 3.3F);
      ElectricBox14.setTextureSize(256, 256);
      ElectricBox14.mirror = true;
      setRotation(ElectricBox14, -0.9666439F, 0F, 0F);
      ElectricBox15 = new ModelRenderer(this, 0, 70);
      ElectricBox15.addBox(0F, -0.5F, 0F, 1, 2, 1);
      ElectricBox15.setRotationPoint(0.5F, -2F, 3.3F);
      ElectricBox15.setTextureSize(256, 256);
      ElectricBox15.mirror = true;
      setRotation(ElectricBox15, -0.9666439F, 0F, 0F);
      ElectricBox16 = new ModelRenderer(this, 0, 70);
      ElectricBox16.addBox(0F, -1.5F, 0F, 1, 2, 1);
      ElectricBox16.setRotationPoint(-1.5F, -1F, 3.3F);
      ElectricBox16.setTextureSize(256, 256);
      ElectricBox16.mirror = true;
      setRotation(ElectricBox16, 0.9666506F, 0F, 0F);
      ElectricBox17 = new ModelRenderer(this, 0, 70);
      ElectricBox17.addBox(0F, -1.5F, 0F, 1, 2, 1);
      ElectricBox17.setRotationPoint(2F, -1F, 3.3F);
      ElectricBox17.setTextureSize(256, 256);
      ElectricBox17.mirror = true;
      setRotation(ElectricBox17, 0.9666506F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    ElectricBox1.render(f5);
    ElectricBox2.render(f5);
    ElectricBox3.render(f5);
    ElectricBox4.render(f5);
    ElectricBox5.render(f5);
    ElectricBox6.render(f5);
    ElectricBox7.render(f5);
    ElectricBox8.render(f5);
    ElectricBox9.render(f5);
    ElectricBox10.render(f5);
    ElectricBox11.render(f5);
    ElectricBox12.render(f5);
    ElectricBox13.render(f5);
    ElectricBox14.render(f5);
    ElectricBox15.render(f5);
    ElectricBox16.render(f5);
    ElectricBox17.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
