// Date: 2/18/2019 11:15:45 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ElectricBox extends ModelBase
{
  //fields
    ModelRenderer ElectricBox1;
    ModelRenderer ElectricBox2;
    ModelRenderer ElectricBox3;
    ModelRenderer ElectricBox4;
  
  public ElectricBox()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      ElectricBox1 = new ModelRenderer(this, 0, 0);
      ElectricBox1.addBox(0F, 0F, 0F, 12, 16, 5);
      ElectricBox1.setRotationPoint(-6F, -8F, 3F);
      ElectricBox1.setTextureSize(256, 256);
      ElectricBox1.mirror = true;
      setRotation(ElectricBox1, 0F, 0F, 0F);
      ElectricBox2 = new ModelRenderer(this, 0, 0);
      ElectricBox2.addBox(0F, 0F, 0F, 10, 14, 1);
      ElectricBox2.setRotationPoint(-5F, -7F, 2.5F);
      ElectricBox2.setTextureSize(256, 256);
      ElectricBox2.mirror = true;
      setRotation(ElectricBox2, 0F, 0F, 0F);
      ElectricBox3 = new ModelRenderer(this, 0, 40);
      ElectricBox3.addBox(0F, 0F, 0F, 2, 16, 2);
      ElectricBox3.setRotationPoint(-1F, 8F, 5F);
      ElectricBox3.setTextureSize(256, 256);
      ElectricBox3.mirror = true;
      setRotation(ElectricBox3, 0F, -0.7853982F, 0F);
      ElectricBox4 = new ModelRenderer(this, 0, 40);
      ElectricBox4.addBox(0F, 0F, 0F, 2, 16, 2);
      ElectricBox4.setRotationPoint(0.5F, 8F, 5F);
      ElectricBox4.setTextureSize(256, 256);
      ElectricBox4.mirror = true;
      setRotation(ElectricBox4, 0F, -0.7853982F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    ElectricBox1.render(f5);
    ElectricBox2.render(f5);
    ElectricBox3.render(f5);
    ElectricBox4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
