// Date: 5/7/2017 1:14:30 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class FamasBipod extends ModelBase
{
  //fields
    ModelRenderer Bipod1;
    ModelRenderer Bipod2;
    ModelRenderer Bipod3;
    ModelRenderer Bipod4;
    ModelRenderer Bipod5;
    ModelRenderer Bipod6;
    ModelRenderer Bipod7;
    ModelRenderer Bipod8;
    ModelRenderer Bipod9;
    ModelRenderer Bipod10;
    ModelRenderer Bipod11;
    ModelRenderer Bipod122;
    ModelRenderer Bipod111;
    ModelRenderer Bipod12;
    ModelRenderer Bipod13;
    ModelRenderer Bipod14;
    ModelRenderer Bipod15;
    ModelRenderer Bipod16;
    ModelRenderer Bipod17;
  
  public FamasBipod()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Bipod1 = new ModelRenderer(this, 0, 0);
      Bipod1.addBox(0F, 0F, 0F, 1, 2, 2);
      Bipod1.setRotationPoint(0F, 0F, 0F);
      Bipod1.setTextureSize(128, 64);
      Bipod1.mirror = true;
      setRotation(Bipod1, 0F, 0F, 0F);
      Bipod2 = new ModelRenderer(this, 0, 0);
      Bipod2.addBox(0F, 0F, 0F, 1, 3, 4);
      Bipod2.setRotationPoint(0.5F, -0.5F, -1F);
      Bipod2.setTextureSize(128, 64);
      Bipod2.mirror = true;
      setRotation(Bipod2, 0F, 0F, 0F);
      Bipod3 = new ModelRenderer(this, 0, 0);
      Bipod3.addBox(0F, 0F, 0F, 1, 2, 1);
      Bipod3.setRotationPoint(0.5F, 0F, -1.5F);
      Bipod3.setTextureSize(128, 64);
      Bipod3.mirror = true;
      setRotation(Bipod3, 0F, 0F, 0F);
      Bipod4 = new ModelRenderer(this, 0, 0);
      Bipod4.addBox(0F, 0F, 0F, 1, 1, 3);
      Bipod4.setRotationPoint(0.5F, 0.5F, 2.9F);
      Bipod4.setTextureSize(128, 64);
      Bipod4.mirror = true;
      setRotation(Bipod4, 0F, 0F, 0F);
      Bipod5 = new ModelRenderer(this, 0, 0);
      Bipod5.addBox(0F, 0F, 0F, 1, 1, 3);
      Bipod5.setRotationPoint(0.5F, -0.5F, 3F);
      Bipod5.setTextureSize(128, 64);
      Bipod5.mirror = true;
      setRotation(Bipod5, -0.3346075F, 0F, 0F);
      Bipod6 = new ModelRenderer(this, 0, 0);
      Bipod6.addBox(0F, 0F, 0F, 1, 3, 1);
      Bipod6.setRotationPoint(0.5F, 2.5F, 3F);
      Bipod6.setTextureSize(128, 64);
      Bipod6.mirror = true;
      setRotation(Bipod6, 1.896109F, 0F, 0F);
      Bipod7 = new ModelRenderer(this, 0, 0);
      Bipod7.addBox(0F, 0F, 0F, 1, 1, 35);
      Bipod7.setRotationPoint(0.3F, 0.5F, 2F);
      Bipod7.setTextureSize(128, 64);
      Bipod7.mirror = true;
      setRotation(Bipod7, 0F, 0F, 0F);
      Bipod8 = new ModelRenderer(this, 0, 0);
      Bipod8.addBox(0F, 0F, 0F, 1, 3, 1);
      Bipod8.setRotationPoint(0.8F, -0.5F, 36F);
      Bipod8.setTextureSize(128, 64);
      Bipod8.mirror = true;
      setRotation(Bipod8, 0F, 0F, 0F);
      Bipod9 = new ModelRenderer(this, 0, 0);
      Bipod9.addBox(0F, 0F, 0F, 1, 3, 2);
      Bipod9.setRotationPoint(0F, -0.5F, 36F);
      Bipod9.setTextureSize(128, 64);
      Bipod9.mirror = true;
      setRotation(Bipod9, 0F, 0F, 0F);
      Bipod10 = new ModelRenderer(this, 0, 0);
      Bipod10.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod10.setRotationPoint(0.3F, 0.4F, 35F);
      Bipod10.setTextureSize(128, 64);
      Bipod10.mirror = true;
      setRotation(Bipod10, 0F, 0F, 0F);
      Bipod11 = new ModelRenderer(this, 0, 0);
      Bipod11.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod11.setRotationPoint(0.3F, 0.6F, 35F);
      Bipod11.setTextureSize(128, 64);
      Bipod11.mirror = true;
      setRotation(Bipod11, 0F, 0F, 0F);
      Bipod122 = new ModelRenderer(this, 0, 0);
      Bipod122.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod122.setRotationPoint(0.4F, 0.5F, 35F);
      Bipod122.setTextureSize(128, 64);
      Bipod122.mirror = true;
      setRotation(Bipod122, 0F, 0F, 0F);
      Bipod111 = new ModelRenderer(this, 0, 0);
      Bipod111.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod111.setRotationPoint(0.2F, 0.5F, 35F);
      Bipod111.setTextureSize(128, 64);
      Bipod111.mirror = true;
      setRotation(Bipod111, 0F, 0F, 0F);
      Bipod12 = new ModelRenderer(this, 0, 0);
      Bipod12.addBox(0F, 0F, 0F, 1, 2, 2);
      Bipod12.setRotationPoint(0.3F, 0F, 8F);
      Bipod12.setTextureSize(128, 64);
      Bipod12.mirror = true;
      setRotation(Bipod12, 0F, 0F, 0F);
      Bipod13 = new ModelRenderer(this, 0, 0);
      Bipod13.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod13.setRotationPoint(0.3F, 0F, 8F);
      Bipod13.setTextureSize(128, 64);
      Bipod13.mirror = true;
      setRotation(Bipod13, -1.003822F, 0F, 0F);
      Bipod14 = new ModelRenderer(this, 0, 0);
      Bipod14.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod14.setRotationPoint(0.3F, 2F, 8F);
      Bipod14.setTextureSize(128, 64);
      Bipod14.mirror = true;
      setRotation(Bipod14, 2.528146F, 0F, 0F);
      Bipod15 = new ModelRenderer(this, 0, 0);
      Bipod15.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod15.setRotationPoint(0.3F, 0F, 10F);
      Bipod15.setTextureSize(128, 64);
      Bipod15.mirror = true;
      setRotation(Bipod15, -0.7063936F, 0F, 0F);
      Bipod16 = new ModelRenderer(this, 0, 0);
      Bipod16.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod16.setRotationPoint(0.3F, 2F, 10F);
      Bipod16.setTextureSize(128, 64);
      Bipod16.mirror = true;
      setRotation(Bipod16, 2.230717F, 0F, 0F);
      Bipod17 = new ModelRenderer(this, 0, 0);
      Bipod17.addBox(0F, 0F, 0F, 1, 1, 1);
      Bipod17.setRotationPoint(0.7F, 0.5F, -0.5F);
      Bipod17.setTextureSize(128, 64);
      Bipod17.mirror = true;
      setRotation(Bipod17, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bipod1.render(f5);
    Bipod2.render(f5);
    Bipod3.render(f5);
    Bipod4.render(f5);
    Bipod5.render(f5);
    Bipod6.render(f5);
    Bipod7.render(f5);
    Bipod8.render(f5);
    Bipod9.render(f5);
    Bipod10.render(f5);
    Bipod111.render(f5);
    Bipod122.render(f5);
    Bipod11.render(f5);
    Bipod12.render(f5);
    Bipod13.render(f5);
    Bipod14.render(f5);
    Bipod15.render(f5);
    Bipod16.render(f5);
    Bipod17.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
