// Date: 5/6/2017 8:42:09 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import com.vicmatskiv.weaponlib.ModelWithAttachments;

public class FamasAction extends ModelWithAttachments
{
  //fields
    
    ModelRenderer Famas280;
    ModelRenderer Famas281;
    ModelRenderer Famas282;
    ModelRenderer Famas283;
    ModelRenderer Famas284;
    ModelRenderer Famas285;
    ModelRenderer Famas286;
    ModelRenderer Famas287;
  
  public FamasAction()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      
      Famas280 = new ModelRenderer(this, 0, 0);
      Famas280.addBox(0F, 0F, 0F, 1, 1, 6);
      Famas280.setRotationPoint(-2F, -15.7F, -19F);
      Famas280.setTextureSize(64, 32);
      Famas280.mirror = true;
      setRotation(Famas280, 0F, 0F, 0F);
      Famas281 = new ModelRenderer(this, 0, 0);
      Famas281.addBox(0F, 0F, 0F, 2, 3, 1);
      Famas281.setRotationPoint(-2.5F, -17.6F, -19F);
      Famas281.setTextureSize(64, 32);
      Famas281.mirror = true;
      setRotation(Famas281, -0.2230717F, 0F, 0F);
      Famas282 = new ModelRenderer(this, 0, 0);
      Famas282.addBox(0F, 0F, 0F, 2, 1, 2);
      Famas282.setRotationPoint(-2.5F, -17.6F, -19F);
      Famas282.setTextureSize(64, 32);
      Famas282.mirror = true;
      setRotation(Famas282, 1.003822F, 0F, 0F);
      Famas283 = new ModelRenderer(this, 0, 0);
      Famas283.addBox(0F, 0F, 0F, 2, 1, 1);
      Famas283.setRotationPoint(-2.5F, -19.3F, -17.9F);
      Famas283.setTextureSize(64, 32);
      Famas283.mirror = true;
      setRotation(Famas283, 0.3717861F, 0F, 0F);
      Famas284 = new ModelRenderer(this, 0, 0);
      Famas284.addBox(0F, 0F, 0F, 2, 3, 1);
      Famas284.setRotationPoint(-2.5F, -17.6F, -19F);
      Famas284.setTextureSize(64, 32);
      Famas284.mirror = true;
      setRotation(Famas284, 0.1487144F, 0F, 0F);
      Famas285 = new ModelRenderer(this, 0, 0);
      Famas285.addBox(0F, 0F, 0F, 1, 5, 1);
      Famas285.setRotationPoint(-2F, -15.7F, -13F);
      Famas285.setTextureSize(64, 32);
      Famas285.mirror = true;
      setRotation(Famas285, -1.747395F, 0F, 0F);
      Famas286 = new ModelRenderer(this, 0, 0);
      Famas286.addBox(0F, 0F, 0F, 2, 1, 2);
      Famas286.setRotationPoint(-2.5F, -15.6F, -18.5F);
      Famas286.setTextureSize(64, 32);
      Famas286.mirror = true;
      setRotation(Famas286, 0F, 0F, 0F);
      Famas287 = new ModelRenderer(this, 0, 0);
      Famas287.addBox(0F, 0F, 0F, 2, 2, 1);
      Famas287.setRotationPoint(-2.5F, -15.6F, -16.5F);
      Famas287.setTextureSize(64, 32);
      Famas287.mirror = true;
      setRotation(Famas287, -2.156359F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    Famas280.render(f5);
    Famas281.render(f5);
    Famas282.render(f5);
    Famas283.render(f5);
    Famas284.render(f5);
    Famas285.render(f5);
    Famas286.render(f5);
    Famas287.render(f5);
  }

}
