// Date: 5/7/2017 3:32:49 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class FelinAction extends ModelBase
{
  //fields
    
    ModelRenderer CarryHandle146;
    ModelRenderer CarryHandle147;
    ModelRenderer CarryHandle148;
    ModelRenderer CarryHandle149;
    ModelRenderer CarryHandle150;
  
  public FelinAction()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      
      CarryHandle146 = new ModelRenderer(this, 0, 0);
      CarryHandle146.addBox(0F, 0F, 0F, 4, 4, 2);
      CarryHandle146.setRotationPoint(-4F, -9F, -26F);
      CarryHandle146.setTextureSize(64, 32);
      CarryHandle146.mirror = true;
      setRotation(CarryHandle146, 0F, 0F, 0F);
      CarryHandle147 = new ModelRenderer(this, 0, 0);
      CarryHandle147.addBox(0F, 0F, 0F, 4, 2, 4);
      CarryHandle147.setRotationPoint(-4F, -9F, -24F);
      CarryHandle147.setTextureSize(64, 32);
      CarryHandle147.mirror = true;
      setRotation(CarryHandle147, -1.115358F, 0F, 0F);
      CarryHandle148 = new ModelRenderer(this, 0, 0);
      CarryHandle148.addBox(0F, 0F, 0F, 4, 2, 1);
      CarryHandle148.setRotationPoint(-0.2F, -9.5F, -26F);
      CarryHandle148.setTextureSize(64, 32);
      CarryHandle148.mirror = true;
      setRotation(CarryHandle148, 0F, 0F, 0F);
      CarryHandle149 = new ModelRenderer(this, 0, 0);
      CarryHandle149.addBox(0F, 0F, 0F, 1, 2, 1);
      CarryHandle149.setRotationPoint(0F, -9.5F, -25F);
      CarryHandle149.setTextureSize(64, 32);
      CarryHandle149.mirror = true;
      setRotation(CarryHandle149, 0F, 0F, 0F);
      CarryHandle150 = new ModelRenderer(this, 0, 0);
      CarryHandle150.addBox(0F, 0F, 0F, 1, 2, 3);
      CarryHandle150.setRotationPoint(1F, -9.5F, -24F);
      CarryHandle150.setTextureSize(64, 32);
      CarryHandle150.mirror = true;
      setRotation(CarryHandle150, 0F, 1.933288F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    CarryHandle146.render(f5);
    CarryHandle147.render(f5);
    CarryHandle148.render(f5);
    CarryHandle149.render(f5);
    CarryHandle150.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
