// Date: 7/30/2019 11:23:34 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class FloodLight extends ModelBase
{
  //fields
    ModelRenderer lamp1;
    ModelRenderer lamp2;
    ModelRenderer lamp3;
    ModelRenderer lamp4;
    ModelRenderer lamp5;
    ModelRenderer lamp6;
    ModelRenderer lamp7;
    ModelRenderer lamp8;
    ModelRenderer lamp9;
    ModelRenderer lamp10;
    ModelRenderer lamp12;
    ModelRenderer lamp13;
    ModelRenderer lamp14;
    ModelRenderer lamp15;
    ModelRenderer lamp16;
    ModelRenderer lamp17;
  
  public FloodLight()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      lamp1 = new ModelRenderer(this, 0, 0);
      lamp1.addBox(0F, 0F, 0F, 12, 2, 2);
      lamp1.setRotationPoint(-6F, 21.5F, -1F);
      lamp1.setTextureSize(256, 256);
      lamp1.mirror = true;
      setRotation(lamp1, 0F, 0F, 0F);
      lamp2 = new ModelRenderer(this, 0, 0);
      lamp2.addBox(0F, 0F, 0F, 1, 1, 7);
      lamp2.setRotationPoint(-5.5F, 23F, -3.5F);
      lamp2.setTextureSize(256, 256);
      lamp2.mirror = true;
      setRotation(lamp2, 0F, 0F, 0F);
      lamp3 = new ModelRenderer(this, 0, 0);
      lamp3.addBox(0F, 0F, 0F, 1, 1, 7);
      lamp3.setRotationPoint(4.5F, 23F, -3.5F);
      lamp3.setTextureSize(256, 256);
      lamp3.mirror = true;
      setRotation(lamp3, 0F, 0F, 0F);
      lamp4 = new ModelRenderer(this, 0, 100);
      lamp4.addBox(0F, 0F, 0F, 10, 1, 1);
      lamp4.setRotationPoint(-5F, 21.2F, -0.5F);
      lamp4.setTextureSize(256, 256);
      lamp4.mirror = true;
      setRotation(lamp4, 0F, 0F, 0F);
      lamp5 = new ModelRenderer(this, 0, 100);
      lamp5.addBox(0F, 0F, 0F, 1, 6, 1);
      lamp5.setRotationPoint(-5F, 15.2F, -0.5F);
      lamp5.setTextureSize(256, 256);
      lamp5.mirror = true;
      setRotation(lamp5, 0F, 0F, 0F);
      lamp6 = new ModelRenderer(this, 0, 100);
      lamp6.addBox(0F, 0F, 0F, 1, 6, 1);
      lamp6.setRotationPoint(4F, 15.2F, -0.5F);
      lamp6.setTextureSize(256, 256);
      lamp6.mirror = true;
      setRotation(lamp6, 0F, 0F, 0F);
      lamp7 = new ModelRenderer(this, 0, 100);
      lamp7.addBox(0F, 0F, 0F, 8, 5, 4);
      lamp7.setRotationPoint(-4F, 13.2F, -0.5F);
      lamp7.setTextureSize(256, 256);
      lamp7.mirror = true;
      setRotation(lamp7, -0.1858931F, 0F, 0F);
      lamp8 = new ModelRenderer(this, 0, 100);
      lamp8.addBox(0F, -0.5F, -0.5F, 1, 6, 1);
      lamp8.setRotationPoint(-4.5F, 13.2F, -0.5F);
      lamp8.setTextureSize(256, 256);
      lamp8.mirror = true;
      setRotation(lamp8, -0.1858931F, 0F, 0F);
      lamp9 = new ModelRenderer(this, 0, 100);
      lamp9.addBox(0F, -0.5F, -0.5F, 1, 6, 1);
      lamp9.setRotationPoint(3.5F, 13.2F, -0.5F);
      lamp9.setTextureSize(256, 256);
      lamp9.mirror = true;
      setRotation(lamp9, -0.1858931F, 0F, 0F);
      lamp10 = new ModelRenderer(this, 0, 100);
      lamp10.addBox(0F, -0.5F, -0.5F, 7, 1, 1);
      lamp10.setRotationPoint(-3.5F, 13.2F, -0.5F);
      lamp10.setTextureSize(256, 256);
      lamp10.mirror = true;
      setRotation(lamp10, -0.1858931F, 0F, 0F);
      lamp12 = new ModelRenderer(this, 0, 100);
      lamp12.addBox(0F, 4.5F, -0.5F, 7, 1, 1);
      lamp12.setRotationPoint(-3.5F, 13.2F, -0.5F);
      lamp12.setTextureSize(256, 256);
      lamp12.mirror = true;
      setRotation(lamp12, -0.1858931F, 0F, 0F);
      lamp13 = new ModelRenderer(this, 0, 150);
      lamp13.addBox(0F, 0.5F, -0.3F, 7, 4, 1);
      lamp13.setRotationPoint(-3.5F, 13.2F, -0.5F);
      lamp13.setTextureSize(256, 256);
      lamp13.mirror = true;
      setRotation(lamp13, -0.1858931F, 0F, 0F);
      lamp14 = new ModelRenderer(this, 0, 0);
      lamp14.addBox(0F, -4F, 0F, 1, 8, 2);
      lamp14.setRotationPoint(-4.4F, 13.2F, -0.5F);
      lamp14.setTextureSize(256, 256);
      lamp14.mirror = true;
      setRotation(lamp14, -0.1858931F, 0F, 0F);
      lamp15 = new ModelRenderer(this, 0, 0);
      lamp15.addBox(0F, -4F, 0F, 1, 8, 2);
      lamp15.setRotationPoint(3.4F, 13.2F, -0.5F);
      lamp15.setTextureSize(256, 256);
      lamp15.mirror = true;
      setRotation(lamp15, -0.1858931F, 0F, 0F);
      lamp16 = new ModelRenderer(this, 0, 0);
      lamp16.addBox(1F, -4.2F, 0F, 8, 1, 2);
      lamp16.setRotationPoint(-5F, 13.2F, -0.5F);
      lamp16.setTextureSize(256, 256);
      lamp16.mirror = true;
      setRotation(lamp16, -0.1858931F, 0F, 0F);
      lamp17 = new ModelRenderer(this, 0, 100);
      lamp17.addBox(1F, -4.6F, -0.5F, 6, 2, 3);
      lamp17.setRotationPoint(-4F, 13.2F, -0.5F);
      lamp17.setTextureSize(256, 256);
      lamp17.mirror = true;
      setRotation(lamp17, -0.1858931F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    lamp1.render(f5);
    lamp2.render(f5);
    lamp3.render(f5);
    lamp4.render(f5);
    lamp5.render(f5);
    lamp6.render(f5);
    lamp7.render(f5);
    lamp8.render(f5);
    lamp9.render(f5);
    lamp10.render(f5);
    lamp12.render(f5);
    lamp13.render(f5);
    lamp14.render(f5);
    lamp15.render(f5);
    lamp16.render(f5);
    lamp17.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
