// Date: 1/4/2017 8:19:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class FNFALMag extends ModelBase
{
  //fields
    ModelRenderer gun16;
    ModelRenderer gun17;
    ModelRenderer gun18;
    ModelRenderer gun19;
    ModelRenderer gun20;
    ModelRenderer gun21;
    ModelRenderer gun22;
    ModelRenderer gun23;
  
  public FNFALMag()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun16 = new ModelRenderer(this, 0, 0);
      gun16.addBox(0F, 0F, 0F, 3, 14, 7);
      gun16.setRotationPoint(1F, -13F, -3.8F);
      gun16.setTextureSize(64, 32);
      gun16.mirror = true;
      setRotation(gun16, 0F, 0F, 0F);
      gun17 = new ModelRenderer(this, 0, 0);
      gun17.addBox(0F, 0F, 0F, 3, 6, 1);
      gun17.setRotationPoint(1F, 1F, -2.8F);
      gun17.setTextureSize(64, 32);
      gun17.mirror = true;
      setRotation(gun17, 1.449966F, 0F, 0F);
      gun18 = new ModelRenderer(this, 0, 0);
      gun18.addBox(0F, 0F, 0F, 1, 14, 2);
      gun18.setRotationPoint(0.9F, -13F, 1.2F);
      gun18.setTextureSize(64, 32);
      gun18.mirror = true;
      setRotation(gun18, 0F, 0F, 0F);
      gun19 = new ModelRenderer(this, 0, 0);
      gun19.addBox(0F, 0F, 0F, 1, 14, 2);
      gun19.setRotationPoint(0.9F, -13F, -1F);
      gun19.setTextureSize(64, 32);
      gun19.mirror = true;
      setRotation(gun19, 0F, 0F, 0F);
      gun20 = new ModelRenderer(this, 0, 0);
      gun20.addBox(0F, 0F, 0F, 3, 14, 2);
      gun20.setRotationPoint(0.9F, -13F, -3.3F);
      gun20.setTextureSize(64, 32);
      gun20.mirror = true;
      setRotation(gun20, 0F, 0F, 0F);
      gun21 = new ModelRenderer(this, 0, 0);
      gun21.addBox(0F, 0F, 0F, 1, 14, 2);
      gun21.setRotationPoint(3.1F, -13F, -3.3F);
      gun21.setTextureSize(64, 32);
      gun21.mirror = true;
      setRotation(gun21, 0F, 0F, 0F);
      gun22 = new ModelRenderer(this, 0, 0);
      gun22.addBox(0F, 0F, 0F, 1, 14, 2);
      gun22.setRotationPoint(3.1F, -13F, -1F);
      gun22.setTextureSize(64, 32);
      gun22.mirror = true;
      setRotation(gun22, 0F, 0F, 0F);
      gun23 = new ModelRenderer(this, 0, 0);
      gun23.addBox(0F, 0F, 0F, 1, 14, 2);
      gun23.setRotationPoint(3.1F, -13F, 1.2F);
      gun23.setTextureSize(64, 32);
      gun23.mirror = true;
      setRotation(gun23, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun16.render(f5);
    gun17.render(f5);
    gun18.render(f5);
    gun19.render(f5);
    gun20.render(f5);
    gun21.render(f5);
    gun22.render(f5);
    gun23.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
