// Date: 2/21/2017 9:31:19 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class G3Mag extends ModelBase
{
  //fields
    ModelRenderer Magazine1;
    ModelRenderer Magazine5;
    ModelRenderer Magazine6;
    ModelRenderer Magazine7;
    ModelRenderer Magazine8;
    ModelRenderer Magazine9;
    ModelRenderer Magazine10;
    ModelRenderer Magazine11;
    ModelRenderer Magazine12;
    ModelRenderer Magazine13;
    ModelRenderer Magazine14;
    ModelRenderer Magazine15;
    ModelRenderer Magazine16;
    ModelRenderer Magazine17;
    ModelRenderer Magazine18;
    ModelRenderer Magazine19;
    ModelRenderer Magazine20;
    ModelRenderer Magazine21;
    ModelRenderer Magazine22;
    ModelRenderer Magazine23;
    ModelRenderer Magazine24;
    ModelRenderer Magazine25;
    ModelRenderer Magazine26;
    ModelRenderer Magazine27;
    ModelRenderer Magazine28;
    ModelRenderer Magazine29;
    ModelRenderer Magazine30;
    ModelRenderer Magazine31;
    ModelRenderer Magazine32;
    ModelRenderer Magazine33;
    ModelRenderer Magazine34;
  
  public G3Mag()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Magazine1 = new ModelRenderer(this, 0, 0);
      Magazine1.addBox(0F, 0F, 0F, 4, 15, 2);
      Magazine1.setRotationPoint(-3.5F, -10.8F, -24.2F);
      Magazine1.setTextureSize(64, 32);
      Magazine1.mirror = true;
      setRotation(Magazine1, 0F, 0F, 0F);
      Magazine5 = new ModelRenderer(this, 0, 0);
      Magazine5.addBox(0F, 0F, 0F, 4, 7, 2);
      Magazine5.setRotationPoint(-3.7F, -5.8F, -24.3F);
      Magazine5.setTextureSize(64, 32);
      Magazine5.mirror = true;
      setRotation(Magazine5, 1.449966F, 0F, 0F);
      Magazine6 = new ModelRenderer(this, 0, 0);
      Magazine6.addBox(0F, 0F, 0F, 1, 7, 2);
      Magazine6.setRotationPoint(-0.3F, -5.8F, -24.3F);
      Magazine6.setTextureSize(64, 32);
      Magazine6.mirror = true;
      setRotation(Magazine6, 1.449966F, 0F, 0F);
      Magazine7 = new ModelRenderer(this, 0, 0);
      Magazine7.addBox(0F, 0F, 0F, 4, 5, 1);
      Magazine7.setRotationPoint(-3.7F, -10.8F, -18.2F);
      Magazine7.setTextureSize(64, 32);
      Magazine7.mirror = true;
      setRotation(Magazine7, 0F, 0F, 0F);
      Magazine8 = new ModelRenderer(this, 0, 0);
      Magazine8.addBox(0F, 0F, 0F, 1, 5, 1);
      Magazine8.setRotationPoint(-0.3F, -10.8F, -18.2F);
      Magazine8.setTextureSize(64, 32);
      Magazine8.mirror = true;
      setRotation(Magazine8, 0F, 0F, 0F);
      Magazine9 = new ModelRenderer(this, 0, 0);
      Magazine9.addBox(0F, 0F, 0F, 1, 5, 1);
      Magazine9.setRotationPoint(-0.3F, -10.8F, -23.2F);
      Magazine9.setTextureSize(64, 32);
      Magazine9.mirror = true;
      setRotation(Magazine9, 0F, 0F, 0F);
      Magazine10 = new ModelRenderer(this, 0, 0);
      Magazine10.addBox(0F, 0F, 0F, 1, 5, 1);
      Magazine10.setRotationPoint(-3.7F, -10.8F, -23.2F);
      Magazine10.setTextureSize(64, 32);
      Magazine10.mirror = true;
      setRotation(Magazine10, 0F, 0F, 0F);
      Magazine11 = new ModelRenderer(this, 0, 0);
      Magazine11.addBox(0F, 0F, 0F, 1, 1, 4);
      Magazine11.setRotationPoint(-3.7F, -9.8F, -22.2F);
      Magazine11.setTextureSize(64, 32);
      Magazine11.mirror = true;
      setRotation(Magazine11, 0F, 0F, 0F);
      Magazine12 = new ModelRenderer(this, 0, 0);
      Magazine12.addBox(0F, 0F, 0F, 1, 1, 4);
      Magazine12.setRotationPoint(-0.3F, -9.8F, -22.2F);
      Magazine12.setTextureSize(64, 32);
      Magazine12.mirror = true;
      setRotation(Magazine12, 0F, 0F, 0F);
      Magazine13 = new ModelRenderer(this, 0, 0);
      Magazine13.addBox(0F, 0F, 0F, 1, 1, 1);
      Magazine13.setRotationPoint(-0.3F, -10.8F, -21F);
      Magazine13.setTextureSize(64, 32);
      Magazine13.mirror = true;
      setRotation(Magazine13, 0F, 0F, 0F);
      Magazine14 = new ModelRenderer(this, 0, 0);
      Magazine14.addBox(0F, 0F, 0F, 1, 1, 1);
      Magazine14.setRotationPoint(-3.7F, -10.8F, -21F);
      Magazine14.setTextureSize(64, 32);
      Magazine14.mirror = true;
      setRotation(Magazine14, 0F, 0F, 0F);
      Magazine15 = new ModelRenderer(this, 0, 0);
      Magazine15.addBox(0F, 0F, 0F, 4, 15, 4);
      Magazine15.setRotationPoint(-3.5F, -10.8F, -21.2F);
      Magazine15.setTextureSize(64, 32);
      Magazine15.mirror = true;
      setRotation(Magazine15, 0F, 0F, 0F);
      Magazine16 = new ModelRenderer(this, 0, 0);
      Magazine16.addBox(0F, 0F, 0F, 4, 5, 1);
      Magazine16.setRotationPoint(-3.5F, -10.8F, -22.2F);
      Magazine16.setTextureSize(64, 32);
      Magazine16.mirror = true;
      setRotation(Magazine16, 0F, 0F, 0F);
      Magazine17 = new ModelRenderer(this, 0, 0);
      Magazine17.addBox(0F, 0F, 0F, 4, 7, 1);
      Magazine17.setRotationPoint(-3.5F, 4.2F, -24.2F);
      Magazine17.setTextureSize(64, 32);
      Magazine17.mirror = true;
      setRotation(Magazine17, 1.487144F, 0F, 0F);
      Magazine18 = new ModelRenderer(this, 0, 0);
      Magazine18.addBox(0F, 0F, 0F, 3, 10, 1);
      Magazine18.setRotationPoint(-3F, -5.8F, -22.2F);
      Magazine18.setTextureSize(64, 32);
      Magazine18.mirror = true;
      setRotation(Magazine18, 0F, 0F, 0F);
      Magazine19 = new ModelRenderer(this, 0, 0);
      Magazine19.addBox(0F, 0F, 0F, 1, 1, 2);
      Magazine19.setRotationPoint(-0.3F, -3.8F, -24.2F);
      Magazine19.setTextureSize(64, 32);
      Magazine19.mirror = true;
      setRotation(Magazine19, 0F, 0F, 0F);
      Magazine20 = new ModelRenderer(this, 0, 0);
      Magazine20.addBox(0F, 0F, 0F, 1, 1, 2);
      Magazine20.setRotationPoint(-0.3F, -1.8F, -24.2F);
      Magazine20.setTextureSize(64, 32);
      Magazine20.mirror = true;
      setRotation(Magazine20, 0F, 0F, 0F);
      Magazine21 = new ModelRenderer(this, 0, 0);
      Magazine21.addBox(0F, 0F, 0F, 1, 1, 2);
      Magazine21.setRotationPoint(-0.3F, 0.2F, -24.2F);
      Magazine21.setTextureSize(64, 32);
      Magazine21.mirror = true;
      setRotation(Magazine21, 0F, 0F, 0F);
      Magazine22 = new ModelRenderer(this, 0, 0);
      Magazine22.addBox(0F, 0F, 0F, 1, 1, 2);
      Magazine22.setRotationPoint(-0.3F, 2.2F, -24.2F);
      Magazine22.setTextureSize(64, 32);
      Magazine22.mirror = true;
      setRotation(Magazine22, 0F, 0F, 0F);
      Magazine23 = new ModelRenderer(this, 0, 0);
      Magazine23.addBox(0F, 0F, 0F, 1, 1, 3);
      Magazine23.setRotationPoint(-0.3F, 2.2F, -21.2F);
      Magazine23.setTextureSize(64, 32);
      Magazine23.mirror = true;
      setRotation(Magazine23, 0F, 0F, 0F);
      Magazine24 = new ModelRenderer(this, 0, 0);
      Magazine24.addBox(0F, 0F, 0F, 1, 1, 3);
      Magazine24.setRotationPoint(-0.3F, 0.2F, -21.2F);
      Magazine24.setTextureSize(64, 32);
      Magazine24.mirror = true;
      setRotation(Magazine24, 0F, 0F, 0F);
      Magazine25 = new ModelRenderer(this, 0, 0);
      Magazine25.addBox(0F, 0F, 0F, 1, 1, 3);
      Magazine25.setRotationPoint(-0.3F, -1.8F, -21.2F);
      Magazine25.setTextureSize(64, 32);
      Magazine25.mirror = true;
      setRotation(Magazine25, 0F, 0F, 0F);
      Magazine26 = new ModelRenderer(this, 0, 0);
      Magazine26.addBox(0F, 0F, 0F, 1, 1, 3);
      Magazine26.setRotationPoint(-0.3F, -3.8F, -21.2F);
      Magazine26.setTextureSize(64, 32);
      Magazine26.mirror = true;
      setRotation(Magazine26, 0F, 0F, 0F);
      Magazine27 = new ModelRenderer(this, 0, 0);
      Magazine27.addBox(0F, 0F, 0F, 1, 1, 2);
      Magazine27.setRotationPoint(-3.7F, -3.8F, -24.2F);
      Magazine27.setTextureSize(64, 32);
      Magazine27.mirror = true;
      setRotation(Magazine27, 0F, 0F, 0F);
      Magazine28 = new ModelRenderer(this, 0, 0);
      Magazine28.addBox(0F, 0F, 0F, 1, 1, 2);
      Magazine28.setRotationPoint(-3.7F, -1.8F, -24.2F);
      Magazine28.setTextureSize(64, 32);
      Magazine28.mirror = true;
      setRotation(Magazine28, 0F, 0F, 0F);
      Magazine29 = new ModelRenderer(this, 0, 0);
      Magazine29.addBox(0F, 0F, 0F, 1, 1, 2);
      Magazine29.setRotationPoint(-3.7F, 0.2F, -24.2F);
      Magazine29.setTextureSize(64, 32);
      Magazine29.mirror = true;
      setRotation(Magazine29, 0F, 0F, 0F);
      Magazine30 = new ModelRenderer(this, 0, 0);
      Magazine30.addBox(0F, 0F, 0F, 1, 1, 2);
      Magazine30.setRotationPoint(-3.7F, 2.2F, -24.2F);
      Magazine30.setTextureSize(64, 32);
      Magazine30.mirror = true;
      setRotation(Magazine30, 0F, 0F, 0F);
      Magazine31 = new ModelRenderer(this, 0, 0);
      Magazine31.addBox(0F, 0F, 0F, 1, 1, 3);
      Magazine31.setRotationPoint(-3.7F, 2.2F, -21.2F);
      Magazine31.setTextureSize(64, 32);
      Magazine31.mirror = true;
      setRotation(Magazine31, 0F, 0F, 0F);
      Magazine32 = new ModelRenderer(this, 0, 0);
      Magazine32.addBox(0F, 0F, 0F, 1, 1, 3);
      Magazine32.setRotationPoint(-3.7F, 0.2F, -21.2F);
      Magazine32.setTextureSize(64, 32);
      Magazine32.mirror = true;
      setRotation(Magazine32, 0F, 0F, 0F);
      Magazine33 = new ModelRenderer(this, 0, 0);
      Magazine33.addBox(0F, 0F, 0F, 1, 1, 3);
      Magazine33.setRotationPoint(-3.7F, -1.8F, -21.2F);
      Magazine33.setTextureSize(64, 32);
      Magazine33.mirror = true;
      setRotation(Magazine33, 0F, 0F, 0F);
      Magazine34 = new ModelRenderer(this, 0, 0);
      Magazine34.addBox(0F, 0F, 0F, 1, 1, 3);
      Magazine34.setRotationPoint(-3.7F, -3.8F, -21.2F);
      Magazine34.setTextureSize(64, 32);
      Magazine34.mirror = true;
      setRotation(Magazine34, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Magazine1.render(f5);
    Magazine5.render(f5);
    Magazine6.render(f5);
    Magazine7.render(f5);
    Magazine8.render(f5);
    Magazine9.render(f5);
    Magazine10.render(f5);
    Magazine11.render(f5);
    Magazine12.render(f5);
    Magazine13.render(f5);
    Magazine14.render(f5);
    Magazine15.render(f5);
    Magazine16.render(f5);
    Magazine17.render(f5);
    Magazine18.render(f5);
    Magazine19.render(f5);
    Magazine20.render(f5);
    Magazine21.render(f5);
    Magazine22.render(f5);
    Magazine23.render(f5);
    Magazine24.render(f5);
    Magazine25.render(f5);
    Magazine26.render(f5);
    Magazine27.render(f5);
    Magazine28.render(f5);
    Magazine29.render(f5);
    Magazine30.render(f5);
    Magazine31.render(f5);
    Magazine32.render(f5);
    Magazine33.render(f5);
    Magazine34.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
