// Date: 11/9/2017 6:01:28 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Gewehr98Action extends ModelBase
{
  //fields
    
    ModelRenderer action1;
    ModelRenderer action2;
    ModelRenderer action3;
    ModelRenderer action4;
    ModelRenderer action5;
    ModelRenderer action6;
    ModelRenderer action7;
    ModelRenderer action8;
    ModelRenderer action9;
    ModelRenderer action10;
    ModelRenderer action11;
    ModelRenderer action12;
    ModelRenderer action13;
    ModelRenderer action14;
    ModelRenderer action15;
    ModelRenderer action16;
    ModelRenderer action17;
    ModelRenderer action18;
    ModelRenderer action22;
    ModelRenderer action24;
    ModelRenderer action25;
    ModelRenderer action26;
    ModelRenderer action27;
    ModelRenderer action29;
    ModelRenderer action31;
    ModelRenderer action32;
    ModelRenderer action33;
    ModelRenderer action35;
    ModelRenderer action36;
    ModelRenderer action37;
    ModelRenderer action42;
    ModelRenderer action43;
    ModelRenderer action44;
    ModelRenderer action45;
    ModelRenderer action46;
    
  
  public Gewehr98Action()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      action1 = new ModelRenderer(this, 200, 0);
      action1.addBox(0F, 0F, 0F, 1, 3, 14);
      action1.setRotationPoint(-2.5F, -16.8F, -31.5F);
      action1.setTextureSize(64, 32);
      action1.mirror = true;
      setRotation(action1, 0F, 0F, 0F);
      action2 = new ModelRenderer(this, 200, 0);
      action2.addBox(0F, 0F, 0F, 3, 1, 16);
      action2.setRotationPoint(-3.5F, -15.8F, -31.5F);
      action2.setTextureSize(64, 32);
      action2.mirror = true;
      setRotation(action2, 0F, 0F, 0F);
      action3 = new ModelRenderer(this, 200, 0);
      action3.addBox(0F, 0F, 0F, 1, 1, 14);
      action3.setRotationPoint(-1.5F, -16.8F, -31.5F);
      action3.setTextureSize(64, 32);
      action3.mirror = true;
      setRotation(action3, 0F, 0F, 0.7853982F);
      action4 = new ModelRenderer(this, 200, 0);
      action4.addBox(0F, 0F, 0F, 1, 1, 14);
      action4.setRotationPoint(-2.5F, -16.8F, -31.5F);
      action4.setTextureSize(64, 32);
      action4.mirror = true;
      setRotation(action4, 0F, 0F, 0.7853982F);
      action5 = new ModelRenderer(this, 200, 0);
      action5.addBox(0F, 0F, 0F, 1, 1, 14);
      action5.setRotationPoint(-3.5F, -15.8F, -31.5F);
      action5.setTextureSize(64, 32);
      action5.mirror = true;
      setRotation(action5, 0F, 0F, -0.7853982F);
      action6 = new ModelRenderer(this, 200, 0);
      action6.addBox(0F, 0F, 0F, 1, 1, 16);
      action6.setRotationPoint(-3.5F, -14.8F, -31.5F);
      action6.setTextureSize(64, 32);
      action6.mirror = true;
      setRotation(action6, 0F, 0F, -0.7853982F);
      action7 = new ModelRenderer(this, 200, 0);
      action7.addBox(0F, 0F, 0F, 1, 1, 14);
      action7.setRotationPoint(-0.5F, -15.8F, -31.5F);
      action7.setTextureSize(64, 32);
      action7.mirror = true;
      setRotation(action7, 0F, 0F, 2.356194F);
      action8 = new ModelRenderer(this, 200, 0);
      action8.addBox(0F, 0F, 0F, 1, 1, 16);
      action8.setRotationPoint(-0.5F, -14.8F, -31.5F);
      action8.setTextureSize(64, 32);
      action8.mirror = true;
      setRotation(action8, 0F, 0F, 2.356194F);
      action9 = new ModelRenderer(this, 200, 0);
      action9.addBox(0F, 0F, 0F, 1, 1, 16);
      action9.setRotationPoint(-2.5F, -13.8F, -31.5F);
      action9.setTextureSize(64, 32);
      action9.mirror = true;
      setRotation(action9, 0F, 0F, -2.356194F);
      action10 = new ModelRenderer(this, 200, 0);
      action10.addBox(0F, 0F, 0F, 1, 1, 16);
      action10.setRotationPoint(-1.5F, -13.8F, -31.5F);
      action10.setTextureSize(64, 32);
      action10.mirror = true;
      setRotation(action10, 0F, 0F, -2.356194F);
      action11 = new ModelRenderer(this, 200, 0);
      action11.addBox(0F, 0F, 0F, 2, 1, 2);
      action11.setRotationPoint(-3F, -16.65F, -17.5F);
      action11.setTextureSize(64, 32);
      action11.mirror = true;
      setRotation(action11, 0F, 0F, 0F);
      action12 = new ModelRenderer(this, 200, 0);
      action12.addBox(0F, 0F, 0F, 1, 1, 4);
      action12.setRotationPoint(-3.2F, -15.7F, -15.5F);
      action12.setTextureSize(64, 32);
      action12.mirror = true;
      setRotation(action12, 0F, 0F, 0F);
      action13 = new ModelRenderer(this, 200, 0);
      action13.addBox(0F, 0F, 0F, 1, 1, 2);
      action13.setRotationPoint(-1.6F, -15.7F, -15.5F);
      action13.setTextureSize(64, 32);
      action13.mirror = true;
      setRotation(action13, 0F, 0F, 0F);
      action14 = new ModelRenderer(this, 200, 0);
      action14.addBox(0F, 0F, 0F, 2, 1, 6);
      action14.setRotationPoint(-0.2F, -14.6F, -17.6F);
      action14.setTextureSize(64, 32);
      action14.mirror = true;
      setRotation(action14, 0F, 0F, 2.825574F);
      action15 = new ModelRenderer(this, 200, 0);
      action15.addBox(0F, 0F, 0F, 1, 1, 4);
      action15.setRotationPoint(-2.4F, -16.9F, -17F);
      action15.setTextureSize(64, 32);
      action15.mirror = true;
      setRotation(action15, 0F, 0F, 0F);
      action16 = new ModelRenderer(this, 200, 0);
      action16.addBox(0F, 0F, 0F, 2, 1, 2);
      action16.setRotationPoint(-1.8F, -16.8F, -14F);
      action16.setTextureSize(64, 32);
      action16.mirror = true;
      setRotation(action16, 0F, 0F, 0F);
      action17 = new ModelRenderer(this, 200, 0);
      action17.addBox(0F, 0F, 0F, 1, 1, 6);
      action17.setRotationPoint(-0.2F, -15.6F, -17.6F);
      action17.setTextureSize(64, 32);
      action17.mirror = true;
      setRotation(action17, 0F, 0F, 1.933288F);
      action18 = new ModelRenderer(this, 200, 0);
      action18.addBox(0F, 0F, 0F, 4, 1, 1);
      action18.setRotationPoint(-7.1F, -15.5F, -16.5F);
      action18.setTextureSize(64, 32);
      action18.mirror = true;
      setRotation(action18, 0F, 0F, 0F);
      action22 = new ModelRenderer(this, 200, 0);
      action22.addBox(0F, 0F, 0F, 1, 1, 4);
      action22.setRotationPoint(-3.2F, -14.7F, -15.5F);
      action22.setTextureSize(64, 32);
      action22.mirror = true;
      setRotation(action22, 0F, 0F, -1.115358F);
      action24 = new ModelRenderer(this, 200, 0);
      action24.addBox(0F, 0F, 0F, 1, 1, 4);
      action24.setRotationPoint(-2.5F, -17F, -17F);
      action24.setTextureSize(64, 32);
      action24.mirror = true;
      setRotation(action24, 0F, 0F, 0F);
      action25 = new ModelRenderer(this, 200, 0);
      action25.addBox(0F, 0F, 0F, 1, 1, 1);
      action25.setRotationPoint(-2.5F, -16.8F, -13.5F);
      action25.setTextureSize(64, 32);
      action25.mirror = true;
      setRotation(action25, 0F, 0F, 0F);
      action26 = new ModelRenderer(this, 200, 0);
      action26.addBox(0F, 0F, 0F, 1, 1, 4);
      action26.setRotationPoint(-2.6F, -16.9F, -17F);
      action26.setTextureSize(64, 32);
      action26.mirror = true;
      setRotation(action26, 0F, 0F, 0F);
      action27 = new ModelRenderer(this, 200, 0);
      action27.addBox(0F, 0F, 0F, 1, 1, 2);
      action27.setRotationPoint(-0.5F, -15.8F, -17.5F);
      action27.setTextureSize(64, 32);
      action27.mirror = true;
      setRotation(action27, 0F, 0F, 2.602503F);
      action29 = new ModelRenderer(this, 200, 0);
      action29.addBox(0F, 0F, 0F, 1, 1, 4);
      action29.setRotationPoint(-3.2F, -15.7F, -15.5F);
      action29.setTextureSize(64, 32);
      action29.mirror = true;
      setRotation(action29, 0F, 0F, -0.3346075F);
      action31 = new ModelRenderer(this, 200, 0);
      action31.addBox(0F, 0F, 0F, 1, 1, 1);
      action31.setRotationPoint(-2.5F, -16.8F, -13F);
      action31.setTextureSize(64, 32);
      action31.mirror = true;
      setRotation(action31, 0F, 0F, 0F);
      action32 = new ModelRenderer(this, 200, 0);
      action32.addBox(0F, 0F, 0F, 1, 1, 2);
      action32.setRotationPoint(-3.5F, -15.8F, -17.5F);
      action32.setTextureSize(64, 32);
      action32.mirror = true;
      setRotation(action32, 0F, 0F, -1.041001F);
      action33 = new ModelRenderer(this, 200, 0);
      action33.addBox(0F, 0F, 0F, 1, 1, 2);
      action33.setRotationPoint(-2.5F, -15.1F, -13.5F);
      action33.setTextureSize(64, 32);
      action33.mirror = true;
      setRotation(action33, 0F, 0F, 0F);
      action35 = new ModelRenderer(this, 200, 0);
      action35.addBox(0F, 0F, 0F, 1, 1, 6);
      action35.setRotationPoint(-1.2F, -15.6F, -17.6F);
      action35.setTextureSize(64, 32);
      action35.mirror = true;
      setRotation(action35, 0F, 0F, 0F);
      action36 = new ModelRenderer(this, 200, 0);
      action36.addBox(0F, 0F, 0F, 2, 2, 2);
      action36.setRotationPoint(-8.7F, -16F, -17F);
      action36.setTextureSize(64, 32);
      action36.mirror = true;
      setRotation(action36, 0F, 0F, 0F);
      action37 = new ModelRenderer(this, 200, 0);
      action37.addBox(0F, 0F, 0F, 1, 1, 4);
      action37.setRotationPoint(-2.5F, -15.8F, -12.8F);
      action37.setTextureSize(64, 32);
      action37.mirror = true;
      setRotation(action37, 0F, 0F, 0F);
      action42 = new ModelRenderer(this, 200, 0);
      action42.addBox(0F, 0F, 0F, 1, 1, 4);
      action42.setRotationPoint(-2.5F, -15.4F, -12.8F);
      action42.setTextureSize(64, 32);
      action42.mirror = true;
      setRotation(action42, 0F, 0F, 0F);
      action43 = new ModelRenderer(this, 200, 0);
      action43.addBox(0F, 0F, 0F, 1, 1, 4);
      action43.setRotationPoint(-2.3F, -15.6F, -12.8F);
      action43.setTextureSize(64, 32);
      action43.mirror = true;
      setRotation(action43, 0F, 0F, 0F);
      action44 = new ModelRenderer(this, 200, 0);
      action44.addBox(0F, 0F, 0F, 1, 1, 4);
      action44.setRotationPoint(-2.7F, -15.6F, -12.8F);
      action44.setTextureSize(64, 32);
      action44.mirror = true;
      setRotation(action44, 0F, 0F, 0F);
      action45 = new ModelRenderer(this, 200, 0);
      action45.addBox(0F, 0F, 0F, 1, 1, 2);
      action45.setRotationPoint(-3.7F, -15.4F, -32F);
      action45.setTextureSize(64, 32);
      action45.mirror = true;
      setRotation(action45, 0F, 0F, 0F);
      action46 = new ModelRenderer(this, 200, 0);
      action46.addBox(0F, 0F, 0F, 1, 1, 8);
      action46.setRotationPoint(-3.6F, -15.4F, -30F);
      action46.setTextureSize(64, 32);
      action46.mirror = true;
      setRotation(action46, 0F, 0F, 0F);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    action1.render(f5);
    action2.render(f5);
    action3.render(f5);
    action4.render(f5);
    action5.render(f5);
    action6.render(f5);
    action7.render(f5);
    action8.render(f5);
    action9.render(f5);
    action10.render(f5);
    action11.render(f5);
    action12.render(f5);
    action13.render(f5);
    action14.render(f5);
    action15.render(f5);
    action16.render(f5);
    action17.render(f5);
    action18.render(f5);
    action22.render(f5);
    action24.render(f5);
    action25.render(f5);
    action26.render(f5);
    action27.render(f5);
    action29.render(f5);
    action31.render(f5);
    action32.render(f5);
    action33.render(f5);
    action35.render(f5);
    action36.render(f5);
    action37.render(f5);
    action42.render(f5);
    action43.render(f5);
    action44.render(f5);
    action45.render(f5);
    action46.render(f5);
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
