// Date: 4/16/2018 10:39:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Ghost350bolt extends ModelBase
{
  //fields
    ModelRenderer bolt1;
    ModelRenderer bolt2;
    ModelRenderer bolt3;
    ModelRenderer bolt4;
    ModelRenderer bolt5;
    ModelRenderer bolt6;
    ModelRenderer bolt7;
  
  public Ghost350bolt()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      bolt1 = new ModelRenderer(this, 300, 0);
      bolt1.addBox(0F, 0F, 0F, 1, 1, 80);
      bolt1.setRotationPoint(-1.5F, -18.8F, -87.5F);
      bolt1.setTextureSize(64, 32);
      bolt1.mirror = true;
      setRotation(bolt1, 0F, 0F, 0F);
      bolt2 = new ModelRenderer(this, 300, 100);
      bolt2.addBox(0F, 0F, 0F, 1, 1, 4);
      bolt2.setRotationPoint(-1.5F, -18.8F, -90.5F);
      bolt2.setTextureSize(64, 32);
      bolt2.mirror = true;
      setRotation(bolt2, 0.1487144F, 0F, 0F);
      bolt3 = new ModelRenderer(this, 300, 100);
      bolt3.addBox(0F, 0F, 0F, 1, 4, 1);
      bolt3.setRotationPoint(-1.5F, -17.8F, -90.5F);
      bolt3.setTextureSize(64, 32);
      bolt3.mirror = true;
      setRotation(bolt3, 1.449966F, 0F, 0F);
      bolt4 = new ModelRenderer(this, 300, 100);
      bolt4.addBox(0F, 0F, 0F, 1, 1, 4);
      bolt4.setRotationPoint(-1.5F, -18.8F, -90.5F);
      bolt4.setTextureSize(64, 32);
      bolt4.mirror = true;
      setRotation(bolt4, 0F, -0.1487144F, 0F);
      bolt5 = new ModelRenderer(this, 300, 100);
      bolt5.addBox(0F, 0F, 0F, 4, 1, 1);
      bolt5.setRotationPoint(-0.5F, -18.8F, -90.5F);
      bolt5.setTextureSize(64, 32);
      bolt5.mirror = true;
      setRotation(bolt5, 0F, -1.449966F, 0F);
      bolt6 = new ModelRenderer(this, 300, 150);
      bolt6.addBox(0F, 0F, 0F, 1, 1, 14);
      bolt6.setRotationPoint(-1.5F, -19.5F, -24.5F);
      bolt6.setTextureSize(64, 32);
      bolt6.mirror = true;
      setRotation(bolt6, 0F, 0F, 0.7853982F);
      bolt7 = new ModelRenderer(this, 300, 150);
      bolt7.addBox(0F, 0F, 0F, 1, 1, 14);
      bolt7.setRotationPoint(-0.5F, -19.5F, -24.5F);
      bolt7.setTextureSize(64, 32);
      bolt7.mirror = true;
      setRotation(bolt7, 0F, 0F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    bolt1.render(f5);
    bolt2.render(f5);
    bolt3.render(f5);
    bolt4.render(f5);
    bolt5.render(f5);
    bolt6.render(f5);
    bolt7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
