// Date: 9/23/2017 7:18:53 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class HK417Mag extends ModelBase
{
  //fields
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
  
  public HK417Mag()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      mag1 = new ModelRenderer(this, 0, 0);
      mag1.addBox(0F, 0F, 0F, 3, 9, 10);
      mag1.setRotationPoint(-3.3F, 5F, -22.8F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, 1.449966F, 0F, 0F);
      mag2 = new ModelRenderer(this, 0, 0);
      mag2.addBox(0F, 0F, 0F, 1, 9, 10);
      mag2.setRotationPoint(-0.7F, 5F, -22.8F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, 1.449966F, 0F, 0F);
      mag3 = new ModelRenderer(this, 40, 0);
      mag3.addBox(0F, 0F, 0F, 4, 10, 2);
      mag3.setRotationPoint(-3.5F, 5.8F, -23.5F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, 1.449966F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
