// Date: 2/17/2017 7:13:10 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class HKMP5Mag extends ModelBase
{
  //fields
    ModelRenderer Magazine1;
    ModelRenderer Magazine2;
    ModelRenderer Magazine3;
    ModelRenderer Magazine4;
    ModelRenderer Magazine5;
    ModelRenderer Magazine6;
    ModelRenderer Magazine7;
  
  public HKMP5Mag()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Magazine1 = new ModelRenderer(this, 0, 0);
      Magazine1.addBox(0F, 0F, 0F, 4, 1, 12);
      Magazine1.setRotationPoint(-3.5F, 1F, -24.2F);
      Magazine1.setTextureSize(128, 128);
      Magazine1.mirror = true;
      setRotation(Magazine1, 1.375609F, 0F, 0F);
      Magazine2 = new ModelRenderer(this, 0, 0);
      Magazine2.addBox(0F, 0F, 0F, 4, 3, 12);
      Magazine2.setRotationPoint(-3.5F, 2F, -19.3F);
      Magazine2.setTextureSize(128, 128);
      Magazine2.mirror = true;
      setRotation(Magazine2, -2.044824F, 0F, 0F);
      Magazine3 = new ModelRenderer(this, 0, 0);
      Magazine3.addBox(0F, 0F, 0F, 4, 1, 12);
      Magazine3.setRotationPoint(-3.5F, 0.3F, -22.8F);
      Magazine3.setTextureSize(128, 128);
      Magazine3.mirror = true;
      setRotation(Magazine3, -2.044824F, 0F, 0F);
      Magazine4 = new ModelRenderer(this, 0, 0);
      Magazine4.addBox(0F, 0F, 0F, 4, 3, 12);
      Magazine4.setRotationPoint(-3.5F, 1.4F, -22.2F);
      Magazine4.setTextureSize(128, 128);
      Magazine4.mirror = true;
      setRotation(Magazine4, 1.375609F, 0F, 0F);
      Magazine5 = new ModelRenderer(this, 0, 0);
      Magazine5.addBox(0F, 0F, 0F, 4, 2, 1);
      Magazine5.setRotationPoint(-3.5F, 10.75F, -26.4F);
      Magazine5.setTextureSize(128, 128);
      Magazine5.mirror = true;
      setRotation(Magazine5, -2.044824F, 0F, 0F);
      Magazine6 = new ModelRenderer(this, 0, 0);
      Magazine6.addBox(0F, 0F, 0F, 3, 1, 12);
      Magazine6.setRotationPoint(-3F, 0.3F, -21.8F);
      Magazine6.setTextureSize(128, 128);
      Magazine6.mirror = true;
      setRotation(Magazine6, -2.044824F, 0F, 0F);
      Magazine7 = new ModelRenderer(this, 0, 0);
      Magazine7.addBox(0F, 0F, 0F, 3, 2, 12);
      Magazine7.setRotationPoint(-3F, 1.2F, -23.5F);
      Magazine7.setTextureSize(128, 128);
      Magazine7.mirror = true;
      setRotation(Magazine7, 1.375609F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Magazine1.render(f5);
    Magazine2.render(f5);
    Magazine3.render(f5);
    Magazine4.render(f5);
    Magazine5.render(f5);
    Magazine6.render(f5);
    Magazine7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
