// Date: 3/19/2016 1:24:21 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Holographic extends ModelBase
{
  //fields
    ModelRenderer gun1;
    ModelRenderer gun2;
    ModelRenderer gun3;
    ModelRenderer gun4;
    ModelRenderer gun5;
    ModelRenderer gun7;
    ModelRenderer gun8;
    ModelRenderer gun9;
    ModelRenderer gun11;
    ModelRenderer gun12;
    ModelRenderer gun13;
    ModelRenderer gun14;
    ModelRenderer gun21;
    ModelRenderer gun22;
    ModelRenderer gun23;
    ModelRenderer gun24;
    ModelRenderer gun25;
    ModelRenderer gun26;
    ModelRenderer gun27;
    ModelRenderer gun28;
    ModelRenderer gun29;
    ModelRenderer gun30;
    ModelRenderer gun31;
    ModelRenderer gun32;
    ModelRenderer gun33;
    ModelRenderer gun34;
    ModelRenderer gun35;
    ModelRenderer gun36;
    ModelRenderer gun37;
    ModelRenderer gun38;
    ModelRenderer gun39;
    ModelRenderer gun40;
    ModelRenderer gun41;
    ModelRenderer gun42;
  
  public Holographic()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun1 = new ModelRenderer(this, 0, 0);
      gun1.addBox(0F, 0F, 0F, 6, 3, 18);
      gun1.setRotationPoint(-4.5F, -4F, -12F);
      gun1.setTextureSize(64, 32);
      gun1.mirror = true;
      setRotation(gun1, 0F, 0F, 0F);
      gun2 = new ModelRenderer(this, 0, 0);
      gun2.addBox(0F, 0F, 0F, 6, 2, 17);
      gun2.setRotationPoint(-4.5F, -2F, -10F);
      gun2.setTextureSize(64, 32);
      gun2.mirror = true;
      setRotation(gun2, 0F, 0F, 0F);
      gun3 = new ModelRenderer(this, 0, 0);
      gun3.addBox(0F, 0F, 0F, 6, 2, 1);
      gun3.setRotationPoint(-4.5F, -1F, -12F);
      gun3.setTextureSize(64, 32);
      gun3.mirror = true;
      setRotation(gun3, 1.115358F, 0F, 0F);
      gun4 = new ModelRenderer(this, 0, 0);
      gun4.addBox(0F, 0F, 0F, 1, 5, 8);
      gun4.setRotationPoint(-5F, -5F, -0.5F);
      gun4.setTextureSize(64, 32);
      gun4.mirror = true;
      setRotation(gun4, 0F, 0F, 0F);
      gun5 = new ModelRenderer(this, 0, 0);
      gun5.addBox(0F, 0F, 0F, 1, 5, 8);
      gun5.setRotationPoint(1F, -5F, -0.5F);
      gun5.setTextureSize(64, 32);
      gun5.mirror = true;
      setRotation(gun5, 0F, 0F, 0F);
      gun7 = new ModelRenderer(this, 0, 0);
      gun7.addBox(0F, 0F, 0F, 1, 4, 6);
      gun7.setRotationPoint(-5F, -9F, 0F);
      gun7.setTextureSize(64, 32);
      gun7.mirror = true;
      setRotation(gun7, 0F, 0F, 0F);
      gun8 = new ModelRenderer(this, 0, 0);
      gun8.addBox(0F, 0F, 0F, 1, 2, 4);
      gun8.setRotationPoint(1F, -2F, -3.5F);
      gun8.setTextureSize(64, 32);
      gun8.mirror = true;
      setRotation(gun8, 0F, 0F, 0F);
      gun9 = new ModelRenderer(this, 0, 0);
      gun9.addBox(0F, 0F, 0F, 1, 2, 4);
      gun9.setRotationPoint(1F, -2F, -3.5F);
      gun9.setTextureSize(64, 32);
      gun9.mirror = true;
      setRotation(gun9, 0.8179294F, 0F, 0F);
      gun11 = new ModelRenderer(this, 0, 0);
      gun11.addBox(0F, 0F, 0F, 1, 2, 4);
      gun11.setRotationPoint(-5F, -2F, -3.5F);
      gun11.setTextureSize(64, 32);
      gun11.mirror = true;
      setRotation(gun11, 0F, 0F, 0F);
      gun12 = new ModelRenderer(this, 0, 0);
      gun12.addBox(0F, 0F, 0F, 5, 1, 6);
      gun12.setRotationPoint(-4F, -10F, 0F);
      gun12.setTextureSize(64, 32);
      gun12.mirror = true;
      setRotation(gun12, 0F, 0F, 0F);
      gun13 = new ModelRenderer(this, 0, 0);
      gun13.addBox(0F, 0F, 0F, 1, 1, 6);
      gun13.setRotationPoint(-4.5F, -9.5F, 0F);
      gun13.setTextureSize(64, 32);
      gun13.mirror = true;
      setRotation(gun13, 0F, 0F, 0F);
      gun14 = new ModelRenderer(this, 0, 0);
      gun14.addBox(0F, 0F, 0F, 1, 1, 6);
      gun14.setRotationPoint(0.5F, -9.5F, 0F);
      gun14.setTextureSize(64, 32);
      gun14.mirror = true;
      setRotation(gun14, 0F, 0F, 0F);
      gun21 = new ModelRenderer(this, 0, 0);
      gun21.addBox(0F, 0F, 0F, 1, 1, 1);
      gun21.setRotationPoint(-5F, -3F, -1.5F);
      gun21.setTextureSize(64, 32);
      gun21.mirror = true;
      setRotation(gun21, 0F, 0F, 0F);
      gun22 = new ModelRenderer(this, 0, 0);
      gun22.addBox(0F, 0F, 0F, 1, 1, 1);
      gun22.setRotationPoint(1F, -3F, -1.5F);
      gun22.setTextureSize(64, 32);
      gun22.mirror = true;
      setRotation(gun22, 0F, 0F, 0F);
      gun23 = new ModelRenderer(this, 0, 0);
      gun23.addBox(0F, 0F, 0F, 1, 2, 4);
      gun23.setRotationPoint(-5F, -2F, -3.5F);
      gun23.setTextureSize(64, 32);
      gun23.mirror = true;
      setRotation(gun23, 0.8179294F, 0F, 0F);
      gun24 = new ModelRenderer(this, 0, 0);
      gun24.addBox(0F, 0F, 0F, 1, 4, 6);
      gun24.setRotationPoint(1F, -9F, 0F);
      gun24.setTextureSize(64, 32);
      gun24.mirror = true;
      setRotation(gun24, 0F, 0F, 0F);
      gun25 = new ModelRenderer(this, 0, 0);
      gun25.addBox(0F, 0F, 0F, 1, 5, 1);
      gun25.setRotationPoint(-5F, -9F, 0F);
      gun25.setTextureSize(64, 32);
      gun25.mirror = true;
      setRotation(gun25, -0.1858931F, 0F, 0F);
      gun26 = new ModelRenderer(this, 0, 0);
      gun26.addBox(0F, 0F, 0F, 1, 5, 1);
      gun26.setRotationPoint(1F, -9F, 0F);
      gun26.setTextureSize(64, 32);
      gun26.mirror = true;
      setRotation(gun26, -0.1858931F, 0F, 0F);
      gun27 = new ModelRenderer(this, 0, 0);
      gun27.addBox(0F, 0F, 0F, 1, 1, 3);
      gun27.setRotationPoint(1F, -7F, 6F);
      gun27.setTextureSize(64, 32);
      gun27.mirror = true;
      setRotation(gun27, -1.226894F, 0F, 0F);
      gun28 = new ModelRenderer(this, 0, 0);
      gun28.addBox(0F, 0F, 0F, 1, 1, 3);
      gun28.setRotationPoint(-5F, -7F, 6F);
      gun28.setTextureSize(64, 32);
      gun28.mirror = true;
      setRotation(gun28, -1.226894F, 0F, 0F);
      gun29 = new ModelRenderer(this, 0, 0);
      gun29.addBox(0F, 0F, 0F, 1, 1, 1);
      gun29.setRotationPoint(0.5F, -9.5F, 5.5F);
      gun29.setTextureSize(64, 32);
      gun29.mirror = true;
      setRotation(gun29, 0F, 0F, 0F);
      gun30 = new ModelRenderer(this, 0, 0);
      gun30.addBox(0F, 0F, 0F, 1, 1, 1);
      gun30.setRotationPoint(-4.5F, -9.5F, 5.5F);
      gun30.setTextureSize(64, 32);
      gun30.mirror = true;
      setRotation(gun30, 0F, 0F, 0F);
      gun31 = new ModelRenderer(this, 0, 0);
      gun31.addBox(0F, 0F, 0F, 5, 1, 1);
      gun31.setRotationPoint(-4F, -10F, 5.5F);
      gun31.setTextureSize(64, 32);
      gun31.mirror = true;
      setRotation(gun31, 0F, 0F, 0F);
      gun32 = new ModelRenderer(this, 0, 0);
      gun32.addBox(0F, 0F, 0F, 1, 2, 1);
      gun32.setRotationPoint(1F, -5F, 7.5F);
      gun32.setTextureSize(64, 32);
      gun32.mirror = true;
      setRotation(gun32, -2.267895F, 0F, 0F);
      gun33 = new ModelRenderer(this, 0, 0);
      gun33.addBox(0F, 0F, 0F, 1, 2, 1);
      gun33.setRotationPoint(-5F, -5F, 7.5F);
      gun33.setTextureSize(64, 32);
      gun33.mirror = true;
      setRotation(gun33, -2.267895F, 0F, 0F);
      gun34 = new ModelRenderer(this, 0, 0);
      gun34.addBox(0F, 0F, 0F, 6, 1, 3);
      gun34.setRotationPoint(-4.5F, -5F, 6F);
      gun34.setTextureSize(64, 32);
      gun34.mirror = true;
      setRotation(gun34, -1.301251F, 0F, 0F);
      gun35 = new ModelRenderer(this, 0, 0);
      gun35.addBox(0F, 0F, 0F, 6, 1, 1);
      gun35.setRotationPoint(-4.5F, -2.5F, 5.8F);
      gun35.setTextureSize(64, 32);
      gun35.mirror = true;
      setRotation(gun35, 0F, 0F, 0F);
      gun36 = new ModelRenderer(this, 0, 0);
      gun36.addBox(0F, 0F, 0F, 6, 1, 5);
      gun36.setRotationPoint(-4.5F, -5F, 1F);
      gun36.setTextureSize(64, 32);
      gun36.mirror = true;
      setRotation(gun36, 0F, 0F, 0F);
      gun37 = new ModelRenderer(this, 0, 0);
      gun37.addBox(0F, 0F, 0F, 5, 1, 13);
      gun37.setRotationPoint(-4F, -4.8F, -12F);
      gun37.setTextureSize(64, 32);
      gun37.mirror = true;
      setRotation(gun37, 0F, 0F, 0F);
      gun38 = new ModelRenderer(this, 0, 0);
      gun38.addBox(0F, 0F, 0F, 1, 1, 13);
      gun38.setRotationPoint(-4.3F, -4.5F, -12F);
      gun38.setTextureSize(64, 32);
      gun38.mirror = true;
      setRotation(gun38, 0F, 0F, 0F);
      gun39 = new ModelRenderer(this, 0, 0);
      gun39.addBox(0F, 0F, 0F, 1, 1, 13);
      gun39.setRotationPoint(0.3F, -4.5F, -12F);
      gun39.setTextureSize(64, 32);
      gun39.mirror = true;
      setRotation(gun39, 0F, 0F, 0F);
      gun40 = new ModelRenderer(this, 0, 0);
      gun40.addBox(0F, 0F, 0F, 3, 1, 10);
      gun40.setRotationPoint(-3F, -5.3F, -5F);
      gun40.setTextureSize(64, 32);
      gun40.mirror = true;
      setRotation(gun40, 0F, 0F, 0F);
      gun41 = new ModelRenderer(this, 50, 0);
      gun41.addBox(0F, 0F, 0F, 1, 2, 2);
      gun41.setRotationPoint(2F, -2.5F, -0.5F);
      gun41.setTextureSize(64, 32);
      gun41.mirror = true;
      setRotation(gun41, 0F, 0F, 0F);
      gun42 = new ModelRenderer(this, 50, 0);
      gun42.addBox(0F, 0F, 0F, 1, 2, 2);
      gun42.setRotationPoint(-6F, -2.5F, -0.5F);
      gun42.setTextureSize(64, 32);
      gun42.mirror = true;
      setRotation(gun42, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun1.render(f5);
    gun2.render(f5);
    gun3.render(f5);
    gun4.render(f5);
    gun5.render(f5);
    gun7.render(f5);
    gun8.render(f5);
    gun9.render(f5);
    gun11.render(f5);
    gun12.render(f5);
    gun13.render(f5);
    gun14.render(f5);
    gun21.render(f5);
    gun22.render(f5);
    gun23.render(f5);
    gun24.render(f5);
    gun25.render(f5);
    gun26.render(f5);
    gun27.render(f5);
    gun28.render(f5);
    gun29.render(f5);
    gun30.render(f5);
    gun31.render(f5);
    gun32.render(f5);
    gun33.render(f5);
    gun34.render(f5);
    gun35.render(f5);
    gun36.render(f5);
    gun37.render(f5);
    gun38.render(f5);
    gun39.render(f5);
    gun40.render(f5);
    gun41.render(f5);
    gun42.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
