// Date: 1/11/2017 9:12:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class KSG12Pump extends ModelBase
{
  //fields
    ModelRenderer gun38;
    ModelRenderer gun40;
    ModelRenderer gun51;
    ModelRenderer gun56;
    ModelRenderer gun84;
    ModelRenderer gun85;
    ModelRenderer gun86;
    ModelRenderer gun87;
    ModelRenderer gun88;
    ModelRenderer gun89;
    ModelRenderer gun90;
    ModelRenderer gun91;
    ModelRenderer gun92;
    ModelRenderer gun106;
    ModelRenderer gun107;
    ModelRenderer gun108;
    ModelRenderer gun109;
    ModelRenderer gun110;
    ModelRenderer gun112;
    ModelRenderer gun113;
    ModelRenderer gun114;
  
  public KSG12Pump()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun38 = new ModelRenderer(this, 0, 50);
      gun38.addBox(0F, 0F, 0F, 4, 2, 25);
      gun38.setRotationPoint(0.5F, -12.5F, -21F);
      gun38.setTextureSize(64, 32);
      gun38.mirror = true;
      setRotation(gun38, 0F, 0F, 0F);
      gun40 = new ModelRenderer(this, 0, 50);
      gun40.addBox(0F, 0F, 0F, 6, 2, 25);
      gun40.setRotationPoint(-0.5F, -13F, -21F);
      gun40.setTextureSize(64, 32);
      gun40.mirror = true;
      setRotation(gun40, 0F, 0F, 0F);
      gun51 = new ModelRenderer(this, 0, 50);
      gun51.addBox(0F, 0F, 0F, 4, 2, 12);
      gun51.setRotationPoint(0.5F, -16F, -21F);
      gun51.setTextureSize(64, 32);
      gun51.mirror = true;
      setRotation(gun51, 0F, 0F, 0F);
      gun56 = new ModelRenderer(this, 0, 50);
      gun56.addBox(0F, 0F, 0F, 2, 1, 12);
      gun56.setRotationPoint(1.5F, -16.5F, -21F);
      gun56.setTextureSize(64, 32);
      gun56.mirror = true;
      setRotation(gun56, 0F, 0F, 0F);
      gun84 = new ModelRenderer(this, 0, 50);
      gun84.addBox(0F, 0F, 0F, 2, 1, 14);
      gun84.setRotationPoint(1.5F, -11.3F, -21F);
      gun84.setTextureSize(64, 32);
      gun84.mirror = true;
      setRotation(gun84, 0F, 0F, 0F);
      gun85 = new ModelRenderer(this, 0, 50);
      gun85.addBox(0F, 0F, 0F, 2, 1, 1);
      gun85.setRotationPoint(1.5F, -11F, -21F);
      gun85.setTextureSize(64, 32);
      gun85.mirror = true;
      setRotation(gun85, 0F, 0F, 0F);
      gun86 = new ModelRenderer(this, 0, 50);
      gun86.addBox(0F, 0F, 0F, 2, 1, 1);
      gun86.setRotationPoint(1.5F, -11F, -19F);
      gun86.setTextureSize(64, 32);
      gun86.mirror = true;
      setRotation(gun86, 0F, 0F, 0F);
      gun87 = new ModelRenderer(this, 0, 50);
      gun87.addBox(0F, 0F, 0F, 2, 1, 1);
      gun87.setRotationPoint(1.5F, -11F, -17F);
      gun87.setTextureSize(64, 32);
      gun87.mirror = true;
      setRotation(gun87, 0F, 0F, 0F);
      gun88 = new ModelRenderer(this, 0, 50);
      gun88.addBox(0F, 0F, 0F, 2, 1, 1);
      gun88.setRotationPoint(1.5F, -11F, -15F);
      gun88.setTextureSize(64, 32);
      gun88.mirror = true;
      setRotation(gun88, 0F, 0F, 0F);
      gun89 = new ModelRenderer(this, 0, 50);
      gun89.addBox(0F, 0F, 0F, 2, 1, 1);
      gun89.setRotationPoint(1.5F, -11F, -13F);
      gun89.setTextureSize(64, 32);
      gun89.mirror = true;
      setRotation(gun89, 0F, 0F, 0F);
      gun90 = new ModelRenderer(this, 0, 50);
      gun90.addBox(0F, 0F, 0F, 2, 1, 1);
      gun90.setRotationPoint(1.5F, -11F, -11F);
      gun90.setTextureSize(64, 32);
      gun90.mirror = true;
      setRotation(gun90, 0F, 0F, 0F);
      gun91 = new ModelRenderer(this, 0, 50);
      gun91.addBox(0F, 0F, 0F, 2, 1, 1);
      gun91.setRotationPoint(1.5F, -11F, -9F);
      gun91.setTextureSize(64, 32);
      gun91.mirror = true;
      setRotation(gun91, 0F, 0F, 0F);
      gun92 = new ModelRenderer(this, 0, 50);
      gun92.addBox(0F, 0F, 0F, 2, 1, 1);
      gun92.setRotationPoint(1.5F, -11F, -7F);
      gun92.setTextureSize(64, 32);
      gun92.mirror = true;
      setRotation(gun92, 0F, 0F, 0F);
      gun106 = new ModelRenderer(this, 0, 50);
      gun106.addBox(0F, 0F, 0F, 1, 1, 12);
      gun106.setRotationPoint(3.5F, -16.5F, -21F);
      gun106.setTextureSize(64, 32);
      gun106.mirror = true;
      setRotation(gun106, 0F, 0F, 0.4089647F);
      gun107 = new ModelRenderer(this, 0, 50);
      gun107.addBox(0F, 0F, 0F, 1, 1, 12);
      gun107.setRotationPoint(1.5F, -16.5F, -21F);
      gun107.setTextureSize(64, 32);
      gun107.mirror = true;
      setRotation(gun107, 0F, 0F, 1.07818F);
      gun108 = new ModelRenderer(this, 0, 50);
      gun108.addBox(0F, 0F, 0F, 3, 1, 12);
      gun108.setRotationPoint(4.5F, -16F, -21F);
      gun108.setTextureSize(64, 32);
      gun108.mirror = true;
      setRotation(gun108, 0F, 0F, 1.375609F);
      gun109 = new ModelRenderer(this, 0, 50);
      gun109.addBox(0F, 0F, 0F, 1, 3, 12);
      gun109.setRotationPoint(0.5F, -16F, -21F);
      gun109.setTextureSize(64, 32);
      gun109.mirror = true;
      setRotation(gun109, 0F, 0F, 0.2602503F);
      gun110 = new ModelRenderer(this, 0, 50);
      gun110.addBox(0F, 0F, 0F, 1, 1, 25);
      gun110.setRotationPoint(3.9F, -14F, -21F);
      gun110.setTextureSize(64, 32);
      gun110.mirror = true;
      setRotation(gun110, 0F, 0F, 0F);
      gun112 = new ModelRenderer(this, 0, 50);
      gun112.addBox(0F, 0F, 0F, 1, 1, 25);
      gun112.setRotationPoint(4.9F, -14F, -21F);
      gun112.setTextureSize(64, 32);
      gun112.mirror = true;
      setRotation(gun112, 0F, 0F, 1.003822F);
      gun113 = new ModelRenderer(this, 0, 50);
      gun113.addBox(0F, 0F, 0F, 1, 1, 25);
      gun113.setRotationPoint(0F, -14F, -21F);
      gun113.setTextureSize(64, 32);
      gun113.mirror = true;
      setRotation(gun113, 0F, 0F, 0F);
      gun114 = new ModelRenderer(this, 0, 50);
      gun114.addBox(0F, 0F, 0F, 1, 1, 25);
      gun114.setRotationPoint(0F, -14F, -21F);
      gun114.setTextureSize(64, 32);
      gun114.mirror = true;
      setRotation(gun114, 0F, 0F, 0.4461433F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun38.render(f5);
    gun40.render(f5);
    gun51.render(f5);
    gun56.render(f5);
    gun84.render(f5);
    gun85.render(f5);
    gun86.render(f5);
    gun87.render(f5);
    gun88.render(f5);
    gun89.render(f5);
    gun90.render(f5);
    gun91.render(f5);
    gun92.render(f5);
    gun106.render(f5);
    gun107.render(f5);
    gun108.render(f5);
    gun109.render(f5);
    gun110.render(f5);
    gun112.render(f5);
    gun113.render(f5);
    gun114.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
