// Date: 11/16/2017 7:41:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LeeEnfieldSMLEAction extends ModelBase
{
  //fields
    
    ModelRenderer action1;
    ModelRenderer action3;
    ModelRenderer action4;
    ModelRenderer action5;
    ModelRenderer action6;
    ModelRenderer action9;
    ModelRenderer action10;
    ModelRenderer action18;
    ModelRenderer action19;
    ModelRenderer action37;
    ModelRenderer action42;
    ModelRenderer action53;
    ModelRenderer action54;
    ModelRenderer action55;
    ModelRenderer action56;
    ModelRenderer action57;
    ModelRenderer action58;
    ModelRenderer action59;
    ModelRenderer action60;
    ModelRenderer action61;
    ModelRenderer action62;
  
  public LeeEnfieldSMLEAction()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      action1 = new ModelRenderer(this, 200, 0);
      action1.addBox(0F, 0F, 0F, 1, 3, 18);
      action1.setRotationPoint(-2.5F, -16.8F, -31.5F);
      action1.setTextureSize(64, 32);
      action1.mirror = true;
      setRotation(action1, 0F, 0F, 0F);
      action3 = new ModelRenderer(this, 200, 0);
      action3.addBox(0F, 0F, 0F, 1, 1, 18);
      action3.setRotationPoint(-1.5F, -16.8F, -31.5F);
      action3.setTextureSize(64, 32);
      action3.mirror = true;
      setRotation(action3, 0F, 0F, 0.7853982F);
      action4 = new ModelRenderer(this, 200, 0);
      action4.addBox(0F, 0F, 0F, 1, 1, 18);
      action4.setRotationPoint(-2.5F, -16.8F, -31.5F);
      action4.setTextureSize(64, 32);
      action4.mirror = true;
      setRotation(action4, 0F, 0F, 0.7853982F);
      action5 = new ModelRenderer(this, 200, 0);
      action5.addBox(0F, 0F, 0F, 1, 1, 18);
      action5.setRotationPoint(-3.5F, -15.8F, -31.5F);
      action5.setTextureSize(64, 32);
      action5.mirror = true;
      setRotation(action5, 0F, 0F, -0.7853982F);
      action6 = new ModelRenderer(this, 200, 0);
      action6.addBox(0F, 0F, 0F, 1, 1, 16);
      action6.setRotationPoint(-3.5F, -14.8F, -31.5F);
      action6.setTextureSize(64, 32);
      action6.mirror = true;
      setRotation(action6, 0F, 0F, -0.7853982F);
      action9 = new ModelRenderer(this, 200, 0);
      action9.addBox(0F, 0F, 0F, 1, 1, 16);
      action9.setRotationPoint(-2.5F, -13.8F, -31.5F);
      action9.setTextureSize(64, 32);
      action9.mirror = true;
      setRotation(action9, 0F, 0F, -2.356194F);
      action10 = new ModelRenderer(this, 200, 0);
      action10.addBox(0F, 0F, 0F, 1, 1, 18);
      action10.setRotationPoint(-1.5F, -13.8F, -31.5F);
      action10.setTextureSize(64, 32);
      action10.mirror = true;
      setRotation(action10, 0F, 0F, -2.356194F);
      action18 = new ModelRenderer(this, 200, 0);
      action18.addBox(0F, 0F, 0F, 3, 1, 1);
      action18.setRotationPoint(-4.5F, -16F, -14F);
      action18.setTextureSize(64, 32);
      action18.mirror = true;
      setRotation(action18, 0F, 0F, 0F);
      action19 = new ModelRenderer(this, 200, 0);
      action19.addBox(0F, 0F, 0F, 1, 5, 1);
      action19.setRotationPoint(-4.5F, -16F, -14F);
      action19.setTextureSize(64, 32);
      action19.mirror = true;
      setRotation(action19, 0F, 0F, 0.669215F);
      action37 = new ModelRenderer(this, 200, 0);
      action37.addBox(0F, 0F, 0F, 1, 2, 3);
      action37.setRotationPoint(-2.5F, -16.5F, -13.5F);
      action37.setTextureSize(64, 32);
      action37.mirror = true;
      setRotation(action37, 0F, 0F, 0F);
      action42 = new ModelRenderer(this, 200, 0);
      action42.addBox(0F, 0F, 0F, 1, 1, 3);
      action42.setRotationPoint(-2.7F, -16.4F, -13.5F);
      action42.setTextureSize(64, 32);
      action42.mirror = true;
      setRotation(action42, 0F, 0F, 0F);
      action53 = new ModelRenderer(this, 200, 0);
      action53.addBox(0F, 0F, 0F, 3, 1, 18);
      action53.setRotationPoint(-3.5F, -15.8F, -31.5F);
      action53.setTextureSize(64, 32);
      action53.mirror = true;
      setRotation(action53, 0F, 0F, 0F);
      action54 = new ModelRenderer(this, 200, 0);
      action54.addBox(0F, 0F, 0F, 1, 1, 18);
      action54.setRotationPoint(-0.7F, -15F, -31.5F);
      action54.setTextureSize(64, 32);
      action54.mirror = true;
      setRotation(action54, 0F, 0F, 2.356194F);
      action55 = new ModelRenderer(this, 200, 0);
      action55.addBox(0F, 0F, 0F, 1, 1, 18);
      action55.setRotationPoint(-0.5F, -15.8F, -31.5F);
      action55.setTextureSize(64, 32);
      action55.mirror = true;
      setRotation(action55, 0F, 0F, 2.356194F);
      action56 = new ModelRenderer(this, 200, 0);
      action56.addBox(0F, 0F, 0F, 1, 1, 1);
      action56.setRotationPoint(-2.5F, -16.7F, -14F);
      action56.setTextureSize(64, 32);
      action56.mirror = true;
      setRotation(action56, 0F, 0F, 0F);
      action57 = new ModelRenderer(this, 200, 0);
      action57.addBox(0F, 0F, 0F, 2, 1, 1);
      action57.setRotationPoint(-4.5F, -16F, -14F);
      action57.setTextureSize(64, 32);
      action57.mirror = true;
      setRotation(action57, 0F, 0F, -0.3316126F);
      action58 = new ModelRenderer(this, 200, 0);
      action58.addBox(0F, 0F, 0F, 1, 1, 1);
      action58.setRotationPoint(-2.5F, -16.7F, -14F);
      action58.setTextureSize(64, 32);
      action58.mirror = true;
      setRotation(action58, 0F, 0F, 1.226894F);
      action59 = new ModelRenderer(this, 200, 0);
      action59.addBox(0F, 0F, 0F, 1, 1, 3);
      action59.setRotationPoint(-2.7F, -15.6F, -13.5F);
      action59.setTextureSize(64, 32);
      action59.mirror = true;
      setRotation(action59, 0F, 0F, 0F);
      action60 = new ModelRenderer(this, 200, 0);
      action60.addBox(0F, 0F, 0F, 1, 1, 3);
      action60.setRotationPoint(-2.3F, -16.4F, -13.5F);
      action60.setTextureSize(64, 32);
      action60.mirror = true;
      setRotation(action60, 0F, 0F, 0F);
      action61 = new ModelRenderer(this, 200, 0);
      action61.addBox(0F, 0F, 0F, 1, 1, 3);
      action61.setRotationPoint(-2.3F, -15.6F, -13.5F);
      action61.setTextureSize(64, 32);
      action61.mirror = true;
      setRotation(action61, 0F, 0F, 0F);
      action62 = new ModelRenderer(this, 200, 0);
      action62.addBox(0F, 0F, 0F, 1, 1, 1);
      action62.setRotationPoint(-2.5F, -15.7F, -11.4F);
      action62.setTextureSize(64, 32);
      action62.mirror = true;
      setRotation(action62, 0F, 0F, 0F);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    action1.render(f5);
    action3.render(f5);
    action4.render(f5);
    action5.render(f5);
    action6.render(f5);
    action9.render(f5);
    action10.render(f5);
    action18.render(f5);
    action19.render(f5);
    action37.render(f5);
    action42.render(f5);
    action53.render(f5);
    action54.render(f5);
    action55.render(f5);
    action56.render(f5);
    action57.render(f5);
    action58.render(f5);
    action59.render(f5);
    action60.render(f5);
    action61.render(f5);
    action62.render(f5);
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
