// Date: 11/17/2017 10:31:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LeeEnfieldNo4Magazine extends ModelBase
{
  //fields
    
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
    ModelRenderer mag5;
    ModelRenderer mag6;
    ModelRenderer mag7;
    ModelRenderer mag8;
    ModelRenderer mag9;
    ModelRenderer mag10;
    ModelRenderer mag11;
    ModelRenderer mag12;
    ModelRenderer mag13;
    ModelRenderer mag14;
    ModelRenderer mag15;
    ModelRenderer mag16;
    ModelRenderer mag17;
    ModelRenderer mag18;
    ModelRenderer mag19;
    ModelRenderer mag20;
  
  public LeeEnfieldNo4Magazine()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      mag1 = new ModelRenderer(this, 200, 0);
      mag1.addBox(0F, 0F, 0F, 3, 5, 1);
      mag1.setRotationPoint(-3.5F, -8.1F, -19.25F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, 0.1487144F, 0F, 0F);
      mag2 = new ModelRenderer(this, 200, 0);
      mag2.addBox(0F, 0F, 0F, 3, 5, 5);
      mag2.setRotationPoint(-3.5F, -8.4F, -25.9F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, 0.1487144F, 0F, 0F);
      mag3 = new ModelRenderer(this, 200, 0);
      mag3.addBox(0F, 0F, 0F, 3, 3, 4);
      mag3.setRotationPoint(-3.5F, -8.5F, -30.6F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, 0.1487144F, 0F, 0F);
      mag4 = new ModelRenderer(this, 200, 0);
      mag4.addBox(0F, 0F, 0F, 3, 4, 1);
      mag4.setRotationPoint(-3.5F, -5.5F, -30.1F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, 1.115358F, 0F, 0F);
      mag5 = new ModelRenderer(this, 200, 0);
      mag5.addBox(0F, 0F, 0F, 3, 5, 1);
      mag5.setRotationPoint(-3.5F, -3.4F, -25.15F);
      mag5.setTextureSize(64, 32);
      mag5.mirror = true;
      setRotation(mag5, 1.301251F, 0F, 0F);
      mag6 = new ModelRenderer(this, 200, 0);
      mag6.addBox(0F, 0F, 0F, 3, 1, 1);
      mag6.setRotationPoint(-3.5F, -2.2F, -18.4F);
      mag6.setTextureSize(64, 32);
      mag6.mirror = true;
      setRotation(mag6, 2.453788F, 0F, 0F);
      mag7 = new ModelRenderer(this, 200, 0);
      mag7.addBox(0F, 0F, 0F, 3, 1, 1);
      mag7.setRotationPoint(-3.5F, -2.5F, -18.15F);
      mag7.setTextureSize(64, 32);
      mag7.mirror = true;
      setRotation(mag7, 2.453788F, 0F, 0F);
      mag8 = new ModelRenderer(this, 200, 0);
      mag8.addBox(0F, 0F, 0F, 3, 2, 1);
      mag8.setRotationPoint(-3.5F, -4.1F, -21.25F);
      mag8.setTextureSize(64, 32);
      mag8.mirror = true;
      setRotation(mag8, 0.1487144F, 0F, 0F);
      mag9 = new ModelRenderer(this, 200, 0);
      mag9.addBox(0F, 0F, 0F, 3, 1, 2);
      mag9.setRotationPoint(-3.5F, -3.9F, -23.1F);
      mag9.setTextureSize(64, 32);
      mag9.mirror = true;
      setRotation(mag9, 0.1487144F, 0F, 0F);
      mag10 = new ModelRenderer(this, 200, 0);
      mag10.addBox(0F, 0F, 0F, 3, 3, 1);
      mag10.setRotationPoint(-3.5F, -6.8F, -27.35F);
      mag10.setTextureSize(64, 32);
      mag10.mirror = true;
      setRotation(mag10, 0.1487144F, 0F, 0F);
      mag11 = new ModelRenderer(this, 200, 0);
      mag11.addBox(0F, 0F, 0F, 3, 1, 2);
      mag11.setRotationPoint(-3.5F, -6.5F, -28.35F);
      mag11.setTextureSize(64, 32);
      mag11.mirror = true;
      setRotation(mag11, -0.2974289F, 0F, 0F);
      mag12 = new ModelRenderer(this, 200, 0);
      mag12.addBox(0F, 0F, 0F, 2, 2, 4);
      mag12.setRotationPoint(-3.3F, -3.8F, -26.5F);
      mag12.setTextureSize(64, 32);
      mag12.mirror = true;
      setRotation(mag12, 1.358155F, 0F, 0F);
      mag13 = new ModelRenderer(this, 200, 0);
      mag13.addBox(0F, 0F, 0F, 1, 2, 4);
      mag13.setRotationPoint(-1.7F, -3.8F, -26.5F);
      mag13.setTextureSize(64, 32);
      mag13.mirror = true;
      setRotation(mag13, 1.358155F, 0F, 0F);
      mag14 = new ModelRenderer(this, 200, 0);
      mag14.addBox(0F, 0F, 0F, 1, 1, 4);
      mag14.setRotationPoint(-1.7F, -5.1F, -26.3F);
      mag14.setTextureSize(64, 32);
      mag14.mirror = true;
      setRotation(mag14, 1.76712F, 0F, 0F);
      mag15 = new ModelRenderer(this, 200, 0);
      mag15.addBox(0F, 0F, 0F, 1, 1, 4);
      mag15.setRotationPoint(-3.3F, -5.1F, -26.3F);
      mag15.setTextureSize(64, 32);
      mag15.mirror = true;
      setRotation(mag15, 1.76712F, 0F, 0F);
      mag16 = new ModelRenderer(this, 200, 0);
      mag16.addBox(0F, 0F, 0F, 2, 6, 1);
      mag16.setRotationPoint(-3.3F, -2.1F, -19.3F);
      mag16.setTextureSize(64, 32);
      mag16.mirror = true;
      setRotation(mag16, -3.104414F, 0F, 0F);
      mag17 = new ModelRenderer(this, 200, 0);
      mag17.addBox(0F, 0F, 0F, 1, 6, 1);
      mag17.setRotationPoint(-1.7F, -2.1F, -19.3F);
      mag17.setTextureSize(64, 32);
      mag17.mirror = true;
      setRotation(mag17, -3.104414F, 0F, 0F);
      mag18 = new ModelRenderer(this, 200, 0);
      mag18.addBox(0F, 0F, 0F, 1, 2, 1);
      mag18.setRotationPoint(-1.7F, -6F, -20.3F);
      mag18.setTextureSize(64, 32);
      mag18.mirror = true;
      setRotation(mag18, -3.104414F, 0F, 0F);
      mag19 = new ModelRenderer(this, 200, 0);
      mag19.addBox(0F, 0F, 0F, 1, 2, 1);
      mag19.setRotationPoint(-3.3F, -6F, -20.3F);
      mag19.setTextureSize(64, 32);
      mag19.mirror = true;
      setRotation(mag19, -3.104414F, 0F, 0F);
      mag20 = new ModelRenderer(this, 200, 0);
      mag20.addBox(0F, 0F, 0F, 3, 6, 1);
      mag20.setRotationPoint(-3.5F, -8F, -20.2F);
      mag20.setTextureSize(64, 32);
      mag20.mirror = true;
      setRotation(mag20, 0.1487144F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
    mag5.render(f5);
    mag6.render(f5);
    mag7.render(f5);
    mag8.render(f5);
    mag9.render(f5);
    mag10.render(f5);
    mag11.render(f5);
    mag12.render(f5);
    mag13.render(f5);
    mag14.render(f5);
    mag15.render(f5);
    mag16.render(f5);
    mag17.render(f5);
    mag18.render(f5);
    mag19.render(f5);
    mag20.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
