// Date: 10/30/2017 6:31:08 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LugerAction1 extends ModelBase
{
  //fields
    
    ModelRenderer action1;
    ModelRenderer action2;
    ModelRenderer action3;
    ModelRenderer action4;
    ModelRenderer action5;
    ModelRenderer action6;
    ModelRenderer action7;
    ModelRenderer action8;
    ModelRenderer action9;
    ModelRenderer action10;
    ModelRenderer action13;
    ModelRenderer action15;
    ModelRenderer action16;
    ModelRenderer action17;
    ModelRenderer action18;
    ModelRenderer action19;
    ModelRenderer action20;
    ModelRenderer action21;
    ModelRenderer action22;
    ModelRenderer action23;
    ModelRenderer action24;
    ModelRenderer action25;
    ModelRenderer action26;
    ModelRenderer action27;
    ModelRenderer action28;
    ModelRenderer action29;
    ModelRenderer action30;
    ModelRenderer action31;
    ModelRenderer action32;
    ModelRenderer action33;
    ModelRenderer action34;
    ModelRenderer action35;
    ModelRenderer action36;
    ModelRenderer action37;
  
  public LugerAction1()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      action1 = new ModelRenderer(this, 0, 0);
      action1.addBox(0F, 0F, 0F, 3, 1, 1);
      action1.setRotationPoint(-3F, -12.3F, 3.5F);
      action1.setTextureSize(64, 32);
      action1.mirror = true;
      setRotation(action1, 0F, 0F, 0F);
      action2 = new ModelRenderer(this, 0, 0);
      action2.addBox(0F, 0F, 0F, 3, 1, 1);
      action2.setRotationPoint(-3F, -11.2F, 4.6F);
      action2.setTextureSize(64, 32);
      action2.mirror = true;
      setRotation(action2, 0F, 0F, 0F);
      action3 = new ModelRenderer(this, 0, 0);
      action3.addBox(0F, 0F, 0F, 3, 1, 1);
      action3.setRotationPoint(-3F, -11.2F, 5.6F);
      action3.setTextureSize(64, 32);
      action3.mirror = true;
      setRotation(action3, -2.356194F, 0F, 0F);
      action4 = new ModelRenderer(this, 0, 0);
      action4.addBox(0F, 0F, 0F, 3, 1, 2);
      action4.setRotationPoint(-3F, -10.2F, 5.6F);
      action4.setTextureSize(64, 32);
      action4.mirror = true;
      setRotation(action4, -2.058766F, 0F, 0F);
      action5 = new ModelRenderer(this, 0, 0);
      action5.addBox(0F, 0F, 0F, 3, 1, 1);
      action5.setRotationPoint(-3F, -12.3F, 4.5F);
      action5.setTextureSize(64, 32);
      action5.mirror = true;
      setRotation(action5, -0.7853982F, 0F, 0F);
      action6 = new ModelRenderer(this, 0, 0);
      action6.addBox(0F, 0F, 0F, 3, 1, 4);
      action6.setRotationPoint(-3F, -12.2F, 0F);
      action6.setTextureSize(64, 32);
      action6.mirror = true;
      setRotation(action6, 0F, 0F, 0F);
      action7 = new ModelRenderer(this, 0, 0);
      action7.addBox(0F, 0F, 0F, 3, 1, 1);
      action7.setRotationPoint(-3F, -12.3F, 3.5F);
      action7.setTextureSize(64, 32);
      action7.mirror = true;
      setRotation(action7, -0.7853982F, 0F, 0F);
      action8 = new ModelRenderer(this, 0, 0);
      action8.addBox(0F, 0F, 0F, 1, 1, 2);
      action8.setRotationPoint(-0.51F, -12.2F, -0.5F);
      action8.setTextureSize(64, 32);
      action8.mirror = true;
      setRotation(action8, 0F, 0F, 0F);
      action9 = new ModelRenderer(this, 0, 0);
      action9.addBox(0F, 0F, 0F, 1, 1, 2);
      action9.setRotationPoint(-3.49F, -12.2F, -0.5F);
      action9.setTextureSize(64, 32);
      action9.mirror = true;
      setRotation(action9, 0F, 0F, 0F);
      action10 = new ModelRenderer(this, 0, 0);
      action10.addBox(0F, 0F, 0F, 2, 3, 1);
      action10.setRotationPoint(-4F, -12.5F, -1F);
      action10.setTextureSize(64, 32);
      action10.mirror = true;
      setRotation(action10, 0F, 0F, 0F);
      action13 = new ModelRenderer(this, 0, 0);
      action13.addBox(0F, 0F, 0F, 2, 3, 1);
      action13.setRotationPoint(-1F, -12.5F, -1F);
      action13.setTextureSize(64, 32);
      action13.mirror = true;
      setRotation(action13, 0F, 0F, 0F);
      action15 = new ModelRenderer(this, 0, 0);
      action15.addBox(0F, 0F, 0F, 2, 1, 3);
      action15.setRotationPoint(-1F, -11.5F, -2F);
      action15.setTextureSize(64, 32);
      action15.mirror = true;
      setRotation(action15, 0F, 0F, 0F);
      action16 = new ModelRenderer(this, 0, 0);
      action16.addBox(0F, 0F, 0F, 2, 1, 3);
      action16.setRotationPoint(-4F, -11.5F, -2F);
      action16.setTextureSize(64, 32);
      action16.mirror = true;
      setRotation(action16, 0F, 0F, 0F);
      action17 = new ModelRenderer(this, 0, 0);
      action17.addBox(0F, 0F, 0F, 2, 1, 1);
      action17.setRotationPoint(-1F, -12.5F, -1F);
      action17.setTextureSize(64, 32);
      action17.mirror = true;
      setRotation(action17, -0.7853982F, 0F, 0F);
      action18 = new ModelRenderer(this, 0, 0);
      action18.addBox(0F, 0F, 0F, 2, 1, 1);
      action18.setRotationPoint(-1F, -12.5F, 0F);
      action18.setTextureSize(64, 32);
      action18.mirror = true;
      setRotation(action18, -0.7853982F, 0F, 0F);
      action19 = new ModelRenderer(this, 0, 0);
      action19.addBox(0F, 0F, 0F, 2, 1, 1);
      action19.setRotationPoint(-4F, -12.5F, 0F);
      action19.setTextureSize(64, 32);
      action19.mirror = true;
      setRotation(action19, -0.7853982F, 0F, 0F);
      action20 = new ModelRenderer(this, 0, 0);
      action20.addBox(0F, 0F, 0F, 2, 1, 1);
      action20.setRotationPoint(-4F, -12.5F, -1F);
      action20.setTextureSize(64, 32);
      action20.mirror = true;
      setRotation(action20, -0.7853982F, 0F, 0F);
      action21 = new ModelRenderer(this, 0, 0);
      action21.addBox(0F, 0F, 0F, 2, 1, 1);
      action21.setRotationPoint(-1F, -11.5F, -2F);
      action21.setTextureSize(64, 32);
      action21.mirror = true;
      setRotation(action21, 0.7853982F, 0F, 0F);
      action22 = new ModelRenderer(this, 0, 0);
      action22.addBox(0F, 0F, 0F, 2, 1, 1);
      action22.setRotationPoint(-1F, -10.5F, -2F);
      action22.setTextureSize(64, 32);
      action22.mirror = true;
      setRotation(action22, 0.7853982F, 0F, 0F);
      action23 = new ModelRenderer(this, 0, 0);
      action23.addBox(0F, 0F, 0F, 2, 1, 1);
      action23.setRotationPoint(-4F, -10.5F, -2F);
      action23.setTextureSize(64, 32);
      action23.mirror = true;
      setRotation(action23, 0.7853982F, 0F, 0F);
      action24 = new ModelRenderer(this, 0, 0);
      action24.addBox(0F, 0F, 0F, 2, 1, 1);
      action24.setRotationPoint(-1F, -9.5F, -1F);
      action24.setTextureSize(64, 32);
      action24.mirror = true;
      setRotation(action24, 2.356194F, 0F, 0F);
      action25 = new ModelRenderer(this, 0, 0);
      action25.addBox(0F, 0F, 0F, 2, 1, 1);
      action25.setRotationPoint(-4F, -9.5F, -1F);
      action25.setTextureSize(64, 32);
      action25.mirror = true;
      setRotation(action25, 2.356194F, 0F, 0F);
      action26 = new ModelRenderer(this, 0, 0);
      action26.addBox(0F, 0F, 0F, 2, 1, 1);
      action26.setRotationPoint(-4F, -11.5F, -2F);
      action26.setTextureSize(64, 32);
      action26.mirror = true;
      setRotation(action26, 0.7853982F, 0F, 0F);
      action27 = new ModelRenderer(this, 0, 0);
      action27.addBox(0F, 0F, 0F, 2, 1, 1);
      action27.setRotationPoint(-1F, -11.5F, 1F);
      action27.setTextureSize(64, 32);
      action27.mirror = true;
      setRotation(action27, -2.356194F, 0F, 0F);
      action28 = new ModelRenderer(this, 0, 0);
      action28.addBox(0F, 0F, 0F, 2, 1, 1);
      action28.setRotationPoint(-4F, -11.5F, 1F);
      action28.setTextureSize(64, 32);
      action28.mirror = true;
      setRotation(action28, -2.356194F, 0F, 0F);
      action29 = new ModelRenderer(this, 0, 0);
      action29.addBox(0F, 0F, 0F, 2, 1, 1);
      action29.setRotationPoint(-4F, -10.5F, 1F);
      action29.setTextureSize(64, 32);
      action29.mirror = true;
      setRotation(action29, -2.356194F, 0F, 0F);
      action30 = new ModelRenderer(this, 0, 0);
      action30.addBox(0F, 0F, 0F, 2, 1, 1);
      action30.setRotationPoint(-1F, -10.5F, 1F);
      action30.setTextureSize(64, 32);
      action30.mirror = true;
      setRotation(action30, -2.356194F, 0F, 0F);
      action31 = new ModelRenderer(this, 0, 0);
      action31.addBox(0F, 0F, 0F, 2, 1, 1);
      action31.setRotationPoint(-4F, -9.5F, 0F);
      action31.setTextureSize(64, 32);
      action31.mirror = true;
      setRotation(action31, 2.356194F, 0F, 0F);
      action32 = new ModelRenderer(this, 0, 0);
      action32.addBox(0F, 0F, 0F, 2, 1, 1);
      action32.setRotationPoint(-1F, -9.5F, 0F);
      action32.setTextureSize(64, 32);
      action32.mirror = true;
      setRotation(action32, 2.356194F, 0F, 0F);
      action33 = new ModelRenderer(this, 0, 0);
      action33.addBox(0F, 0F, 0F, 2, 5, 1);
      action33.setRotationPoint(-2.5F, -11.2F, 0F);
      action33.setTextureSize(64, 32);
      action33.mirror = true;
      setRotation(action33, 0.669215F, 0F, 0F);
      action34 = new ModelRenderer(this, 0, 0);
      action34.addBox(0F, 0F, 0F, 1, 1, 1);
      action34.setRotationPoint(-3F, -12.8F, 3F);
      action34.setTextureSize(64, 32);
      action34.mirror = true;
      setRotation(action34, 0F, 0F, 0F);
      action35 = new ModelRenderer(this, 0, 0);
      action35.addBox(0F, 0F, 0F, 1, 1, 1);
      action35.setRotationPoint(-1F, -12.8F, 3F);
      action35.setTextureSize(64, 32);
      action35.mirror = true;
      setRotation(action35, 0F, 0F, 0F);
      action36 = new ModelRenderer(this, 0, 0);
      action36.addBox(0F, 0F, 0F, 1, 1, 1);
      action36.setRotationPoint(-1F, -12.8F, 3F);
      action36.setTextureSize(64, 32);
      action36.mirror = true;
      setRotation(action36, 0F, 0F, 0.7853982F);
      action37 = new ModelRenderer(this, 0, 0);
      action37.addBox(0F, 0F, 0F, 1, 1, 1);
      action37.setRotationPoint(-2F, -12.8F, 3F);
      action37.setTextureSize(64, 32);
      action37.mirror = true;
      setRotation(action37, 0F, 0F, 0.7853982F);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    action1.render(f5);
    action2.render(f5);
    action3.render(f5);
    action4.render(f5);
    action5.render(f5);
    action6.render(f5);
    action7.render(f5);
    action8.render(f5);
    action9.render(f5);
    action10.render(f5);
    action13.render(f5);
    action15.render(f5);
    action16.render(f5);
    action17.render(f5);
    action18.render(f5);
    action19.render(f5);
    action20.render(f5);
    action21.render(f5);
    action22.render(f5);
    action23.render(f5);
    action24.render(f5);
    action25.render(f5);
    action26.render(f5);
    action27.render(f5);
    action28.render(f5);
    action29.render(f5);
    action30.render(f5);
    action31.render(f5);
    action32.render(f5);
    action33.render(f5);
    action34.render(f5);
    action35.render(f5);
    action36.render(f5);
    action37.render(f5);
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
