// Date: 10/30/2017 6:30:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LugerMag extends ModelBase
{
  //fields
    
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
    ModelRenderer mag5;
    ModelRenderer mag6;
    ModelRenderer mag7;
    ModelRenderer mag8;
    ModelRenderer mag9;
    ModelRenderer mag10;
    ModelRenderer mag11;
  
  public LugerMag()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      mag1 = new ModelRenderer(this, 0, 0);
      mag1.addBox(0F, 0F, 0F, 3, 16, 6);
      mag1.setRotationPoint(-3.3F, 5.4F, 6.8F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, -2.67686F, 0F, 0F);
      mag2 = new ModelRenderer(this, 0, 0);
      mag2.addBox(0F, 0F, 0F, 1, 16, 6);
      mag2.setRotationPoint(-0.7F, 5.4F, 6.8F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, -2.67686F, 0F, 0F);
      mag3 = new ModelRenderer(this, 0, 0);
      mag3.addBox(0F, 0F, 0F, 3, 2, 3);
      mag3.setRotationPoint(-3.3F, 5.4F, 6.8F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, -2.007645F, 0F, 0F);
      mag4 = new ModelRenderer(this, 0, 0);
      mag4.addBox(0F, 0F, 0F, 1, 2, 3);
      mag4.setRotationPoint(-0.7F, 5.4F, 6.8F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, -2.007645F, 0F, 0F);
      mag5 = new ModelRenderer(this, 0, 0);
      mag5.addBox(0F, 0F, 0F, 3, 2, 2);
      mag5.setRotationPoint(-3.3F, 8.2F, 1.5F);
      mag5.setTextureSize(64, 32);
      mag5.mirror = true;
      setRotation(mag5, 1.07818F, 0F, 0F);
      mag6 = new ModelRenderer(this, 0, 0);
      mag6.addBox(0F, 0F, 0F, 1, 2, 2);
      mag6.setRotationPoint(-0.7F, 8.2F, 1.5F);
      mag6.setTextureSize(64, 32);
      mag6.mirror = true;
      setRotation(mag6, 1.07818F, 0F, 0F);
      mag7 = new ModelRenderer(this, 0, 0);
      mag7.addBox(0F, 0F, 0F, 1, 2, 2);
      mag7.setRotationPoint(-0.7F, 7.4F, 2.5F);
      mag7.setTextureSize(64, 32);
      mag7.mirror = true;
      setRotation(mag7, 0.4461433F, 0F, 0F);
      mag8 = new ModelRenderer(this, 0, 0);
      mag8.addBox(0F, 0F, 0F, 3, 2, 2);
      mag8.setRotationPoint(-3.3F, 7.4F, 2.5F);
      mag8.setTextureSize(64, 32);
      mag8.mirror = true;
      setRotation(mag8, 0.4461433F, 0F, 0F);
      mag9 = new ModelRenderer(this, 0, 0);
      mag9.addBox(0F, 0F, 0F, 3, 2, 1);
      mag9.setRotationPoint(-3.3F, 6.75F, 3.8F);
      mag9.setTextureSize(64, 32);
      mag9.mirror = true;
      setRotation(mag9, 0.4461433F, 0F, 0F);
      mag10 = new ModelRenderer(this, 0, 0);
      mag10.addBox(0F, 0F, 0F, 1, 2, 1);
      mag10.setRotationPoint(-0.7F, 6.75F, 3.8F);
      mag10.setTextureSize(64, 32);
      mag10.mirror = true;
      setRotation(mag10, 0.4461433F, 0F, 0F);
      mag11 = new ModelRenderer(this, 0, 0);
      mag11.addBox(0F, 0F, 0F, 4, 2, 2);
      mag11.setRotationPoint(-3.5F, 7.8F, 3F);
      mag11.setTextureSize(64, 32);
      mag11.mirror = true;
      setRotation(mag11, 0.4461433F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
    mag5.render(f5);
    mag6.render(f5);
    mag7.render(f5);
    mag8.render(f5);
    mag9.render(f5);
    mag10.render(f5);
    mag11.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
}
