// Date: 5/25/2017 9:56:35 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M14Action2 extends ModelBase
{
  //fields
    ModelRenderer Action1;
    ModelRenderer Action4;
    ModelRenderer Action5;
    ModelRenderer Action8;
    ModelRenderer Action9;
    ModelRenderer Action10;
    ModelRenderer Action11;
  
  public M14Action2()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Action1 = new ModelRenderer(this, 0, 0);
      Action1.addBox(0F, 0F, 0F, 1, 1, 19);
      Action1.setRotationPoint(-2F, -15.7F, -37F);
      Action1.setTextureSize(64, 32);
      Action1.mirror = true;
      setRotation(Action1, 0F, 0F, 0F);
      Action4 = new ModelRenderer(this, 0, 0);
      Action4.addBox(0F, 0F, 0F, 1, 1, 19);
      Action4.setRotationPoint(-3.2F, -14.2F, -37.5F);
      Action4.setTextureSize(64, 32);
      Action4.mirror = true;
      setRotation(Action4, 0F, 0F, 0F);
      Action5 = new ModelRenderer(this, 0, 0);
      Action5.addBox(0F, 0F, 0F, 1, 1, 19);
      Action5.setRotationPoint(-0.8F, -14.2F, -37.5F);
      Action5.setTextureSize(64, 32);
      Action5.mirror = true;
      setRotation(Action5, 0F, 0F, 0F);
      Action8 = new ModelRenderer(this, 0, 0);
      Action8.addBox(0F, 0F, 0F, 1, 1, 19);
      Action8.setRotationPoint(-2F, -15.7F, -37F);
      Action8.setTextureSize(64, 32);
      Action8.mirror = true;
      setRotation(Action8, 0F, 0F, 0.9294653F);
      Action9 = new ModelRenderer(this, 0, 0);
      Action9.addBox(0F, 0F, 0F, 1, 1, 19);
      Action9.setRotationPoint(-3.2F, -14.2F, -37.5F);
      Action9.setTextureSize(64, 32);
      Action9.mirror = true;
      setRotation(Action9, 0F, 0F, -1.152537F);
      Action10 = new ModelRenderer(this, 0, 0);
      Action10.addBox(0F, 0F, 0F, 1, 1, 19);
      Action10.setRotationPoint(-1F, -15.7F, -37F);
      Action10.setTextureSize(64, 32);
      Action10.mirror = true;
      setRotation(Action10, 0F, 0F, 0.7063936F);
      Action11 = new ModelRenderer(this, 0, 0);
      Action11.addBox(0F, 0F, 0F, 1, 1, 19);
      Action11.setRotationPoint(0.2F, -14.2F, -37.5F);
      Action11.setTextureSize(64, 32);
      Action11.mirror = true;
      setRotation(Action11, 0F, 0F, 2.670354F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Action1.render(f5);
    Action4.render(f5);
    Action5.render(f5);
    Action8.render(f5);
    Action9.render(f5);
    Action10.render(f5);
    Action11.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
