// Date: 6/26/2019 2:54:36 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M16Stock extends ModelBase
{
  //fields
    ModelRenderer gun369;
    ModelRenderer gun370;
    ModelRenderer gun371;
    ModelRenderer gun372;
    ModelRenderer gun373;
    ModelRenderer gun375;
    ModelRenderer gun376;
    ModelRenderer gun385;
    ModelRenderer gun386;
    ModelRenderer gun387;
    ModelRenderer gun388;
    ModelRenderer gun389;
    ModelRenderer gun390;
    ModelRenderer gun391;
    ModelRenderer gun392;
    ModelRenderer gun393;
    ModelRenderer gun394;
    ModelRenderer gun395;
    ModelRenderer gun396;
  
  public M16Stock()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      gun369 = new ModelRenderer(this, 0, 0);
      gun369.addBox(0F, 0F, 0F, 2, 1, 41);
      gun369.setRotationPoint(-3.2F, -10.5F, 7.5F);
      gun369.setTextureSize(64, 32);
      gun369.mirror = true;
      setRotation(gun369, 0F, 0F, 0F);
      gun370 = new ModelRenderer(this, 0, 0);
      gun370.addBox(0F, 0F, 0F, 2, 1, 41);
      gun370.setRotationPoint(-1.8F, -10.5F, 7.5F);
      gun370.setTextureSize(64, 32);
      gun370.mirror = true;
      setRotation(gun370, 0F, 0F, 0F);
      gun371 = new ModelRenderer(this, 0, 0);
      gun371.addBox(0F, 0F, 0F, 1, 1, 41);
      gun371.setRotationPoint(-1F, -11.7F, 7.5F);
      gun371.setTextureSize(64, 32);
      gun371.mirror = true;
      setRotation(gun371, 0F, 0F, 0.7853982F);
      gun372 = new ModelRenderer(this, 0, 0);
      gun372.addBox(0F, 0F, 0F, 1, 1, 41);
      gun372.setRotationPoint(-2F, -11.7F, 7.5F);
      gun372.setTextureSize(64, 32);
      gun372.mirror = true;
      setRotation(gun372, 0F, 0F, 0.7853982F);
      gun373 = new ModelRenderer(this, 0, 0);
      gun373.addBox(0F, 0F, 0F, 1, 1, 41);
      gun373.setRotationPoint(-3.2F, -10.5F, 7.5F);
      gun373.setTextureSize(64, 32);
      gun373.mirror = true;
      setRotation(gun373, 0F, 0F, -0.7853982F);
      gun375 = new ModelRenderer(this, 0, 0);
      gun375.addBox(0F, 0F, 0F, 1, 1, 41);
      gun375.setRotationPoint(0.2F, -10.5F, 7.5F);
      gun375.setTextureSize(64, 32);
      gun375.mirror = true;
      setRotation(gun375, 0F, 0F, 2.356194F);
      gun376 = new ModelRenderer(this, 0, 0);
      gun376.addBox(0F, 0F, 0F, 4, 1, 39);
      gun376.setRotationPoint(0.2F, -9.5F, 7.5F);
      gun376.setTextureSize(64, 32);
      gun376.mirror = true;
      setRotation(gun376, 0F, 0F, 1.761337F);
      gun385 = new ModelRenderer(this, 0, 0);
      gun385.addBox(0F, 0F, 0F, 1, 3, 41);
      gun385.setRotationPoint(-2F, -11.7F, 7.5F);
      gun385.setTextureSize(64, 32);
      gun385.mirror = true;
      setRotation(gun385, 0F, 0F, 0F);
      gun386 = new ModelRenderer(this, 0, 0);
      gun386.addBox(0F, 0F, 0F, 2, 2, 14);
      gun386.setRotationPoint(-2.5F, -8.7F, 48.5F);
      gun386.setTextureSize(64, 32);
      gun386.mirror = true;
      setRotation(gun386, -1.784573F, 0F, 0F);
      gun387 = new ModelRenderer(this, 0, 0);
      gun387.addBox(0F, 0F, 0F, 2, 4, 2);
      gun387.setRotationPoint(-2.5F, -9.7F, 7.5F);
      gun387.setTextureSize(64, 32);
      gun387.mirror = true;
      setRotation(gun387, 0F, 0F, 0F);
      gun388 = new ModelRenderer(this, 0, 0);
      gun388.addBox(0F, 0F, 0F, 2, 14, 4);
      gun388.setRotationPoint(-2.5F, -5.7F, 7.5F);
      gun388.setTextureSize(64, 32);
      gun388.mirror = true;
      setRotation(gun388, 1.449966F, 0F, 0F);
      gun389 = new ModelRenderer(this, 0, 0);
      gun389.addBox(0F, 0F, 0F, 2, 26, 6);
      gun389.setRotationPoint(-2.5F, -4.1F, 20F);
      gun389.setTextureSize(64, 32);
      gun389.mirror = true;
      setRotation(gun389, 1.226894F, 0F, 0F);
      gun390 = new ModelRenderer(this, 0, 0);
      gun390.addBox(-4F, 0F, 0F, 4, 1, 39);
      gun390.setRotationPoint(-3.2F, -9.5F, 7.5F);
      gun390.setTextureSize(64, 32);
      gun390.mirror = true;
      setRotation(gun390, 0F, 0F, -1.761334F);
      gun391 = new ModelRenderer(this, 0, 0);
      gun391.addBox(0F, 0F, 0F, 6, 1, 21);
      gun391.setRotationPoint(0.2F, -9.5F, 25.5F);
      gun391.setTextureSize(64, 32);
      gun391.mirror = true;
      setRotation(gun391, 0F, 0F, 1.675516F);
      gun392 = new ModelRenderer(this, 0, 0);
      gun392.addBox(-6F, 0F, 0F, 6, 1, 21);
      gun392.setRotationPoint(-3.2F, -9.5F, 25.5F);
      gun392.setTextureSize(64, 32);
      gun392.mirror = true;
      setRotation(gun392, 0F, 0F, -1.675516F);
      gun393 = new ModelRenderer(this, 0, 0);
      gun393.addBox(-10F, 0F, 0F, 10, 1, 10);
      gun393.setRotationPoint(-3.2F, -9.5F, 35.5F);
      gun393.setTextureSize(64, 32);
      gun393.mirror = true;
      setRotation(gun393, 0F, 0F, -1.638337F);
      gun394 = new ModelRenderer(this, 0, 0);
      gun394.addBox(0F, 0F, 0F, 10, 1, 10);
      gun394.setRotationPoint(0.2F, -9.5F, 35.5F);
      gun394.setTextureSize(64, 32);
      gun394.mirror = true;
      setRotation(gun394, 0F, 0F, 1.638341F);
      gun395 = new ModelRenderer(this, 0, 0);
      gun395.addBox(0F, 0F, 0F, 2, 2, 2);
      gun395.setRotationPoint(-3.2F, -9.5F, 46.5F);
      gun395.setTextureSize(64, 32);
      gun395.mirror = true;
      setRotation(gun395, 0F, 0F, -0.4833219F);
      gun396 = new ModelRenderer(this, 0, 0);
      gun396.addBox(-1F, 0F, 0F, 1, 2, 2);
      gun396.setRotationPoint(0.2F, -9.5F, 46.5F);
      gun396.setTextureSize(64, 32);
      gun396.mirror = true;
      setRotation(gun396, 0F, 0F, 0.4833166F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun369.render(f5);
    gun370.render(f5);
    gun371.render(f5);
    gun372.render(f5);
    gun373.render(f5);
    gun375.render(f5);
    gun376.render(f5);
    gun385.render(f5);
    gun386.render(f5);
    gun387.render(f5);
    gun388.render(f5);
    gun389.render(f5);
    gun390.render(f5);
    gun391.render(f5);
    gun392.render(f5);
    gun393.render(f5);
    gun394.render(f5);
    gun395.render(f5);
    gun396.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
