// Date: 10/22/2017 11:45:56 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M1903A1scope2 extends ModelBase
{
  //fields
    ModelRenderer scope1;
    ModelRenderer scope2;
    ModelRenderer scope3;
    ModelRenderer scope4;
    ModelRenderer scope5;
    ModelRenderer scope7;
    ModelRenderer scope8;
    ModelRenderer scope9;
    ModelRenderer scope10;
    ModelRenderer scope11;
    ModelRenderer scope12;
    ModelRenderer scope13;
    ModelRenderer scope14;
    ModelRenderer scope15;
    ModelRenderer scope16;
    ModelRenderer scope17;
    ModelRenderer scope18;
    ModelRenderer scope19;
    ModelRenderer scope20;
    ModelRenderer scope21;
  
  public M1903A1scope2()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      scope1 = new ModelRenderer(this, 0, 0);
      scope1.addBox(0F, 0F, 0F, 3, 1, 20);
      scope1.setRotationPoint(0F, 0F, 0F);
      scope1.setTextureSize(64, 32);
      scope1.mirror = true;
      setRotation(scope1, 0F, 0F, 0F);
      scope2 = new ModelRenderer(this, 0, 0);
      scope2.addBox(0F, 0F, 0F, 3, 1, 20);
      scope2.setRotationPoint(0F, -8F, 0F);
      scope2.setTextureSize(64, 32);
      scope2.mirror = true;
      setRotation(scope2, 0F, 0F, 0F);
      scope3 = new ModelRenderer(this, 0, 0);
      scope3.addBox(0F, 0F, 0F, 1, 3, 20);
      scope3.setRotationPoint(-3F, -5F, 0F);
      scope3.setTextureSize(64, 32);
      scope3.mirror = true;
      setRotation(scope3, 0F, 0F, 0F);
      scope4 = new ModelRenderer(this, 0, 0);
      scope4.addBox(0F, 0F, 0F, 1, 3, 20);
      scope4.setRotationPoint(5F, -5F, 0F);
      scope4.setTextureSize(64, 32);
      scope4.mirror = true;
      setRotation(scope4, 0F, 0F, 0F);
      scope5 = new ModelRenderer(this, 0, 0);
      scope5.addBox(0F, 0F, 0F, 4, 1, 20);
      scope5.setRotationPoint(-3F, -5F, 0F);
      scope5.setTextureSize(64, 32);
      scope5.mirror = true;
      setRotation(scope5, 0F, 0F, -0.7853982F);
      scope7 = new ModelRenderer(this, 0, 0);
      scope7.addBox(0F, 0F, 0F, 1, 4, 20);
      scope7.setRotationPoint(-3F, -2F, 0F);
      scope7.setTextureSize(64, 32);
      scope7.mirror = true;
      setRotation(scope7, 0F, 0F, -0.7853982F);
      scope8 = new ModelRenderer(this, 0, 0);
      scope8.addBox(0F, 0F, 0F, 4, 1, 20);
      scope8.setRotationPoint(6F, -2F, 0F);
      scope8.setTextureSize(64, 32);
      scope8.mirror = true;
      setRotation(scope8, 0F, 0F, 2.356194F);
      scope9 = new ModelRenderer(this, 0, 0);
      scope9.addBox(0F, 0F, 0F, 1, 4, 20);
      scope9.setRotationPoint(6F, -5F, 0F);
      scope9.setTextureSize(64, 32);
      scope9.mirror = true;
      setRotation(scope9, 0F, 0F, 2.356194F);
      scope10 = new ModelRenderer(this, 0, 0);
      scope10.addBox(0F, 0F, 0F, 3, 1, 1);
      scope10.setRotationPoint(0F, -7.5F, 18.5F);
      scope10.setTextureSize(64, 32);
      scope10.mirror = true;
      setRotation(scope10, 0F, 0F, 0F);
      scope11 = new ModelRenderer(this, 0, 0);
      scope11.addBox(0F, 0F, 0F, 3, 1, 1);
      scope11.setRotationPoint(0F, -0.5F, 18.5F);
      scope11.setTextureSize(64, 32);
      scope11.mirror = true;
      setRotation(scope11, 0F, 0F, 0F);
      scope12 = new ModelRenderer(this, 0, 0);
      scope12.addBox(0F, 0F, 0F, 1, 3, 1);
      scope12.setRotationPoint(-2.5F, -5F, 18.5F);
      scope12.setTextureSize(64, 32);
      scope12.mirror = true;
      setRotation(scope12, 0F, 0F, 0F);
      scope13 = new ModelRenderer(this, 0, 0);
      scope13.addBox(0F, 0F, 0F, 1, 3, 1);
      scope13.setRotationPoint(4.5F, -5F, 18.5F);
      scope13.setTextureSize(64, 32);
      scope13.mirror = true;
      setRotation(scope13, 0F, 0F, 0F);
      scope14 = new ModelRenderer(this, 0, 0);
      scope14.addBox(0F, 0F, 0F, 1, 4, 1);
      scope14.setRotationPoint(5.5F, -5F, 18.5F);
      scope14.setTextureSize(64, 32);
      scope14.mirror = true;
      setRotation(scope14, 0F, 0F, 2.356194F);
      scope15 = new ModelRenderer(this, 0, 0);
      scope15.addBox(0F, 0F, 0F, 4, 1, 1);
      scope15.setRotationPoint(5.5F, -2F, 18.5F);
      scope15.setTextureSize(64, 32);
      scope15.mirror = true;
      setRotation(scope15, 0F, 0F, 2.356194F);
      scope16 = new ModelRenderer(this, 0, 0);
      scope16.addBox(0F, 0F, 0F, 1, 4, 1);
      scope16.setRotationPoint(0F, -7.5F, 18.5F);
      scope16.setTextureSize(64, 32);
      scope16.mirror = true;
      setRotation(scope16, 0F, 0F, 0.7853982F);
      scope17 = new ModelRenderer(this, 0, 0);
      scope17.addBox(0F, 0F, 0F, 1, 4, 1);
      scope17.setRotationPoint(-2.5F, -2F, 18.5F);
      scope17.setTextureSize(64, 32);
      scope17.mirror = true;
      setRotation(scope17, 0F, 0F, -0.7853982F);
      scope18 = new ModelRenderer(this, 0, 0);
      scope18.addBox(0F, 0F, 0F, 1, 1, 20);
      scope18.setRotationPoint(0F, -8F, 0F);
      scope18.setTextureSize(64, 32);
      scope18.mirror = true;
      setRotation(scope18, 0F, 0F, 0.7853982F);
      scope19 = new ModelRenderer(this, 0, 0);
      scope19.addBox(0F, 0F, 0F, 1, 1, 20);
      scope19.setRotationPoint(3F, -8F, 0F);
      scope19.setTextureSize(64, 32);
      scope19.mirror = true;
      setRotation(scope19, 0F, 0F, 0.7853982F);
      scope20 = new ModelRenderer(this, 0, 0);
      scope20.addBox(0F, 0F, 0F, 1, 1, 20);
      scope20.setRotationPoint(0F, 1F, 0F);
      scope20.setTextureSize(64, 32);
      scope20.mirror = true;
      setRotation(scope20, 0F, 0F, -2.356194F);
      scope21 = new ModelRenderer(this, 0, 0);
      scope21.addBox(0F, 0F, 0F, 1, 1, 20);
      scope21.setRotationPoint(3F, 1F, 0F);
      scope21.setTextureSize(64, 32);
      scope21.mirror = true;
      setRotation(scope21, 0F, 0F, -2.356194F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    scope1.render(f5);
    scope2.render(f5);
    scope3.render(f5);
    scope4.render(f5);
    scope5.render(f5);
    scope7.render(f5);
    scope8.render(f5);
    scope9.render(f5);
    scope10.render(f5);
    scope11.render(f5);
    scope12.render(f5);
    scope13.render(f5);
    scope14.render(f5);
    scope15.render(f5);
    scope16.render(f5);
    scope17.render(f5);
    scope18.render(f5);
    scope19.render(f5);
    scope20.render(f5);
    scope21.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
