// Date: 10/28/2017 1:19:32 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M1928action extends ModelBase
{
  //fields
    
    ModelRenderer action5;
    ModelRenderer action6;
    ModelRenderer action7;
    ModelRenderer action8;
    ModelRenderer action9;
    ModelRenderer action10;
    ModelRenderer action11;
    ModelRenderer action12;
  
  public M1928action()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      action5 = new ModelRenderer(this, 0, 0);
      action5.addBox(0F, 0F, 0F, 2, 1, 7);
      action5.setRotationPoint(-2.8F, -8.8F, -14.5F);
      action5.setTextureSize(64, 32);
      action5.mirror = true;
      setRotation(action5, 0F, 0F, 0F);
      action6 = new ModelRenderer(this, 0, 0);
      action6.addBox(0F, 0F, 0F, 1, 1, 7);
      action6.setRotationPoint(-1.8F, -9.8F, -14.5F);
      action6.setTextureSize(64, 32);
      action6.mirror = true;
      setRotation(action6, 0F, 0F, 0F);
      action7 = new ModelRenderer(this, 0, 0);
      action7.addBox(0F, 0F, 0F, 1, 1, 7);
      action7.setRotationPoint(-1.8F, -9.8F, -14.5F);
      action7.setTextureSize(64, 32);
      action7.mirror = true;
      setRotation(action7, 0F, 0F, 0.7853982F);
      action8 = new ModelRenderer(this, 0, 0);
      action8.addBox(0F, 0F, 0F, 1, 1, 7);
      action8.setRotationPoint(-2.8F, -8.8F, -14.5F);
      action8.setTextureSize(64, 32);
      action8.mirror = true;
      setRotation(action8, 0F, 0F, -0.7853982F);
      
      action9 = new ModelRenderer(this, 0, 0);
      action9.addBox(0F, 0F, 0F, 1, 1, 18);
      action9.setRotationPoint(-1.5F, -10F, -6.5F);
      action9.setTextureSize(64, 32);
      action9.mirror = true;
      setRotation(action9, 0F, 0F, 0F);
      action10 = new ModelRenderer(this, 0, 0);
      action10.addBox(0F, 0F, 0F, 1, 1, 1);
      action10.setRotationPoint(-1.4F, -11.3F, -6.5F);
      action10.setTextureSize(64, 32);
      action10.mirror = true;
      setRotation(action10, 0F, 0F, 0.7853982F);
      action11 = new ModelRenderer(this, 0, 0);
      action11.addBox(0F, 0F, 0F, 1, 1, 1);
      action11.setRotationPoint(-0.6F, -11.3F, -6.5F);
      action11.setTextureSize(64, 32);
      action11.mirror = true;
      setRotation(action11, 0F, 0F, 0.7853982F);
      action12 = new ModelRenderer(this, 0, 0);
      action12.addBox(0F, 0F, 0F, 1, 1, 1);
      action12.setRotationPoint(-1.5F, -10.5F, -6.5F);
      action12.setTextureSize(64, 32);
      action12.mirror = true;
      setRotation(action12, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    action5.render(f5);
    action6.render(f5);
    action7.render(f5);
    action8.render(f5);
    
    action9.render(f5);
    action10.render(f5);
    action11.render(f5);
    action12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
