// Date: 10/20/2017 9:20:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M1CarbineRearSight extends ModelBase
{
  //fields
    ModelRenderer sight1;
    ModelRenderer sight2;
    ModelRenderer sight3;
    ModelRenderer sight4;
    ModelRenderer sight5;
    ModelRenderer sight6;
    ModelRenderer sight7;
    ModelRenderer sight77;
    ModelRenderer sight8;
    ModelRenderer sight9;
    ModelRenderer sight10;
    ModelRenderer sight11;
    ModelRenderer sight12;
    ModelRenderer sight13;
    ModelRenderer sight14;
    ModelRenderer sight15;
    ModelRenderer sight16;
    ModelRenderer sight17;
    ModelRenderer sight18;
    ModelRenderer sight19;
    ModelRenderer sight20;
    ModelRenderer sight21;
    ModelRenderer sight22;
    ModelRenderer sight23;
    ModelRenderer sight24;
  
  public M1CarbineRearSight()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      sight1 = new ModelRenderer(this, 0, 0);
      sight1.addBox(0F, 0F, 0F, 2, 5, 3);
      sight1.setRotationPoint(-2F, -6F, -2F);
      sight1.setTextureSize(64, 32);
      sight1.mirror = true;
      setRotation(sight1, 0F, 0F, 0F);
      sight2 = new ModelRenderer(this, 0, 0);
      sight2.addBox(0F, 0F, 0F, 2, 5, 3);
      sight2.setRotationPoint(4F, -6F, -2F);
      sight2.setTextureSize(64, 32);
      sight2.mirror = true;
      setRotation(sight2, 0F, 0F, 0F);
      sight3 = new ModelRenderer(this, 0, 0);
      sight3.addBox(0F, 0F, 0F, 2, 2, 3);
      sight3.setRotationPoint(1F, -8F, -2F);
      sight3.setTextureSize(64, 32);
      sight3.mirror = true;
      setRotation(sight3, 0F, 0F, 0F);
      sight4 = new ModelRenderer(this, 0, 0);
      sight4.addBox(0F, 0F, 0F, 4, 2, 3);
      sight4.setRotationPoint(0F, -3F, -2F);
      sight4.setTextureSize(64, 32);
      sight4.mirror = true;
      setRotation(sight4, 0F, 0F, 0F);
      sight5 = new ModelRenderer(this, 0, 0);
      sight5.addBox(0F, 0F, 0F, 2, 6, 12);
      sight5.setRotationPoint(6F, -3F, -6F);
      sight5.setTextureSize(64, 32);
      sight5.mirror = true;
      setRotation(sight5, 0F, 0F, 0F);
      sight6 = new ModelRenderer(this, 0, 0);
      sight6.addBox(0F, 0F, 0F, 2, 6, 12);
      sight6.setRotationPoint(-4F, -3F, -6F);
      sight6.setTextureSize(64, 32);
      sight6.mirror = true;
      setRotation(sight6, 0F, 0F, 0F);
      sight7 = new ModelRenderer(this, 0, 0);
      sight7.addBox(0F, 0F, 0F, 1, 3, 3);
      sight7.setRotationPoint(3.5F, -6F, -2F);
      sight7.setTextureSize(64, 32);
      sight7.mirror = true;
      setRotation(sight7, 0F, 0F, 0F);
      sight77 = new ModelRenderer(this, 0, 0);
      sight77.addBox(0F, 0F, 0F, 1, 3, 3);
      sight77.setRotationPoint(-0.5F, -6F, -2F);
      sight77.setTextureSize(64, 32);
      sight77.mirror = true;
      setRotation(sight77, 0F, 0F, 0F);
      sight8 = new ModelRenderer(this, 0, 0);
      sight8.addBox(0F, 0F, 0F, 2, 2, 3);
      sight8.setRotationPoint(3F, -8F, -2F);
      sight8.setTextureSize(64, 32);
      sight8.mirror = true;
      setRotation(sight8, 0F, 0F, 0.2602503F);
      sight9 = new ModelRenderer(this, 0, 0);
      sight9.addBox(0F, 0F, 0F, 2, 2, 3);
      sight9.setRotationPoint(1F, -8F, -2F);
      sight9.setTextureSize(64, 32);
      sight9.mirror = true;
      setRotation(sight9, 0F, 0F, 1.291544F);
      sight10 = new ModelRenderer(this, 0, 0);
      sight10.addBox(0F, 0F, 0F, 2, 2, 3);
      sight10.setRotationPoint(-2F, -6F, -2F);
      sight10.setTextureSize(64, 32);
      sight10.mirror = true;
      setRotation(sight10, 0F, 0F, -0.8922867F);
      sight11 = new ModelRenderer(this, 0, 0);
      sight11.addBox(0F, 0F, 0F, 2, 2, 3);
      sight11.setRotationPoint(6F, -6F, -2F);
      sight11.setTextureSize(64, 32);
      sight11.mirror = true;
      setRotation(sight11, 0F, 0F, 2.490967F);
      sight12 = new ModelRenderer(this, 0, 0);
      sight12.addBox(0F, 0F, 0F, 2, 1, 3);
      sight12.setRotationPoint(0F, -4F, -2F);
      sight12.setTextureSize(64, 32);
      sight12.mirror = true;
      setRotation(sight12, 0F, 0F, 0.7853982F);
      sight13 = new ModelRenderer(this, 0, 0);
      sight13.addBox(0F, 0F, 0F, 1, 2, 3);
      sight13.setRotationPoint(4F, -4F, -2F);
      sight13.setTextureSize(64, 32);
      sight13.mirror = true;
      setRotation(sight13, 0F, 0F, 0.7853982F);
      sight14 = new ModelRenderer(this, 0, 0);
      sight14.addBox(0F, 0F, 0F, 1, 2, 3);
      sight14.setRotationPoint(0F, -5F, -2F);
      sight14.setTextureSize(64, 32);
      sight14.mirror = true;
      setRotation(sight14, 0F, 0F, -2.356194F);
      sight15 = new ModelRenderer(this, 0, 0);
      sight15.addBox(0F, 0F, 0F, 2, 1, 3);
      sight15.setRotationPoint(4F, -5F, -2F);
      sight15.setTextureSize(64, 32);
      sight15.mirror = true;
      setRotation(sight15, 0F, 0F, -2.356194F);
      sight16 = new ModelRenderer(this, 0, 0);
      sight16.addBox(0F, 0F, 0F, 8, 4, 5);
      sight16.setRotationPoint(-2F, -1F, -3F);
      sight16.setTextureSize(64, 32);
      sight16.mirror = true;
      setRotation(sight16, 0F, 0F, 0F);
      sight17 = new ModelRenderer(this, 0, 0);
      sight17.addBox(0F, 0F, 0F, 8, 1, 2);
      sight17.setRotationPoint(-2F, -1F, -3F);
      sight17.setTextureSize(64, 32);
      sight17.mirror = true;
      setRotation(sight17, 0.6738623F, 0F, 0F);
      sight18 = new ModelRenderer(this, 0, 0);
      sight18.addBox(0F, 0F, 0F, 8, 2, 1);
      sight18.setRotationPoint(-2F, -1F, 2F);
      sight18.setTextureSize(64, 32);
      sight18.mirror = true;
      setRotation(sight18, -2.170301F, 0F, 0F);
      sight19 = new ModelRenderer(this, 0, 0);
      sight19.addBox(0F, 0F, 0F, 8, 3, 8);
      sight19.setRotationPoint(-2F, -1F, -11F);
      sight19.setTextureSize(64, 32);
      sight19.mirror = true;
      setRotation(sight19, 0F, 0F, 0F);
      sight20 = new ModelRenderer(this, 0, 0);
      sight20.addBox(0F, 0F, 0F, 2, 3, 2);
      sight20.setRotationPoint(1F, -1F, -13F);
      sight20.setTextureSize(64, 32);
      sight20.mirror = true;
      setRotation(sight20, 0F, 0F, 0F);
      sight21 = new ModelRenderer(this, 0, 0);
      sight21.addBox(0F, 0F, 0F, 2, 3, 2);
      sight21.setRotationPoint(1F, -1F, -13F);
      sight21.setTextureSize(64, 32);
      sight21.mirror = true;
      setRotation(sight21, 0F, -1.226894F, 0F);
      sight22 = new ModelRenderer(this, 0, 0);
      sight22.addBox(0F, 0F, 0F, 2, 3, 2);
      sight22.setRotationPoint(3F, -1F, -13F);
      sight22.setTextureSize(64, 32);
      sight22.mirror = true;
      setRotation(sight22, 0F, -0.3346075F, 0F);
      sight23 = new ModelRenderer(this, 0, 0);
      sight23.addBox(0F, 0F, 0F, 2, 3, 2);
      sight23.setRotationPoint(-2F, -1F, -11F);
      sight23.setTextureSize(64, 32);
      sight23.mirror = true;
      setRotation(sight23, 0F, 0.8179294F, 0F);
      sight24 = new ModelRenderer(this, 0, 0);
      sight24.addBox(0F, 0F, 0F, 2, 3, 2);
      sight24.setRotationPoint(6F, -1F, -11F);
      sight24.setTextureSize(64, 32);
      sight24.mirror = true;
      setRotation(sight24, 0F, -2.41661F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    sight1.render(f5);
    sight2.render(f5);
    sight3.render(f5);
    sight4.render(f5);
    sight5.render(f5);
    sight6.render(f5);
    sight7.render(f5);
    sight77.render(f5);
    sight8.render(f5);
    sight9.render(f5);
    sight10.render(f5);
    sight11.render(f5);
    sight12.render(f5);
    sight13.render(f5);
    sight14.render(f5);
    sight15.render(f5);
    sight16.render(f5);
    sight17.render(f5);
    sight18.render(f5);
    sight19.render(f5);
    sight20.render(f5);
    sight21.render(f5);
    sight22.render(f5);
    sight23.render(f5);
    sight24.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
