// Date: 10/20/2017 11:16:54 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M2CarbineMag extends ModelBase
{
  //fields
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
    ModelRenderer mag5;
    ModelRenderer mag6;
    ModelRenderer mag7;
    ModelRenderer mag8;
    ModelRenderer mag9;
    ModelRenderer mag10;
    ModelRenderer mag11;
    ModelRenderer mag12;
    ModelRenderer mag13;
    ModelRenderer mag14;
    ModelRenderer mag15;
    ModelRenderer mag16;
    ModelRenderer mag17;
    ModelRenderer mag18;
    ModelRenderer mag19;
    ModelRenderer mag20;
    ModelRenderer mag21;
    ModelRenderer mag22;
    ModelRenderer mag23;
  
  public M2CarbineMag()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      mag1 = new ModelRenderer(this, 200, 0);
      mag1.addBox(0F, 0F, 0F, 2, 9, 1);
      mag1.setRotationPoint(1.5F, -12.65F, -2.3F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, -0.0743572F, 0F, 0F);
      mag2 = new ModelRenderer(this, 200, 0);
      mag2.addBox(0F, 0F, 0F, 3, 15, 2);
      mag2.setRotationPoint(1F, -13F, -7F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, 0F, 0F, 0F);
      mag3 = new ModelRenderer(this, 200, 0);
      mag3.addBox(0F, 0F, 0F, 3, 9, 1);
      mag3.setRotationPoint(1F, -12.6F, -1.5F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, -0.0743572F, 0F, 0F);
      mag4 = new ModelRenderer(this, 200, 0);
      mag4.addBox(0F, 0F, 0F, 3, 10, 1);
      mag4.setRotationPoint(1F, -13F, -7F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, -0.0743572F, 0F, 0F);
      mag5 = new ModelRenderer(this, 200, 0);
      mag5.addBox(0F, 0F, 0F, 3, 15, 1);
      mag5.setRotationPoint(1F, -5.5F, -7F);
      mag5.setTextureSize(64, 32);
      mag5.mirror = true;
      setRotation(mag5, -0.3346075F, 0F, 0F);
      mag6 = new ModelRenderer(this, 200, 0);
      mag6.addBox(0F, 0F, 0F, 3, 15, 1);
      mag6.setRotationPoint(1F, -3.95F, -2.1F);
      mag6.setTextureSize(64, 32);
      mag6.mirror = true;
      setRotation(mag6, -0.3346075F, 0F, 0F);
      mag7 = new ModelRenderer(this, 200, 0);
      mag7.addBox(0F, 0F, 0F, 2, 15, 1);
      mag7.setRotationPoint(1.5F, -4.2F, -2.9F);
      mag7.setTextureSize(64, 32);
      mag7.mirror = true;
      setRotation(mag7, -0.3346075F, 0F, 0F);
      mag8 = new ModelRenderer(this, 200, 0);
      mag8.addBox(0F, 0F, 0F, 3, 9, 1);
      mag8.setRotationPoint(1F, -12.7F, -3.2F);
      mag8.setTextureSize(64, 32);
      mag8.mirror = true;
      setRotation(mag8, -0.0743572F, 0F, 0F);
      mag9 = new ModelRenderer(this, 200, 0);
      mag9.addBox(0F, 0F, 0F, 3, 15, 1);
      mag9.setRotationPoint(1F, -4.5F, -3.7F);
      mag9.setTextureSize(64, 32);
      mag9.mirror = true;
      setRotation(mag9, -0.3346075F, 0F, 0F);
      mag10 = new ModelRenderer(this, 200, 0);
      mag10.addBox(0F, 0F, 0F, 3, 11, 1);
      mag10.setRotationPoint(1F, -13F, -4.5F);
      mag10.setTextureSize(64, 32);
      mag10.mirror = true;
      setRotation(mag10, 0F, 0F, 0F);
      mag11 = new ModelRenderer(this, 200, 0);
      mag11.addBox(0F, 0F, 0F, 3, 4, 1);
      mag11.setRotationPoint(1F, -12.7F, -3.7F);
      mag11.setTextureSize(64, 32);
      mag11.mirror = true;
      setRotation(mag11, -0.0743572F, 0F, 0F);
      mag12 = new ModelRenderer(this, 200, 0);
      mag12.addBox(0F, 0F, 0F, 3, 1, 1);
      mag12.setRotationPoint(1F, -1.7F, -5.2F);
      mag12.setTextureSize(64, 32);
      mag12.mirror = true;
      setRotation(mag12, 0F, 0F, 0F);
      mag13 = new ModelRenderer(this, 200, 0);
      mag13.addBox(0F, 0F, 0F, 3, 3, 1);
      mag13.setRotationPoint(1F, 2F, -7F);
      mag13.setTextureSize(64, 32);
      mag13.mirror = true;
      setRotation(mag13, 0F, 0F, 0F);
      mag14 = new ModelRenderer(this, 200, 0);
      mag14.addBox(0F, 0F, 0F, 3, 1, 1);
      mag14.setRotationPoint(1F, 2F, -6.5F);
      mag14.setTextureSize(64, 32);
      mag14.mirror = true;
      setRotation(mag14, 0F, 0F, 0F);
      mag15 = new ModelRenderer(this, 200, 0);
      mag15.addBox(0F, 0F, 0F, 3, 10, 1);
      mag15.setRotationPoint(1F, -1F, -8.5F);
      mag15.setTextureSize(64, 32);
      mag15.mirror = true;
      setRotation(mag15, 0F, 0F, 0F);
      mag16 = new ModelRenderer(this, 200, 0);
      mag16.addBox(0F, 0F, 0F, 3, 2, 1);
      mag16.setRotationPoint(1F, -3F, -7.5F);
      mag16.setTextureSize(64, 32);
      mag16.mirror = true;
      setRotation(mag16, 0F, 0F, 0F);
      mag17 = new ModelRenderer(this, 200, 0);
      mag17.addBox(0F, 0F, 0F, 3, 3, 3);
      mag17.setRotationPoint(1F, 6.1F, -10.1F);
      mag17.setTextureSize(64, 32);
      mag17.mirror = true;
      setRotation(mag17, -0.3346075F, 0F, 0F);
      mag18 = new ModelRenderer(this, 200, 0);
      mag18.addBox(0F, 0F, 0F, 3, 6, 1);
      mag18.setRotationPoint(1F, 0.5F, -8.5F);
      mag18.setTextureSize(64, 32);
      mag18.mirror = true;
      setRotation(mag18, -0.3346075F, 0F, 0F);
      mag19 = new ModelRenderer(this, 200, 0);
      mag19.addBox(0F, 0F, 0F, 3, 4, 1);
      mag19.setRotationPoint(1F, 2.5F, -8.7F);
      mag19.setTextureSize(64, 32);
      mag19.mirror = true;
      setRotation(mag19, -0.3346075F, 0F, 0F);
      mag20 = new ModelRenderer(this, 200, 0);
      mag20.addBox(0F, 0F, 0F, 3, 2, 1);
      mag20.setRotationPoint(1F, 4.8F, -8.7F);
      mag20.setTextureSize(64, 32);
      mag20.mirror = true;
      setRotation(mag20, -0.3346075F, 0F, 0F);
      mag21 = new ModelRenderer(this, 200, 0);
      mag21.addBox(0F, 0F, 0F, 3, 2, 1);
      mag21.setRotationPoint(1F, 4.5F, -7.8F);
      mag21.setTextureSize(64, 32);
      mag21.mirror = true;
      setRotation(mag21, 0F, 0F, 0F);
      mag22 = new ModelRenderer(this, 200, 0);
      mag22.addBox(0F, 0F, 0F, 2, 12, 1);
      mag22.setRotationPoint(1.5F, -13F, -5.3F);
      mag22.setTextureSize(64, 32);
      mag22.mirror = true;
      setRotation(mag22, 0F, 0F, 0F);
      mag23 = new ModelRenderer(this, 200, 0);
      mag23.addBox(0F, 0F, 0F, 2, 6, 1);
      mag23.setRotationPoint(1.5F, -1.5F, -7.8F);
      mag23.setTextureSize(64, 32);
      mag23.mirror = true;
      setRotation(mag23, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
    mag5.render(f5);
    mag6.render(f5);
    mag7.render(f5);
    mag8.render(f5);
    mag9.render(f5);
    mag10.render(f5);
    mag11.render(f5);
    mag12.render(f5);
    mag13.render(f5);
    mag14.render(f5);
    mag15.render(f5);
    mag16.render(f5);
    mag17.render(f5);
    mag18.render(f5);
    mag19.render(f5);
    mag20.render(f5);
    mag21.render(f5);
    mag22.render(f5);
    mag23.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
