// Date: 11/1/2017 5:12:49 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M3A1rearsight extends ModelBase
{
  //fields
    ModelRenderer sight1;
    ModelRenderer sight2;
    ModelRenderer sight3;
    ModelRenderer sight4;
    ModelRenderer sight5;
    ModelRenderer sight6;
    ModelRenderer sight7;
    ModelRenderer sight8;
    ModelRenderer sight9;
    ModelRenderer sight10;
    ModelRenderer sight11;
    ModelRenderer sight12;
    ModelRenderer sight13;
    ModelRenderer sight14;
    ModelRenderer sight15;
    ModelRenderer sight16;
    ModelRenderer sight17;
    ModelRenderer sight18;
    ModelRenderer sight19;
    ModelRenderer sight20;
    ModelRenderer sight21;
    ModelRenderer sight22;
    ModelRenderer sight23;
  
  public M3A1rearsight()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      sight1 = new ModelRenderer(this, 0, 0);
      sight1.addBox(0F, 0F, 0F, 1, 2, 5);
      sight1.setRotationPoint(-2F, -1F, 4F);
      sight1.setTextureSize(256, 128);
      sight1.mirror = true;
      setRotation(sight1, 0F, 0F, 0F);
      sight2 = new ModelRenderer(this, 0, 0);
      sight2.addBox(0F, 0F, 0F, 1, 2, 5);
      sight2.setRotationPoint(2F, -1F, 4F);
      sight2.setTextureSize(256, 128);
      sight2.mirror = true;
      setRotation(sight2, 0F, 0F, 0F);
      sight3 = new ModelRenderer(this, 0, 0);
      sight3.addBox(0F, 0F, 0F, 1, 5, 1);
      sight3.setRotationPoint(2F, -4F, 9F);
      sight3.setTextureSize(256, 128);
      sight3.mirror = true;
      setRotation(sight3, 0F, 0F, 0F);
      sight4 = new ModelRenderer(this, 0, 0);
      sight4.addBox(0F, 0F, 0F, 1, 5, 1);
      sight4.setRotationPoint(-2F, -4F, 9F);
      sight4.setTextureSize(256, 128);
      sight4.mirror = true;
      setRotation(sight4, 0F, 0F, 0F);
      sight5 = new ModelRenderer(this, 0, 0);
      sight5.addBox(0F, 0F, 0F, 2, 1, 1);
      sight5.setRotationPoint(-0.5F, -5.5F, 9F);
      sight5.setTextureSize(256, 128);
      sight5.mirror = true;
      setRotation(sight5, 0F, 0F, 0F);
      sight6 = new ModelRenderer(this, 0, 0);
      sight6.addBox(0F, 0F, 0F, 1, 1, 1);
      sight6.setRotationPoint(1.5F, -5.5F, 9F);
      sight6.setTextureSize(256, 128);
      sight6.mirror = true;
      setRotation(sight6, 0F, 0F, 0.4507907F);
      sight7 = new ModelRenderer(this, 0, 0);
      sight7.addBox(0F, 0F, 0F, 1, 1, 1);
      sight7.setRotationPoint(-0.5F, -5.5F, 9F);
      sight7.setTextureSize(256, 128);
      sight7.mirror = true;
      setRotation(sight7, 0F, 0F, 1.082827F);
      sight8 = new ModelRenderer(this, 0, 0);
      sight8.addBox(0F, 0F, 0F, 1, 1, 1);
      sight8.setRotationPoint(-2F, -4F, 9F);
      sight8.setTextureSize(256, 128);
      sight8.mirror = true;
      setRotation(sight8, 0F, 0F, -1.082827F);
      sight9 = new ModelRenderer(this, 0, 0);
      sight9.addBox(0F, 0F, 0F, 1, 1, 1);
      sight9.setRotationPoint(3F, -4F, 9F);
      sight9.setTextureSize(256, 128);
      sight9.mirror = true;
      setRotation(sight9, 0F, 0F, 2.727981F);
      sight10 = new ModelRenderer(this, 0, 0);
      sight10.addBox(0F, 0F, 0F, 2, 3, 1);
      sight10.setRotationPoint(-0.5F, -2F, 9F);
      sight10.setTextureSize(256, 128);
      sight10.mirror = true;
      setRotation(sight10, 0F, 0F, 0F);
      sight11 = new ModelRenderer(this, 0, 0);
      sight11.addBox(0F, 0F, 0F, 3, 1, 1);
      sight11.setRotationPoint(-1F, -5F, 9F);
      sight11.setTextureSize(256, 128);
      sight11.mirror = true;
      setRotation(sight11, 0F, 0F, 0F);
      sight12 = new ModelRenderer(this, 0, 0);
      sight12.addBox(0F, 0F, 0F, 1, 5, 1);
      sight12.setRotationPoint(-1.5F, -4F, 9F);
      sight12.setTextureSize(256, 128);
      sight12.mirror = true;
      setRotation(sight12, 0F, 0F, 0F);
      sight13 = new ModelRenderer(this, 0, 0);
      sight13.addBox(0F, 0F, 0F, 1, 5, 1);
      sight13.setRotationPoint(1.5F, -4F, 9F);
      sight13.setTextureSize(256, 128);
      sight13.mirror = true;
      setRotation(sight13, 0F, 0F, 0F);
      sight14 = new ModelRenderer(this, 0, 0);
      sight14.addBox(0F, 0F, 0F, 1, 1, 1);
      sight14.setRotationPoint(1F, -2F, 9F);
      sight14.setTextureSize(256, 128);
      sight14.mirror = true;
      setRotation(sight14, 0F, 0F, -0.7853982F);
      sight15 = new ModelRenderer(this, 0, 0);
      sight15.addBox(0F, 0F, 0F, 1, 1, 1);
      sight15.setRotationPoint(0F, -2F, 9F);
      sight15.setTextureSize(256, 128);
      sight15.mirror = true;
      setRotation(sight15, 0F, 0F, 2.356194F);
      sight16 = new ModelRenderer(this, 0, 0);
      sight16.addBox(0F, 0F, 0F, 1, 1, 1);
      sight16.setRotationPoint(0F, -4F, 9F);
      sight16.setTextureSize(256, 128);
      sight16.mirror = true;
      setRotation(sight16, 0F, 0F, 2.356194F);
      sight17 = new ModelRenderer(this, 0, 0);
      sight17.addBox(0F, 0F, 0F, 1, 1, 1);
      sight17.setRotationPoint(1F, -4F, 9F);
      sight17.setTextureSize(256, 128);
      sight17.mirror = true;
      setRotation(sight17, 0F, 0F, -0.7853982F);
      sight18 = new ModelRenderer(this, 0, 0);
      sight18.addBox(0F, 0F, 0F, 1, 2, 5);
      sight18.setRotationPoint(-2F, -1F, 4F);
      sight18.setTextureSize(256, 128);
      sight18.mirror = true;
      setRotation(sight18, 0.3346075F, 0F, 0F);
      sight19 = new ModelRenderer(this, 0, 0);
      sight19.addBox(0F, 0F, 0F, 1, 2, 5);
      sight19.setRotationPoint(2F, -1F, 4F);
      sight19.setTextureSize(256, 128);
      sight19.mirror = true;
      setRotation(sight19, 0.3346075F, 0F, 0F);
      sight20 = new ModelRenderer(this, 0, 0);
      sight20.addBox(0F, 0F, 0F, 1, 2, 1);
      sight20.setRotationPoint(2F, -4F, 9F);
      sight20.setTextureSize(256, 128);
      sight20.mirror = true;
      setRotation(sight20, -0.5205006F, 0F, 0F);
      sight21 = new ModelRenderer(this, 0, 0);
      sight21.addBox(0F, 0F, 0F, 1, 2, 1);
      sight21.setRotationPoint(-2F, -4F, 9F);
      sight21.setTextureSize(256, 128);
      sight21.mirror = true;
      setRotation(sight21, -0.5205006F, 0F, 0F);
      sight22 = new ModelRenderer(this, 0, 0);
      sight22.addBox(0F, 0F, 0F, 1, 1, 1);
      sight22.setRotationPoint(2F, -2.5F, 8.5F);
      sight22.setTextureSize(256, 128);
      sight22.mirror = true;
      setRotation(sight22, 0F, 0F, 0F);
      sight23 = new ModelRenderer(this, 0, 0);
      sight23.addBox(0F, 0F, 0F, 1, 1, 1);
      sight23.setRotationPoint(-2F, -2.5F, 8.5F);
      sight23.setTextureSize(256, 128);
      sight23.mirror = true;
      setRotation(sight23, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    sight1.render(f5);
    sight2.render(f5);
    sight3.render(f5);
    sight4.render(f5);
    sight5.render(f5);
    sight6.render(f5);
    sight7.render(f5);
    sight8.render(f5);
    sight9.render(f5);
    sight10.render(f5);
    sight11.render(f5);
    sight12.render(f5);
    sight13.render(f5);
    sight14.render(f5);
    sight15.render(f5);
    sight16.render(f5);
    sight17.render(f5);
    sight18.render(f5);
    sight19.render(f5);
    sight20.render(f5);
    sight21.render(f5);
    sight22.render(f5);
    sight23.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
