// Date: 6/24/2019 10:33:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M4Grip extends ModelBase
{
  //fields
    ModelRenderer grip1;
    ModelRenderer grip2;
    ModelRenderer grip3;
    ModelRenderer grip4;
    ModelRenderer grip5;
    ModelRenderer grip6;
    ModelRenderer grip7;
    ModelRenderer grip8;
    ModelRenderer grip9;
    ModelRenderer grip10;
    ModelRenderer grip11;
    ModelRenderer grip12;
  
  public M4Grip()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      grip1 = new ModelRenderer(this, 0, 0);
      grip1.addBox(0F, 0F, 0F, 4, 5, 5);
      grip1.setRotationPoint(-3.5F, -7F, -6F);
      grip1.setTextureSize(256, 128);
      grip1.mirror = true;
      setRotation(grip1, 0F, 0F, 0F);
      grip2 = new ModelRenderer(this, 0, 0);
      grip2.addBox(0F, -0.5F, 0F, 4, 11, 4);
      grip2.setRotationPoint(-3.5F, -2F, -5.5F);
      grip2.setTextureSize(256, 128);
      grip2.mirror = true;
      setRotation(grip2, 0.3717861F, 0F, 0F);
      grip3 = new ModelRenderer(this, 0, 0);
      grip3.addBox(0F, 0F, 0F, 4, 3, 12);
      grip3.setRotationPoint(-3.5F, -5F, -1F);
      grip3.setTextureSize(256, 128);
      grip3.mirror = true;
      setRotation(grip3, -1.07818F, 0F, 0F);
      grip4 = new ModelRenderer(this, 0, 0);
      grip4.addBox(0F, 0F, 0F, 4, 1, 7);
      grip4.setRotationPoint(-3.5F, 7.2F, -2.6F);
      grip4.setTextureSize(256, 128);
      grip4.mirror = true;
      setRotation(grip4, 0.2230717F, 0F, 0F);
      grip5 = new ModelRenderer(this, 0, 0);
      grip5.addBox(0F, 0F, 0F, 4, 1, 1);
      grip5.setRotationPoint(-3.5F, 7.2F, -2.6F);
      grip5.setTextureSize(256, 128);
      grip5.mirror = true;
      setRotation(grip5, 1.07818F, 0F, 0F);
      grip6 = new ModelRenderer(this, 0, 0);
      grip6.addBox(0F, 0F, 0F, 3, 5, 1);
      grip6.setRotationPoint(-3F, -7F, -1F);
      grip6.setTextureSize(256, 128);
      grip6.mirror = true;
      setRotation(grip6, 0F, 0F, 0F);
      grip7 = new ModelRenderer(this, 0, 0);
      grip7.addBox(0F, -1F, 0F, 3, 1, 12);
      grip7.setRotationPoint(-3F, -5F, -1F);
      grip7.setTextureSize(256, 128);
      grip7.mirror = true;
      setRotation(grip7, -1.07818F, 0F, 0F);
      grip8 = new ModelRenderer(this, 0, 0);
      grip8.addBox(0F, 0F, 6.5F, 4, 1, 1);
      grip8.setRotationPoint(-3.5F, 7.2F, -2.6F);
      grip8.setTextureSize(256, 128);
      grip8.mirror = true;
      setRotation(grip8, 0.2230717F, 0F, 0F);
      grip9 = new ModelRenderer(this, 0, 0);
      grip9.addBox(0F, 0F, 7.5F, 3, 1, 1);
      grip9.setRotationPoint(-3F, 7.2F, -2.6F);
      grip9.setTextureSize(256, 128);
      grip9.mirror = true;
      setRotation(grip9, 0.2230717F, 0F, 0F);
      grip10 = new ModelRenderer(this, 0, 0);
      grip10.addBox(0F, -0.3F, 7.5F, 3, 1, 1);
      grip10.setRotationPoint(-3F, 7.2F, -2.6F);
      grip10.setTextureSize(256, 128);
      grip10.mirror = true;
      setRotation(grip10, 0.2230717F, 0F, 0F);
      grip11 = new ModelRenderer(this, 0, 15);
      grip11.addBox(0F, 0.5F, 1F, 1, 9, 4);
      grip11.setRotationPoint(-0.4F, -2F, -5.5F);
      grip11.setTextureSize(256, 128);
      grip11.mirror = true;
      setRotation(grip11, 0.3717861F, 0F, 0F);
      grip12 = new ModelRenderer(this, 0, 15);
      grip12.addBox(0F, 0.5F, 1F, 1, 9, 4);
      grip12.setRotationPoint(-3.6F, -2F, -5.5F);
      grip12.setTextureSize(256, 128);
      grip12.mirror = true;
      setRotation(grip12, 0.3717861F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    grip1.render(f5);
    grip2.render(f5);
    grip3.render(f5);
    grip4.render(f5);
    grip5.render(f5);
    grip6.render(f5);
    grip7.render(f5);
    grip8.render(f5);
    grip9.render(f5);
    grip10.render(f5);
    grip11.render(f5);
    grip12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
