// Date: 2/24/2018 7:06:01 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M6Gmag extends ModelBase
{
  //fields
    
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
    ModelRenderer mag5;
    ModelRenderer mag6;
  
  public M6Gmag()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      mag1 = new ModelRenderer(this, 0, 0);
      mag1.addBox(0F, 0F, 0F, 4, 1, 9);
      mag1.setRotationPoint(-3.5F, 12F, -5.6F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, 0.1858931F, 0F, 0F);
      mag2 = new ModelRenderer(this, 0, 0);
      mag2.addBox(0F, 0F, 0F, 4, 2, 5);
      mag2.setRotationPoint(-3.5F, 12F, -5.6F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, -0.0743572F, 0F, 0F);
      mag3 = new ModelRenderer(this, 0, 0);
      mag3.addBox(0F, 0F, 0F, 4, 1, 9);
      mag3.setRotationPoint(-3.5F, 12.5F, -5.5F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, 0.1858931F, 0F, 0F);
      mag4 = new ModelRenderer(this, 0, 0);
      mag4.addBox(0F, 0F, 0F, 4, 1, 5);
      mag4.setRotationPoint(-3.5F, 11.8F, 3.6F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, -2.617994F, 0F, 0F);
      mag5 = new ModelRenderer(this, 0, 0);
      mag5.addBox(0F, 0F, 0F, 4, 1, 3);
      mag5.setRotationPoint(-3.5F, 12F, 1.6F);
      mag5.setTextureSize(64, 32);
      mag5.mirror = true;
      setRotation(mag5, -2.617994F, 0F, 0F);
      mag6 = new ModelRenderer(this, 0, 0);
      mag6.addBox(0F, 0F, 0F, 3, 15, 6);
      mag6.setRotationPoint(-3F, -3F, -6.6F);
      mag6.setTextureSize(64, 32);
      mag6.mirror = true;
      setRotation(mag6, 0.1858931F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
    mag5.render(f5);
    mag6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
