// Date: 2/24/2018 7:06:01 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M6Gscope extends ModelBase
{
  //fields
    
    ModelRenderer scope1;
    ModelRenderer scope2;
    ModelRenderer scope3;
    ModelRenderer scope4;
    ModelRenderer scope5;
    ModelRenderer scope6;
    ModelRenderer scope7;
    ModelRenderer scope8;
    ModelRenderer scope9;
    ModelRenderer scope10;
    ModelRenderer scope11;
    ModelRenderer scope12;
    ModelRenderer scope13;
    ModelRenderer scope14;
    ModelRenderer scope15;
    ModelRenderer scope16;
    ModelRenderer scope17;
    ModelRenderer scope18;
    ModelRenderer scope19;
    ModelRenderer scope20;
    ModelRenderer scope21;
    ModelRenderer scope22;
    ModelRenderer scope23;
    ModelRenderer scope24;
    ModelRenderer scope25;
    ModelRenderer scope26;
    ModelRenderer scope27;
    ModelRenderer scope28;
    ModelRenderer scope29;
    ModelRenderer scope30;
    ModelRenderer scope31;
    
  public M6Gscope()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      scope1 = new ModelRenderer(this, 100, 0);
      scope1.addBox(0F, 0F, 0F, 3, 3, 13);
      scope1.setRotationPoint(-3F, -13.1F, -27F);
      scope1.setTextureSize(64, 32);
      scope1.mirror = true;
      setRotation(scope1, 0F, 0F, 0F);
      scope2 = new ModelRenderer(this, 100, 0);
      scope2.addBox(0F, 0F, 0F, 1, 4, 3);
      scope2.setRotationPoint(-4.2F, -11.5F, -17F);
      scope2.setTextureSize(64, 32);
      scope2.mirror = true;
      setRotation(scope2, 0F, 0F, 0F);
      scope3 = new ModelRenderer(this, 100, 0);
      scope3.addBox(0F, 0F, 0F, 3, 2, 6);
      scope3.setRotationPoint(-3F, -13.1F, -14F);
      scope3.setTextureSize(64, 32);
      scope3.mirror = true;
      setRotation(scope3, -0.5205006F, 0F, 0F);
      scope4 = new ModelRenderer(this, 100, 0);
      scope4.addBox(0F, 0F, 0F, 2, 5, 8);
      scope4.setRotationPoint(-4.2F, -11.5F, -27F);
      scope4.setTextureSize(64, 32);
      scope4.mirror = true;
      setRotation(scope4, 0F, 0F, 0F);
      scope5 = new ModelRenderer(this, 100, 0);
      scope5.addBox(0F, 0F, 0F, 2, 5, 8);
      scope5.setRotationPoint(-0.8F, -11.5F, -27F);
      scope5.setTextureSize(64, 32);
      scope5.mirror = true;
      setRotation(scope5, 0F, 0F, 0F);
      scope6 = new ModelRenderer(this, 100, 0);
      scope6.addBox(0F, 0F, 0F, 1, 1, 2);
      scope6.setRotationPoint(-4.2F, -7.5F, -17F);
      scope6.setTextureSize(64, 32);
      scope6.mirror = true;
      setRotation(scope6, 0F, 0F, 0F);
      scope7 = new ModelRenderer(this, 100, 0);
      scope7.addBox(0F, 0F, 0F, 2, 4, 3);
      scope7.setRotationPoint(-0.8F, -11.5F, -17F);
      scope7.setTextureSize(64, 32);
      scope7.mirror = true;
      setRotation(scope7, 0F, 0F, 0F);
      scope8 = new ModelRenderer(this, 100, 0);
      scope8.addBox(0F, 0F, 0F, 1, 2, 4);
      scope8.setRotationPoint(-4.2F, -9F, -14F);
      scope8.setTextureSize(64, 32);
      scope8.mirror = true;
      setRotation(scope8, 0F, 0.1115358F, 0F);
      scope9 = new ModelRenderer(this, 100, 0);
      scope9.addBox(0F, 0F, 0F, 1, 1, 4);
      scope9.setRotationPoint(-4.2F, -9.5F, -14F);
      scope9.setTextureSize(64, 32);
      scope9.mirror = true;
      setRotation(scope9, 0F, 0.1115358F, 0F);
      scope10 = new ModelRenderer(this, 100, 0);
      scope10.addBox(0F, 0F, 0F, 1, 4, 2);
      scope10.setRotationPoint(-3.7F, -9.5F, -10F);
      scope10.setTextureSize(64, 32);
      scope10.mirror = true;
      setRotation(scope10, -2.082002F, 0F, 0F);
      scope11 = new ModelRenderer(this, 100, 0);
      scope11.addBox(0F, 0F, 0F, 1, 1, 1);
      scope11.setRotationPoint(-4.2F, -8F, -15F);
      scope11.setTextureSize(64, 32);
      scope11.mirror = true;
      setRotation(scope11, 0F, 0F, 0F);
      scope12 = new ModelRenderer(this, 100, 0);
      scope12.addBox(0F, 0F, 0F, 1, 1, 1);
      scope12.setRotationPoint(-3.7F, -11.5F, -14.5F);
      scope12.setTextureSize(64, 32);
      scope12.mirror = true;
      setRotation(scope12, 0F, 0F, 0F);
      scope13 = new ModelRenderer(this, 100, 0);
      scope13.addBox(0F, 0F, 0F, 2, 1, 2);
      scope13.setRotationPoint(-0.8F, -7.5F, -17F);
      scope13.setTextureSize(64, 32);
      scope13.mirror = true;
      setRotation(scope13, 0F, 0F, 0F);
      scope14 = new ModelRenderer(this, 100, 0);
      scope14.addBox(0F, 0F, 0F, 2, 1, 1);
      scope14.setRotationPoint(-0.8F, -8F, -15F);
      scope14.setTextureSize(64, 32);
      scope14.mirror = true;
      setRotation(scope14, 0F, 0F, 0F);
      scope15 = new ModelRenderer(this, 100, 0);
      scope15.addBox(0F, 0F, 0F, 4, 2, 1);
      scope15.setRotationPoint(1.2F, -9F, -14F);
      scope15.setTextureSize(64, 32);
      scope15.mirror = true;
      setRotation(scope15, 0F, -1.710216F, 0F);
      scope16 = new ModelRenderer(this, 100, 0);
      scope16.addBox(0F, 0F, 0F, 4, 1, 1);
      scope16.setRotationPoint(1.2F, -9.5F, -14F);
      scope16.setTextureSize(64, 32);
      scope16.mirror = true;
      setRotation(scope16, 0F, -1.710216F, 0F);
      scope17 = new ModelRenderer(this, 100, 0);
      scope17.addBox(0F, 0F, 0F, 1, 4, 2);
      scope17.setRotationPoint(-0.35F, -9.5F, -10F);
      scope17.setTextureSize(64, 32);
      scope17.mirror = true;
      setRotation(scope17, -2.082002F, 0F, 0F);
      scope18 = new ModelRenderer(this, 100, 0);
      scope18.addBox(0F, 0F, 0F, 1, 1, 1);
      scope18.setRotationPoint(-0.35F, -11.5F, -14.5F);
      scope18.setTextureSize(64, 32);
      scope18.mirror = true;
      setRotation(scope18, 0F, 0F, 0F);
      scope19 = new ModelRenderer(this, 100, 0);
      scope19.addBox(0F, 0F, 0F, 2, 1, 13);
      scope19.setRotationPoint(-4.2F, -11.5F, -27F);
      scope19.setTextureSize(64, 32);
      scope19.mirror = true;
      setRotation(scope19, 0F, 0F, -0.9294653F);
      scope20 = new ModelRenderer(this, 100, 50);
      scope20.addBox(0F, 0F, 0F, 1, 5, 2);
      scope20.setRotationPoint(-4.2F, -11.5F, -19F);
      scope20.setTextureSize(64, 32);
      scope20.mirror = true;
      setRotation(scope20, 0F, 0F, 0F);
      scope21 = new ModelRenderer(this, 100, 50);
      scope21.addBox(0F, 0F, 0F, 1, 5, 2);
      scope21.setRotationPoint(0.2F, -11.5F, -19F);
      scope21.setTextureSize(64, 32);
      scope21.mirror = true;
      setRotation(scope21, 0F, 0F, 0F);
      scope22 = new ModelRenderer(this, 100, 0);
      scope22.addBox(0F, 0F, 0F, 1, 2, 13);
      scope22.setRotationPoint(1.2F, -11.5F, -27F);
      scope22.setTextureSize(64, 32);
      scope22.mirror = true;
      setRotation(scope22, 0F, 0F, 2.513274F);
      scope23 = new ModelRenderer(this, 100, 0);
      scope23.addBox(0F, 0F, 0F, 3, 1, 1);
      scope23.setRotationPoint(1.2F, -10F, -14F);
      scope23.setTextureSize(64, 32);
      scope23.mirror = true;
      setRotation(scope23, 0F, -1.710216F, 0F);
      scope24 = new ModelRenderer(this, 100, 0);
      scope24.addBox(0F, 0F, 0F, 2, 1, 1);
      scope24.setRotationPoint(1.2F, -10.5F, -14F);
      scope24.setTextureSize(64, 32);
      scope24.mirror = true;
      setRotation(scope24, 0F, -1.710216F, 0F);
      scope25 = new ModelRenderer(this, 100, 0);
      scope25.addBox(0F, 0F, 0F, 1, 1, 1);
      scope25.setRotationPoint(1.2F, -11F, -14F);
      scope25.setTextureSize(64, 32);
      scope25.mirror = true;
      setRotation(scope25, 0F, -1.710216F, 0F);
      scope26 = new ModelRenderer(this, 100, 0);
      scope26.addBox(0F, 0F, 0F, 1, 1, 3);
      scope26.setRotationPoint(-4.2F, -10F, -14F);
      scope26.setTextureSize(64, 32);
      scope26.mirror = true;
      setRotation(scope26, 0F, 0.1115358F, 0F);
      scope27 = new ModelRenderer(this, 100, 0);
      scope27.addBox(0F, 0F, 0F, 1, 1, 2);
      scope27.setRotationPoint(-4.2F, -10.5F, -14F);
      scope27.setTextureSize(64, 32);
      scope27.mirror = true;
      setRotation(scope27, 0F, 0.1115358F, 0F);
      scope28 = new ModelRenderer(this, 100, 0);
      scope28.addBox(0F, 0F, 0F, 1, 1, 1);
      scope28.setRotationPoint(-4.2F, -11F, -14F);
      scope28.setTextureSize(64, 32);
      scope28.mirror = true;
      setRotation(scope28, 0F, 0.1115358F, 0F);
      scope29 = new ModelRenderer(this, 0, 0);
      scope29.addBox(0F, 0F, 0F, 1, 1, 2);
      scope29.setRotationPoint(-2F, -10.8F, -10F);
      scope29.setTextureSize(64, 32);
      scope29.mirror = true;
      setRotation(scope29, 0F, 0F, 0F);
      scope30 = new ModelRenderer(this, 0, 0);
      scope30.addBox(0F, 0F, 0F, 1, 3, 1);
      scope30.setRotationPoint(-2F, -10.8F, -8F);
      scope30.setTextureSize(64, 32);
      scope30.mirror = true;
      setRotation(scope30, -1.858931F, 0F, 0F);
      scope31 = new ModelRenderer(this, 0, 0);
      scope31.addBox(0F, 0F, 0F, 1, 1, 1);
      scope31.setRotationPoint(-2F, -12.1F, -28F);
      scope31.setTextureSize(64, 32);
      scope31.mirror = true;
      setRotation(scope31, 0F, 0F, 0F);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    scope1.render(f5);
    scope2.render(f5);
    scope3.render(f5);
    scope4.render(f5);
    scope5.render(f5);
    scope6.render(f5);
    scope7.render(f5);
    scope8.render(f5);
    scope9.render(f5);
    scope10.render(f5);
    scope11.render(f5);
    scope12.render(f5);
    scope13.render(f5);
    scope14.render(f5);
    scope15.render(f5);
    scope16.render(f5);
    scope17.render(f5);
    scope18.render(f5);
    scope19.render(f5);
    scope20.render(f5);
    scope21.render(f5);
    scope22.render(f5);
    scope23.render(f5);
    scope24.render(f5);
    scope25.render(f5);
    scope26.render(f5);
    scope27.render(f5);
    scope28.render(f5);
    scope29.render(f5);
    scope30.render(f5);
    scope31.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
 
}
