// Date: 1/7/2017 11:54:28 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M9Top extends ModelBase
{
  //fields
    ModelRenderer gun11;
    ModelRenderer gun32;
    ModelRenderer gun37;
    ModelRenderer gun49;
    ModelRenderer gun50;
    ModelRenderer gun51;
    ModelRenderer gun52;
    ModelRenderer gun53;
    ModelRenderer gun54;
    ModelRenderer gun55;
    ModelRenderer gun66;
    ModelRenderer gun69;
    ModelRenderer gun71;
    ModelRenderer gun72;
    ModelRenderer gun73;
    ModelRenderer gun74;
    ModelRenderer gun75;
    ModelRenderer gun76;
    ModelRenderer gun77;
    ModelRenderer gun78;
    ModelRenderer gun79;
    ModelRenderer gun80;
    ModelRenderer gun81;
    ModelRenderer gun99;
    ModelRenderer gun120;
    ModelRenderer gun121;
    ModelRenderer gun122;
    ModelRenderer gun123;
    ModelRenderer gun124;
    ModelRenderer gun126;
    ModelRenderer gun127;
  
  public M9Top()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      gun11 = new ModelRenderer(this, 100, 0);
      gun11.addBox(0F, 0F, 0F, 2, 3, 11);
      gun11.setRotationPoint(-2.8F, -14F, -10.5F);
      gun11.setTextureSize(64, 32);
      gun11.mirror = true;
      setRotation(gun11, 0F, 0F, 0F);
      
      gun32 = new ModelRenderer(this, 100, 0);
      gun32.addBox(0F, 0F, 0F, 4, 3, 24);
      gun32.setRotationPoint(-3.7F, -12F, -23.5F);
      gun32.setTextureSize(64, 32);
      gun32.mirror = true;
      setRotation(gun32, 0F, 0F, 0F);
      gun37 = new ModelRenderer(this, 100, 0);
      gun37.addBox(0F, 0F, 0F, 2, 4, 4);
      gun37.setRotationPoint(-2.8F, -14F, -26.5F);
      gun37.setTextureSize(64, 32);
      gun37.mirror = true;
      setRotation(gun37, 0F, 0F, 0F);
      
      gun49 = new ModelRenderer(this, 100, 0);
      gun49.addBox(0F, 0F, 0F, 6, 3, 20);
      gun49.setRotationPoint(-4.5F, -12F, -23.5F);
      gun49.setTextureSize(64, 32);
      gun49.mirror = true;
      setRotation(gun49, 0F, 0F, 0F);
      gun50 = new ModelRenderer(this, 100, 0);
      gun50.addBox(0F, 0F, 0F, 1, 1, 11);
      gun50.setRotationPoint(-2.8F, -14F, -10.5F);
      gun50.setTextureSize(64, 32);
      gun50.mirror = true;
      setRotation(gun50, 0F, 0F, 0.6320364F);
      gun51 = new ModelRenderer(this, 100, 0);
      gun51.addBox(0F, 0F, 0F, 1, 1, 11);
      gun51.setRotationPoint(-0.2F, -14F, -10.5F);
      gun51.setTextureSize(64, 32);
      gun51.mirror = true;
      setRotation(gun51, 0F, 0F, 0.8551081F);
      gun52 = new ModelRenderer(this, 100, 0);
      gun52.addBox(0F, 0F, 0F, 1, 1, 11);
      gun52.setRotationPoint(0.7F, -12F, -10.5F);
      gun52.setTextureSize(64, 32);
      gun52.mirror = true;
      setRotation(gun52, 0F, 0F, 3.011467F);
      gun53 = new ModelRenderer(this, 100, 0);
      gun53.addBox(0F, 0F, 0F, 1, 1, 11);
      gun53.setRotationPoint(-3.7F, -12F, -10.5F);
      gun53.setTextureSize(64, 32);
      gun53.mirror = true;
      setRotation(gun53, 0F, 0F, -1.375609F);
      gun54 = new ModelRenderer(this, 100, 0);
      gun54.addBox(0F, 0F, 0F, 1, 1, 11);
      gun54.setRotationPoint(0.6F, -12.2F, -10.5F);
      gun54.setTextureSize(64, 32);
      gun54.mirror = true;
      setRotation(gun54, 0F, 0F, 3.011467F);
      gun55 = new ModelRenderer(this, 100, 0);
      gun55.addBox(0F, 0F, 0F, 1, 1, 11);
      gun55.setRotationPoint(-3.6F, -12.2F, -10.5F);
      gun55.setTextureSize(64, 32);
      gun55.mirror = true;
      setRotation(gun55, 0F, 0F, -1.375609F);
      
      gun66 = new ModelRenderer(this, 100, 0);
      gun66.addBox(0F, 0F, 0F, 1, 1, 4);
      gun66.setRotationPoint(-0.2F, -14F, -26.5F);
      gun66.setTextureSize(64, 32);
      gun66.mirror = true;
      setRotation(gun66, 0F, 0F, 1.07818F);
      gun69 = new ModelRenderer(this, 100, 0);
      gun69.addBox(0F, 0F, 0F, 1, 1, 4);
      gun69.setRotationPoint(-2.8F, -14F, -26.5F);
      gun69.setTextureSize(64, 32);
      gun69.mirror = true;
      setRotation(gun69, 0F, 0F, 0.5205006F);
      gun71 = new ModelRenderer(this, 100, 0);
      gun71.addBox(0F, 0F, 0F, 3, 3, 2);
      gun71.setRotationPoint(-3.5F, -12F, -26.5F);
      gun71.setTextureSize(64, 32);
      gun71.mirror = true;
      setRotation(gun71, 0F, 0F, 0F);
      gun72 = new ModelRenderer(this, 100, 0);
      gun72.addBox(0F, 0F, 0F, 1, 3, 2);
      gun72.setRotationPoint(-0.5F, -12F, -26.5F);
      gun72.setTextureSize(64, 32);
      gun72.mirror = true;
      setRotation(gun72, 0F, 0F, 0F);
      gun73 = new ModelRenderer(this, 100, 0);
      gun73.addBox(0F, 0F, 0F, 1, 1, 4);
      gun73.setRotationPoint(0.5F, -12F, -26.5F);
      gun73.setTextureSize(64, 32);
      gun73.mirror = true;
      setRotation(gun73, 0F, 0F, 2.974289F);
      gun74 = new ModelRenderer(this, 100, 0);
      gun74.addBox(0F, 0F, 0F, 1, 1, 4);
      gun74.setRotationPoint(-3.5F, -12F, -26.5F);
      gun74.setTextureSize(64, 32);
      gun74.mirror = true;
      setRotation(gun74, 0F, 0F, -1.412787F);
      gun75 = new ModelRenderer(this, 100, 0);
      gun75.addBox(0F, 0F, 0F, 1, 1, 4);
      gun75.setRotationPoint(-3.5F, -12.2F, -26.5F);
      gun75.setTextureSize(64, 32);
      gun75.mirror = true;
      setRotation(gun75, 0F, 0F, -1.412787F);
      gun76 = new ModelRenderer(this, 100, 0);
      gun76.addBox(0F, 0F, 0F, 1, 1, 4);
      gun76.setRotationPoint(0.5F, -12.2F, -26.5F);
      gun76.setTextureSize(64, 32);
      gun76.mirror = true;
      setRotation(gun76, 0F, 0F, 2.974289F);
      gun77 = new ModelRenderer(this, 100, 0);
      gun77.addBox(0F, 0F, 0F, 1, 3, 3);
      gun77.setRotationPoint(1.5F, -12F, -23.5F);
      gun77.setTextureSize(64, 32);
      gun77.mirror = true;
      setRotation(gun77, 0F, -2.639681F, 0F);
      gun78 = new ModelRenderer(this, 100, 0);
      gun78.addBox(0F, 0F, 0F, 2, 3, 1);
      gun78.setRotationPoint(-4.5F, -12F, -23.5F);
      gun78.setTextureSize(64, 32);
      gun78.mirror = true;
      setRotation(gun78, 0F, 1.003822F, 0F);
      gun79 = new ModelRenderer(this, 100, 0);
      gun79.addBox(0F, 0F, 0F, 1, 2, 3);
      gun79.setRotationPoint(-2.8F, -14F, 0.5F);
      gun79.setTextureSize(64, 32);
      gun79.mirror = true;
      setRotation(gun79, -0.8551081F, 0F, 0F);
      gun80 = new ModelRenderer(this, 100, 0);
      gun80.addBox(0F, 0F, 0F, 2, 3, 1);
      gun80.setRotationPoint(0.7F, -12F, 0.5F);
      gun80.setTextureSize(64, 32);
      gun80.mirror = true;
      setRotation(gun80, 0F, -2.007645F, 0F);
      gun81 = new ModelRenderer(this, 100, 0);
      gun81.addBox(0F, 0F, 0F, 1, 3, 2);
      gun81.setRotationPoint(-3.7F, -12F, 0.5F);
      gun81.setTextureSize(64, 32);
      gun81.mirror = true;
      setRotation(gun81, 0F, 0.4461433F, 0F);
      gun99 = new ModelRenderer(this, 100, 0);
      gun99.addBox(0F, 0F, 0F, 1, 3, 10);
      gun99.setRotationPoint(-0.2F, -12F, -8.5F);
      gun99.setTextureSize(64, 32);
      gun99.mirror = true;
      setRotation(gun99, 0F, 0F, 0F);
      
      gun120 = new ModelRenderer(this, 100, 0);
      gun120.addBox(0F, 0F, 0F, 2, 1, 20);
      gun120.setRotationPoint(-4.5F, -12F, -23.5F);
      gun120.setTextureSize(64, 32);
      gun120.mirror = true;
      setRotation(gun120, 0F, 0F, -0.3346075F);
      gun121 = new ModelRenderer(this, 100, 0);
      gun121.addBox(0F, 0F, 0F, 1, 2, 20);
      gun121.setRotationPoint(1.5F, -12F, -23.5F);
      gun121.setTextureSize(64, 32);
      gun121.mirror = true;
      setRotation(gun121, 0F, 0F, 1.933288F);
      gun122 = new ModelRenderer(this, 100, 0);
      gun122.addBox(0F, 0F, 0F, 1, 3, 11);
      gun122.setRotationPoint(-1.2F, -14F, -10.5F);
      gun122.setTextureSize(64, 32);
      gun122.mirror = true;
      setRotation(gun122, 0F, 0F, 0F);
      gun123 = new ModelRenderer(this, 100, 0);
      gun123.addBox(0F, 0F, 0F, 1, 4, 4);
      gun123.setRotationPoint(-1.2F, -14F, -26.5F);
      gun123.setTextureSize(64, 32);
      gun123.mirror = true;
      setRotation(gun123, 0F, 0F, 0F);
      gun124 = new ModelRenderer(this, 100, 0);
      gun124.addBox(0F, 0F, 0F, 1, 2, 3);
      gun124.setRotationPoint(-1.2F, -14F, 0.5F);
      gun124.setTextureSize(64, 32);
      gun124.mirror = true;
      setRotation(gun124, -0.8551081F, 0F, 0F);
      gun126 = new ModelRenderer(this, 100, 0);
      gun126.addBox(0F, 0F, 0F, 1, 1, 9);
      gun126.setRotationPoint(0.55F, -11.9F, -22.5F);
      gun126.setTextureSize(64, 32);
      gun126.mirror = true;
      setRotation(gun126, 0F, 0F, 2.974289F);
      gun127 = new ModelRenderer(this, 100, 0);
      gun127.addBox(0F, 0F, 0F, 1, 1, 9);
      gun127.setRotationPoint(-3.55F, -11.9F, -22.5F);
      gun127.setTextureSize(64, 32);
      gun127.mirror = true;
      setRotation(gun127, 0F, 0F, -1.412787F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun11.render(f5);
    gun32.render(f5);
    gun37.render(f5);
    
    gun49.render(f5);
    gun50.render(f5);
    gun51.render(f5);
    gun52.render(f5);
    gun53.render(f5);
    gun54.render(f5);
    gun55.render(f5);
    
    gun66.render(f5);
    gun69.render(f5);
    gun71.render(f5);
    gun72.render(f5);
    gun73.render(f5);
    gun74.render(f5);
    gun75.render(f5);
    gun76.render(f5);
    gun77.render(f5);
    gun78.render(f5);
    gun79.render(f5);
    gun80.render(f5);
    gun81.render(f5);
    gun99.render(f5);
    
    gun120.render(f5);
    gun121.render(f5);
    gun122.render(f5);
    gun123.render(f5);
    gun124.render(f5);
    gun126.render(f5);
    gun127.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
