// Date: 3/11/2018 6:19:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MA5Dcover extends ModelBase
{
  //fields
    ModelRenderer cover1;
    ModelRenderer cover2;
    ModelRenderer cover3;
    ModelRenderer cover4;
    ModelRenderer cover5;
    ModelRenderer cover6;
    ModelRenderer cover7;
    ModelRenderer cover8;
    ModelRenderer cover9;
    ModelRenderer cover10;
    ModelRenderer cover11;
    ModelRenderer cover12;
    ModelRenderer cover13;
    ModelRenderer cover14;
    ModelRenderer cover15;
    ModelRenderer cover16;
    ModelRenderer cover17;
    ModelRenderer cover18;
    ModelRenderer cover19;
    ModelRenderer cover20;
    ModelRenderer cover21;
    ModelRenderer cover22;
    ModelRenderer cover23;
    ModelRenderer cover24;
    ModelRenderer cover25;
    ModelRenderer cover26;
    ModelRenderer cover27;
    ModelRenderer cover28;
    ModelRenderer cover29;
    ModelRenderer cover30;
    ModelRenderer cover31;
    ModelRenderer cover32;
    ModelRenderer gun204;
    ModelRenderer gun207;
  
  public MA5Dcover()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      cover1 = new ModelRenderer(this, 150, 0);
      cover1.addBox(0F, 0F, 0F, 2, 12, 1);
      cover1.setRotationPoint(-2.5F, -23.1F, -26.5F);
      cover1.setTextureSize(64, 32);
      cover1.mirror = true;
      setRotation(cover1, -1.553343F, 0F, 0F);
      cover2 = new ModelRenderer(this, 150, 0);
      cover2.addBox(0F, 0F, 0F, 1, 1, 12);
      cover2.setRotationPoint(-0.5F, -22.5F, -38.5F);
      cover2.setTextureSize(64, 32);
      cover2.mirror = true;
      setRotation(cover2, 0F, 0F, 0.7853982F);
      cover3 = new ModelRenderer(this, 150, 0);
      cover3.addBox(0F, 0F, 0F, 1, 1, 12);
      cover3.setRotationPoint(-2.5F, -22.5F, -38.5F);
      cover3.setTextureSize(64, 32);
      cover3.mirror = true;
      setRotation(cover3, 0F, 0F, 0.7853982F);
      cover4 = new ModelRenderer(this, 150, 0);
      cover4.addBox(0F, 0F, 0F, 1, 1, 1);
      cover4.setRotationPoint(-0.5F, -22.5F, -40.3F);
      cover4.setTextureSize(64, 32);
      cover4.mirror = true;
      setRotation(cover4, 0F, 0F, 0.7853982F);
      cover5 = new ModelRenderer(this, 150, 0);
      cover5.addBox(0F, 0F, 0F, 1, 1, 1);
      cover5.setRotationPoint(-2.5F, -22.5F, -40.3F);
      cover5.setTextureSize(64, 32);
      cover5.mirror = true;
      setRotation(cover5, 0F, 0F, 0.7853982F);
      cover6 = new ModelRenderer(this, 100, 100);
      cover6.addBox(0F, 0F, 0F, 1, 1, 8);
      cover6.setRotationPoint(-2.5F, -22.5F, -48.3F);
      cover6.setTextureSize(64, 32);
      cover6.mirror = true;
      setRotation(cover6, 0F, 0F, 0.7853982F);
      cover7 = new ModelRenderer(this, 100, 100);
      cover7.addBox(0F, 0F, 0F, 1, 1, 8);
      cover7.setRotationPoint(-0.5F, -22.5F, -48.3F);
      cover7.setTextureSize(64, 32);
      cover7.mirror = true;
      setRotation(cover7, 0F, 0F, 0.7853982F);
      cover8 = new ModelRenderer(this, 100, 100);
      cover8.addBox(0F, 0F, 0F, 2, 8, 1);
      cover8.setRotationPoint(-2.5F, -22.75F, -40.45F);
      cover8.setTextureSize(64, 32);
      cover8.mirror = true;
      setRotation(cover8, -1.553343F, 0F, 0F);
      cover9 = new ModelRenderer(this, 100, 100);
      cover9.addBox(0F, 0F, 0F, 1, 1, 9);
      cover9.setRotationPoint(-0.3F, -22.3F, -48.3F);
      cover9.setTextureSize(64, 32);
      cover9.mirror = true;
      setRotation(cover9, 0F, 0F, 0.7853982F);
      cover10 = new ModelRenderer(this, 100, 100);
      cover10.addBox(0F, 0F, 0F, 1, 1, 8);
      cover10.setRotationPoint(-2.65F, -22.35F, -48.3F);
      cover10.setTextureSize(64, 32);
      cover10.mirror = true;
      setRotation(cover10, 0F, 0F, 0.7853982F);
      cover11 = new ModelRenderer(this, 150, 0);
      cover11.addBox(0F, 0F, 0F, 2, 1, 1);
      cover11.setRotationPoint(-2.5F, -22.76F, -39.5F);
      cover11.setTextureSize(64, 32);
      cover11.mirror = true;
      setRotation(cover11, -1.553343F, 0F, 0F);
      cover12 = new ModelRenderer(this, 150, 0);
      cover12.addBox(0F, 0F, 0F, 2, 1, 1);
      cover12.setRotationPoint(-2.5F, -22.76F, -39.3F);
      cover12.setTextureSize(64, 32);
      cover12.mirror = true;
      setRotation(cover12, -1.553343F, 0F, 0F);
      cover13 = new ModelRenderer(this, 150, 0);
      cover13.addBox(0F, 0F, 0F, 1, 1, 1);
      cover13.setRotationPoint(-0.5F, -22.5F, -38.8F);
      cover13.setTextureSize(64, 32);
      cover13.mirror = true;
      setRotation(cover13, 0F, 0F, 0.7853982F);
      cover14 = new ModelRenderer(this, 150, 0);
      cover14.addBox(0F, 0F, 0F, 1, 1, 1);
      cover14.setRotationPoint(-2.5F, -22.5F, -38.8F);
      cover14.setTextureSize(64, 32);
      cover14.mirror = true;
      setRotation(cover14, 0F, 0F, 0.7853982F);
      cover15 = new ModelRenderer(this, 150, 0);
      cover15.addBox(0F, 0F, 0F, 1, 1, 1);
      cover15.setRotationPoint(-0.5F, -22.8F, -27.5F);
      cover15.setTextureSize(64, 32);
      cover15.mirror = true;
      setRotation(cover15, 0F, 0F, 0.7853982F);
      cover16 = new ModelRenderer(this, 150, 0);
      cover16.addBox(0F, 0F, 0F, 1, 1, 1);
      cover16.setRotationPoint(-2.5F, -22.8F, -27.5F);
      cover16.setTextureSize(64, 32);
      cover16.mirror = true;
      setRotation(cover16, 0F, 0F, 0.7853982F);
      cover17 = new ModelRenderer(this, 150, 0);
      cover17.addBox(0F, 0F, 0F, 1, 3, 12);
      cover17.setRotationPoint(1.25F, -18.7F, -38.8F);
      cover17.setTextureSize(64, 32);
      cover17.mirror = true;
      setRotation(cover17, 0F, 0F, 2.871067F);
      cover18 = new ModelRenderer(this, 150, 0);
      cover18.addBox(0F, 0F, 0F, 1, 3, 1);
      cover18.setRotationPoint(1.25F, -18.7F, -40.3F);
      cover18.setTextureSize(64, 32);
      cover18.mirror = true;
      setRotation(cover18, 0F, 0F, 2.871067F);
      cover19 = new ModelRenderer(this, 150, 0);
      cover19.addBox(0F, 0F, 0F, 1, 1, 1);
      cover19.setRotationPoint(-2.65F, -22.35F, -40.3F);
      cover19.setTextureSize(64, 32);
      cover19.mirror = true;
      setRotation(cover19, 0F, 0F, 0.7853982F);
      cover20 = new ModelRenderer(this, 150, 0);
      cover20.addBox(0F, 0F, 0F, 3, 1, 1);
      cover20.setRotationPoint(-4.15F, -18.75F, -40.3F);
      cover20.setTextureSize(64, 32);
      cover20.mirror = true;
      setRotation(cover20, 0F, 0F, -1.30027F);
      cover21 = new ModelRenderer(this, 150, 0);
      cover21.addBox(0F, 0F, 0F, 1, 1, 12);
      cover21.setRotationPoint(-2.65F, -22.35F, -38.8F);
      cover21.setTextureSize(64, 32);
      cover21.mirror = true;
      setRotation(cover21, 0F, 0F, 0.7853982F);
      cover22 = new ModelRenderer(this, 150, 0);
      cover22.addBox(0F, 0F, 0F, 3, 1, 12);
      cover22.setRotationPoint(-4.15F, -18.75F, -38.8F);
      cover22.setTextureSize(64, 32);
      cover22.mirror = true;
      setRotation(cover22, 0F, 0F, -1.30027F);
      cover23 = new ModelRenderer(this, 150, 0);
      cover23.addBox(0F, 0F, 0F, 2, 1, 1);
      cover23.setRotationPoint(-2.5F, -22.81F, -37.8F);
      cover23.setTextureSize(64, 32);
      cover23.mirror = true;
      setRotation(cover23, -1.553343F, 0F, 0F);
      cover24 = new ModelRenderer(this, 150, 0);
      cover24.addBox(0F, 0F, 0F, 1, 1, 12);
      cover24.setRotationPoint(-0.3F, -22.3F, -38.8F);
      cover24.setTextureSize(64, 32);
      cover24.mirror = true;
      setRotation(cover24, 0F, 0F, 0.7853982F);
      cover25 = new ModelRenderer(this, 0, 0);
      cover25.addBox(0F, 0F, 0F, 1, 1, 1);
      cover25.setRotationPoint(-2.4F, -22.7F, -38.5F);
      cover25.setTextureSize(64, 32);
      cover25.mirror = true;
      setRotation(cover25, -1.553343F, 0F, 0F);
      cover26 = new ModelRenderer(this, 0, 0);
      cover26.addBox(0F, 0F, 0F, 1, 1, 1);
      cover26.setRotationPoint(-1.6F, -22.7F, -38.5F);
      cover26.setTextureSize(64, 32);
      cover26.mirror = true;
      setRotation(cover26, -1.553343F, 0F, 0F);
      cover27 = new ModelRenderer(this, 0, 0);
      cover27.addBox(0F, 0F, 0F, 1, 1, 1);
      cover27.setRotationPoint(-0.6F, -22.5F, -39.5F);
      cover27.setTextureSize(64, 32);
      cover27.mirror = true;
      setRotation(cover27, 0F, 0F, 0.7853982F);
      cover28 = new ModelRenderer(this, 0, 0);
      cover28.addBox(0F, 0F, 0F, 1, 1, 1);
      cover28.setRotationPoint(-0.3F, -22.2F, -39.5F);
      cover28.setTextureSize(64, 32);
      cover28.mirror = true;
      setRotation(cover28, 0F, 0F, 0.7853982F);
      cover29 = new ModelRenderer(this, 0, 0);
      cover29.addBox(0F, 0F, 0F, 3, 1, 1);
      cover29.setRotationPoint(0.4F, -21.45F, -39.5F);
      cover29.setTextureSize(64, 32);
      cover29.mirror = true;
      setRotation(cover29, 0F, 0F, 1.301251F);
      cover30 = new ModelRenderer(this, 0, 0);
      cover30.addBox(0F, 0F, 0F, 1, 1, 1);
      cover30.setRotationPoint(-2.4F, -22.5F, -39.5F);
      cover30.setTextureSize(64, 32);
      cover30.mirror = true;
      setRotation(cover30, 0F, 0F, 0.7853982F);
      cover31 = new ModelRenderer(this, 0, 0);
      cover31.addBox(0F, 0F, 0F, 1, 1, 1);
      cover31.setRotationPoint(-2.65F, -22.2F, -39.5F);
      cover31.setTextureSize(64, 32);
      cover31.mirror = true;
      setRotation(cover31, 0F, 0F, 0.7853982F);
      cover32 = new ModelRenderer(this, 0, 0);
      cover32.addBox(0F, 0F, 0F, 3, 1, 1);
      cover32.setRotationPoint(-4.15F, -18.6F, -39.5F);
      cover32.setTextureSize(64, 32);
      cover32.mirror = true;
      setRotation(cover32, 0F, 0F, -1.30027F);
      gun204 = new ModelRenderer(this, 100, 100);
      gun204.addBox(0F, 0F, 0F, 1, 3, 8);
      gun204.setRotationPoint(1.25F, -18.7F, -48.3F);
      gun204.setTextureSize(64, 32);
      gun204.mirror = true;
      setRotation(gun204, 0F, 0F, 2.871067F);
      gun207 = new ModelRenderer(this, 100, 100);
      gun207.addBox(0F, 0F, 0F, 3, 1, 8);
      gun207.setRotationPoint(-4.15F, -18.75F, -48.3F);
      gun207.setTextureSize(64, 32);
      gun207.mirror = true;
      setRotation(gun207, 0F, 0F, -1.30027F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    cover1.render(f5);
    cover2.render(f5);
    cover3.render(f5);
    cover4.render(f5);
    cover5.render(f5);
    cover6.render(f5);
    cover7.render(f5);
    cover8.render(f5);
    cover9.render(f5);
    cover10.render(f5);
    cover11.render(f5);
    cover12.render(f5);
    cover13.render(f5);
    cover14.render(f5);
    cover15.render(f5);
    cover16.render(f5);
    cover17.render(f5);
    cover18.render(f5);
    cover19.render(f5);
    cover20.render(f5);
    cover21.render(f5);
    cover22.render(f5);
    cover23.render(f5);
    cover24.render(f5);
    cover25.render(f5);
    cover26.render(f5);
    cover27.render(f5);
    cover28.render(f5);
    cover29.render(f5);
    cover30.render(f5);
    cover31.render(f5);
    cover32.render(f5);
    gun204.render(f5);
    gun207.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
