// Date: 4/4/2016 8:13:09 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Marine extends ModelBiped
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer vest1;
    ModelRenderer vest2;
    ModelRenderer vest3;
    ModelRenderer vest4;
    ModelRenderer vest5;
    ModelRenderer vest6;
    ModelRenderer vest7;
    ModelRenderer vest8;
    ModelRenderer vest9;
    ModelRenderer vest10;
    ModelRenderer helmet1;
    ModelRenderer helmet2;
    ModelRenderer helmet3;
    ModelRenderer helmet4;
    ModelRenderer helmet5;
    ModelRenderer helmet6;
    ModelRenderer helmet7;
    ModelRenderer helmet8;
    ModelRenderer helmet9;
    ModelRenderer helmet10;
    ModelRenderer helmet11;
    ModelRenderer helmet12;
    ModelRenderer helmet13;
    ModelRenderer helmet14;
    ModelRenderer helmet15;
  
    public Marine()
    {
  	  super(0.01f, 0, 512, 256);
    textureWidth = 512;
    textureHeight = 256;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(512, 256);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(512, 256);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(512, 256);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(512, 256);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(512, 256);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(512, 256);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      vest1 = new ModelRenderer(this, 0, 70);
      vest1.addBox(-3F, 4F, -3.5F, 6, 2, 1);
      vest1.setRotationPoint(0F, 0F, 0F);
      vest1.setTextureSize(512, 256);
      vest1.mirror = true;
      setRotation(vest1, 0F, 0F, 0F);
      vest2 = new ModelRenderer(this, 0, 70);
      vest2.addBox(-4F, 3F, -3F, 8, 8, 1);
      vest2.setRotationPoint(0F, 0F, 0F);
      vest2.setTextureSize(512, 256);
      vest2.mirror = true;
      setRotation(vest2, 0F, 0F, 0F);
      vest3 = new ModelRenderer(this, 0, 70);
      vest3.addBox(-3.5F, 7F, -3.5F, 2, 4, 1);
      vest3.setRotationPoint(0F, 0F, 0F);
      vest3.setTextureSize(512, 256);
      vest3.mirror = true;
      setRotation(vest3, 0F, 0F, 0F);
      vest4 = new ModelRenderer(this, 0, 70);
      vest4.addBox(1.5F, 7F, -3.5F, 2, 4, 1);
      vest4.setRotationPoint(0F, 0F, 0F);
      vest4.setTextureSize(512, 256);
      vest4.mirror = true;
      setRotation(vest4, 0F, 0F, 0F);
      vest5 = new ModelRenderer(this, 0, 70);
      vest5.addBox(-1F, 7F, -3.5F, 2, 4, 1);
      vest5.setRotationPoint(0F, 0F, 0F);
      vest5.setTextureSize(512, 256);
      vest5.mirror = true;
      setRotation(vest5, 0F, 0F, 0F);
      vest6 = new ModelRenderer(this, 100, 70);
      vest6.addBox(-4F, 0.8F, -1.8F, 2, 3, 0);
      vest6.setRotationPoint(0F, 0F, 0F);
      vest6.setTextureSize(512, 256);
      vest6.mirror = true;
      setRotation(vest6, -0.3346075F, 0F, 0F);
      vest7 = new ModelRenderer(this, 100, 70);
      vest7.addBox(2F, 0.8F, -1.8F, 2, 3, 0);
      vest7.setRotationPoint(0F, 0F, 0F);
      vest7.setTextureSize(512, 256);
      vest7.mirror = true;
      setRotation(vest7, -0.3346075F, 0F, 0F);
      vest8 = new ModelRenderer(this, 0, 70);
      vest8.addBox(-4F, 4F, 2F, 8, 7, 1);
      vest8.setRotationPoint(0F, 0F, 0F);
      vest8.setTextureSize(512, 256);
      vest8.mirror = true;
      setRotation(vest8, 0F, 0F, 0F);
      vest9 = new ModelRenderer(this, 100, 100);
      vest9.addBox(-4F, 0.6F, 2F, 2, 4, 0);
      vest9.setRotationPoint(0F, 0F, 0F);
      vest9.setTextureSize(512, 256);
      vest9.mirror = true;
      setRotation(vest9, 0.2230717F, 0F, 0F);
      vest10 = new ModelRenderer(this, 100, 100);
      vest10.addBox(2F, 0.6F, 2F, 2, 4, 0);
      vest10.setRotationPoint(0F, 0F, 0F);
      vest10.setTextureSize(512, 256);
      vest10.mirror = true;
      setRotation(vest10, 0.2230717F, 0F, 0F);
      helmet1 = new ModelRenderer(this, 100, 0);
      helmet1.addBox(-4.5F, -8F, -4F, 1, 3, 8);
      helmet1.setRotationPoint(0F, 0F, 0F);
      helmet1.setTextureSize(512, 256);
      helmet1.mirror = true;
      setRotation(helmet1, 0F, 0F, 0F);
      helmet2 = new ModelRenderer(this, 100, 0);
      helmet2.addBox(3.5F, -8F, -4F, 1, 3, 8);
      helmet2.setRotationPoint(0F, 0F, 0F);
      helmet2.setTextureSize(512, 256);
      helmet2.mirror = true;
      setRotation(helmet2, 0F, 0F, 0F);
      helmet3 = new ModelRenderer(this, 100, 0);
      helmet3.addBox(-4.5F, -5F, -1F, 1, 3, 5);
      helmet3.setRotationPoint(0F, 0F, 0F);
      helmet3.setTextureSize(512, 256);
      helmet3.mirror = true;
      setRotation(helmet3, 0F, 0F, 0F);
      helmet4 = new ModelRenderer(this, 100, 0);
      helmet4.addBox(3.5F, -5F, -1F, 1, 3, 5);
      helmet4.setRotationPoint(0F, 0F, 0F);
      helmet4.setTextureSize(512, 256);
      helmet4.mirror = true;
      setRotation(helmet4, 0F, 0F, 0F);
      helmet5 = new ModelRenderer(this, 100, 0);
      helmet5.addBox(-4.5F, -8F, 3.5F, 9, 6, 1);
      helmet5.setRotationPoint(0F, 0F, 0F);
      helmet5.setTextureSize(512, 256);
      helmet5.mirror = true;
      setRotation(helmet5, 0F, 0F, 0F);
      helmet6 = new ModelRenderer(this, 100, 0);
      helmet6.addBox(-4.5F, -9F, -4.5F, 9, 1, 9);
      helmet6.setRotationPoint(0F, 0F, 0F);
      helmet6.setTextureSize(512, 256);
      helmet6.mirror = true;
      setRotation(helmet6, 0F, 0F, 0F);
      helmet7 = new ModelRenderer(this, 0, 100);
      helmet7.addBox(-4F, -8F, -4.5F, 8, 2, 1);
      helmet7.setRotationPoint(0F, 0F, 0F);
      helmet7.setTextureSize(512, 256);
      helmet7.mirror = true;
      setRotation(helmet7, 0F, 0F, 0F);
      helmet8 = new ModelRenderer(this, 0, 150);
      helmet8.addBox(-4.5F, -9F, -5F, 1, 4, 1);
      helmet8.setRotationPoint(0F, 0F, 0F);
      helmet8.setTextureSize(512, 256);
      helmet8.mirror = true;
      setRotation(helmet8, 0F, 0F, 0F);
      helmet9 = new ModelRenderer(this, 0, 150);
      helmet9.addBox(3.5F, -9F, -5F, 1, 4, 1);
      helmet9.setRotationPoint(0F, 0F, 0F);
      helmet9.setTextureSize(512, 256);
      helmet9.mirror = true;
      setRotation(helmet9, 0F, 0F, 0F);
      helmet10 = new ModelRenderer(this, 0, 150);
      helmet10.addBox(-4.5F, -9F, -5F, 9, 1, 1);
      helmet10.setRotationPoint(0F, 0F, 0F);
      helmet10.setTextureSize(512, 256);
      helmet10.mirror = true;
      setRotation(helmet10, 0F, 0F, 0F);
      helmet11 = new ModelRenderer(this, 0, 150);
      helmet11.addBox(1F, -6F, -5F, 3, 1, 1);
      helmet11.setRotationPoint(0F, 0F, 0F);
      helmet11.setTextureSize(512, 256);
      helmet11.mirror = true;
      setRotation(helmet11, 0F, 0F, 0F);
      helmet12 = new ModelRenderer(this, 0, 150);
      helmet12.addBox(-4F, -6F, -5F, 3, 1, 1);
      helmet12.setRotationPoint(0F, 0F, 0F);
      helmet12.setTextureSize(512, 256);
      helmet12.mirror = true;
      setRotation(helmet12, 0F, 0F, 0F);
      helmet13 = new ModelRenderer(this, 0, 150);
      helmet13.addBox(-1F, -6.5F, -5F, 2, 1, 1);
      helmet13.setRotationPoint(0F, 0F, 0F);
      helmet13.setTextureSize(512, 256);
      helmet13.mirror = true;
      setRotation(helmet13, 0F, 0F, 0F);
      helmet14 = new ModelRenderer(this, 30, 100);
      helmet14.addBox(4.5F, -2F, -5F, 0, 1, 5);
      helmet14.setRotationPoint(0F, 0F, 0F);
      helmet14.setTextureSize(512, 256);
      helmet14.mirror = true;
      setRotation(helmet14, 0F, 0F, 0F);
      helmet15 = new ModelRenderer(this, 30, 110);
      helmet15.addBox(1.5F, -2F, -5F, 3, 1, 0);
      helmet15.setRotationPoint(0F, 0F, 0F);
      helmet15.setTextureSize(512, 256);
      helmet15.mirror = true;
      setRotation(helmet15, 0F, 0F, 0F);
      
      this.bipedHead.addChild(helmet1);
      this.bipedHead.addChild(helmet2);
      this.bipedHead.addChild(helmet3);
      this.bipedHead.addChild(helmet4);
      this.bipedHead.addChild(helmet5);
      this.bipedHead.addChild(helmet6);
      this.bipedHead.addChild(helmet7);
      this.bipedHead.addChild(helmet8);
      this.bipedHead.addChild(helmet9);
      this.bipedHead.addChild(helmet10);
      this.bipedHead.addChild(helmet11);
      this.bipedHead.addChild(helmet12);
      this.bipedHead.addChild(helmet13);
      this.bipedHead.addChild(helmet14);
      this.bipedHead.addChild(helmet15);
      this.bipedBody.addChild(vest1);
      this.bipedBody.addChild(vest2);
      this.bipedBody.addChild(vest3);
      this.bipedBody.addChild(vest4);
      this.bipedBody.addChild(vest5);
      this.bipedBody.addChild(vest6);
      this.bipedBody.addChild(vest7);
      this.bipedBody.addChild(vest8);
      this.bipedBody.addChild(vest9);
      this.bipedBody.addChild(vest10);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
