// Date: 4/14/2018 10:45:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Maxim9cover extends ModelBase
{
  //fields
   
    ModelRenderer cover1;
    ModelRenderer cover2;
    ModelRenderer cover3;
    ModelRenderer cover4;
  
  public Maxim9cover()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      cover1 = new ModelRenderer(this, 0, 0);
      cover1.addBox(0F, 0F, 0F, 2, 1, 8);
      cover1.setRotationPoint(-2.7F, -14.3F, -23.5F);
      cover1.setTextureSize(64, 32);
      cover1.mirror = true;
      setRotation(cover1, 0F, 0F, 0F);
      cover2 = new ModelRenderer(this, 0, 0);
      cover2.addBox(0F, 0F, 0F, 1, 1, 8);
      cover2.setRotationPoint(-1.3F, -14.3F, -23.5F);
      cover2.setTextureSize(64, 32);
      cover2.mirror = true;
      setRotation(cover2, 0F, 0F, 0F);
      cover3 = new ModelRenderer(this, 0, 0);
      cover3.addBox(0F, 0F, 0F, 1, 1, 8);
      cover3.setRotationPoint(-0.3F, -14.3F, -23.5F);
      cover3.setTextureSize(64, 32);
      cover3.mirror = true;
      setRotation(cover3, 0F, 0F, 1.003822F);
      cover4 = new ModelRenderer(this, 0, 0);
      cover4.addBox(0F, 0F, 0F, 1, 1, 8);
      cover4.setRotationPoint(-2.7F, -14.3F, -23.5F);
      cover4.setTextureSize(64, 32);
      cover4.mirror = true;
      setRotation(cover4, 0F, 0F, 0.5948578F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    cover1.render(f5);
    cover2.render(f5);
    cover3.render(f5);
    cover4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
 
}
