// Date: 4/2/2018 12:35:08 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MP43Edoublebarrel extends ModelBase
{
  //fields
    
    ModelRenderer Barrel1;
    ModelRenderer Barrel2;
    ModelRenderer Barrel3;
    ModelRenderer Barrel4;
    ModelRenderer Barrel5;
    ModelRenderer Barrel6;
    ModelRenderer Barrel7;
    ModelRenderer Barrel8;
    ModelRenderer Barrel9;
    ModelRenderer Barrel10;
    ModelRenderer Barrel11;
    ModelRenderer Barrel12;
    ModelRenderer Barrel13;
    ModelRenderer Barrel14;
    ModelRenderer Barrel15;
    ModelRenderer Barrel16;
    ModelRenderer Barrel17;
    ModelRenderer Barrel18;
    ModelRenderer Barrel19;
    ModelRenderer Barrel20;
    ModelRenderer Barrel21;
    ModelRenderer Barrel22;
    ModelRenderer Barrel23;
    ModelRenderer Barrel24;
    ModelRenderer Barrel25;
  
  public MP43Edoublebarrel()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      Barrel1 = new ModelRenderer(this, 0, 0);
      Barrel1.addBox(0F, 0F, 0F, 1, 2, 79);
      Barrel1.setRotationPoint(-1.5F, -8F, -77F);
      Barrel1.setTextureSize(64, 32);
      Barrel1.mirror = true;
      setRotation(Barrel1, 0F, 0F, 0F);
      Barrel2 = new ModelRenderer(this, 0, 0);
      Barrel2.addBox(0F, 0F, 0F, 1, 2, 79);
      Barrel2.setRotationPoint(-1.5F, -4.6F, -77F);
      Barrel2.setTextureSize(64, 32);
      Barrel2.mirror = true;
      setRotation(Barrel2, 0F, 0F, -2.356194F);
      Barrel3 = new ModelRenderer(this, 0, 0);
      Barrel3.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel3.setRotationPoint(-0.5F, -4.6F, -77F);
      Barrel3.setTextureSize(64, 32);
      Barrel3.mirror = true;
      setRotation(Barrel3, 0F, 0F, -2.356194F);
      Barrel4 = new ModelRenderer(this, 250, 0);
      Barrel4.addBox(0F, 0F, 0F, 4, 1, 3);
      Barrel4.setRotationPoint(-3F, -3F, -6F);
      Barrel4.setTextureSize(64, 32);
      Barrel4.mirror = true;
      setRotation(Barrel4, 3.085825F, 0F, 0F);
      Barrel5 = new ModelRenderer(this, 250, 0);
      Barrel5.addBox(0F, 0F, 0F, 2, 3, 1);
      Barrel5.setRotationPoint(1F, -4.8F, -5.9F);
      Barrel5.setTextureSize(64, 32);
      Barrel5.mirror = true;
      setRotation(Barrel5, 0F, -1.747395F, 0F);
      Barrel6 = new ModelRenderer(this, 250, 0);
      Barrel6.addBox(0F, 0F, 0F, 1, 3, 2);
      Barrel6.setRotationPoint(-3F, -4.8F, -5.9F);
      Barrel6.setTextureSize(64, 32);
      Barrel6.mirror = true;
      setRotation(Barrel6, 0F, 0.1858931F, 0F);
      Barrel7 = new ModelRenderer(this, 250, 0);
      Barrel7.addBox(0F, 0F, 0F, 4, 1, 17);
      Barrel7.setRotationPoint(-3F, -2.6F, -6F);
      Barrel7.setTextureSize(64, 32);
      Barrel7.mirror = true;
      setRotation(Barrel7, 3.085825F, 0F, 0F);
      Barrel8 = new ModelRenderer(this, 250, 0);
      Barrel8.addBox(0F, 0F, 0F, 1, 1, 25);
      Barrel8.setRotationPoint(1F, -4.8F, -30.9F);
      Barrel8.setTextureSize(64, 32);
      Barrel8.mirror = true;
      setRotation(Barrel8, 0F, 0F, 2.356194F);
      Barrel9 = new ModelRenderer(this, 250, 0);
      Barrel9.addBox(0F, 0F, 0F, 1, 1, 25);
      Barrel9.setRotationPoint(-3F, -4.8F, -30.9F);
      Barrel9.setTextureSize(64, 32);
      Barrel9.mirror = true;
      setRotation(Barrel9, 0F, 0F, -0.7853982F);
      Barrel10 = new ModelRenderer(this, 250, 0);
      Barrel10.addBox(0F, 0F, 0F, 4, 1, 1);
      Barrel10.setRotationPoint(-3F, -4.8F, -30.9F);
      Barrel10.setTextureSize(64, 32);
      Barrel10.mirror = true;
      setRotation(Barrel10, -0.7807508F, 0F, 0F);
      Barrel11 = new ModelRenderer(this, 250, 0);
      Barrel11.addBox(0F, 0F, 0F, 4, 1, 25);
      Barrel11.setRotationPoint(-3F, -4.8F, -30.9F);
      Barrel11.setTextureSize(64, 32);
      Barrel11.mirror = true;
      setRotation(Barrel11, 0F, 0F, 0F);
      Barrel12 = new ModelRenderer(this, 250, 0);
      Barrel12.addBox(0F, 0F, 0F, 4, 1, 25);
      Barrel12.setRotationPoint(-3F, -1.6F, -6F);
      Barrel12.setTextureSize(64, 32);
      Barrel12.mirror = true;
      setRotation(Barrel12, 3.085825F, 0F, 0F);
      Barrel13 = new ModelRenderer(this, 250, 0);
      Barrel13.addBox(0F, 0F, 0F, 1, 3, 2);
      Barrel13.setRotationPoint(-0.3F, -1.8F, -4F);
      Barrel13.setTextureSize(64, 32);
      Barrel13.mirror = true;
      setRotation(Barrel13, -3.048646F, 0F, 0F);
      Barrel14 = new ModelRenderer(this, 250, 0);
      Barrel14.addBox(0F, 0F, 0F, 3, 1, 2);
      Barrel14.setRotationPoint(-2.7F, -1.8F, -4F);
      Barrel14.setTextureSize(64, 32);
      Barrel14.mirror = true;
      setRotation(Barrel14, -3.048646F, 0F, 0F);
      Barrel15 = new ModelRenderer(this, 0, 0);
      Barrel15.addBox(0F, 0F, 0F, 1, 3, 79);
      Barrel15.setRotationPoint(-0.5F, -7.6F, -77F);
      Barrel15.setTextureSize(64, 32);
      Barrel15.mirror = true;
      setRotation(Barrel15, 0F, 0F, 0F);
      Barrel16 = new ModelRenderer(this, 0, 0);
      Barrel16.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel16.setRotationPoint(-2.5F, -4.6F, -77F);
      Barrel16.setTextureSize(64, 32);
      Barrel16.mirror = true;
      setRotation(Barrel16, 0F, 0F, -2.356194F);
      Barrel17 = new ModelRenderer(this, 0, 0);
      Barrel17.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel17.setRotationPoint(-3.5F, -5.6F, -77F);
      Barrel17.setTextureSize(64, 32);
      Barrel17.mirror = true;
      setRotation(Barrel17, 0F, 0F, -0.7853982F);
      Barrel18 = new ModelRenderer(this, 0, 0);
      Barrel18.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel18.setRotationPoint(-3.5F, -6.6F, -77F);
      Barrel18.setTextureSize(64, 32);
      Barrel18.mirror = true;
      setRotation(Barrel18, 0F, 0F, -0.7853982F);
      Barrel19 = new ModelRenderer(this, 0, 0);
      Barrel19.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel19.setRotationPoint(-2.5F, -7.6F, -77F);
      Barrel19.setTextureSize(64, 32);
      Barrel19.mirror = true;
      setRotation(Barrel19, 0F, 0F, 0.7853982F);
      Barrel20 = new ModelRenderer(this, 0, 0);
      Barrel20.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel20.setRotationPoint(0.5F, -4.6F, -77F);
      Barrel20.setTextureSize(64, 32);
      Barrel20.mirror = true;
      setRotation(Barrel20, 0F, 0F, -2.356194F);
      Barrel21 = new ModelRenderer(this, 0, 0);
      Barrel21.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel21.setRotationPoint(1.5F, -5.6F, -77F);
      Barrel21.setTextureSize(64, 32);
      Barrel21.mirror = true;
      setRotation(Barrel21, 0F, 0F, 2.356194F);
      Barrel22 = new ModelRenderer(this, 0, 0);
      Barrel22.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel22.setRotationPoint(1.5F, -6.6F, -77F);
      Barrel22.setTextureSize(64, 32);
      Barrel22.mirror = true;
      setRotation(Barrel22, 0F, 0F, 2.356194F);
      Barrel23 = new ModelRenderer(this, 0, 0);
      Barrel23.addBox(0F, 0F, 0F, 1, 1, 79);
      Barrel23.setRotationPoint(0.5F, -7.6F, -77F);
      Barrel23.setTextureSize(64, 32);
      Barrel23.mirror = true;
      setRotation(Barrel23, 0F, 0F, 0.8028515F);
      Barrel24 = new ModelRenderer(this, 0, 0);
      Barrel24.addBox(0F, 0F, 0F, 5, 1, 79);
      Barrel24.setRotationPoint(-3.5F, -6.6F, -77F);
      Barrel24.setTextureSize(64, 32);
      Barrel24.mirror = true;
      setRotation(Barrel24, 0F, 0F, 0F);
      Barrel25 = new ModelRenderer(this, 0, 0);
      Barrel25.addBox(0F, 0F, 0F, 1, 3, 79);
      Barrel25.setRotationPoint(-2.5F, -7.6F, -77F);
      Barrel25.setTextureSize(64, 32);
      Barrel25.mirror = true;
      setRotation(Barrel25, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    Barrel1.render(f5);
    Barrel2.render(f5);
    Barrel3.render(f5);
    Barrel4.render(f5);
    Barrel5.render(f5);
    Barrel6.render(f5);
    Barrel7.render(f5);
    Barrel8.render(f5);
    Barrel9.render(f5);
    Barrel10.render(f5);
    Barrel11.render(f5);
    Barrel12.render(f5);
    Barrel13.render(f5);
    Barrel14.render(f5);
    Barrel15.render(f5);
    Barrel16.render(f5);
    Barrel17.render(f5);
    Barrel18.render(f5);
    Barrel19.render(f5);
    Barrel20.render(f5);
    Barrel21.render(f5);
    Barrel22.render(f5);
    Barrel23.render(f5);
    Barrel24.render(f5);
    Barrel25.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
 
}
