// Date: 6/26/2019 6:15:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MP5A4Stock extends ModelBase
{
  //fields
    ModelRenderer stock1;
    ModelRenderer stock2;
    ModelRenderer stock3;
    ModelRenderer stock4;
    ModelRenderer stock5;
    ModelRenderer stock6;
    ModelRenderer stock7;
    ModelRenderer stock8;
    ModelRenderer stock9;
    ModelRenderer stock10;
    ModelRenderer stock11;
    ModelRenderer stock12;
    ModelRenderer stock13;
  
  public MP5A4Stock()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      stock1 = new ModelRenderer(this, 0, 0);
      stock1.addBox(0F, 0F, 0F, 2, 1, 7);
      stock1.setRotationPoint(-2.5F, -15.5F, 4.4F);
      stock1.setTextureSize(64, 32);
      stock1.mirror = true;
      setRotation(stock1, -0.4461433F, 0F, 0F);
      stock2 = new ModelRenderer(this, 0, 0);
      stock2.addBox(0F, 0F, 0F, 4, 2, 7);
      stock2.setRotationPoint(-3.5F, -14.5F, 4.4F);
      stock2.setTextureSize(64, 32);
      stock2.mirror = true;
      setRotation(stock2, -0.4461433F, 0F, 0F);
      stock3 = new ModelRenderer(this, 0, 0);
      stock3.addBox(0F, 0F, 0F, 2, 1, 23);
      stock3.setRotationPoint(-2.5F, -13F, 9.4F);
      stock3.setTextureSize(64, 32);
      stock3.mirror = true;
      setRotation(stock3, 0F, 0F, 0F);
      stock4 = new ModelRenderer(this, 0, 0);
      stock4.addBox(0F, 0F, 0F, 4, 1, 23);
      stock4.setRotationPoint(-3.5F, -12F, 9.4F);
      stock4.setTextureSize(64, 32);
      stock4.mirror = true;
      setRotation(stock4, 0F, 0F, 0F);
      stock5 = new ModelRenderer(this, 0, 0);
      stock5.addBox(0F, 0F, 0F, 4, 2, 10);
      stock5.setRotationPoint(-3.5F, -11F, 32.4F);
      stock5.setTextureSize(64, 32);
      stock5.mirror = true;
      setRotation(stock5, -1.710216F, 0F, 0F);
      stock6 = new ModelRenderer(this, 0, 0);
      stock6.addBox(0F, -3F, 0F, 4, 4, 24);
      stock6.setRotationPoint(-3.5F, -9F, 6.4F);
      stock6.setTextureSize(64, 32);
      stock6.mirror = true;
      setRotation(stock6, -0.2974289F, 0F, 0F);
      stock7 = new ModelRenderer(this, 0, 0);
      stock7.addBox(0F, 0F, 0F, 4, 4, 4);
      stock7.setRotationPoint(-3.5F, -12F, 4.4F);
      stock7.setTextureSize(64, 32);
      stock7.mirror = true;
      setRotation(stock7, 0F, 0F, 0F);
      stock8 = new ModelRenderer(this, 0, 0);
      stock8.addBox(0F, 0F, 0F, 4, 4, 20);
      stock8.setRotationPoint(-3.5F, -11F, 10.4F);
      stock8.setTextureSize(64, 32);
      stock8.mirror = true;
      setRotation(stock8, 0F, 0F, 0F);
      stock9 = new ModelRenderer(this, 0, 0);
      stock9.addBox(0F, 0F, 0F, 4, 3, 7);
      stock9.setRotationPoint(-3.5F, -7F, 23.4F);
      stock9.setTextureSize(64, 32);
      stock9.mirror = true;
      setRotation(stock9, 0F, 0F, 0F);
      stock10 = new ModelRenderer(this, 0, 0);
      stock10.addBox(0F, 0F, 0F, 1, 1, 25);
      stock10.setRotationPoint(-0.5F, -13F, 7.4F);
      stock10.setTextureSize(64, 32);
      stock10.mirror = true;
      setRotation(stock10, 0F, 0F, 0.7853982F);
      stock11 = new ModelRenderer(this, 0, 0);
      stock11.addBox(0F, 0F, 0F, 1, 1, 25);
      stock11.setRotationPoint(-2.5F, -13F, 7.4F);
      stock11.setTextureSize(64, 32);
      stock11.mirror = true;
      setRotation(stock11, 0F, 0F, 0.7853982F);
      stock12 = new ModelRenderer(this, 0, 0);
      stock12.addBox(0F, 0.4F, 0F, 1, 1, 25);
      stock12.setRotationPoint(-2.5F, -13F, 7.4F);
      stock12.setTextureSize(64, 32);
      stock12.mirror = true;
      setRotation(stock12, 0F, 0F, 0.7853982F);
      stock13 = new ModelRenderer(this, 0, 0);
      stock13.addBox(0.4F, 0F, 0F, 1, 1, 25);
      stock13.setRotationPoint(-0.5F, -13F, 7.4F);
      stock13.setTextureSize(64, 32);
      stock13.mirror = true;
      setRotation(stock13, 0F, 0F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    stock1.render(f5);
    stock2.render(f5);
    stock3.render(f5);
    stock4.render(f5);
    stock5.render(f5);
    stock6.render(f5);
    stock7.render(f5);
    stock8.render(f5);
    stock9.render(f5);
    stock10.render(f5);
    stock11.render(f5);
    stock12.render(f5);
    stock13.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
