// Date: 6/26/2019 4:36:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MP5HOGUEGrip extends ModelBase
{
  //fields
    ModelRenderer grip3;
    ModelRenderer grip4;
    ModelRenderer grip5;
    ModelRenderer grip6;
    ModelRenderer grip7;
    ModelRenderer grip8;
    ModelRenderer grip9;
    ModelRenderer grip10;
    ModelRenderer grip11;
    ModelRenderer grip12;
  
  public MP5HOGUEGrip()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      grip3 = new ModelRenderer(this, 0, 0);
      grip3.addBox(0F, -3F, 5F, 4, 6, 6);
      grip3.setRotationPoint(-3.7F, -6.8F, -4.5F);
      grip3.setTextureSize(256, 256);
      grip3.mirror = true;
      setRotation(grip3, -1.226894F, 0F, 0F);
      grip4 = new ModelRenderer(this, 0, 0);
      grip4.addBox(0F, -3F, 5F, 1, 6, 6);
      grip4.setRotationPoint(-0.3F, -6.8F, -4.5F);
      grip4.setTextureSize(256, 256);
      grip4.mirror = true;
      setRotation(grip4, -1.226894F, 0F, 0F);
      grip5 = new ModelRenderer(this, 0, 0);
      grip5.addBox(0F, 0F, 0.5F, 1, 1, 8);
      grip5.setRotationPoint(-0.3F, -5.8F, -0.5F);
      grip5.setTextureSize(256, 256);
      grip5.mirror = true;
      setRotation(grip5, -1.07818F, 0F, 0F);
      grip6 = new ModelRenderer(this, 0, 0);
      grip6.addBox(0F, 0F, 0.5F, 4, 1, 8);
      grip6.setRotationPoint(-3.7F, -5.8F, -0.5F);
      grip6.setTextureSize(256, 256);
      grip6.mirror = true;
      setRotation(grip6, -1.07818F, 0F, 0F);
      grip7 = new ModelRenderer(this, 0, 0);
      grip7.addBox(0F, 0F, 0F, 1, 5, 2);
      grip7.setRotationPoint(-0.3F, -4.9F, -1.1F);
      grip7.setTextureSize(256, 256);
      grip7.mirror = true;
      setRotation(grip7, -0.7435722F, 0F, 0F);
      grip8 = new ModelRenderer(this, 0, 0);
      grip8.addBox(0F, 0F, 0F, 1, 5, 2);
      grip8.setRotationPoint(-3.7F, -4.9F, -1.1F);
      grip8.setTextureSize(256, 256);
      grip8.mirror = true;
      setRotation(grip8, -0.7435722F, 0F, 0F);
      grip9 = new ModelRenderer(this, 0, 0);
      grip9.addBox(0F, 1F, 2.5F, 1, 1, 6);
      grip9.setRotationPoint(-0.3F, -5.8F, -0.5F);
      grip9.setTextureSize(256, 256);
      grip9.mirror = true;
      setRotation(grip9, -1.07818F, 0F, 0F);
      grip10 = new ModelRenderer(this, 0, 0);
      grip10.addBox(0F, 1F, 2.5F, 1, 1, 6);
      grip10.setRotationPoint(-3.7F, -5.8F, -0.5F);
      grip10.setTextureSize(256, 256);
      grip10.mirror = true;
      setRotation(grip10, -1.07818F, 0F, 0F);
      grip11 = new ModelRenderer(this, 0, 0);
      grip11.addBox(0F, 0F, 0F, 4, 1, 1);
      grip11.setRotationPoint(-3.5F, -0.1F, -4.9F);
      grip11.setTextureSize(256, 256);
      grip11.mirror = true;
      setRotation(grip11, -0.5995051F, 0F, 0F);
      grip12 = new ModelRenderer(this, 0, 0);
      grip12.addBox(0F, 0F, 0F, 4, 1, 1);
      grip12.setRotationPoint(-3.5F, 2F, -4.3F);
      grip12.setTextureSize(256, 256);
      grip12.mirror = true;
      setRotation(grip12, -0.5995051F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    grip3.render(f5);
    grip4.render(f5);
    grip5.render(f5);
    grip6.render(f5);
    grip7.render(f5);
    grip8.render(f5);
    grip9.render(f5);
    grip10.render(f5);
    grip11.render(f5);
    grip12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
