// Date: 12/12/2017 10:11:23 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MPXmag extends ModelBase
{
  //fields
    
    ModelRenderer Mag1;
    ModelRenderer Mag2;
    ModelRenderer Mag3;
    ModelRenderer Mag4;
  
  public MPXmag()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      
      Mag1 = new ModelRenderer(this, 0, 0);
      Mag1.addBox(0F, 0F, 0F, 4, 11, 5);
      Mag1.setRotationPoint(-3.5F, -8.5F, -20.6F);
      Mag1.setTextureSize(64, 32);
      Mag1.mirror = true;
      setRotation(Mag1, -0.2230717F, 0F, 0F);
      Mag2 = new ModelRenderer(this, 0, 0);
      Mag2.addBox(0F, 0F, 0F, 4, 5, 15);
      Mag2.setRotationPoint(-3.5F, 3.3F, -18.1F);
      Mag2.setTextureSize(64, 32);
      Mag2.mirror = true;
      setRotation(Mag2, -2.044824F, 0F, 0F);
      Mag3 = new ModelRenderer(this, 0, 0);
      Mag3.addBox(0F, 0F, 0F, 3, 1, 15);
      Mag3.setRotationPoint(-3F, 3.3F, -17.7F);
      Mag3.setTextureSize(64, 32);
      Mag3.mirror = true;
      setRotation(Mag3, -2.044824F, 0F, 0F);
      Mag4 = new ModelRenderer(this, 0, 0);
      Mag4.addBox(0F, 0F, 0F, 3, 12, 1);
      Mag4.setRotationPoint(-3F, -8.5F, -16.1F);
      Mag4.setTextureSize(64, 32);
      Mag4.mirror = true;
      setRotation(Mag4, -0.2230717F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    Mag1.render(f5);
    Mag2.render(f5);
    Mag3.render(f5);
    Mag4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
