// Date: 1/28/2017 4:03:21 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MXMag extends ModelBase
{
  //fields
    ModelRenderer gun1;
    ModelRenderer gun2;
    ModelRenderer gun3;
    ModelRenderer gun4;
    ModelRenderer gun5;
    ModelRenderer gun6;
    ModelRenderer gun7;
    ModelRenderer gun8;
    ModelRenderer gun9;
    ModelRenderer gun10;
    ModelRenderer gun11;
    ModelRenderer gun12;
    ModelRenderer gun13;
    ModelRenderer gun14;
    ModelRenderer gun15;
    ModelRenderer gun16;
    ModelRenderer gun17;
    ModelRenderer gun18;
    ModelRenderer gun19;
    ModelRenderer gun20;
    ModelRenderer gun21;
    ModelRenderer gun22;
    ModelRenderer gun23;
  
  public MXMag()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun1 = new ModelRenderer(this, 200, 0);
      gun1.addBox(0F, 0F, 0F, 3, 15, 6);
      gun1.setRotationPoint(1F, -12F, -4.5F);
      gun1.setTextureSize(64, 32);
      gun1.mirror = true;
      setRotation(gun1, -0.1487144F, 0F, 0F);
      gun2 = new ModelRenderer(this, 200, 0);
      gun2.addBox(0F, 0F, 0F, 1, 15, 1);
      gun2.setRotationPoint(0.9F, -11.3F, 0.5F);
      gun2.setTextureSize(64, 32);
      gun2.mirror = true;
      setRotation(gun2, -0.1487144F, 0F, 0F);
      gun3 = new ModelRenderer(this, 200, 0);
      gun3.addBox(0F, 0F, 0F, 1, 15, 1);
      gun3.setRotationPoint(0.9F, -11.5F, -1F);
      gun3.setTextureSize(64, 32);
      gun3.mirror = true;
      setRotation(gun3, -0.1487144F, 0F, 0F);
      gun4 = new ModelRenderer(this, 200, 0);
      gun4.addBox(0F, 0F, 0F, 1, 15, 1);
      gun4.setRotationPoint(0.9F, -11.7F, -2.5F);
      gun4.setTextureSize(64, 32);
      gun4.mirror = true;
      setRotation(gun4, -0.1487144F, 0F, 0F);
      gun5 = new ModelRenderer(this, 200, 0);
      gun5.addBox(0F, 0F, 0F, 1, 15, 1);
      gun5.setRotationPoint(0.9F, -12F, -4F);
      gun5.setTextureSize(64, 32);
      gun5.mirror = true;
      setRotation(gun5, -0.1487144F, 0F, 0F);
      gun6 = new ModelRenderer(this, 200, 0);
      gun6.addBox(0F, 0F, 0F, 1, 15, 1);
      gun6.setRotationPoint(3.1F, -12F, -4F);
      gun6.setTextureSize(64, 32);
      gun6.mirror = true;
      setRotation(gun6, -0.1487144F, 0F, 0F);
      gun7 = new ModelRenderer(this, 200, 0);
      gun7.addBox(0F, 0F, 0F, 1, 15, 1);
      gun7.setRotationPoint(3.1F, -11.7F, -2.5F);
      gun7.setTextureSize(64, 32);
      gun7.mirror = true;
      setRotation(gun7, -0.1487144F, 0F, 0F);
      gun8 = new ModelRenderer(this, 200, 0);
      gun8.addBox(0F, 0F, 0F, 1, 15, 1);
      gun8.setRotationPoint(3.1F, -11.5F, -1F);
      gun8.setTextureSize(64, 32);
      gun8.mirror = true;
      setRotation(gun8, -0.1487144F, 0F, 0F);
      gun9 = new ModelRenderer(this, 200, 0);
      gun9.addBox(0F, 0F, 0F, 1, 15, 1);
      gun9.setRotationPoint(3.1F, -11.3F, 0.5F);
      gun9.setTextureSize(64, 32);
      gun9.mirror = true;
      setRotation(gun9, -0.1487144F, 0F, 0F);
      gun10 = new ModelRenderer(this, 200, 0);
      gun10.addBox(0F, 0F, 0F, 1, 1, 5);
      gun10.setRotationPoint(3.1F, -11F, -4F);
      gun10.setTextureSize(64, 32);
      gun10.mirror = true;
      setRotation(gun10, -0.1487144F, 0F, 0F);
      gun11 = new ModelRenderer(this, 200, 0);
      gun11.addBox(0F, 0F, 0F, 1, 1, 5);
      gun11.setRotationPoint(3.1F, -9F, -4.2F);
      gun11.setTextureSize(64, 32);
      gun11.mirror = true;
      setRotation(gun11, -0.1487144F, 0F, 0F);
      gun12 = new ModelRenderer(this, 200, 0);
      gun12.addBox(0F, 0F, 0F, 1, 1, 5);
      gun12.setRotationPoint(3.1F, -7F, -4.5F);
      gun12.setTextureSize(64, 32);
      gun12.mirror = true;
      setRotation(gun12, -0.1487144F, 0F, 0F);
      gun13 = new ModelRenderer(this, 200, 0);
      gun13.addBox(0F, 0F, 0F, 1, 1, 5);
      gun13.setRotationPoint(3.1F, -5F, -4.7F);
      gun13.setTextureSize(64, 32);
      gun13.mirror = true;
      setRotation(gun13, -0.1487144F, 0F, 0F);
      gun14 = new ModelRenderer(this, 200, 0);
      gun14.addBox(0F, 0F, 0F, 1, 1, 5);
      gun14.setRotationPoint(3.1F, -3F, -5F);
      gun14.setTextureSize(64, 32);
      gun14.mirror = true;
      setRotation(gun14, -0.1487144F, 0F, 0F);
      gun15 = new ModelRenderer(this, 200, 0);
      gun15.addBox(0F, 0F, 0F, 1, 1, 5);
      gun15.setRotationPoint(3.1F, -1F, -5.3F);
      gun15.setTextureSize(64, 32);
      gun15.mirror = true;
      setRotation(gun15, -0.1487144F, 0F, 0F);
      gun16 = new ModelRenderer(this, 200, 0);
      gun16.addBox(0F, 0F, 0F, 1, 1, 5);
      gun16.setRotationPoint(3.1F, 1F, -5.6F);
      gun16.setTextureSize(64, 32);
      gun16.mirror = true;
      setRotation(gun16, -0.1487144F, 0F, 0F);
      gun17 = new ModelRenderer(this, 200, 0);
      gun17.addBox(0F, 0F, 0F, 1, 1, 5);
      gun17.setRotationPoint(0.9F, -11F, -4F);
      gun17.setTextureSize(64, 32);
      gun17.mirror = true;
      setRotation(gun17, -0.1487144F, 0F, 0F);
      gun18 = new ModelRenderer(this, 200, 0);
      gun18.addBox(0F, 0F, 0F, 1, 1, 5);
      gun18.setRotationPoint(0.9F, -9F, -4.2F);
      gun18.setTextureSize(64, 32);
      gun18.mirror = true;
      setRotation(gun18, -0.1487144F, 0F, 0F);
      gun19 = new ModelRenderer(this, 200, 0);
      gun19.addBox(0F, 0F, 0F, 1, 1, 5);
      gun19.setRotationPoint(0.9F, -7F, -4.5F);
      gun19.setTextureSize(64, 32);
      gun19.mirror = true;
      setRotation(gun19, -0.1487144F, 0F, 0F);
      gun20 = new ModelRenderer(this, 200, 0);
      gun20.addBox(0F, 0F, 0F, 1, 1, 5);
      gun20.setRotationPoint(0.9F, -5F, -4.7F);
      gun20.setTextureSize(64, 32);
      gun20.mirror = true;
      setRotation(gun20, -0.1487144F, 0F, 0F);
      gun21 = new ModelRenderer(this, 200, 0);
      gun21.addBox(0F, 0F, 0F, 1, 1, 5);
      gun21.setRotationPoint(0.9F, -3F, -5F);
      gun21.setTextureSize(64, 32);
      gun21.mirror = true;
      setRotation(gun21, -0.1487144F, 0F, 0F);
      gun22 = new ModelRenderer(this, 200, 0);
      gun22.addBox(0F, 0F, 0F, 1, 1, 5);
      gun22.setRotationPoint(0.9F, -1F, -5.3F);
      gun22.setTextureSize(64, 32);
      gun22.mirror = true;
      setRotation(gun22, -0.1487144F, 0F, 0F);
      gun23 = new ModelRenderer(this, 200, 0);
      gun23.addBox(0F, 0F, 0F, 1, 1, 5);
      gun23.setRotationPoint(0.9F, 1F, -5.6F);
      gun23.setTextureSize(64, 32);
      gun23.mirror = true;
      setRotation(gun23, -0.1487144F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun1.render(f5);
    gun2.render(f5);
    gun3.render(f5);
    gun4.render(f5);
    gun5.render(f5);
    gun6.render(f5);
    gun7.render(f5);
    gun8.render(f5);
    gun9.render(f5);
    gun10.render(f5);
    gun11.render(f5);
    gun12.render(f5);
    gun13.render(f5);
    gun14.render(f5);
    gun15.render(f5);
    gun16.render(f5);
    gun17.render(f5);
    gun18.render(f5);
    gun19.render(f5);
    gun20.render(f5);
    gun21.render(f5);
    gun22.render(f5);
    gun23.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
