// Date: 1/3/2017 9:42:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class NATOG36Mag extends ModelBase
{
  //fields
    ModelRenderer gun133;
    ModelRenderer gun134;
    ModelRenderer gun135;
    ModelRenderer gun136;
    ModelRenderer gun137;
    ModelRenderer gun138;
    ModelRenderer gun139;
    ModelRenderer gun140;
    ModelRenderer gun141;
    ModelRenderer gun142;
  
  public NATOG36Mag()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun133 = new ModelRenderer(this, 0, 50);
      gun133.addBox(0F, 0F, 0F, 1, 8, 2);
      gun133.setRotationPoint(0.8F, -12.4F, -2.8F);
      gun133.setTextureSize(64, 32);
      gun133.mirror = true;
      setRotation(gun133, -0.1487144F, 0F, 0F);
      gun134 = new ModelRenderer(this, 0, 50);
      gun134.addBox(0F, 0F, 0F, 3, 8, 2);
      gun134.setRotationPoint(1.2F, -12.4F, -2.8F);
      gun134.setTextureSize(64, 32);
      gun134.mirror = true;
      setRotation(gun134, -0.1487144F, 0F, 0F);
      gun135 = new ModelRenderer(this, 0, 50);
      gun135.addBox(0F, 0F, 0F, 3, 8, 3);
      gun135.setRotationPoint(1.2F, -11.9F, 0.1F);
      gun135.setTextureSize(64, 32);
      gun135.mirror = true;
      setRotation(gun135, -0.1487144F, 0F, 0F);
      gun136 = new ModelRenderer(this, 0, 50);
      gun136.addBox(0F, 0F, 0F, 1, 8, 3);
      gun136.setRotationPoint(0.8F, -11.9F, 0.1F);
      gun136.setTextureSize(64, 32);
      gun136.mirror = true;
      setRotation(gun136, -0.1487144F, 0F, 0F);
      gun137 = new ModelRenderer(this, 0, 50);
      gun137.addBox(0F, 0F, 0F, 1, 3, 5);
      gun137.setRotationPoint(0.8F, -3.6F, 1.9F);
      gun137.setTextureSize(64, 32);
      gun137.mirror = true;
      setRotation(gun137, -1.896109F, 0F, 0F);
      gun138 = new ModelRenderer(this, 0, 50);
      gun138.addBox(0F, 0F, 0F, 3, 3, 5);
      gun138.setRotationPoint(1.2F, -3.6F, 1.9F);
      gun138.setTextureSize(64, 32);
      gun138.mirror = true;
      setRotation(gun138, -1.896109F, 0F, 0F);
      gun139 = new ModelRenderer(this, 0, 50);
      gun139.addBox(0F, 0F, 0F, 3, 2, 4);
      gun139.setRotationPoint(1.2F, -4.2F, -2.05F);
      gun139.setTextureSize(64, 32);
      gun139.mirror = true;
      setRotation(gun139, -1.896109F, 0F, 0F);
      gun140 = new ModelRenderer(this, 0, 50);
      gun140.addBox(0F, 0F, 0F, 1, 2, 4);
      gun140.setRotationPoint(0.8F, -4.2F, -2.05F);
      gun140.setTextureSize(64, 32);
      gun140.mirror = true;
      setRotation(gun140, -1.896109F, 0F, 0F);
      gun141 = new ModelRenderer(this, 0, 50);
      gun141.addBox(0F, 0F, 0F, 4, 1, 6);
      gun141.setRotationPoint(0.5F, -1.2F, -5.2F);
      gun141.setTextureSize(64, 32);
      gun141.mirror = true;
      setRotation(gun141, -0.2974289F, 0F, 0F);
      gun142 = new ModelRenderer(this, 0, 50);
      gun142.addBox(0F, 0F, 0F, 3, 12, 3);
      gun142.setRotationPoint(1F, -12.4F, -2.5F);
      gun142.setTextureSize(64, 32);
      gun142.mirror = true;
      setRotation(gun142, -0.1858931F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun133.render(f5);
    gun134.render(f5);
    gun135.render(f5);
    gun136.render(f5);
    gun137.render(f5);
    gun138.render(f5);
    gun139.render(f5);
    gun140.render(f5);
    gun141.render(f5);
    gun142.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
