// Date: 2/4/2017 1:36:48 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class PMAG762x39 extends ModelBase
{
  //fields
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
    ModelRenderer mag5;
    ModelRenderer mag6;
    ModelRenderer mag7;
    ModelRenderer mag8;
    ModelRenderer mag9;
    ModelRenderer mag10;
    ModelRenderer mag11;
    ModelRenderer mag12;
    ModelRenderer mag13;
    ModelRenderer mag14;
    ModelRenderer mag15;
    ModelRenderer mag16;
    ModelRenderer mag17;
    ModelRenderer mag18;
    ModelRenderer mag19;
    ModelRenderer mag20;
    ModelRenderer mag21;
    ModelRenderer mag22;
    ModelRenderer mag23;
    ModelRenderer mag24;
    ModelRenderer mag25;
    ModelRenderer mag26;
    ModelRenderer mag27;
    ModelRenderer mag28;
    ModelRenderer mag29;
  
  public PMAG762x39()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      mag1 = new ModelRenderer(this, 0, 0);
      mag1.addBox(0F, 0F, 0F, 4, 6, 7);
      mag1.setRotationPoint(0.5F, -11F, 2F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, -1.784573F, 0F, 0F);
      mag2 = new ModelRenderer(this, 0, 0);
      mag2.addBox(0F, 0F, 0F, 4, 6, 6);
      mag2.setRotationPoint(0.5F, -4.2F, 0.6F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, -1.933288F, 0F, 0F);
      mag3 = new ModelRenderer(this, 0, 0);
      mag3.addBox(0F, 0F, 0F, 4, 6, 8);
      mag3.setRotationPoint(0.5F, 1.4F, -1.5F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, -2.193538F, 0F, 0F);
      mag4 = new ModelRenderer(this, 0, 0);
      mag4.addBox(0F, 0F, 0F, 5, 7, 2);
      mag4.setRotationPoint(0F, 6.3F, -5F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, -2.193538F, 0F, 0F);
      mag5 = new ModelRenderer(this, 0, 0);
      mag5.addBox(0F, 0F, 0F, 3, 7, 7);
      mag5.setRotationPoint(1F, -11F, 2F);
      mag5.setTextureSize(64, 32);
      mag5.mirror = true;
      setRotation(mag5, -1.784573F, 0F, 0F);
      mag6 = new ModelRenderer(this, 0, 0);
      mag6.addBox(0F, 0F, 0F, 3, 6, 6);
      mag6.setRotationPoint(1F, -4F, -0.5F);
      mag6.setTextureSize(64, 32);
      mag6.mirror = true;
      setRotation(mag6, -1.933288F, 0F, 0F);
      mag7 = new ModelRenderer(this, 0, 0);
      mag7.addBox(0F, 0F, 0F, 3, 1, 7);
      mag7.setRotationPoint(1F, -1.5F, -6.7F);
      mag7.setTextureSize(64, 32);
      mag7.mirror = true;
      setRotation(mag7, -2.193538F, 0F, 0F);
      mag8 = new ModelRenderer(this, 0, 0);
      mag8.addBox(0F, 0F, 0F, 1, 1, 3);
      mag8.setRotationPoint(0.3F, -8F, -3.4F);
      mag8.setTextureSize(64, 32);
      mag8.mirror = true;
      setRotation(mag8, -1.784573F, 0F, 0F);
      mag9 = new ModelRenderer(this, 0, 0);
      mag9.addBox(0F, 0F, 0F, 1, 1, 3);
      mag9.setRotationPoint(3.7F, -8F, -3.4F);
      mag9.setTextureSize(64, 32);
      mag9.mirror = true;
      setRotation(mag9, -1.784573F, 0F, 0F);
      mag10 = new ModelRenderer(this, 0, 0);
      mag10.addBox(0F, 0F, 0F, 1, 1, 5);
      mag10.setRotationPoint(0.3F, -5.2F, -4F);
      mag10.setTextureSize(64, 32);
      mag10.mirror = true;
      setRotation(mag10, -1.933288F, 0F, 0F);
      mag11 = new ModelRenderer(this, 0, 0);
      mag11.addBox(0F, 0F, 0F, 1, 1, 5);
      mag11.setRotationPoint(3.7F, -5.2F, -4F);
      mag11.setTextureSize(64, 32);
      mag11.mirror = true;
      setRotation(mag11, -1.933288F, 0F, 0F);
      mag12 = new ModelRenderer(this, 0, 0);
      mag12.addBox(0F, 0F, 0F, 1, 1, 6);
      mag12.setRotationPoint(0.3F, -0.6F, -5.7F);
      mag12.setTextureSize(64, 32);
      mag12.mirror = true;
      setRotation(mag12, -2.193538F, 0F, 0F);
      mag13 = new ModelRenderer(this, 0, 0);
      mag13.addBox(0F, 0F, 0F, 1, 1, 6);
      mag13.setRotationPoint(3.7F, -0.6F, -5.7F);
      mag13.setTextureSize(64, 32);
      mag13.mirror = true;
      setRotation(mag13, -2.193538F, 0F, 0F);
      mag14 = new ModelRenderer(this, 0, 0);
      mag14.addBox(0F, 0F, 0F, 1, 1, 4);
      mag14.setRotationPoint(0.3F, -9F, -0.4F);
      mag14.setTextureSize(64, 32);
      mag14.mirror = true;
      setRotation(mag14, -1.784573F, 0F, 0F);
      mag15 = new ModelRenderer(this, 0, 0);
      mag15.addBox(0F, 0F, 0F, 1, 1, 4);
      mag15.setRotationPoint(3.7F, -9F, -0.4F);
      mag15.setTextureSize(64, 32);
      mag15.mirror = true;
      setRotation(mag15, -1.784573F, 0F, 0F);
      mag16 = new ModelRenderer(this, 0, 0);
      mag16.addBox(0F, 0F, 0F, 1, 1, 5);
      mag16.setRotationPoint(3.7F, -5.2F, -1.2F);
      mag16.setTextureSize(64, 32);
      mag16.mirror = true;
      setRotation(mag16, -1.933288F, 0F, 0F);
      mag17 = new ModelRenderer(this, 0, 0);
      mag17.addBox(0F, 0F, 0F, 1, 1, 5);
      mag17.setRotationPoint(0.3F, -5.2F, -1.2F);
      mag17.setTextureSize(64, 32);
      mag17.mirror = true;
      setRotation(mag17, -1.933288F, 0F, 0F);
      mag18 = new ModelRenderer(this, 0, 0);
      mag18.addBox(0F, 0F, 0F, 1, 1, 4);
      mag18.setRotationPoint(3.7F, -0.6F, -2.9F);
      mag18.setTextureSize(64, 32);
      mag18.mirror = true;
      setRotation(mag18, -2.193538F, 0F, 0F);
      mag19 = new ModelRenderer(this, 0, 0);
      mag19.addBox(0F, 0F, 0F, 1, 1, 4);
      mag19.setRotationPoint(0.3F, -0.6F, -2.9F);
      mag19.setTextureSize(64, 32);
      mag19.mirror = true;
      setRotation(mag19, -2.193538F, 0F, 0F);
      mag20 = new ModelRenderer(this, 0, 0);
      mag20.addBox(0F, 0F, 0F, 1, 5, 1);
      mag20.setRotationPoint(3.7F, -6.5F, 1.1F);
      mag20.setTextureSize(64, 32);
      mag20.mirror = true;
      setRotation(mag20, -1.784573F, 0F, 0F);
      mag21 = new ModelRenderer(this, 0, 0);
      mag21.addBox(0F, 0F, 0F, 4, 5, 1);
      mag21.setRotationPoint(0.3F, -6.5F, 1.1F);
      mag21.setTextureSize(64, 32);
      mag21.mirror = true;
      setRotation(mag21, -1.784573F, 0F, 0F);
      mag22 = new ModelRenderer(this, 0, 0);
      mag22.addBox(0F, 0F, 0F, 1, 5, 1);
      mag22.setRotationPoint(3.7F, -3.5F, 0.5F);
      mag22.setTextureSize(64, 32);
      mag22.mirror = true;
      setRotation(mag22, -1.933288F, 0F, 0F);
      mag23 = new ModelRenderer(this, 0, 0);
      mag23.addBox(0F, 0F, 0F, 4, 5, 1);
      mag23.setRotationPoint(0.3F, -3.5F, 0.5F);
      mag23.setTextureSize(64, 32);
      mag23.mirror = true;
      setRotation(mag23, -1.933288F, 0F, 0F);
      mag24 = new ModelRenderer(this, 0, 0);
      mag24.addBox(0F, 0F, 0F, 1, 5, 1);
      mag24.setRotationPoint(3.7F, -1F, -0.3F);
      mag24.setTextureSize(64, 32);
      mag24.mirror = true;
      setRotation(mag24, -1.933288F, 0F, 0F);
      mag25 = new ModelRenderer(this, 0, 0);
      mag25.addBox(0F, 0F, 0F, 4, 5, 1);
      mag25.setRotationPoint(0.3F, -1F, -0.3F);
      mag25.setTextureSize(64, 32);
      mag25.mirror = true;
      setRotation(mag25, -1.933288F, 0F, 0F);
      mag26 = new ModelRenderer(this, 0, 0);
      mag26.addBox(0F, 0F, 0F, 1, 5, 1);
      mag26.setRotationPoint(3.7F, 2F, -1.7F);
      mag26.setTextureSize(64, 32);
      mag26.mirror = true;
      setRotation(mag26, -2.193538F, 0F, 0F);
      mag27 = new ModelRenderer(this, 0, 0);
      mag27.addBox(0F, 0F, 0F, 4, 5, 1);
      mag27.setRotationPoint(0.3F, 2F, -1.7F);
      mag27.setTextureSize(64, 32);
      mag27.mirror = true;
      setRotation(mag27, -2.193538F, 0F, 0F);
      mag28 = new ModelRenderer(this, 0, 0);
      mag28.addBox(0F, 0F, 0F, 1, 5, 1);
      mag28.setRotationPoint(3.7F, 3.8F, -3F);
      mag28.setTextureSize(64, 32);
      mag28.mirror = true;
      setRotation(mag28, -2.193538F, 0F, 0F);
      mag29 = new ModelRenderer(this, 0, 0);
      mag29.addBox(0F, 0F, 0F, 4, 5, 1);
      mag29.setRotationPoint(0.3F, 3.8F, -3F);
      mag29.setTextureSize(64, 32);
      mag29.mirror = true;
      setRotation(mag29, -2.193538F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
    mag5.render(f5);
    mag6.render(f5);
    mag7.render(f5);
    mag8.render(f5);
    mag9.render(f5);
    mag10.render(f5);
    mag11.render(f5);
    mag12.render(f5);
    mag13.render(f5);
    mag14.render(f5);
    mag15.render(f5);
    mag16.render(f5);
    mag17.render(f5);
    mag18.render(f5);
    mag19.render(f5);
    mag20.render(f5);
    mag21.render(f5);
    mag22.render(f5);
    mag23.render(f5);
    mag24.render(f5);
    mag25.render(f5);
    mag26.render(f5);
    mag27.render(f5);
    mag28.render(f5);
    mag29.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
