// Date: 9/2/2017 1:31:19 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class PPSHRearSight extends ModelBase
{
  //fields
    ModelRenderer RearSight1;
    ModelRenderer RearSight2;
    ModelRenderer RearSight3;
    ModelRenderer RearSight4;
    ModelRenderer RearSight5;
    ModelRenderer RearSight6;
    ModelRenderer RearSight7;
    ModelRenderer RearSight8;
    ModelRenderer RearSight9;
    ModelRenderer RearSight10;
    ModelRenderer RearSight11;
    ModelRenderer RearSight12;
    ModelRenderer RearSight13;
    ModelRenderer RearSight14;
    ModelRenderer RearSight15;
    ModelRenderer RearSight16;
    ModelRenderer RearSight17;
    ModelRenderer RearSight18;
    ModelRenderer RearSight19;
    ModelRenderer RearSight20;
    ModelRenderer RearSight21;
  
  public PPSHRearSight()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      RearSight1 = new ModelRenderer(this, 0, 0);
      RearSight1.addBox(0F, 0F, 0F, 3, 5, 1);
      RearSight1.setRotationPoint(1F, -4F, 0F);
      RearSight1.setTextureSize(128, 64);
      RearSight1.mirror = true;
      setRotation(RearSight1, 0F, 0F, 0F);
      RearSight2 = new ModelRenderer(this, 0, 0);
      RearSight2.addBox(0F, 0F, 0F, 3, 5, 1);
      RearSight2.setRotationPoint(6F, -4F, 0F);
      RearSight2.setTextureSize(128, 64);
      RearSight2.mirror = true;
      setRotation(RearSight2, 0F, 0F, 0F);
      RearSight3 = new ModelRenderer(this, 0, 0);
      RearSight3.addBox(0F, 0F, 0F, 1, 7, 5);
      RearSight3.setRotationPoint(9F, -6F, -2F);
      RearSight3.setTextureSize(128, 64);
      RearSight3.mirror = true;
      setRotation(RearSight3, 0F, 0F, 0F);
      RearSight4 = new ModelRenderer(this, 0, 0);
      RearSight4.addBox(0F, 0F, 0F, 1, 7, 5);
      RearSight4.setRotationPoint(0F, -6F, -2F);
      RearSight4.setTextureSize(128, 64);
      RearSight4.mirror = true;
      setRotation(RearSight4, 0F, 0F, 0F);
      RearSight5 = new ModelRenderer(this, 0, 0);
      RearSight5.addBox(0F, 0F, 0F, 1, 3, 5);
      RearSight5.setRotationPoint(9F, -2F, -7F);
      RearSight5.setTextureSize(128, 64);
      RearSight5.mirror = true;
      setRotation(RearSight5, 0F, 0F, 0F);
      RearSight6 = new ModelRenderer(this, 0, 0);
      RearSight6.addBox(0F, 0F, 0F, 1, 3, 5);
      RearSight6.setRotationPoint(9F, -2F, 3F);
      RearSight6.setTextureSize(128, 64);
      RearSight6.mirror = true;
      setRotation(RearSight6, 0F, 0F, 0F);
      RearSight7 = new ModelRenderer(this, 0, 0);
      RearSight7.addBox(0F, 0F, 0F, 1, 3, 5);
      RearSight7.setRotationPoint(0F, -2F, 3F);
      RearSight7.setTextureSize(128, 64);
      RearSight7.mirror = true;
      setRotation(RearSight7, 0F, 0F, 0F);
      RearSight8 = new ModelRenderer(this, 0, 0);
      RearSight8.addBox(0F, 0F, 0F, 1, 3, 5);
      RearSight8.setRotationPoint(0F, -2F, -7F);
      RearSight8.setTextureSize(128, 64);
      RearSight8.mirror = true;
      setRotation(RearSight8, 0F, 0F, 0F);
      RearSight9 = new ModelRenderer(this, 0, 0);
      RearSight9.addBox(0F, 0F, 0F, 1, 3, 5);
      RearSight9.setRotationPoint(0F, -6F, 3F);
      RearSight9.setTextureSize(128, 64);
      RearSight9.mirror = true;
      setRotation(RearSight9, -1.041001F, 0F, 0F);
      RearSight10 = new ModelRenderer(this, 0, 0);
      RearSight10.addBox(0F, 0F, 0F, 1, 5, 2);
      RearSight10.setRotationPoint(0F, -2F, 8F);
      RearSight10.setTextureSize(128, 64);
      RearSight10.mirror = true;
      setRotation(RearSight10, -2.007645F, 0F, 0F);
      RearSight11 = new ModelRenderer(this, 0, 0);
      RearSight11.addBox(0F, 0F, 0F, 1, 5, 2);
      RearSight11.setRotationPoint(9F, -2F, 8F);
      RearSight11.setTextureSize(128, 64);
      RearSight11.mirror = true;
      setRotation(RearSight11, -2.007645F, 0F, 0F);
      RearSight12 = new ModelRenderer(this, 0, 0);
      RearSight12.addBox(0F, 0F, 0F, 1, 3, 5);
      RearSight12.setRotationPoint(9F, -6F, 3F);
      RearSight12.setTextureSize(128, 64);
      RearSight12.mirror = true;
      setRotation(RearSight12, -1.041001F, 0F, 0F);
      RearSight13 = new ModelRenderer(this, 0, 0);
      RearSight13.addBox(0F, 0F, 0F, 1, 5, 2);
      RearSight13.setRotationPoint(9F, -6F, -2F);
      RearSight13.setTextureSize(128, 64);
      RearSight13.mirror = true;
      setRotation(RearSight13, -0.4833219F, 0F, 0F);
      RearSight14 = new ModelRenderer(this, 0, 0);
      RearSight14.addBox(0F, 0F, 0F, 1, 5, 2);
      RearSight14.setRotationPoint(0F, -6F, -2F);
      RearSight14.setTextureSize(128, 64);
      RearSight14.mirror = true;
      setRotation(RearSight14, -0.4833219F, 0F, 0F);
      RearSight15 = new ModelRenderer(this, 0, 0);
      RearSight15.addBox(0F, 0F, 0F, 1, 2, 5);
      RearSight15.setRotationPoint(0F, -2F, -7F);
      RearSight15.setTextureSize(128, 64);
      RearSight15.mirror = true;
      setRotation(RearSight15, 0.4089647F, 0F, 0F);
      RearSight16 = new ModelRenderer(this, 0, 0);
      RearSight16.addBox(0F, 0F, 0F, 1, 2, 5);
      RearSight16.setRotationPoint(9F, -2F, -7F);
      RearSight16.setTextureSize(128, 64);
      RearSight16.mirror = true;
      setRotation(RearSight16, 0.4089647F, 0F, 0F);
      RearSight17 = new ModelRenderer(this, 0, 0);
      RearSight17.addBox(0F, 0F, 0F, 10, 1, 15);
      RearSight17.setRotationPoint(0F, 1F, -7F);
      RearSight17.setTextureSize(128, 64);
      RearSight17.mirror = true;
      setRotation(RearSight17, 0F, 0F, 0F);
      RearSight18 = new ModelRenderer(this, 0, 0);
      RearSight18.addBox(0F, 0F, 0F, 2, 4, 1);
      RearSight18.setRotationPoint(4F, -2.5F, 0F);
      RearSight18.setTextureSize(128, 64);
      RearSight18.mirror = true;
      setRotation(RearSight18, 0F, 0F, 0F);
      RearSight19 = new ModelRenderer(this, 0, 0);
      RearSight19.addBox(0F, 0F, 0F, 8, 1, 4);
      RearSight19.setRotationPoint(1F, -1.5F, 1F);
      RearSight19.setTextureSize(128, 64);
      RearSight19.mirror = true;
      setRotation(RearSight19, -0.7063936F, 0F, 0F);
      RearSight20 = new ModelRenderer(this, 0, 0);
      RearSight20.addBox(0F, 0F, 0F, 8, 4, 1);
      RearSight20.setRotationPoint(1F, -1.5F, 0F);
      RearSight20.setTextureSize(128, 64);
      RearSight20.mirror = true;
      setRotation(RearSight20, -0.8551081F, 0F, 0F);
      RearSight21 = new ModelRenderer(this, 0, 0);
      RearSight21.addBox(0F, 0F, 0F, 8, 1, 9);
      RearSight21.setRotationPoint(1F, 0F, -4F);
      RearSight21.setTextureSize(128, 64);
      RearSight21.mirror = true;
      setRotation(RearSight21, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    RearSight1.render(f5);
    RearSight2.render(f5);
    RearSight3.render(f5);
    RearSight4.render(f5);
    RearSight5.render(f5);
    RearSight6.render(f5);
    RearSight7.render(f5);
    RearSight8.render(f5);
    RearSight9.render(f5);
    RearSight10.render(f5);
    RearSight11.render(f5);
    RearSight12.render(f5);
    RearSight13.render(f5);
    RearSight14.render(f5);
    RearSight15.render(f5);
    RearSight16.render(f5);
    RearSight17.render(f5);
    RearSight18.render(f5);
    RearSight19.render(f5);
    RearSight20.render(f5);
    RearSight21.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
