// Date: 10/13/2017 6:56:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class PUreticle extends ModelBase
{
  //fields
    ModelRenderer reticle1;
    ModelRenderer reticle2;
    ModelRenderer reticle3;
    ModelRenderer reticle4;
    ModelRenderer reticle5;
  
  public PUreticle()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      reticle1 = new ModelRenderer(this, 0, 0);
      reticle1.addBox(0F, 0F, 0F, 1, 31, 0);
      reticle1.setRotationPoint(7.2F, -10.3F, 0F);
      reticle1.setTextureSize(256, 128);
      reticle1.mirror = true;
      setRotation(reticle1, 0F, 0F, 0F);
      reticle2 = new ModelRenderer(this, 0, 0);
      reticle2.addBox(0F, 0F, 0F, 30, 1, 0);
      reticle2.setRotationPoint(-24F, -11F, 0F);
      reticle2.setTextureSize(256, 128);
      reticle2.mirror = true;
      setRotation(reticle2, 0F, 0F, 0F);
      reticle3 = new ModelRenderer(this, 0, 0);
      reticle3.addBox(0F, 0F, 0F, 30, 1, 0);
      reticle3.setRotationPoint(9F, -11F, 0F);
      reticle3.setTextureSize(256, 128);
      reticle3.mirror = true;
      setRotation(reticle3, 0F, 0F, 0F);
      reticle4 = new ModelRenderer(this, 0, 0);
      reticle4.addBox(0F, 0F, 0F, 1, 1, 0);
      reticle4.setRotationPoint(7.5F, -11F, 0F);
      reticle4.setTextureSize(256, 128);
      reticle4.mirror = true;
      setRotation(reticle4, 0F, 0F, 0.7853982F);
      reticle5 = new ModelRenderer(this, 0, 0);
      reticle5.addBox(0F, 0F, 0F, 1, 31, 0);
      reticle5.setRotationPoint(6.8F, -10.3F, 0F);
      reticle5.setTextureSize(256, 128);
      reticle5.mirror = true;
      setRotation(reticle5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    reticle1.render(f5);
    reticle2.render(f5);
    reticle3.render(f5);
    reticle4.render(f5);
    reticle5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
