// Date: 9/16/2017 9:12:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class R700action extends ModelBase
{
  //fields
    ModelRenderer boltaction1;
    ModelRenderer boltaction2;
    ModelRenderer boltaction3;
    ModelRenderer boltaction4;
    ModelRenderer boltaction5;
    ModelRenderer boltaction6;
    ModelRenderer boltaction7;
    ModelRenderer boltaction8;
    ModelRenderer boltaction9;
    ModelRenderer boltaction10;
    ModelRenderer boltaction11;
    ModelRenderer boltaction12;
    ModelRenderer boltaction13;
    ModelRenderer boltaction14;
    ModelRenderer boltaction15;
    ModelRenderer boltaction16;
    ModelRenderer boltaction17;
    ModelRenderer boltaction18;
    ModelRenderer boltaction19;
    ModelRenderer boltaction20;
    ModelRenderer boltaction21;
    ModelRenderer boltaction22;
    ModelRenderer boltaction23;
    ModelRenderer boltaction24;
    ModelRenderer boltaction25;
    ModelRenderer boltaction26;
    ModelRenderer boltaction27;
    ModelRenderer boltaction28;
    ModelRenderer boltaction29;
    ModelRenderer boltaction30;
    ModelRenderer boltaction31;
    ModelRenderer boltaction32;
    ModelRenderer boltaction33;
    ModelRenderer boltaction34;
  
  public R700action()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      boltaction1 = new ModelRenderer(this, 0, 0);
      boltaction1.addBox(0F, 0F, 0F, 1, 3, 3);
      boltaction1.setRotationPoint(0F, 0F, 0F);
      boltaction1.setTextureSize(64, 32);
      boltaction1.mirror = true;
      setRotation(boltaction1, 0F, 0F, 0F);
      boltaction2 = new ModelRenderer(this, 0, 0);
      boltaction2.addBox(0F, 0F, 0F, 3, 1, 3);
      boltaction2.setRotationPoint(-1F, 1F, 0F);
      boltaction2.setTextureSize(64, 32);
      boltaction2.mirror = true;
      setRotation(boltaction2, 0F, 0F, 0F);
      boltaction3 = new ModelRenderer(this, 0, 0);
      boltaction3.addBox(0F, 0F, 0F, 1, 1, 3);
      boltaction3.setRotationPoint(1F, 0F, 0F);
      boltaction3.setTextureSize(64, 32);
      boltaction3.mirror = true;
      setRotation(boltaction3, 0F, 0F, 0.7853982F);
      boltaction4 = new ModelRenderer(this, 0, 0);
      boltaction4.addBox(0F, 0F, 0F, 1, 1, 3);
      boltaction4.setRotationPoint(2F, 1F, 0F);
      boltaction4.setTextureSize(64, 32);
      boltaction4.mirror = true;
      setRotation(boltaction4, 0F, 0F, 2.356194F);
      boltaction5 = new ModelRenderer(this, 0, 0);
      boltaction5.addBox(0F, 0F, 0F, 1, 1, 3);
      boltaction5.setRotationPoint(0F, 0F, 0F);
      boltaction5.setTextureSize(64, 32);
      boltaction5.mirror = true;
      setRotation(boltaction5, 0F, 0F, 0.7853982F);
      boltaction6 = new ModelRenderer(this, 0, 0);
      boltaction6.addBox(0F, 0F, 0F, 1, 1, 3);
      boltaction6.setRotationPoint(-1F, 1F, 0F);
      boltaction6.setTextureSize(64, 32);
      boltaction6.mirror = true;
      setRotation(boltaction6, 0F, 0F, -0.7853982F);
      boltaction7 = new ModelRenderer(this, 0, 0);
      boltaction7.addBox(0F, 0F, 0F, 1, 1, 3);
      boltaction7.setRotationPoint(-1F, 2F, 0F);
      boltaction7.setTextureSize(64, 32);
      boltaction7.mirror = true;
      setRotation(boltaction7, 0F, 0F, -0.7853982F);
      boltaction8 = new ModelRenderer(this, 0, 0);
      boltaction8.addBox(0F, 0F, 0F, 1, 1, 3);
      boltaction8.setRotationPoint(2F, 2F, 0F);
      boltaction8.setTextureSize(64, 32);
      boltaction8.mirror = true;
      setRotation(boltaction8, 0F, 0F, 2.356194F);
      boltaction9 = new ModelRenderer(this, 0, 0);
      boltaction9.addBox(0F, 0F, 0F, 1, 1, 3);
      boltaction9.setRotationPoint(1F, 3F, 0F);
      boltaction9.setTextureSize(64, 32);
      boltaction9.mirror = true;
      setRotation(boltaction9, 0F, 0F, -2.356194F);
      boltaction10 = new ModelRenderer(this, 0, 0);
      boltaction10.addBox(0F, 0F, 0F, 1, 1, 3);
      boltaction10.setRotationPoint(0F, 3F, 0F);
      boltaction10.setTextureSize(64, 32);
      boltaction10.mirror = true;
      setRotation(boltaction10, 0F, 0F, -2.356194F);
      boltaction11 = new ModelRenderer(this, 0, 0);
      boltaction11.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction11.setRotationPoint(0F, 0.2F, -24F);
      boltaction11.setTextureSize(64, 32);
      boltaction11.mirror = true;
      setRotation(boltaction11, 0F, 0F, 0F);
      boltaction12 = new ModelRenderer(this, 0, 0);
      boltaction12.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction12.setRotationPoint(0F, 1.8F, -24F);
      boltaction12.setTextureSize(64, 32);
      boltaction12.mirror = true;
      setRotation(boltaction12, 0F, 0F, 0F);
      boltaction13 = new ModelRenderer(this, 0, 0);
      boltaction13.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction13.setRotationPoint(-0.8F, 1F, -24F);
      boltaction13.setTextureSize(64, 32);
      boltaction13.mirror = true;
      setRotation(boltaction13, 0F, 0F, 0F);
      boltaction14 = new ModelRenderer(this, 0, 0);
      boltaction14.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction14.setRotationPoint(0.8F, 1F, -24F);
      boltaction14.setTextureSize(64, 32);
      boltaction14.mirror = true;
      setRotation(boltaction14, 0F, 0F, 0F);
      boltaction15 = new ModelRenderer(this, 0, 0);
      boltaction15.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction15.setRotationPoint(1F, 0.2F, -24F);
      boltaction15.setTextureSize(64, 32);
      boltaction15.mirror = true;
      setRotation(boltaction15, 0F, 0F, 0.7853982F);
      boltaction16 = new ModelRenderer(this, 0, 0);
      boltaction16.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction16.setRotationPoint(0F, 0.2F, -24F);
      boltaction16.setTextureSize(64, 32);
      boltaction16.mirror = true;
      setRotation(boltaction16, 0F, 0F, 0.7853982F);
      boltaction17 = new ModelRenderer(this, 0, 0);
      boltaction17.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction17.setRotationPoint(1.8F, 1F, -24F);
      boltaction17.setTextureSize(64, 32);
      boltaction17.mirror = true;
      setRotation(boltaction17, 0F, 0F, 2.356194F);
      boltaction18 = new ModelRenderer(this, 0, 0);
      boltaction18.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction18.setRotationPoint(-0.8F, 1F, -24F);
      boltaction18.setTextureSize(64, 32);
      boltaction18.mirror = true;
      setRotation(boltaction18, 0F, 0F, -0.7853982F);
      boltaction19 = new ModelRenderer(this, 0, 0);
      boltaction19.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction19.setRotationPoint(-0.8F, 2F, -24F);
      boltaction19.setTextureSize(64, 32);
      boltaction19.mirror = true;
      setRotation(boltaction19, 0F, 0F, -0.7853982F);
      boltaction20 = new ModelRenderer(this, 0, 0);
      boltaction20.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction20.setRotationPoint(1.8F, 2F, -24F);
      boltaction20.setTextureSize(64, 32);
      boltaction20.mirror = true;
      setRotation(boltaction20, 0F, 0F, 2.356194F);
      boltaction21 = new ModelRenderer(this, 0, 0);
      boltaction21.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction21.setRotationPoint(1F, 2.8F, -24F);
      boltaction21.setTextureSize(64, 32);
      boltaction21.mirror = true;
      setRotation(boltaction21, 0F, 0F, -2.356194F);
      boltaction22 = new ModelRenderer(this, 0, 0);
      boltaction22.addBox(0F, 0F, 0F, 1, 1, 30);
      boltaction22.setRotationPoint(0F, 2.8F, -24F);
      boltaction22.setTextureSize(64, 32);
      boltaction22.mirror = true;
      setRotation(boltaction22, 0F, 0F, -2.356194F);
      boltaction23 = new ModelRenderer(this, 0, 0);
      boltaction23.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction23.setRotationPoint(0F, 0.3F, 5.1F);
      boltaction23.setTextureSize(64, 32);
      boltaction23.mirror = true;
      setRotation(boltaction23, 0F, 0F, 0F);
      boltaction24 = new ModelRenderer(this, 0, 0);
      boltaction24.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction24.setRotationPoint(0F, 1.7F, 5.1F);
      boltaction24.setTextureSize(64, 32);
      boltaction24.mirror = true;
      setRotation(boltaction24, 0F, 0F, 0F);
      boltaction25 = new ModelRenderer(this, 0, 0);
      boltaction25.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction25.setRotationPoint(0.7F, 1F, 5.1F);
      boltaction25.setTextureSize(64, 32);
      boltaction25.mirror = true;
      setRotation(boltaction25, 0F, 0F, 0F);
      boltaction26 = new ModelRenderer(this, 0, 0);
      boltaction26.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction26.setRotationPoint(-0.7F, 1F, 5.1F);
      boltaction26.setTextureSize(64, 32);
      boltaction26.mirror = true;
      setRotation(boltaction26, 0F, 0F, 0F);
      boltaction27 = new ModelRenderer(this, 0, 0);
      boltaction27.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction27.setRotationPoint(1.7F, 1F, 5.1F);
      boltaction27.setTextureSize(64, 32);
      boltaction27.mirror = true;
      setRotation(boltaction27, 0F, 0F, 2.356194F);
      boltaction28 = new ModelRenderer(this, 0, 0);
      boltaction28.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction28.setRotationPoint(0F, 0.3F, 5.1F);
      boltaction28.setTextureSize(64, 32);
      boltaction28.mirror = true;
      setRotation(boltaction28, 0F, 0F, 0.7853982F);
      boltaction29 = new ModelRenderer(this, 0, 0);
      boltaction29.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction29.setRotationPoint(-0.7F, 2F, 5.1F);
      boltaction29.setTextureSize(64, 32);
      boltaction29.mirror = true;
      setRotation(boltaction29, 0F, 0F, -0.7853982F);
      boltaction30 = new ModelRenderer(this, 0, 0);
      boltaction30.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction30.setRotationPoint(0.3F, 2F, 5.1F);
      boltaction30.setTextureSize(64, 32);
      boltaction30.mirror = true;
      setRotation(boltaction30, 0F, 0F, -0.7853982F);
      boltaction31 = new ModelRenderer(this, 0, 0);
      boltaction31.addBox(0F, 0F, 0F, 1, 1, 1);
      boltaction31.setRotationPoint(0F, 1F, 5.1F);
      boltaction31.setTextureSize(64, 32);
      boltaction31.mirror = true;
      setRotation(boltaction31, 0F, 0F, 0F);
      boltaction32 = new ModelRenderer(this, 0, 0);
      boltaction32.addBox(0F, 0F, 0F, 2, 2, 2);
      boltaction32.setRotationPoint(-1.5F, 1F, 0F);
      boltaction32.setTextureSize(64, 32);
      boltaction32.mirror = true;
      setRotation(boltaction32, 0F, 0F, 0F);
      boltaction33 = new ModelRenderer(this, 0, 0);
      boltaction33.addBox(0F, 0F, 0F, 6, 1, 2);
      boltaction33.setRotationPoint(-0.5F, 3F, 0F);
      boltaction33.setTextureSize(64, 32);
      boltaction33.mirror = true;
      setRotation(boltaction33, 0F, 0F, 2.305074F);
      boltaction34 = new ModelRenderer(this, 0, 0);
      boltaction34.addBox(0F, 0F, 0F, 2, 1, 3);
      boltaction34.setRotationPoint(-3.5F, 6F, -0.5F);
      boltaction34.setTextureSize(64, 32);
      boltaction34.mirror = true;
      setRotation(boltaction34, 0F, 0F, 2.305074F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    boltaction1.render(f5);
    boltaction2.render(f5);
    boltaction3.render(f5);
    boltaction4.render(f5);
    boltaction5.render(f5);
    boltaction6.render(f5);
    boltaction7.render(f5);
    boltaction8.render(f5);
    boltaction9.render(f5);
    boltaction10.render(f5);
    boltaction11.render(f5);
    boltaction12.render(f5);
    boltaction13.render(f5);
    boltaction14.render(f5);
    boltaction15.render(f5);
    boltaction16.render(f5);
    boltaction17.render(f5);
    boltaction18.render(f5);
    boltaction19.render(f5);
    boltaction20.render(f5);
    boltaction21.render(f5);
    boltaction22.render(f5);
    boltaction23.render(f5);
    boltaction24.render(f5);
    boltaction25.render(f5);
    boltaction26.render(f5);
    boltaction27.render(f5);
    boltaction28.render(f5);
    boltaction29.render(f5);
    boltaction30.render(f5);
    boltaction31.render(f5);
    boltaction32.render(f5);
    boltaction33.render(f5);
    boltaction34.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
}
