// Date: 11/29/2015 6:18:48 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import com.vicmatskiv.weaponlib.ModelWithAttachments;

public class Remington870 extends ModelWithAttachments
{
  //fields
    ModelRenderer gun1;
    ModelRenderer gun2;
    ModelRenderer gun3;
    ModelRenderer gun4;
    ModelRenderer gun5;
    ModelRenderer gun6;
    ModelRenderer gun7;
    ModelRenderer gun8;
    ModelRenderer gun9;
    ModelRenderer gun10;
    ModelRenderer gun11;
    ModelRenderer gun12;
    ModelRenderer gun13;
    ModelRenderer gun14;
    ModelRenderer gun15;
    ModelRenderer gun16;
    ModelRenderer gun17;
    ModelRenderer gun18;
    ModelRenderer gun19;
    ModelRenderer gun20;
    ModelRenderer gun21;
    ModelRenderer gun22;
    ModelRenderer gun23;
    ModelRenderer gun24;
    ModelRenderer gun25;
    ModelRenderer gun26;
    ModelRenderer gun27;
    ModelRenderer gun28;
    ModelRenderer gun29;
  
  public Remington870()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun1 = new ModelRenderer(this, 0, 0);
      gun1.addBox(0F, 0F, 0F, 5, 2, 25);
      gun1.setRotationPoint(0F, -17F, -10F);
      gun1.setTextureSize(64, 32);
      gun1.mirror = true;
      setRotation(gun1, 0F, 0F, 0F);
      gun2 = new ModelRenderer(this, 0, 0);
      gun2.addBox(0F, 0F, 0F, 3, 3, 1);
      gun2.setRotationPoint(1F, -15F, 18F);
      gun2.setTextureSize(64, 32);
      gun2.mirror = true;
      setRotation(gun2, -2.379431F, 0F, 0F);
      gun3 = new ModelRenderer(this, 0, 0);
      gun3.addBox(0F, 0F, 0F, 1, 3, 3);
      gun3.setRotationPoint(0.6F, -15F, 18F);
      gun3.setTextureSize(64, 32);
      gun3.mirror = true;
      setRotation(gun3, -2.379431F, 0F, 0F);
      gun4 = new ModelRenderer(this, 0, 0);
      gun4.addBox(0F, 0F, 0F, 1, 3, 3);
      gun4.setRotationPoint(3.5F, -15F, 18F);
      gun4.setTextureSize(64, 32);
      gun4.mirror = true;
      setRotation(gun4, -2.379431F, 0F, 0F);
      gun5 = new ModelRenderer(this, 0, 0);
      gun5.addBox(0F, 0F, 0F, 3, 1, 26);
      gun5.setRotationPoint(1F, -17.2F, -10.1F);
      gun5.setTextureSize(64, 32);
      gun5.mirror = true;
      setRotation(gun5, 0F, 0F, 0F);
      gun6 = new ModelRenderer(this, 0, 0);
      gun6.addBox(0F, 0F, 0F, 1, 1, 26);
      gun6.setRotationPoint(0.6F, -17.2F, -10.1F);
      gun6.setTextureSize(64, 32);
      gun6.mirror = true;
      setRotation(gun6, 0F, 0F, 0F);
      gun7 = new ModelRenderer(this, 0, 0);
      gun7.addBox(0F, 0F, 0F, 1, 1, 26);
      gun7.setRotationPoint(3.5F, -17.2F, -10.1F);
      gun7.setTextureSize(64, 32);
      gun7.mirror = true;
      setRotation(gun7, 0F, 0F, 0F);
      gun8 = new ModelRenderer(this, 0, 0);
      gun8.addBox(0F, 0F, 0F, 4, 1, 25);
      gun8.setRotationPoint(0.5F, -12.15F, -10.1F);
      gun8.setTextureSize(64, 32);
      gun8.mirror = true;
      setRotation(gun8, 0F, 0F, 0F);
      gun9 = new ModelRenderer(this, 0, 50);
      gun9.addBox(0F, 0F, 0F, 3, 3, 14);
      gun9.setRotationPoint(1F, -2F, 35.4F);
      gun9.setTextureSize(64, 32);
      gun9.mirror = true;
      setRotation(gun9, 2.825574F, 0F, 0F);
      gun10 = new ModelRenderer(this, 0, 0);
      gun10.addBox(0F, 0F, 0F, 3, 1, 2);
      gun10.setRotationPoint(1F, -7.5F, 10F);
      gun10.setTextureSize(64, 32);
      gun10.mirror = true;
      setRotation(gun10, -2.41661F, 0F, 0F);
      gun11 = new ModelRenderer(this, 0, 0);
      gun11.addBox(0F, 0F, 0F, 3, 1, 5);
      gun11.setRotationPoint(1F, -7.15F, 3.5F);
      gun11.setTextureSize(64, 32);
      gun11.mirror = true;
      setRotation(gun11, 0F, 0F, 0F);
      gun12 = new ModelRenderer(this, 0, 0);
      gun12.addBox(0F, 0F, 0F, 2, 3, 1);
      gun12.setRotationPoint(1.5F, -11.5F, 8F);
      gun12.setTextureSize(64, 32);
      gun12.mirror = true;
      setRotation(gun12, -0.5576792F, 0F, 0F);
      gun13 = new ModelRenderer(this, 0, 0);
      gun13.addBox(0F, 0F, 0F, 2, 1, 3);
      gun13.setRotationPoint(1.5F, -11.8F, 7F);
      gun13.setTextureSize(64, 32);
      gun13.mirror = true;
      setRotation(gun13, -0.3346075F, 0F, 0F);
      gun14 = new ModelRenderer(this, 0, 0);
      gun14.addBox(0F, 0F, 0F, 2, 2, 30);
      gun14.setRotationPoint(2F, -17.5F, -40F);
      gun14.setTextureSize(64, 32);
      gun14.mirror = true;
      setRotation(gun14, 0F, 0F, 0F);
      gun15 = new ModelRenderer(this, 0, 50);
      gun15.addBox(0F, 0F, 0F, 3, 4, 5);
      gun15.setRotationPoint(1F, -11F, 9F);
      gun15.setTextureSize(64, 32);
      gun15.mirror = true;
      setRotation(gun15, 0.1115358F, 0F, 0F);
      gun16 = new ModelRenderer(this, 0, 0);
      gun16.addBox(0F, 0F, 0F, 5, 3, 28);
      gun16.setRotationPoint(0F, -15F, -10F);
      gun16.setTextureSize(64, 32);
      gun16.mirror = true;
      setRotation(gun16, 0F, 0F, 0F);
      gun17 = new ModelRenderer(this, 0, 50);
      gun17.addBox(0F, 0F, 0F, 3, 6, 3);
      gun17.setRotationPoint(1F, -12.7F, 16F);
      gun17.setTextureSize(64, 32);
      gun17.mirror = true;
      setRotation(gun17, 0.9666439F, 0F, 0F);
      gun18 = new ModelRenderer(this, 0, 50);
      gun18.addBox(0F, 0F, 0F, 3, 25, 5);
      gun18.setRotationPoint(1F, -8F, 12F);
      gun18.setTextureSize(64, 32);
      gun18.mirror = true;
      setRotation(gun18, 1.449966F, 0F, 0F);
      gun19 = new ModelRenderer(this, 0, 50);
      gun19.addBox(0F, 0F, 0F, 3, 1, 3);
      gun19.setRotationPoint(1F, -2F, 35.4F);
      gun19.setTextureSize(64, 32);
      gun19.mirror = true;
      setRotation(gun19, 1.449966F, 0F, 0F);
      gun20 = new ModelRenderer(this, 0, 50);
      gun20.addBox(0F, 0F, 0F, 3, 5, 5);
      gun20.setRotationPoint(1F, -7F, 9F);
      gun20.setTextureSize(64, 32);
      gun20.mirror = true;
      setRotation(gun20, 1.189716F, 0F, 0F);
      gun21 = new ModelRenderer(this, 0, 50);
      gun21.addBox(0F, 0F, 0F, 3, 6, 8);
      gun21.setRotationPoint(1F, -7F, 12F);
      gun21.setTextureSize(64, 32);
      gun21.mirror = true;
      setRotation(gun21, 0.6320364F, 0F, 0F);
      gun22 = new ModelRenderer(this, 0, 0);
      gun22.addBox(0F, 0F, 0F, 4, 1, 25);
      gun22.setRotationPoint(0.5F, -18.15F, -10.1F);
      gun22.setTextureSize(64, 32);
      gun22.mirror = true;
      setRotation(gun22, 0F, 0F, 0F);
      gun23 = new ModelRenderer(this, 0, 0);
      gun23.addBox(0F, 0F, 0F, 2, 2, 30);
      gun23.setRotationPoint(2F, -17.5F, -40F);
      gun23.setTextureSize(64, 32);
      gun23.mirror = true;
      setRotation(gun23, 0F, 0F, 0F);
      gun24 = new ModelRenderer(this, 0, 0);
      gun24.addBox(0F, 0F, 0F, 2, 2, 19);
      gun24.setRotationPoint(2F, -14.5F, -29F);
      gun24.setTextureSize(64, 32);
      gun24.mirror = true;
      setRotation(gun24, 0F, 0F, 0F);
      gun25 = new ModelRenderer(this, 0, 0);
      gun25.addBox(0F, 0F, 0F, 1, 3, 16);
      gun25.setRotationPoint(1F, -15F, -28F);
      gun25.setTextureSize(64, 32);
      gun25.mirror = true;
      setRotation(gun25, 0F, 0F, 0F);
      gun26 = new ModelRenderer(this, 0, 0);
      gun26.addBox(0F, 0F, 0F, 1, 3, 16);
      gun26.setRotationPoint(4F, -15F, -28F);
      gun26.setTextureSize(64, 32);
      gun26.mirror = true;
      setRotation(gun26, 0F, 0F, 0F);
      gun27 = new ModelRenderer(this, 0, 0);
      gun27.addBox(0F, 0F, 0F, 2, 2, 16);
      gun27.setRotationPoint(2F, -13F, -28F);
      gun27.setTextureSize(64, 32);
      gun27.mirror = true;
      setRotation(gun27, 0F, 0F, 0F);
      gun28 = new ModelRenderer(this, 0, 0);
      gun28.addBox(0F, 0F, 0F, 3, 2, 13);
      gun28.setRotationPoint(1.5F, -16F, -28F);
      gun28.setTextureSize(64, 32);
      gun28.mirror = true;
      setRotation(gun28, 0F, 0F, 0F);
      gun29 = new ModelRenderer(this, 0, 0);
      gun29.addBox(0F, 0F, 0F, 3, 2, 3);
      gun29.setRotationPoint(1.5F, -15.5F, -15F);
      gun29.setTextureSize(64, 32);
      gun29.mirror = true;
      setRotation(gun29, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun1.render(f5);
    gun2.render(f5);
    gun3.render(f5);
    gun4.render(f5);
    gun5.render(f5);
    gun6.render(f5);
    gun7.render(f5);
    gun8.render(f5);
    gun9.render(f5);
    gun10.render(f5);
    gun11.render(f5);
    gun12.render(f5);
    gun13.render(f5);
    gun14.render(f5);
    gun15.render(f5);
    gun16.render(f5);
    gun17.render(f5);
    gun18.render(f5);
    gun19.render(f5);
    gun20.render(f5);
    gun21.render(f5);
    gun22.render(f5);
    gun23.render(f5);
    gun24.render(f5);
    gun25.render(f5);
    gun26.render(f5);
    gun27.render(f5);
    gun28.render(f5);
    gun29.render(f5);
  }

}
