// Date: 7/17/2017 9:56:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import com.vicmatskiv.weaponlib.ModelWithAttachments;

public class Remington870TacPump extends ModelBase
{
  //fields
    
    ModelRenderer pump1;
    ModelRenderer pump2;
    ModelRenderer pump3;
    ModelRenderer pump4;
    ModelRenderer pump5;
    ModelRenderer pump6;
    ModelRenderer pump7;
    ModelRenderer pump8;
    ModelRenderer pump9;
    ModelRenderer pump10;
    ModelRenderer pump11;
    ModelRenderer pump12;
    ModelRenderer pump13;
    ModelRenderer pump14;
    ModelRenderer pump15;
    ModelRenderer pump16;
  
  public Remington870TacPump()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      pump1 = new ModelRenderer(this, 0, 0);
      pump1.addBox(0F, 0F, 0F, 4, 1, 13);
      pump1.setRotationPoint(-3F, -2.6F, -39F);
      pump1.setTextureSize(64, 32);
      pump1.mirror = true;
      setRotation(pump1, 0F, 0F, 0F);
      pump2 = new ModelRenderer(this, 0, 0);
      pump2.addBox(0F, 0F, 0F, 1, 1, 13);
      pump2.setRotationPoint(-1.5F, -1F, -39F);
      pump2.setTextureSize(64, 32);
      pump2.mirror = true;
      setRotation(pump2, 0F, 0F, 0F);
      pump3 = new ModelRenderer(this, 0, 0);
      pump3.addBox(0F, 0F, 0F, 1, 1, 13);
      pump3.setRotationPoint(-3F, -1.6F, -39F);
      pump3.setTextureSize(64, 32);
      pump3.mirror = true;
      setRotation(pump3, 0F, 0F, -0.7853982F);
      pump4 = new ModelRenderer(this, 0, 0);
      pump4.addBox(0F, 0F, 0F, 2, 1, 13);
      pump4.setRotationPoint(-1.5F, 0F, -39F);
      pump4.setTextureSize(64, 32);
      pump4.mirror = true;
      setRotation(pump4, 0F, 0F, -2.356194F);
      pump5 = new ModelRenderer(this, 0, 0);
      pump5.addBox(0F, 0F, 0F, 1, 1, 13);
      pump5.setRotationPoint(1F, -1.6F, -39F);
      pump5.setTextureSize(64, 32);
      pump5.mirror = true;
      setRotation(pump5, 0F, 0F, 2.356194F);
      pump6 = new ModelRenderer(this, 0, 0);
      pump6.addBox(0F, 0F, 0F, 1, 2, 13);
      pump6.setRotationPoint(-0.5F, 0F, -39F);
      pump6.setTextureSize(64, 32);
      pump6.mirror = true;
      setRotation(pump6, 0F, 0F, -2.391101F);
      pump7 = new ModelRenderer(this, 0, 0);
      pump7.addBox(0F, 0F, 0F, 4, 2, 2);
      pump7.setRotationPoint(-3F, -4F, -28F);
      pump7.setTextureSize(64, 32);
      pump7.mirror = true;
      setRotation(pump7, 0F, 0F, 0F);
      pump8 = new ModelRenderer(this, 0, 0);
      pump8.addBox(0F, 0F, 0F, 4, 1, 11);
      pump8.setRotationPoint(-3F, -3F, -39F);
      pump8.setTextureSize(64, 32);
      pump8.mirror = true;
      setRotation(pump8, 0F, 0F, 0F);
      pump9 = new ModelRenderer(this, 0, 0);
      pump9.addBox(0F, 0F, 0F, 1, 1, 11);
      pump9.setRotationPoint(-3F, -3F, -39F);
      pump9.setTextureSize(64, 32);
      pump9.mirror = true;
      setRotation(pump9, 0F, 0F, -0.7853982F);
      pump10 = new ModelRenderer(this, 0, 0);
      pump10.addBox(0F, 0F, 0F, 1, 1, 11);
      pump10.setRotationPoint(1F, -3F, -39F);
      pump10.setTextureSize(64, 32);
      pump10.mirror = true;
      setRotation(pump10, 0F, 0F, 2.356194F);
      pump11 = new ModelRenderer(this, 0, 0);
      pump11.addBox(0F, 0F, 0F, 3, 2, 12);
      pump11.setRotationPoint(-2.5F, -4F, -39F);
      pump11.setTextureSize(64, 32);
      pump11.mirror = true;
      setRotation(pump11, 0F, 0F, 0F);
      pump12 = new ModelRenderer(this, 200, 0);
      pump12.addBox(0F, 0F, 0F, 1, 2, 4);
      pump12.setRotationPoint(-0.5F, 0.1F, -32F);
      pump12.setTextureSize(64, 32);
      pump12.mirror = true;
      setRotation(pump12, 0F, 0F, -2.391101F);
      pump13 = new ModelRenderer(this, 200, 0);
      pump13.addBox(0F, 0F, 0F, 2, 1, 4);
      pump13.setRotationPoint(-1.5F, 0.1F, -32F);
      pump13.setTextureSize(64, 32);
      pump13.mirror = true;
      setRotation(pump13, 0F, 0F, -2.356194F);
      pump14 = new ModelRenderer(this, 200, 0);
      pump14.addBox(0F, 0F, 0F, 1, 1, 4);
      pump14.setRotationPoint(-1.5F, -0.9F, -32F);
      pump14.setTextureSize(64, 32);
      pump14.mirror = true;
      setRotation(pump14, 0F, 0F, 0F);
      pump15 = new ModelRenderer(this, 0, 0);
      pump15.addBox(0F, 0F, 0F, 1, 1, 3);
      pump15.setRotationPoint(-3.1F, -2.8F, -36F);
      pump15.setTextureSize(64, 32);
      pump15.mirror = true;
      setRotation(pump15, 0F, 0F, 0F);
      pump16 = new ModelRenderer(this, 0, 0);
      pump16.addBox(0F, 0F, 0F, 1, 1, 3);
      pump16.setRotationPoint(0.1F, -2.8F, -36F);
      pump16.setTextureSize(64, 32);
      pump16.mirror = true;
      setRotation(pump16, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    pump1.render(f5);
    pump2.render(f5);
    pump3.render(f5);
    pump4.render(f5);
    pump5.render(f5);
    pump6.render(f5);
    pump7.render(f5);
    pump8.render(f5);
    pump9.render(f5);
    pump10.render(f5);
    pump11.render(f5);
    pump12.render(f5);
    pump13.render(f5);
    pump14.render(f5);
    pump15.render(f5);
    pump16.render(f5);
  }
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
