// Date: 7/16/2017 11:47:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import com.vicmatskiv.weaponlib.ModelWithAttachments;

public class RemingtonPump extends ModelBase
{
  //fields
   
    ModelRenderer pump1;
    ModelRenderer pump2;
    ModelRenderer pump3;
    ModelRenderer pump4;
    ModelRenderer pump5;
    ModelRenderer pump6;
    ModelRenderer pump7;
    ModelRenderer pump8;
    ModelRenderer pump9;
    ModelRenderer pump10;
    ModelRenderer pump11;
    ModelRenderer pump12;
    ModelRenderer pump13;
    ModelRenderer pump14;
    ModelRenderer pump15;
    ModelRenderer pump16;
  
  public RemingtonPump()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      pump1 = new ModelRenderer(this, 250, 0);
      pump1.addBox(0F, 0F, 0F, 1, 1, 20);
      pump1.setRotationPoint(-2.8F, -3F, -39F);
      pump1.setTextureSize(64, 32);
      pump1.mirror = true;
      setRotation(pump1, 0F, 0F, 0F);
      pump2 = new ModelRenderer(this, 250, 0);
      pump2.addBox(0F, 0F, 0F, 1, 1, 20);
      pump2.setRotationPoint(-0.2F, -3F, -39F);
      pump2.setTextureSize(64, 32);
      pump2.mirror = true;
      setRotation(pump2, 0F, 0F, 0F);
      pump3 = new ModelRenderer(this, 250, 0);
      pump3.addBox(0F, 0F, 0F, 2, 1, 20);
      pump3.setRotationPoint(-2F, -1.2F, -39F);
      pump3.setTextureSize(64, 32);
      pump3.mirror = true;
      setRotation(pump3, 0F, 0F, 0F);
      pump4 = new ModelRenderer(this, 250, 0);
      pump4.addBox(0F, 0F, 0F, 2, 1, 20);
      pump4.setRotationPoint(0.8F, -2F, -39F);
      pump4.setTextureSize(64, 32);
      pump4.mirror = true;
      setRotation(pump4, 0F, 0F, 2.007645F);
      pump5 = new ModelRenderer(this, 250, 0);
      pump5.addBox(0F, 0F, 0F, 1, 2, 20);
      pump5.setRotationPoint(-2.8F, -2F, -39F);
      pump5.setTextureSize(64, 32);
      pump5.mirror = true;
      setRotation(pump5, 0F, 0F, -0.4089647F);
      pump6 = new ModelRenderer(this, 250, 0);
      pump6.addBox(0F, 0F, 0F, 3, 2, 15);
      pump6.setRotationPoint(-2.5F, -4.4F, -39F);
      pump6.setTextureSize(64, 32);
      pump6.mirror = true;
      setRotation(pump6, 0F, 0F, 0F);
      pump7 = new ModelRenderer(this, 250, 0);
      pump7.addBox(0F, 0F, 0F, 1, 2, 1);
      pump7.setRotationPoint(-2.8F, -4.4F, -25F);
      pump7.setTextureSize(64, 32);
      pump7.mirror = true;
      setRotation(pump7, 0F, 0F, 0F);
      pump8 = new ModelRenderer(this, 250, 0);
      pump8.addBox(0F, 0F, 0F, 1, 2, 1);
      pump8.setRotationPoint(-0.2F, -4.4F, -25F);
      pump8.setTextureSize(64, 32);
      pump8.mirror = true;
      setRotation(pump8, 0F, 0F, 0F);
      pump9 = new ModelRenderer(this, 250, 0);
      pump9.addBox(0F, 0F, 0F, 1, 1, 4);
      pump9.setRotationPoint(-2.8F, -4.4F, -24F);
      pump9.setTextureSize(64, 32);
      pump9.mirror = true;
      setRotation(pump9, -0.3717861F, 0F, 0F);
      pump10 = new ModelRenderer(this, 250, 0);
      pump10.addBox(0F, 0F, 0F, 1, 1, 4);
      pump10.setRotationPoint(-0.2F, -4.4F, -24F);
      pump10.setTextureSize(64, 32);
      pump10.mirror = true;
      setRotation(pump10, -0.3717861F, 0F, 0F);
      pump11 = new ModelRenderer(this, 250, 0);
      pump11.addBox(0F, 0F, 0F, 1, 1, 1);
      pump11.setRotationPoint(-2.8F, -3.5F, -24F);
      pump11.setTextureSize(64, 32);
      pump11.mirror = true;
      setRotation(pump11, 0F, 0F, 0F);
      pump12 = new ModelRenderer(this, 250, 0);
      pump12.addBox(0F, 0F, 0F, 1, 1, 1);
      pump12.setRotationPoint(-0.2F, -3.5F, -24F);
      pump12.setTextureSize(64, 32);
      pump12.mirror = true;
      setRotation(pump12, 0F, 0F, 0F);
      pump13 = new ModelRenderer(this, 250, 0);
      pump13.addBox(0F, 0F, 0F, 1, 1, 1);
      pump13.setRotationPoint(-0.2F, -4.4F, -25F);
      pump13.setTextureSize(64, 32);
      pump13.mirror = true;
      setRotation(pump13, -0.6320364F, 0F, 0F);
      pump14 = new ModelRenderer(this, 250, 0);
      pump14.addBox(0F, 0F, 0F, 1, 1, 1);
      pump14.setRotationPoint(-2.8F, -4.4F, -25F);
      pump14.setTextureSize(64, 32);
      pump14.mirror = true;
      setRotation(pump14, -0.6320364F, 0F, 0F);
      pump15 = new ModelRenderer(this, 250, 0);
      pump15.addBox(0F, 0F, 0F, 1, 1, 15);
      pump15.setRotationPoint(-2.8F, -3F, -39F);
      pump15.setTextureSize(64, 32);
      pump15.mirror = true;
      setRotation(pump15, 0F, 0F, -1.115358F);
      pump16 = new ModelRenderer(this, 250, 0);
      pump16.addBox(0F, 0F, 0F, 1, 1, 20);
      pump16.setRotationPoint(0.8F, -3F, -39F);
      pump16.setTextureSize(64, 32);
      pump16.mirror = true;
      setRotation(pump16, 0F, 0F, 2.67686F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    pump1.render(f5);
    pump2.render(f5);
    pump3.render(f5);
    pump4.render(f5);
    pump5.render(f5);
    pump6.render(f5);
    pump7.render(f5);
    pump8.render(f5);
    pump9.render(f5);
    pump10.render(f5);
    pump11.render(f5);
    pump12.render(f5);
    pump13.render(f5);
    pump14.render(f5);
    pump15.render(f5);
    pump16.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
