// Date: 2/29/2020 11:09:14 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class RPKstock extends ModelBase
{
  //fields
    ModelRenderer stock1;
    ModelRenderer stock2;
    ModelRenderer stock5;
    ModelRenderer stock6;
    ModelRenderer stock7;
    ModelRenderer stock8;
    ModelRenderer stock9;
    ModelRenderer stock10;
    ModelRenderer stock11;
    ModelRenderer stock12;
    ModelRenderer stock13;
    ModelRenderer stock14;
  
  public RPKstock()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      stock1 = new ModelRenderer(this, 0, 0);
      stock1.addBox(0F, 0F, 0F, 4, 5, 27);
      stock1.setRotationPoint(-3.5F, -10.9F, 3.5F);
      stock1.setTextureSize(64, 32);
      stock1.mirror = true;
      setRotation(stock1, -0.0872665F, 0F, 0F);
      stock2 = new ModelRenderer(this, 0, 0);
      stock2.addBox(0F, 0F, 0F, 3, 2, 28);
      stock2.setRotationPoint(-3F, -11.9F, 3.5F);
      stock2.setTextureSize(64, 32);
      stock2.mirror = true;
      setRotation(stock2, -0.0872665F, 0F, 0F);
      stock5 = new ModelRenderer(this, 100, 0);
      stock5.addBox(0F, 0F, 0F, 2, 2, 1);
      stock5.setRotationPoint(-2.9F, -9.7F, 30.8F);
      stock5.setTextureSize(64, 32);
      stock5.mirror = true;
      setRotation(stock5, -0.0872665F, 0F, 0F);
      stock6 = new ModelRenderer(this, 100, 0);
      stock6.addBox(0F, 0F, 0F, 3, 10, 2);
      stock6.setRotationPoint(-3.4F, -8.9F, 29.7F);
      stock6.setTextureSize(64, 32);
      stock6.mirror = true;
      setRotation(stock6, -0.0872665F, 0F, 0F);
      stock7 = new ModelRenderer(this, 100, 0);
      stock7.addBox(0F, 0F, 0F, 1, 10, 2);
      stock7.setRotationPoint(-0.6F, -8.9F, 29.7F);
      stock7.setTextureSize(64, 32);
      stock7.mirror = true;
      setRotation(stock7, -0.0872665F, 0F, 0F);
      stock8 = new ModelRenderer(this, 100, 0);
      stock8.addBox(0F, 0F, 0F, 1, 2, 1);
      stock8.setRotationPoint(-1.1F, -9.7F, 30.8F);
      stock8.setTextureSize(64, 32);
      stock8.mirror = true;
      setRotation(stock8, -0.0872665F, 0F, 0F);
      stock9 = new ModelRenderer(this, 100, 0);
      stock9.addBox(0F, 0F, 0F, 1, 1, 3);
      stock9.setRotationPoint(-0.4F, -8.6F, 7.5F);
      stock9.setTextureSize(64, 32);
      stock9.mirror = true;
      setRotation(stock9, -0.1858931F, 0F, 0F);
      stock10 = new ModelRenderer(this, 100, 0);
      stock10.addBox(0F, 0F, 0F, 1, 3, 1);
      stock10.setRotationPoint(-0.1F, -9.5F, 8.5F);
      stock10.setTextureSize(64, 32);
      stock10.mirror = true;
      setRotation(stock10, -0.1858931F, 0F, 0F);
      stock11 = new ModelRenderer(this, 100, 0);
      stock11.addBox(0F, 0F, 0F, 2, 1, 4);
      stock11.setRotationPoint(-2.5F, -12F, 3.5F);
      stock11.setTextureSize(64, 32);
      stock11.mirror = true;
      setRotation(stock11, -0.0872665F, 0F, 0F);
      stock12 = new ModelRenderer(this, 0, 0);
      stock12.addBox(0F, -6F, 0F, 4, 6, 13);
      stock12.setRotationPoint(-3.5F, 1F, 16.6F);
      stock12.setTextureSize(64, 32);
      stock12.mirror = true;
      setRotation(stock12, -0.0523599F, 0F, 0F);
      stock13 = new ModelRenderer(this, 0, 0);
      stock13.addBox(0F, -4F, 0F, 4, 4, 2);
      stock13.setRotationPoint(-3.5F, 0F, 16.7F);
      stock13.setTextureSize(64, 32);
      stock13.mirror = true;
      setRotation(stock13, 0.1335332F, 0F, 0F);
      stock14 = new ModelRenderer(this, 0, 0);
      stock14.addBox(0F, -4F, 0F, 4, 4, 2);
      stock14.setRotationPoint(-3.5F, -3F, 16.4F);
      stock14.setTextureSize(64, 32);
      stock14.mirror = true;
      setRotation(stock14, 0.9514626F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    stock1.render(f5);
    stock2.render(f5);
    stock5.render(f5);
    stock6.render(f5);
    stock7.render(f5);
    stock8.render(f5);
    stock9.render(f5);
    stock10.render(f5);
    stock11.render(f5);
    stock12.render(f5);
    stock13.render(f5);
    stock14.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
