// Date: 10/14/2017 6:11:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SKSaction extends ModelBase
{
  //fields
    
    ModelRenderer action1;
    ModelRenderer action2;
    ModelRenderer action3;
    ModelRenderer action4;
    ModelRenderer action5;
    ModelRenderer action6;
    ModelRenderer action7;
    ModelRenderer action8;
    ModelRenderer action9;
    ModelRenderer action10;
  
  public SKSaction()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      action1 = new ModelRenderer(this, 150, 0);
      action1.addBox(0F, 0F, 0F, 1, 1, 10);
      action1.setRotationPoint(-1.5F, -8.4F, -11F);
      action1.setTextureSize(64, 32);
      action1.mirror = true;
      setRotation(action1, 0F, 0F, 0F);
      action2 = new ModelRenderer(this, 150, 0);
      action2.addBox(0F, 0F, 0F, 1, 1, 10);
      action2.setRotationPoint(-0.5F, -8.4F, -11F);
      action2.setTextureSize(64, 32);
      action2.mirror = true;
      setRotation(action2, 0F, 0F, 0.5948578F);
      action3 = new ModelRenderer(this, 150, 0);
      action3.addBox(0F, 0F, 0F, 1, 1, 10);
      action3.setRotationPoint(-1.5F, -8.4F, -11F);
      action3.setTextureSize(64, 32);
      action3.mirror = true;
      setRotation(action3, 0F, 0F, 0.9666439F);
      action4 = new ModelRenderer(this, 150, 0);
      action4.addBox(0F, 0F, 0F, 1, 1, 10);
      action4.setRotationPoint(-0.65F, -7.85F, -11F);
      action4.setTextureSize(64, 32);
      action4.mirror = true;
      setRotation(action4, 0F, 0F, 0F);
      action5 = new ModelRenderer(this, 150, 0);
      action5.addBox(0F, 0F, 0F, 1, 2, 10);
      action5.setRotationPoint(-2.3F, -7.85F, -11F);
      action5.setTextureSize(64, 32);
      action5.mirror = true;
      setRotation(action5, 0F, 0F, 0F);
      action6 = new ModelRenderer(this, 150, 0);
      action6.addBox(0F, 0F, 0F, 2, 1, 2);
      action6.setRotationPoint(-2.3F, -8.5F, -11F);
      action6.setTextureSize(64, 32);
      action6.mirror = true;
      setRotation(action6, 0F, 0F, 0F);
      action7 = new ModelRenderer(this, 150, 0);
      action7.addBox(0F, 0F, 0F, 1, 1, 2);
      action7.setRotationPoint(-0.65F, -8.5F, -11F);
      action7.setTextureSize(64, 32);
      action7.mirror = true;
      setRotation(action7, 0F, 0F, 0F);
      action8 = new ModelRenderer(this, 150, 0);
      action8.addBox(0F, 0F, 0F, 2, 1, 1);
      action8.setRotationPoint(-2.3F, -8.5F, -9F);
      action8.setTextureSize(64, 32);
      action8.mirror = true;
      setRotation(action8, -0.7853982F, 0F, 0F);
      action9 = new ModelRenderer(this, 150, 0);
      action9.addBox(0F, 0F, 0F, 1, 1, 1);
      action9.setRotationPoint(-0.65F, -8.5F, -9F);
      action9.setTextureSize(64, 32);
      action9.mirror = true;
      setRotation(action9, -0.7853982F, 0F, 0F);
      action10 = new ModelRenderer(this, 150, 0);
      action10.addBox(0F, 0F, 0F, 2, 1, 1);
      action10.setRotationPoint(-4.3F, -8.3F, -10.3F);
      action10.setTextureSize(64, 32);
      action10.mirror = true;
      setRotation(action10, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    action1.render(f5);
    action2.render(f5);
    action3.render(f5);
    action4.render(f5);
    action5.render(f5);
    action6.render(f5);
    action7.render(f5);
    action8.render(f5);
    action9.render(f5);
    action10.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
}
