// Date: 10/14/2017 10:20:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SKSstripper2 extends ModelBase
{
  //fields
    
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
  
  public SKSstripper2()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      
      mag1 = new ModelRenderer(this, 100, 0);
      mag1.addBox(0F, 0F, 0F, 2, 7, 1);
      mag1.setRotationPoint(-0.5F, -6F, 2.5F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, 0F, 0F, 0F);
      mag2 = new ModelRenderer(this, 100, 0);
      mag2.addBox(0F, 0F, 0F, 2, 2, 1);
      mag2.setRotationPoint(-0.5F, -7.2F, 2.5F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, 0F, 0F, 0F);
      mag3 = new ModelRenderer(this, 100, 0);
      mag3.addBox(0F, 0F, 0F, 2, 8, 1);
      mag3.setRotationPoint(-0.5F, -7.2F, 3.5F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, -2.93711F, 0F, 0F);
      mag4 = new ModelRenderer(this, 100, 0);
      mag4.addBox(0F, 0F, 0F, 2, 1, 1);
      mag4.setRotationPoint(-0.5F, -14.4F, 1.88F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, -2.93711F, 0F, 0F);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
