// Date: 2/11/2018 9:51:49 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SRS99S5mag extends ModelBase
{
  //fields
    
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
    ModelRenderer mag5;
    ModelRenderer mag6;
    ModelRenderer mag7;
    ModelRenderer mag8;
    ModelRenderer mag9;
    ModelRenderer mag10;
    ModelRenderer mag11;
    ModelRenderer mag12;
    ModelRenderer mag13;
    ModelRenderer mag14;
    ModelRenderer mag15;
    ModelRenderer mag16;
    ModelRenderer mag17;
  
  public SRS99S5mag()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      
      mag1 = new ModelRenderer(this, 0, 0);
      mag1.addBox(0F, 0F, 0F, 4, 15, 21);
      mag1.setRotationPoint(-3.5F, -6.8F, -40F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, 0F, 0F, 0F);
      mag2 = new ModelRenderer(this, 0, 0);
      mag2.addBox(0F, 0F, 0F, 4, 3, 11);
      mag2.setRotationPoint(-3.5F, 8.2F, -30F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, 0F, 0F, 0F);
      mag3 = new ModelRenderer(this, 100, 0);
      mag3.addBox(0F, 0F, 0F, 5, 3, 2);
      mag3.setRotationPoint(-4F, 5.4F, -40.2F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, 0F, 0F, 0F);
      mag4 = new ModelRenderer(this, 100, 0);
      mag4.addBox(0F, 0F, 0F, 5, 3, 10);
      mag4.setRotationPoint(-4F, 5.4F, -38.2F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, -0.2602503F, 0F, 0F);
      mag5 = new ModelRenderer(this, 100, 0);
      mag5.addBox(0F, 0F, 0F, 5, 11, 1);
      mag5.setRotationPoint(-4F, 8.4F, -40.2F);
      mag5.setTextureSize(64, 32);
      mag5.mirror = true;
      setRotation(mag5, 1.301251F, 0F, 0F);
      mag6 = new ModelRenderer(this, 0, 0);
      mag6.addBox(0F, 0F, 0F, 4, 1, 2);
      mag6.setRotationPoint(-3.5F, 8.2F, -32F);
      mag6.setTextureSize(64, 32);
      mag6.mirror = true;
      setRotation(mag6, 0F, 0F, 0F);
      mag7 = new ModelRenderer(this, 100, 0);
      mag7.addBox(0F, 0F, 0F, 5, 1, 10);
      mag7.setRotationPoint(-4F, 10.4F, -29.6F);
      mag7.setTextureSize(64, 32);
      mag7.mirror = true;
      setRotation(mag7, 0F, 0F, 0F);
      mag8 = new ModelRenderer(this, 100, 0);
      mag8.addBox(0F, 0F, 0F, 5, 3, 1);
      mag8.setRotationPoint(-4F, 8F, -29.5F);
      mag8.setTextureSize(64, 32);
      mag8.mirror = true;
      setRotation(mag8, 0F, 0F, 0F);
      mag9 = new ModelRenderer(this, 0, 0);
      mag9.addBox(0F, 0F, 0F, 4, 15, 12);
      mag9.setRotationPoint(-3.9F, -6.8F, -39.5F);
      mag9.setTextureSize(64, 32);
      mag9.mirror = true;
      setRotation(mag9, 0F, 0F, 0F);
      mag10 = new ModelRenderer(this, 0, 0);
      mag10.addBox(0F, 0F, 0F, 1, 15, 12);
      mag10.setRotationPoint(-0.1F, -6.8F, -39.5F);
      mag10.setTextureSize(64, 32);
      mag10.mirror = true;
      setRotation(mag10, 0F, 0F, 0F);
      mag11 = new ModelRenderer(this, 0, 0);
      mag11.addBox(0F, 0F, 0F, 4, 3, 1);
      mag11.setRotationPoint(-3.9F, 8.2F, -28.5F);
      mag11.setTextureSize(64, 32);
      mag11.mirror = true;
      setRotation(mag11, 0F, 0F, 0F);
      mag12 = new ModelRenderer(this, 0, 0);
      mag12.addBox(0F, 0F, 0F, 1, 3, 1);
      mag12.setRotationPoint(-0.1F, 8.2F, -28.5F);
      mag12.setTextureSize(64, 32);
      mag12.mirror = true;
      setRotation(mag12, 0F, 0F, 0F);
      mag13 = new ModelRenderer(this, 0, 0);
      mag13.addBox(0F, 0F, 0F, 4, 18, 5);
      mag13.setRotationPoint(-3.9F, -6.8F, -25F);
      mag13.setTextureSize(64, 32);
      mag13.mirror = true;
      setRotation(mag13, 0F, 0F, 0F);
      mag14 = new ModelRenderer(this, 0, 0);
      mag14.addBox(0F, 0F, 0F, 1, 18, 5);
      mag14.setRotationPoint(-0.1F, -6.8F, -25F);
      mag14.setTextureSize(64, 32);
      mag14.mirror = true;
      setRotation(mag14, 0F, 0F, 0F);
      mag15 = new ModelRenderer(this, 0, 0);
      mag15.addBox(0F, 0F, 0F, 2, 2, 1);
      mag15.setRotationPoint(-2.5F, 8.3F, -19.5F);
      mag15.setTextureSize(64, 32);
      mag15.mirror = true;
      setRotation(mag15, 0F, 0F, 0F);
      mag16 = new ModelRenderer(this, 0, 0);
      mag16.addBox(0F, 0F, 0F, 2, 1, 1);
      mag16.setRotationPoint(-2.5F, 8.3F, -18.5F);
      mag16.setTextureSize(64, 32);
      mag16.mirror = true;
      setRotation(mag16, -2.356194F, 0F, 0F);
      mag17 = new ModelRenderer(this, 0, 0);
      mag17.addBox(0F, 0F, 0F, 2, 1, 1);
      mag17.setRotationPoint(-2.5F, 10.3F, -18.5F);
      mag17.setTextureSize(64, 32);
      mag17.mirror = true;
      setRotation(mag17, -2.356194F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
    mag5.render(f5);
    mag6.render(f5);
    mag7.render(f5);
    mag8.render(f5);
    mag9.render(f5);
    mag10.render(f5);
    mag11.render(f5);
    mag12.render(f5);
    mag13.render(f5);
    mag14.render(f5);
    mag15.render(f5);
    mag16.render(f5);
    mag17.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
