// Date: 6/10/2017 12:18:55 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SV98Mag extends ModelBase
{
  //fields
    ModelRenderer Mag1;
    ModelRenderer Mag3;
    ModelRenderer Mag6;
    ModelRenderer Mag9;
    ModelRenderer Mag11;
    ModelRenderer Mag12;
    ModelRenderer Mag13;
    ModelRenderer Mag14;
    ModelRenderer Mag15;
    ModelRenderer Mag16;
    ModelRenderer Mag18;
    ModelRenderer Mag20;
    ModelRenderer Mag21;
    ModelRenderer Mag22;
    ModelRenderer Mag33;
    ModelRenderer Mag34;
    ModelRenderer Mag35;
    ModelRenderer Mag36;
    ModelRenderer Mag37;
    ModelRenderer Mag38;
    ModelRenderer Mag39;
    ModelRenderer Mag40;
    ModelRenderer Mag41;
    ModelRenderer Mag42;
    ModelRenderer Mag43;
    ModelRenderer Mag44;
  
  public SV98Mag()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Mag1 = new ModelRenderer(this, 0, 0);
      Mag1.addBox(0F, 0F, 0F, 2, 1, 6);
      Mag1.setRotationPoint(1.5F, -7.3F, -7F);
      Mag1.setTextureSize(64, 32);
      Mag1.mirror = true;
      setRotation(Mag1, 1.673038F, 0F, 0F);
      Mag3 = new ModelRenderer(this, 0, 0);
      Mag3.addBox(0F, 0F, 0F, 3, 2, 2);
      Mag3.setRotationPoint(1F, -9F, -6.5F);
      Mag3.setTextureSize(64, 32);
      Mag3.mirror = true;
      setRotation(Mag3, 0F, 0F, 0F);
      Mag6 = new ModelRenderer(this, 0, 0);
      Mag6.addBox(0F, 0F, 0F, 2, 7, 1);
      Mag6.setRotationPoint(1.2F, -12.3F, 1.5F);
      Mag6.setTextureSize(64, 32);
      Mag6.mirror = true;
      setRotation(Mag6, -0.1115358F, 0F, 0F);
      Mag9 = new ModelRenderer(this, 0, 0);
      Mag9.addBox(0F, 0F, 0F, 1, 7, 1);
      Mag9.setRotationPoint(2.8F, -12.3F, 1.5F);
      Mag9.setTextureSize(64, 32);
      Mag9.mirror = true;
      setRotation(Mag9, -0.1115358F, 0F, 0F);
      Mag11 = new ModelRenderer(this, 0, 0);
      Mag11.addBox(0F, 0F, 0F, 3, 1, 1);
      Mag11.setRotationPoint(1F, -9.2F, -6F);
      Mag11.setTextureSize(64, 32);
      Mag11.mirror = true;
      setRotation(Mag11, 0F, 0F, 0F);
      Mag12 = new ModelRenderer(this, 0, 0);
      Mag12.addBox(0F, 0F, 0F, 3, 1, 1);
      Mag12.setRotationPoint(1F, -7.8F, -6F);
      Mag12.setTextureSize(64, 32);
      Mag12.mirror = true;
      setRotation(Mag12, 0F, 0F, 0F);
      Mag13 = new ModelRenderer(this, 0, 0);
      Mag13.addBox(0F, 0F, 0F, 3, 1, 1);
      Mag13.setRotationPoint(1F, -8.5F, -6.7F);
      Mag13.setTextureSize(64, 32);
      Mag13.mirror = true;
      setRotation(Mag13, 0F, 0F, 0F);
      Mag14 = new ModelRenderer(this, 0, 0);
      Mag14.addBox(0F, 0F, 0F, 3, 1, 1);
      Mag14.setRotationPoint(1F, -8.5F, -5.3F);
      Mag14.setTextureSize(64, 32);
      Mag14.mirror = true;
      setRotation(Mag14, 0F, 0F, 0F);
      Mag15 = new ModelRenderer(this, 0, 0);
      Mag15.addBox(0F, 0F, 0F, 2, 4, 1);
      Mag15.setRotationPoint(1.2F, -12.2F, -5.2F);
      Mag15.setTextureSize(64, 32);
      Mag15.mirror = true;
      setRotation(Mag15, -0.1115358F, 0F, 0F);
      Mag16 = new ModelRenderer(this, 0, 0);
      Mag16.addBox(0F, 0F, 0F, 1, 5, 1);
      Mag16.setRotationPoint(2.8F, -13.2F, -5.1F);
      Mag16.setTextureSize(64, 32);
      Mag16.mirror = true;
      setRotation(Mag16, -0.1115358F, 0F, 0F);
      Mag18 = new ModelRenderer(this, 0, 0);
      Mag18.addBox(0F, 0F, 0F, 2, 6, 4);
      Mag18.setRotationPoint(1.5F, -12.6F, -4.6F);
      Mag18.setTextureSize(64, 32);
      Mag18.mirror = true;
      setRotation(Mag18, -0.1115358F, 0F, 0F);
      Mag20 = new ModelRenderer(this, 0, 0);
      Mag20.addBox(0F, 0F, 0F, 2, 1, 7);
      Mag20.setRotationPoint(1.2F, -13.1F, -4.5F);
      Mag20.setTextureSize(64, 32);
      Mag20.mirror = true;
      setRotation(Mag20, -0.1115358F, 0F, 0F);
      Mag21 = new ModelRenderer(this, 0, 0);
      Mag21.addBox(0F, 0F, 0F, 1, 1, 7);
      Mag21.setRotationPoint(2.8F, -13.1F, -4.5F);
      Mag21.setTextureSize(64, 32);
      Mag21.mirror = true;
      setRotation(Mag21, -0.1115358F, 0F, 0F);
      Mag22 = new ModelRenderer(this, 0, 0);
      Mag22.addBox(0F, 0F, 0F, 2, 1, 7);
      Mag22.setRotationPoint(1.2F, -7.6F, -5.5F);
      Mag22.setTextureSize(64, 32);
      Mag22.mirror = true;
      setRotation(Mag22, -0.2230717F, 0F, 0F);
      Mag33 = new ModelRenderer(this, 0, 0);
      Mag33.addBox(0F, 0F, 0F, 1, 3, 1);
      Mag33.setRotationPoint(1.4F, -12.3F, 1.5F);
      Mag33.setTextureSize(64, 32);
      Mag33.mirror = true;
      setRotation(Mag33, -0.4089647F, 0F, 0F);
      Mag34 = new ModelRenderer(this, 0, 0);
      Mag34.addBox(0F, 0F, 0F, 2, 5, 1);
      Mag34.setRotationPoint(1.2F, -13.2F, -5.1F);
      Mag34.setTextureSize(64, 32);
      Mag34.mirror = true;
      setRotation(Mag34, -0.1115358F, 0F, 0F);
      Mag35 = new ModelRenderer(this, 0, 0);
      Mag35.addBox(0F, 0F, 0F, 1, 2, 6);
      Mag35.setRotationPoint(1.7F, -7.3F, -7F);
      Mag35.setTextureSize(64, 32);
      Mag35.mirror = true;
      setRotation(Mag35, 1.561502F, 0F, 0F);
      Mag36 = new ModelRenderer(this, 0, 0);
      Mag36.addBox(0F, 0F, 0F, 1, 2, 6);
      Mag36.setRotationPoint(2.3F, -7.3F, -7F);
      Mag36.setTextureSize(64, 32);
      Mag36.mirror = true;
      setRotation(Mag36, 1.561502F, 0F, 0F);
      Mag37 = new ModelRenderer(this, 0, 0);
      Mag37.addBox(0F, 0F, 0F, 2, 1, 4);
      Mag37.setRotationPoint(1.5F, -13.3F, -8F);
      Mag37.setTextureSize(64, 32);
      Mag37.mirror = true;
      setRotation(Mag37, -0.0743572F, 0F, 0F);
      Mag38 = new ModelRenderer(this, 0, 0);
      Mag38.addBox(0F, 0F, 0F, 1, 6, 4);
      Mag38.setRotationPoint(2.7F, -12.3F, -2F);
      Mag38.setTextureSize(64, 32);
      Mag38.mirror = true;
      setRotation(Mag38, -0.1115358F, 0F, 0F);
      Mag39 = new ModelRenderer(this, 0, 0);
      Mag39.addBox(0F, 0F, 0F, 1, 6, 4);
      Mag39.setRotationPoint(1.3F, -12.3F, -2F);
      Mag39.setTextureSize(64, 32);
      Mag39.mirror = true;
      setRotation(Mag39, -0.1115358F, 0F, 0F);
      Mag40 = new ModelRenderer(this, 0, 0);
      Mag40.addBox(0F, 0F, 0F, 1, 1, 7);
      Mag40.setRotationPoint(2.8F, -7.6F, -5.5F);
      Mag40.setTextureSize(64, 32);
      Mag40.mirror = true;
      setRotation(Mag40, -0.2230717F, 0F, 0F);
      Mag41 = new ModelRenderer(this, 0, 0);
      Mag41.addBox(0F, 0F, 0F, 1, 1, 3);
      Mag41.setRotationPoint(2.6F, -11.3F, -4.5F);
      Mag41.setTextureSize(64, 32);
      Mag41.mirror = true;
      setRotation(Mag41, -0.1115358F, 0F, 0F);
      Mag42 = new ModelRenderer(this, 0, 0);
      Mag42.addBox(0F, 0F, 0F, 1, 1, 3);
      Mag42.setRotationPoint(1.4F, -11.3F, -4.5F);
      Mag42.setTextureSize(64, 32);
      Mag42.mirror = true;
      setRotation(Mag42, -0.1115358F, 0F, 0F);
      Mag43 = new ModelRenderer(this, 0, 0);
      Mag43.addBox(0F, 0F, 0F, 1, 1, 3);
      Mag43.setRotationPoint(2.6F, -9.8F, -4.6F);
      Mag43.setTextureSize(64, 32);
      Mag43.mirror = true;
      setRotation(Mag43, -0.2974289F, 0F, 0F);
      Mag44 = new ModelRenderer(this, 0, 0);
      Mag44.addBox(0F, 0F, 0F, 1, 1, 3);
      Mag44.setRotationPoint(1.4F, -9.8F, -4.6F);
      Mag44.setTextureSize(64, 32);
      Mag44.mirror = true;
      setRotation(Mag44, -0.2974289F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Mag1.render(f5);
    Mag3.render(f5);
    Mag6.render(f5);
    Mag9.render(f5);
    Mag11.render(f5);
    Mag12.render(f5);
    Mag13.render(f5);
    Mag14.render(f5);
    Mag15.render(f5);
    Mag16.render(f5);
    Mag18.render(f5);
    Mag20.render(f5);
    Mag21.render(f5);
    Mag22.render(f5);
    Mag33.render(f5);
    Mag34.render(f5);
    Mag35.render(f5);
    Mag36.render(f5);
    Mag37.render(f5);
    Mag38.render(f5);
    Mag39.render(f5);
    Mag40.render(f5);
    Mag41.render(f5);
    Mag42.render(f5);
    Mag43.render(f5);
    Mag44.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
