// Date: 6/10/2017 12:17:57 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SV98Action extends ModelBase
{
  //fields
    ModelRenderer Action1;
    ModelRenderer Action2;
    ModelRenderer Action3;
    ModelRenderer Action4;
    ModelRenderer Action5;
    ModelRenderer Action6;
    ModelRenderer Action7;
    ModelRenderer Action8;
    ModelRenderer Action9;
    ModelRenderer Action10;
    ModelRenderer Action11;
    ModelRenderer Action12;
    ModelRenderer Action13;
    ModelRenderer Action14;
    ModelRenderer Action15;
    ModelRenderer Action16;
    ModelRenderer Action17;
    ModelRenderer Action18;
    ModelRenderer Action19;
    ModelRenderer Action20;
    ModelRenderer Action21;
    ModelRenderer Action22;
  
  public SV98Action()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Action1 = new ModelRenderer(this, 0, 0);
      Action1.addBox(0F, 0F, 0F, 1, 1, 18);
      Action1.setRotationPoint(-1F, -16F, -27.8F);
      Action1.setTextureSize(64, 32);
      Action1.mirror = true;
      setRotation(Action1, 0F, 0F, 0F);
      Action2 = new ModelRenderer(this, 0, 0);
      Action2.addBox(0F, 0F, 0F, 1, 1, 18);
      Action2.setRotationPoint(-1F, -14.5F, -27.8F);
      Action2.setTextureSize(64, 32);
      Action2.mirror = true;
      setRotation(Action2, 0F, 0F, 0F);
      Action3 = new ModelRenderer(this, 0, 0);
      Action3.addBox(0F, 0F, 0F, 1, 1, 18);
      Action3.setRotationPoint(-1.7F, -15.25F, -27.8F);
      Action3.setTextureSize(64, 32);
      Action3.mirror = true;
      setRotation(Action3, 0F, 0F, 0F);
      Action4 = new ModelRenderer(this, 0, 0);
      Action4.addBox(0F, 0F, 0F, 1, 1, 18);
      Action4.setRotationPoint(-0.3F, -15.25F, -27.8F);
      Action4.setTextureSize(64, 32);
      Action4.mirror = true;
      setRotation(Action4, 0F, 0F, 0F);
      Action5 = new ModelRenderer(this, 0, 0);
      Action5.addBox(0F, 0F, 0F, 1, 1, 18);
      Action5.setRotationPoint(0F, -16F, -27.8F);
      Action5.setTextureSize(64, 32);
      Action5.mirror = true;
      setRotation(Action5, 0F, 0F, 0.8551081F);
      Action6 = new ModelRenderer(this, 0, 0);
      Action6.addBox(0F, 0F, 0F, 1, 1, 18);
      Action6.setRotationPoint(-1F, -16F, -27.8F);
      Action6.setTextureSize(64, 32);
      Action6.mirror = true;
      setRotation(Action6, 0F, 0F, 0.7435722F);
      Action7 = new ModelRenderer(this, 0, 0);
      Action7.addBox(0F, 0F, 0F, 1, 1, 18);
      Action7.setRotationPoint(-1.7F, -14.25F, -27.8F);
      Action7.setTextureSize(64, 32);
      Action7.mirror = true;
      setRotation(Action7, 0F, 0F, -0.7435722F);
      Action8 = new ModelRenderer(this, 0, 0);
      Action8.addBox(0F, 0F, 0F, 1, 1, 18);
      Action8.setRotationPoint(0.7F, -14.25F, -27.8F);
      Action8.setTextureSize(64, 32);
      Action8.mirror = true;
      setRotation(Action8, 0F, 0F, 2.342252F);
      Action9 = new ModelRenderer(this, 50, 0);
      Action9.addBox(0F, 0F, 0F, 1, 1, 1);
      Action9.setRotationPoint(-1F, -15.8F, -10.6F);
      Action9.setTextureSize(64, 32);
      Action9.mirror = true;
      setRotation(Action9, 0F, 0F, 0F);
      Action10 = new ModelRenderer(this, 50, 0);
      Action10.addBox(0F, 0F, 0F, 1, 1, 1);
      Action10.setRotationPoint(-1F, -14.7F, -10.6F);
      Action10.setTextureSize(64, 32);
      Action10.mirror = true;
      setRotation(Action10, 0F, 0F, 0F);
      Action11 = new ModelRenderer(this, 50, 0);
      Action11.addBox(0F, 0F, 0F, 2, 1, 1);
      Action11.setRotationPoint(-1.5F, -15.25F, -10.6F);
      Action11.setTextureSize(64, 32);
      Action11.mirror = true;
      setRotation(Action11, 0F, 0F, 0F);
      Action12 = new ModelRenderer(this, 50, 0);
      Action12.addBox(0F, 0F, 0F, 1, 1, 1);
      Action12.setRotationPoint(-1.3F, -15.6F, -10.6F);
      Action12.setTextureSize(64, 32);
      Action12.mirror = true;
      setRotation(Action12, 0F, 0F, 0F);
      Action13 = new ModelRenderer(this, 50, 0);
      Action13.addBox(0F, 0F, 0F, 1, 1, 1);
      Action13.setRotationPoint(-1.3F, -14.9F, -10.6F);
      Action13.setTextureSize(64, 32);
      Action13.mirror = true;
      setRotation(Action13, 0F, 0F, 0F);
      Action14 = new ModelRenderer(this, 50, 0);
      Action14.addBox(0F, 0F, 0F, 1, 1, 1);
      Action14.setRotationPoint(-0.7F, -15.6F, -10.6F);
      Action14.setTextureSize(64, 32);
      Action14.mirror = true;
      setRotation(Action14, 0F, 0F, 0F);
      Action15 = new ModelRenderer(this, 50, 0);
      Action15.addBox(0F, 0F, 0F, 1, 1, 1);
      Action15.setRotationPoint(-0.7F, -14.9F, -10.6F);
      Action15.setTextureSize(64, 32);
      Action15.mirror = true;
      setRotation(Action15, 0F, 0F, 0F);
      Action16 = new ModelRenderer(this, 0, 0);
      Action16.addBox(0F, 0F, 0F, 1, 1, 1);
      Action16.setRotationPoint(-2.7F, -15.25F, -13.5F);
      Action16.setTextureSize(64, 32);
      Action16.mirror = true;
      setRotation(Action16, 0F, 0F, 0F);
      Action17 = new ModelRenderer(this, 0, 0);
      Action17.addBox(0F, 0F, 0F, 1, 1, 1);
      Action17.setRotationPoint(-2.7F, -15.25F, -13.3F);
      Action17.setTextureSize(64, 32);
      Action17.mirror = true;
      setRotation(Action17, 0F, 0F, 0F);
      Action18 = new ModelRenderer(this, 0, 0);
      Action18.addBox(0F, 0F, 0F, 1, 3, 1);
      Action18.setRotationPoint(-2.7F, -15.25F, -13.4F);
      Action18.setTextureSize(64, 32);
      Action18.mirror = true;
      setRotation(Action18, 0F, 0F, 1.115358F);
      Action19 = new ModelRenderer(this, 50, 0);
      Action19.addBox(0F, 0F, 0F, 1, 1, 1);
      Action19.setRotationPoint(-5.4F, -14.25F, -13.6F);
      Action19.setTextureSize(64, 32);
      Action19.mirror = true;
      setRotation(Action19, 0F, 0F, 1.115358F);
      Action20 = new ModelRenderer(this, 50, 0);
      Action20.addBox(0F, 0F, 0F, 1, 1, 1);
      Action20.setRotationPoint(-5.4F, -14.25F, -13.2F);
      Action20.setTextureSize(64, 32);
      Action20.mirror = true;
      setRotation(Action20, 0F, 0F, 1.115358F);
      Action21 = new ModelRenderer(this, 50, 0);
      Action21.addBox(0F, 0F, 0F, 1, 1, 1);
      Action21.setRotationPoint(-5.2F, -13.8F, -13.2F);
      Action21.setTextureSize(64, 32);
      Action21.mirror = true;
      setRotation(Action21, 0F, 0F, 1.115358F);
      Action22 = new ModelRenderer(this, 50, 0);
      Action22.addBox(0F, 0F, 0F, 1, 1, 1);
      Action22.setRotationPoint(-5.2F, -13.8F, -13.6F);
      Action22.setTextureSize(64, 32);
      Action22.mirror = true;
      setRotation(Action22, 0F, 0F, 1.115358F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Action1.render(f5);
    Action2.render(f5);
    Action3.render(f5);
    Action4.render(f5);
    Action5.render(f5);
    Action6.render(f5);
    Action7.render(f5);
    Action8.render(f5);
    Action9.render(f5);
    Action10.render(f5);
    Action11.render(f5);
    Action12.render(f5);
    Action13.render(f5);
    Action14.render(f5);
    Action15.render(f5);
    Action16.render(f5);
    Action17.render(f5);
    Action18.render(f5);
    Action19.render(f5);
    Action20.render(f5);
    Action21.render(f5);
    Action22.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
