// Date: 6/11/2020 3:22:32 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Tokyo90RearSights extends ModelBase
{
  //fields
    ModelRenderer rearsights1;
    ModelRenderer rearsights2;
    ModelRenderer rearsights3;
    ModelRenderer rearsights4;
    ModelRenderer rearsights5;
    ModelRenderer rearsights6;
    ModelRenderer rearsights7;
    ModelRenderer frontsights1;
    ModelRenderer frontsights2;
    ModelRenderer frontsights3;
    ModelRenderer frontsights4;
    ModelRenderer frontsights5;
  
  public Tokyo90RearSights()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      rearsights1 = new ModelRenderer(this, 0, 0);
      rearsights1.addBox(0F, 0F, 0F, 6, 4, 5);
      rearsights1.setRotationPoint(-2.5F, 0F, 0F);
      rearsights1.setTextureSize(128, 128);
      rearsights1.mirror = true;
      setRotation(rearsights1, 0F, 0F, 0F);
      rearsights2 = new ModelRenderer(this, 0, 0);
      rearsights2.addBox(0F, 0F, 0F, 2, 1, 2);
      rearsights2.setRotationPoint(-2F, -0.9F, 1.5F);
      rearsights2.setTextureSize(128, 128);
      rearsights2.mirror = true;
      setRotation(rearsights2, 0F, 0F, 0F);
      rearsights3 = new ModelRenderer(this, 0, 0);
      rearsights3.addBox(0F, 0F, 0F, 2, 1, 2);
      rearsights3.setRotationPoint(1F, -0.9F, 1.5F);
      rearsights3.setTextureSize(128, 128);
      rearsights3.mirror = true;
      setRotation(rearsights3, 0F, 0F, 0F);
      rearsights4 = new ModelRenderer(this, 0, 0);
      rearsights4.addBox(0F, 0F, 0F, 1, 1, 2);
      rearsights4.setRotationPoint(-2F, -0.9F, 1.5F);
      rearsights4.setTextureSize(128, 128);
      rearsights4.mirror = true;
      setRotation(rearsights4, 0F, 0F, 0.4833219F);
      rearsights5 = new ModelRenderer(this, 0, 0);
      rearsights5.addBox(-1F, 0F, 0F, 1, 1, 2);
      rearsights5.setRotationPoint(3F, -0.9F, 1.5F);
      rearsights5.setTextureSize(128, 128);
      rearsights5.mirror = true;
      setRotation(rearsights5, 0F, 0F, -0.4833166F);
      rearsights6 = new ModelRenderer(this, 0, 50);
      rearsights6.addBox(0F, 0F, 0F, 1, 1, 1);
      rearsights6.setRotationPoint(-1.3F, -0.7F, 2.6F);
      rearsights6.setTextureSize(128, 128);
      rearsights6.mirror = true;
      setRotation(rearsights6, 0F, 0F, 0F);
      rearsights7 = new ModelRenderer(this, 0, 50);
      rearsights7.addBox(0F, 0F, 0F, 1, 1, 1);
      rearsights7.setRotationPoint(1.3F, -0.7F, 2.6F);
      rearsights7.setTextureSize(128, 128);
      rearsights7.mirror = true;
      setRotation(rearsights7, 0F, 0F, 0F);
      frontsights1 = new ModelRenderer(this, 0, 0);
      frontsights1.addBox(0F, 0F, 0F, 2, 1, 5);
      frontsights1.setRotationPoint(-0.5F, 1F, -9F);
      frontsights1.setTextureSize(128, 128);
      frontsights1.mirror = true;
      setRotation(frontsights1, 0F, 0F, 0F);
      frontsights2 = new ModelRenderer(this, 0, 0);
      frontsights2.addBox(0F, 0F, 0F, 1, 2, 5);
      frontsights2.setRotationPoint(-0.3F, -0.3F, -9.25F);
      frontsights2.setTextureSize(128, 128);
      frontsights2.mirror = true;
      setRotation(frontsights2, 0.122173F, 0F, 0F);
      frontsights3 = new ModelRenderer(this, 0, 0);
      frontsights3.addBox(0F, 0F, 0F, 1, 2, 5);
      frontsights3.setRotationPoint(0.3F, -0.3F, -9.25F);
      frontsights3.setTextureSize(128, 128);
      frontsights3.mirror = true;
      setRotation(frontsights3, 0.122173F, 0F, 0F);
      frontsights4 = new ModelRenderer(this, 0, 0);
      frontsights4.addBox(0F, 0.2F, 4.1F, 1, 1, 1);
      frontsights4.setRotationPoint(0F, -0.3F, -9.25F);
      frontsights4.setTextureSize(128, 128);
      frontsights4.mirror = true;
      setRotation(frontsights4, 0.122173F, 0F, 0F);
      frontsights5 = new ModelRenderer(this, 0, 0);
      frontsights5.addBox(0F, 0F, 0F, 2, 1, 5);
      frontsights5.setRotationPoint(-0.5F, 0.5F, -9F);
      frontsights5.setTextureSize(128, 128);
      frontsights5.mirror = true;
      setRotation(frontsights5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    rearsights1.render(f5);
    rearsights2.render(f5);
    rearsights3.render(f5);
    rearsights4.render(f5);
    rearsights5.render(f5);
    rearsights6.render(f5);
    rearsights7.render(f5);
//    frontsights1.render(f5);
//    frontsights2.render(f5);
//    frontsights3.render(f5);
//    frontsights4.render(f5);
//    frontsights5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
