// Date: 2/19/2019 2:22:36 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class VendingMachine extends ModelBase
{
  //fields
    ModelRenderer VendingMachine1;
    ModelRenderer VendingMachine2;
    ModelRenderer VendingMachine3;
    ModelRenderer VendingMachine4;
    ModelRenderer VendingMachine5;
    ModelRenderer VendingMachine6;
    ModelRenderer VendingMachine7;
    ModelRenderer VendingMachine8;
    ModelRenderer VendingMachine9;
    ModelRenderer VendingMachine10;
    ModelRenderer VendingMachine11;
    ModelRenderer VendingMachine12;
    ModelRenderer VendingMachine13;
    ModelRenderer VendingMachine14;
    ModelRenderer VendingMachine15;
  
  public VendingMachine()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      VendingMachine1 = new ModelRenderer(this, 0, 0);
      VendingMachine1.addBox(0F, 0F, 0F, 4, 38, 15);
      VendingMachine1.setRotationPoint(-15F, -17F, -7F);
      VendingMachine1.setTextureSize(256, 256);
      VendingMachine1.mirror = true;
      setRotation(VendingMachine1, 0F, 0F, 0F);
      VendingMachine2 = new ModelRenderer(this, 0, 0);
      VendingMachine2.addBox(0F, 0F, 0F, 4, 38, 15);
      VendingMachine2.setRotationPoint(11F, -17F, -7F);
      VendingMachine2.setTextureSize(256, 256);
      VendingMachine2.mirror = true;
      setRotation(VendingMachine2, 0F, 0F, 0F);
      VendingMachine3 = new ModelRenderer(this, 0, 0);
      VendingMachine3.addBox(0F, 0F, 0F, 30, 4, 15);
      VendingMachine3.setRotationPoint(-15F, -21F, -7F);
      VendingMachine3.setTextureSize(256, 256);
      VendingMachine3.mirror = true;
      setRotation(VendingMachine3, 0F, 0F, 0F);
      VendingMachine4 = new ModelRenderer(this, 0, 0);
      VendingMachine4.addBox(0F, 0F, 0F, 22, 38, 9);
      VendingMachine4.setRotationPoint(-11F, -17F, -1F);
      VendingMachine4.setTextureSize(256, 256);
      VendingMachine4.mirror = true;
      setRotation(VendingMachine4, 0F, 0F, 0F);
      VendingMachine5 = new ModelRenderer(this, 0, 0);
      VendingMachine5.addBox(0F, 0F, 0F, 22, 4, 6);
      VendingMachine5.setRotationPoint(-11F, 17F, -7F);
      VendingMachine5.setTextureSize(256, 256);
      VendingMachine5.mirror = true;
      setRotation(VendingMachine5, 0F, 0F, 0F);
      VendingMachine6 = new ModelRenderer(this, 0, 0);
      VendingMachine6.addBox(0F, 0F, 0F, 26, 3, 13);
      VendingMachine6.setRotationPoint(-13F, 21F, -6F);
      VendingMachine6.setTextureSize(256, 256);
      VendingMachine6.mirror = true;
      setRotation(VendingMachine6, 0F, 0F, 0F);
      VendingMachine7 = new ModelRenderer(this, 0, 80);
      VendingMachine7.addBox(0F, 0F, 0F, 16, 1, 1);
      VendingMachine7.setRotationPoint(-11F, 8F, -7.3F);
      VendingMachine7.setTextureSize(256, 256);
      VendingMachine7.mirror = true;
      setRotation(VendingMachine7, 0F, 0F, 0F);
      VendingMachine8 = new ModelRenderer(this, 0, 80);
      VendingMachine8.addBox(0F, 0F, 0F, 6, 34, 6);
      VendingMachine8.setRotationPoint(5F, -17F, -7.3F);
      VendingMachine8.setTextureSize(256, 256);
      VendingMachine8.mirror = true;
      setRotation(VendingMachine8, 0F, 0F, 0F);
      VendingMachine9 = new ModelRenderer(this, 0, 150);
      VendingMachine9.addBox(0F, 0F, 0F, 16, 25, 1);
      VendingMachine9.setRotationPoint(-11F, -17F, -6.3F);
      VendingMachine9.setTextureSize(256, 256);
      VendingMachine9.mirror = true;
      setRotation(VendingMachine9, 0F, 0F, 0F);
      VendingMachine10 = new ModelRenderer(this, 0, 80);
      VendingMachine10.addBox(0F, 0F, 0F, 16, 4, 1);
      VendingMachine10.setRotationPoint(-11F, 13F, -7.3F);
      VendingMachine10.setTextureSize(256, 256);
      VendingMachine10.mirror = true;
      setRotation(VendingMachine10, 0F, 0F, 0F);
      VendingMachine11 = new ModelRenderer(this, 0, 80);
      VendingMachine11.addBox(0F, 0F, 0F, 4, 4, 1);
      VendingMachine11.setRotationPoint(-11F, 9F, -7.3F);
      VendingMachine11.setTextureSize(256, 256);
      VendingMachine11.mirror = true;
      setRotation(VendingMachine11, 0F, 0F, 0F);
      VendingMachine12 = new ModelRenderer(this, 0, 80);
      VendingMachine12.addBox(0F, 0F, 0F, 4, 4, 1);
      VendingMachine12.setRotationPoint(1F, 9F, -7.3F);
      VendingMachine12.setTextureSize(256, 256);
      VendingMachine12.mirror = true;
      setRotation(VendingMachine12, 0F, 0F, 0F);
      VendingMachine13 = new ModelRenderer(this, 0, 80);
      VendingMachine13.addBox(0F, 0F, 0F, 8, 5, 1);
      VendingMachine13.setRotationPoint(-7F, 9F, -7.3F);
      VendingMachine13.setTextureSize(256, 256);
      VendingMachine13.mirror = true;
      setRotation(VendingMachine13, 0.1487144F, 0F, 0F);
      VendingMachine14 = new ModelRenderer(this, 0, 80);
      VendingMachine14.addBox(0F, 0F, 0F, 4, 5, 1);
      VendingMachine14.setRotationPoint(6F, -1F, -7.4F);
      VendingMachine14.setTextureSize(256, 256);
      VendingMachine14.mirror = true;
      setRotation(VendingMachine14, 0F, 0F, 0F);
      VendingMachine15 = new ModelRenderer(this, 0, 80);
      VendingMachine15.addBox(0F, 0F, 0F, 5, 1, 1);
      VendingMachine15.setRotationPoint(5.5F, -4F, -7.4F);
      VendingMachine15.setTextureSize(256, 256);
      VendingMachine15.mirror = true;
      setRotation(VendingMachine15, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    VendingMachine1.render(f5);
    VendingMachine2.render(f5);
    VendingMachine3.render(f5);
    VendingMachine4.render(f5);
    VendingMachine5.render(f5);
    VendingMachine6.render(f5);
    VendingMachine7.render(f5);
    VendingMachine8.render(f5);
    VendingMachine9.render(f5);
    VendingMachine10.render(f5);
    VendingMachine11.render(f5);
    VendingMachine12.render(f5);
    VendingMachine13.render(f5);
    VendingMachine14.render(f5);
    VendingMachine15.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
