// Date: 11/26/2017 10:14:33 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class VEPRMag extends ModelBase
{
  //fields
    
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
  
  public VEPRMag()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      mag1 = new ModelRenderer(this, 100, 0);
      mag1.addBox(0F, 0F, 0F, 3, 8, 11);
      mag1.setRotationPoint(-3.4F, -7.2F, -31.8F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, -0.2602503F, 0F, 0F);
      mag2 = new ModelRenderer(this, 100, 0);
      mag2.addBox(0F, 0F, 0F, 1, 8, 11);
      mag2.setRotationPoint(-0.6F, -7.2F, -31.8F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, -0.2602503F, 0F, 0F);
      mag3 = new ModelRenderer(this, 100, 0);
      mag3.addBox(0F, 0F, 0F, 3, 11, 12);
      mag3.setRotationPoint(-3.4F, 3.4F, -23.2F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, -2.044824F, 0F, 0F);
      mag4 = new ModelRenderer(this, 100, 0);
      mag4.addBox(0F, 0F, 0F, 1, 11, 12);
      mag4.setRotationPoint(-0.6F, 3.4F, -23.2F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, -2.044824F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
