// Date: 6/23/2019 8:51:32 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class VeprDustCover extends ModelBase
{
  //fields
    ModelRenderer DustCover19;
    ModelRenderer DustCover17;
    ModelRenderer DustCover18;
    ModelRenderer DustCover37;
    ModelRenderer DustCover38;
    ModelRenderer DustCover13;
    ModelRenderer DustCover11;
    ModelRenderer DustCover12;
    ModelRenderer DustCover36;
    ModelRenderer DustCover14;
    ModelRenderer DustCover15;
    ModelRenderer DustCover47;
    ModelRenderer DustCover1;
    ModelRenderer DustCover10;
    ModelRenderer DustCover42;
    ModelRenderer DustCover41;
    ModelRenderer DustCover43;
    ModelRenderer DustCover39;
    ModelRenderer DustCover40;
    ModelRenderer DustCover50;
    ModelRenderer DustCover51;
    ModelRenderer DustCover52;
    ModelRenderer DustCover53;
    ModelRenderer DustCover54;
    ModelRenderer DustCover55;
    ModelRenderer DustCover56;
    ModelRenderer DustCover57;
    ModelRenderer DustCover58;
    ModelRenderer DustCover59;
  
  public VeprDustCover()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      DustCover19 = new ModelRenderer(this, 100, 0);
      DustCover19.addBox(0F, 0F, 0F, 1, 1, 28);
      DustCover19.setRotationPoint(-0.2F, -12F, -24.5F);
      DustCover19.setTextureSize(64, 32);
      DustCover19.mirror = true;
      setRotation(DustCover19, 0F, 0F, 0F);
      DustCover17 = new ModelRenderer(this, 100, 0);
      DustCover17.addBox(0F, 0F, 0F, 1, 1, 12);
      DustCover17.setRotationPoint(-3.8F, -12F, -9.5F);
      DustCover17.setTextureSize(64, 32);
      DustCover17.mirror = true;
      setRotation(DustCover17, 0F, 0F, 0F);
      DustCover18 = new ModelRenderer(this, 100, 0);
      DustCover18.addBox(0F, 0F, 0F, 4, 1, 1);
      DustCover18.setRotationPoint(-3.8F, -12F, 2.5F);
      DustCover18.setTextureSize(64, 32);
      DustCover18.mirror = true;
      setRotation(DustCover18, 0F, 0F, 0F);
      DustCover37 = new ModelRenderer(this, 100, 0);
      DustCover37.addBox(0F, 0F, 0F, 1, 1, 9);
      DustCover37.setRotationPoint(-0.2F, -13F, -33.5F);
      DustCover37.setTextureSize(64, 32);
      DustCover37.mirror = true;
      setRotation(DustCover37, 0F, 0F, 0F);
      DustCover38 = new ModelRenderer(this, 100, 0);
      DustCover38.addBox(0F, 0F, 0F, 1, 1, 9);
      DustCover38.setRotationPoint(-0.2F, -13.5F, -33.5F);
      DustCover38.setTextureSize(64, 32);
      DustCover38.mirror = true;
      setRotation(DustCover38, 0F, 0F, 0F);
      DustCover13 = new ModelRenderer(this, 100, 0);
      DustCover13.addBox(0F, 0F, 0F, 1, 1, 2);
      DustCover13.setRotationPoint(-3.8F, -11F, -9.5F);
      DustCover13.setTextureSize(64, 32);
      DustCover13.mirror = true;
      setRotation(DustCover13, 2.193538F, 0F, 0F);
      DustCover11 = new ModelRenderer(this, 100, 0);
      DustCover11.addBox(0F, 0F, 0F, 1, 1, 12);
      DustCover11.setRotationPoint(-3.8F, -13.5F, -22.1F);
      DustCover11.setTextureSize(64, 32);
      DustCover11.mirror = true;
      setRotation(DustCover11, 0F, 0F, 0F);
      DustCover12 = new ModelRenderer(this, 100, 0);
      DustCover12.addBox(0F, 0F, 0F, 1, 1, 1);
      DustCover12.setRotationPoint(-3.8F, -13.5F, -10.1F);
      DustCover12.setTextureSize(64, 32);
      DustCover12.mirror = true;
      setRotation(DustCover12, -0.8922867F, 0F, 0F);
      DustCover36 = new ModelRenderer(this, 100, 0);
      DustCover36.addBox(0F, 0F, 0F, 1, 1, 2);
      DustCover36.setRotationPoint(-0.2F, -13.5F, -24.5F);
      DustCover36.setTextureSize(64, 32);
      DustCover36.mirror = true;
      setRotation(DustCover36, -1.152537F, 0F, 0F);
      DustCover14 = new ModelRenderer(this, 100, 0);
      DustCover14.addBox(0F, 0F, 0F, 1, 1, 13);
      DustCover14.setRotationPoint(-3.7F, -13.7F, -11F);
      DustCover14.setTextureSize(64, 32);
      DustCover14.mirror = true;
      setRotation(DustCover14, 0F, 0F, 0F);
      DustCover15 = new ModelRenderer(this, 100, 0);
      DustCover15.addBox(0F, 0F, 0F, 1, 1, 11);
      DustCover15.setRotationPoint(-3.7F, -12.7F, -9.1F);
      DustCover15.setTextureSize(64, 32);
      DustCover15.mirror = true;
      setRotation(DustCover15, 0F, 0F, 0F);
      DustCover47 = new ModelRenderer(this, 100, 0);
      DustCover47.addBox(0F, 0F, 0F, 1, 1, 1);
      DustCover47.setRotationPoint(-3.7F, -13F, -9.5F);
      DustCover47.setTextureSize(64, 32);
      DustCover47.mirror = true;
      setRotation(DustCover47, 0F, 0F, 0F);
      DustCover1 = new ModelRenderer(this, 100, 0);
      DustCover1.addBox(0F, 0F, 0F, 2, 1, 34);
      DustCover1.setRotationPoint(-2.5F, -15.8F, -33.5F);
      DustCover1.setTextureSize(64, 32);
      DustCover1.mirror = true;
      setRotation(DustCover1, 0F, 0F, 0F);
      DustCover10 = new ModelRenderer(this, 100, 0);
      DustCover10.addBox(0F, 0F, 0F, 2, 1, 12);
      DustCover10.setRotationPoint(-3.8F, -13.5F, -22.1F);
      DustCover10.setTextureSize(64, 32);
      DustCover10.mirror = true;
      setRotation(DustCover10, 0F, 0F, -1.07818F);
      DustCover42 = new ModelRenderer(this, 100, 0);
      DustCover42.addBox(0F, 0F, 0F, 2, 1, 5);
      DustCover42.setRotationPoint(-2.5F, -15.8F, 0.5F);
      DustCover42.setTextureSize(64, 32);
      DustCover42.mirror = true;
      setRotation(DustCover42, -0.9294653F, 0F, 0F);
      DustCover41 = new ModelRenderer(this, 100, 0);
      DustCover41.addBox(0F, 0F, 0F, 1, 1, 4);
      DustCover41.setRotationPoint(-2.8F, -15.3F, 0.88F);
      DustCover41.setTextureSize(64, 32);
      DustCover41.mirror = true;
      setRotation(DustCover41, -0.9294653F, 0F, 0F);
      DustCover43 = new ModelRenderer(this, 100, 0);
      DustCover43.addBox(0F, 0F, 0F, 1, 1, 4);
      DustCover43.setRotationPoint(-1.2F, -15.3F, 0.88F);
      DustCover43.setTextureSize(64, 32);
      DustCover43.mirror = true;
      setRotation(DustCover43, -0.9294653F, 0F, 0F);
      DustCover39 = new ModelRenderer(this, 100, 0);
      DustCover39.addBox(0F, 0F, 0F, 2, 2, 2);
      DustCover39.setRotationPoint(-1.3F, -13.5F, 2.2F);
      DustCover39.setTextureSize(64, 32);
      DustCover39.mirror = true;
      setRotation(DustCover39, -0.9294653F, 0F, 0F);
      DustCover40 = new ModelRenderer(this, 100, 0);
      DustCover40.addBox(0F, 0F, 0F, 2, 2, 2);
      DustCover40.setRotationPoint(-3.7F, -13.5F, 2.2F);
      DustCover40.setTextureSize(64, 32);
      DustCover40.mirror = true;
      setRotation(DustCover40, -0.9294653F, 0F, 0F);
      DustCover50 = new ModelRenderer(this, 100, 0);
      DustCover50.addBox(0F, 0F, 0F, 1, 2, 27);
      DustCover50.setRotationPoint(-0.3F, -13.7F, -25.1F);
      DustCover50.setTextureSize(64, 32);
      DustCover50.mirror = true;
      setRotation(DustCover50, 0F, 0F, 0F);
      DustCover51 = new ModelRenderer(this, 100, 0);
      DustCover51.addBox(0.2F, 0F, 0F, 2, 1, 11);
      DustCover51.setRotationPoint(-3.8F, -13.5F, -10.1F);
      DustCover51.setTextureSize(64, 32);
      DustCover51.mirror = true;
      setRotation(DustCover51, 0F, 0F, -1.07818F);
      DustCover52 = new ModelRenderer(this, 100, 0);
      DustCover52.addBox(0F, 0F, -0.2F, 1, 1, 1);
      DustCover52.setRotationPoint(-3.7F, -13.5F, 2.2F);
      DustCover52.setTextureSize(64, 32);
      DustCover52.mirror = true;
      setRotation(DustCover52, -0.9294653F, 0F, 0F);
      DustCover53 = new ModelRenderer(this, 100, 0);
      DustCover53.addBox(1.6F, 0F, 0F, 1, 1, 34);
      DustCover53.setRotationPoint(-3.8F, -13.5F, -33.5F);
      DustCover53.setTextureSize(64, 32);
      DustCover53.mirror = true;
      setRotation(DustCover53, 0F, 0F, -1.07818F);
      DustCover54 = new ModelRenderer(this, 100, 0);
      DustCover54.addBox(-2F, 0F, 0F, 2, 1, 9);
      DustCover54.setRotationPoint(0.8F, -13.5F, -33.5F);
      DustCover54.setTextureSize(64, 32);
      DustCover54.mirror = true;
      setRotation(DustCover54, 0F, 0F, 1.078177F);
      DustCover55 = new ModelRenderer(this, 100, 0);
      DustCover55.addBox(-2.2F, 0F, 0F, 2, 1, 26);
      DustCover55.setRotationPoint(0.8F, -13.5F, -25.1F);
      DustCover55.setTextureSize(64, 32);
      DustCover55.mirror = true;
      setRotation(DustCover55, 0F, 0F, 1.078177F);
      DustCover56 = new ModelRenderer(this, 100, 0);
      DustCover56.addBox(0F, 0F, -0.2F, 1, 1, 1);
      DustCover56.setRotationPoint(-0.3F, -13.5F, 2.2F);
      DustCover56.setTextureSize(64, 32);
      DustCover56.mirror = true;
      setRotation(DustCover56, -0.9294653F, 0F, 0F);
      DustCover57 = new ModelRenderer(this, 100, 0);
      DustCover57.addBox(-2.6F, 0F, 0F, 1, 1, 34);
      DustCover57.setRotationPoint(0.8F, -13.5F, -33.5F);
      DustCover57.setTextureSize(64, 32);
      DustCover57.mirror = true;
      setRotation(DustCover57, 0F, 0F, 1.078177F);
      DustCover58 = new ModelRenderer(this, 100, 0);
      DustCover58.addBox(0.2F, 0F, 0F, 1, 1, 1);
      DustCover58.setRotationPoint(-3.8F, -13.5F, 0.5F);
      DustCover58.setTextureSize(64, 32);
      DustCover58.mirror = true;
      setRotation(DustCover58, 0F, 0F, -1.07818F);
      DustCover59 = new ModelRenderer(this, 100, 0);
      DustCover59.addBox(-1.2F, 0F, 0F, 1, 1, 1);
      DustCover59.setRotationPoint(0.8F, -13.5F, 0.5F);
      DustCover59.setTextureSize(64, 32);
      DustCover59.mirror = true;
      setRotation(DustCover59, 0F, 0F, 1.078177F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    DustCover19.render(f5);
    DustCover17.render(f5);
    DustCover18.render(f5);
    DustCover37.render(f5);
    DustCover38.render(f5);
    DustCover13.render(f5);
    DustCover11.render(f5);
    DustCover12.render(f5);
    DustCover36.render(f5);
    DustCover14.render(f5);
    DustCover15.render(f5);
    DustCover47.render(f5);
    DustCover1.render(f5);
    DustCover10.render(f5);
    DustCover42.render(f5);
    DustCover41.render(f5);
    DustCover43.render(f5);
    DustCover39.render(f5);
    DustCover40.render(f5);
    DustCover50.render(f5);
    DustCover51.render(f5);
    DustCover52.render(f5);
    DustCover53.render(f5);
    DustCover54.render(f5);
    DustCover55.render(f5);
    DustCover56.render(f5);
    DustCover57.render(f5);
    DustCover58.render(f5);
    DustCover59.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
