// Date: 2/17/2019 6:56:34 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class WoodenCrate extends ModelBase
{
  //fields
    ModelRenderer box1;
    ModelRenderer box2;
    ModelRenderer box3;
    ModelRenderer box4;
    ModelRenderer box5;
    ModelRenderer box6;
    ModelRenderer box7;
    ModelRenderer box8;
    ModelRenderer box9;
    ModelRenderer box10;
  
  public WoodenCrate()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      box1 = new ModelRenderer(this, 0, 0);
      box1.addBox(0F, 0F, 0F, 15, 14, 15);
      box1.setRotationPoint(-7.5F, 8.7F, -7.5F);
      box1.setTextureSize(128, 128);
      box1.mirror = true;
      setRotation(box1, 0F, 0F, 0F);
      box2 = new ModelRenderer(this, 0, 0);
      box2.addBox(0F, 0F, 0F, 2, 14, 16);
      box2.setRotationPoint(-8F, 10F, -8F);
      box2.setTextureSize(128, 128);
      box2.mirror = true;
      setRotation(box2, 0F, 0F, 0F);
      box3 = new ModelRenderer(this, 0, 0);
      box3.addBox(0F, 0F, 0F, 2, 14, 16);
      box3.setRotationPoint(6F, 10F, -8F);
      box3.setTextureSize(128, 128);
      box3.mirror = true;
      setRotation(box3, 0F, 0F, 0F);
      box4 = new ModelRenderer(this, 0, 0);
      box4.addBox(0F, 0F, 0F, 16, 2, 2);
      box4.setRotationPoint(-8F, 8F, 3F);
      box4.setTextureSize(128, 128);
      box4.mirror = true;
      setRotation(box4, 0F, 0F, 0F);
      box5 = new ModelRenderer(this, 0, 0);
      box5.addBox(0F, 0F, 0F, 12, 2, 2);
      box5.setRotationPoint(-6F, 21F, 6F);
      box5.setTextureSize(128, 128);
      box5.mirror = true;
      setRotation(box5, 0F, 0F, 0F);
      box6 = new ModelRenderer(this, 0, 0);
      box6.addBox(0F, 0F, 0F, 16, 2, 2);
      box6.setRotationPoint(-8F, 8F, -5F);
      box6.setTextureSize(128, 128);
      box6.mirror = true;
      setRotation(box6, 0F, 0F, 0F);
      box7 = new ModelRenderer(this, 0, 0);
      box7.addBox(0F, 0F, 0F, 2, 11, 16);
      box7.setRotationPoint(-1F, 10F, -8F);
      box7.setTextureSize(128, 128);
      box7.mirror = true;
      setRotation(box7, 0F, 0F, 0F);
      box8 = new ModelRenderer(this, 0, 0);
      box8.addBox(0F, 0F, 0F, 16, 2, 2);
      box8.setRotationPoint(-8F, 8.5F, -8F);
      box8.setTextureSize(128, 128);
      box8.mirror = true;
      setRotation(box8, 0F, 0F, 0F);
      box9 = new ModelRenderer(this, 0, 0);
      box9.addBox(0F, 0F, 0F, 16, 2, 2);
      box9.setRotationPoint(-8F, 8.5F, 6F);
      box9.setTextureSize(128, 128);
      box9.mirror = true;
      setRotation(box9, 0F, 0F, 0F);
      box10 = new ModelRenderer(this, 0, 0);
      box10.addBox(0F, 0F, 0F, 12, 2, 2);
      box10.setRotationPoint(-6F, 21F, -8F);
      box10.setTextureSize(128, 128);
      box10.mirror = true;
      setRotation(box10, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    box1.render(f5);
    box2.render(f5);
    box3.render(f5);
    box4.render(f5);
    box5.render(f5);
    box6.render(f5);
    box7.render(f5);
    box8.render(f5);
    box9.render(f5);
    box10.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
