// Date: 2/17/2019 7:21:38 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vicmatskiv.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class WoodenCrateOpened extends ModelBase
{
  //fields
    ModelRenderer box1;
    ModelRenderer box2;
    ModelRenderer box3;
    ModelRenderer box5;
    ModelRenderer box7;
    ModelRenderer box8;
    ModelRenderer box9;
    ModelRenderer box10;
    ModelRenderer box11;
    ModelRenderer box12;
    ModelRenderer box13;
  
  public WoodenCrateOpened()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      box1 = new ModelRenderer(this, 0, 0);
      box1.addBox(0F, 0F, 0F, 15, 12, 15);
      box1.setRotationPoint(-7.5F, 10.7F, -7.5F);
      box1.setTextureSize(64, 32);
      box1.mirror = true;
      setRotation(box1, 0F, 0F, 0F);
      box2 = new ModelRenderer(this, 0, 0);
      box2.addBox(0F, 0F, 0F, 2, 14, 16);
      box2.setRotationPoint(-8F, 10F, -8F);
      box2.setTextureSize(64, 32);
      box2.mirror = true;
      setRotation(box2, 0F, 0F, 0F);
      box3 = new ModelRenderer(this, 0, 0);
      box3.addBox(0F, 0F, 0F, 2, 14, 16);
      box3.setRotationPoint(6F, 10F, -8F);
      box3.setTextureSize(64, 32);
      box3.mirror = true;
      setRotation(box3, 0F, 0F, 0F);
      box5 = new ModelRenderer(this, 0, 0);
      box5.addBox(0F, 0F, 0F, 12, 2, 2);
      box5.setRotationPoint(-6F, 21F, 6F);
      box5.setTextureSize(64, 32);
      box5.mirror = true;
      setRotation(box5, 0F, 0F, 0F);
      box7 = new ModelRenderer(this, 0, 0);
      box7.addBox(0F, 0F, 0F, 2, 11, 16);
      box7.setRotationPoint(-1F, 10F, -8F);
      box7.setTextureSize(64, 32);
      box7.mirror = true;
      setRotation(box7, 0F, 0F, 0F);
      box8 = new ModelRenderer(this, 0, 0);
      box8.addBox(0F, 0F, 0F, 16, 2, 2);
      box8.setRotationPoint(-8F, 9.5F, -8F);
      box8.setTextureSize(64, 32);
      box8.mirror = true;
      setRotation(box8, 0F, 0F, 0F);
      box9 = new ModelRenderer(this, 0, 0);
      box9.addBox(0F, 0F, 0F, 16, 2, 2);
      box9.setRotationPoint(-8F, 9.5F, 6F);
      box9.setTextureSize(64, 32);
      box9.mirror = true;
      setRotation(box9, 0F, 0F, 0F);
      box10 = new ModelRenderer(this, 0, 0);
      box10.addBox(0F, 0F, 0F, 12, 2, 2);
      box10.setRotationPoint(-6F, 21F, -8F);
      box10.setTextureSize(64, 32);
      box10.mirror = true;
      setRotation(box10, 0F, 0F, 0F);
      box11 = new ModelRenderer(this, 0, 0);
      box11.addBox(0F, 0F, 0F, 15, 2, 15);
      box11.setRotationPoint(-7.5F, 7.5F, 4.5F);
      box11.setTextureSize(64, 32);
      box11.mirror = true;
      setRotation(box11, 0F, 1.226894F, 0F);
      box12 = new ModelRenderer(this, 0, 0);
      box12.addBox(2F, -0.5F, -0.5F, 2, 2, 16);
      box12.setRotationPoint(-7.5F, 7.5F, 4.5F);
      box12.setTextureSize(64, 32);
      box12.mirror = true;
      setRotation(box12, 0F, 1.226894F, 0F);
      box13 = new ModelRenderer(this, 0, 0);
      box13.addBox(11F, -0.5F, -0.5F, 2, 2, 16);
      box13.setRotationPoint(-7.5F, 7.5F, 4.5F);
      box13.setTextureSize(64, 32);
      box13.mirror = true;
      setRotation(box13, 0F, 1.226894F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    box1.render(f5);
    box2.render(f5);
    box3.render(f5);
    box5.render(f5);
    box7.render(f5);
    box8.render(f5);
    box9.render(f5);
    box10.render(f5);
    box11.render(f5);
    box12.render(f5);
    box13.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
